### ISSUE TITLE
Bug:buy cards with  corporation  helion

### ISSUE THREAD

**Issue by jijiqw** [bafolts/terraforming-mars#1000]
![image](https://user-images.githubusercontent.com/16096558/87618843-62125800-c74d-11ea-8709-aa3310fd4816.png)
Can't  adjust mc  by  '+-' button  , however  'pay by heat'  buttons  work fine .

**Comment by nwai90** [comment]
Should be resolved in https://github.com/bafolts/terraforming-mars/pull/1001
