### ISSUE TITLE
Add warning alert if player might not be able to afford selected Prelude(s)

### ISSUE THREAD

**Issue by duckmammal** [bafolts/terraforming-mars#1004]
When I select Huge Asteroid as a Prelude in a Solo variant, it doesn't appear as a card to play during the preludes phase. 

The game continues, with me having played only 1 prelude.

**Comment by jijiqw** [comment]
I guess you don't have 5 mc to pay

**Comment by nwai90** [comment]
Yes, the game will remove Preludes that are unplayable if the cost cannot be paid

**Comment by duckmammal** [comment]
There should be some sort of notification about that before it happens?

**Comment by nwai90** [comment]
It might be possible to add an optional warning alert if corporation's start MC - total cost of selected Project cards - cost of prelude cards is negative. Will add to list of queued features

**Comment by kevinb9n** [comment]
If #1285 is implemented as currently discussed it will take care of this; the user would simply have to notice that they will have a negative amount of MC left after Preludes.

I believe that nothing else can cause a Prelude to be unplayable, unless you bizarrely take Ecology Experts/Eccentric Sponsor and no project cards. That seems strange enough that you could consider this issue resolved anyway.

(On the other hand if a corp is ever introduced that decreases your own MC production by any amount, then this problem can return if anyone else took Mons. Cross that bridge if we come to it...)

**Comment by kevinb9n** [comment]
I think the on-screen message saying you will have a negative amount of money resolves this request.
