### ISSUE TITLE
Idea: Common Tags and Resources boards

### ISSUE THREAD

**Issue by ssimeonoff** [bafolts/terraforming-mars#1009]
### Reason
Before taking an action, often you scroll up to check an opponent resources or tags count. This causes a lot of scrolling and keeping the other players tableau open.

### Idea
Display the opponents tags and resources close to the player's resources and tags. The assumption is that if the player can see an overview of the opponents' resources and tags, and with the actions log visible, the opponents' tableau will remain closed, which will save space and avoid scrolling.

Current UI:
![1](https://user-images.githubusercontent.com/6917565/87814914-e99eba80-c864-11ea-973e-14b32d158c6b.png)
Suggested UI:
![2](https://user-images.githubusercontent.com/6917565/87815654-4e0e4980-c866-11ea-9fcf-c63db375da1e.png)

### Notes
- all tags types are displayed
- if tag count is 0, maybe the number can be not displayed (to reduce the displayed total numbers)
- cards' count can also be added on the side
- maybe there should be a toggle button that shows/hides the opponents tags/resources. (to keep the UI clear)

The suggested UI is just for an example (the tags table above the resources irritates me, but don't have a better idea for now).

**Comment by nwai90** [comment]
This is a nice idea! That way, players only need to click to open tableaus if they want to see more detailed information. Agree that this can be controlled by a preference toggle
