### ISSUE TITLE
Bug? Ecology Experts count for Tactician milestone?

### ISSUE THREAD

**Issue by Dudurandil** [bafolts/terraforming-mars#1010]
In this game : https://terraforming-mars.herokuapp.com/player?id=a150ad814f16

This player had Electro Catapult, Natural Preserve, Supported Reasearch and Eos Chasma National Park and could pay for Tactician milestone even if he had only 4 cards with requirements (if we counted correctly)

He played the prelude Ecology Experts so does the game mistakenly counted this card as a prelude?

Thanks for your help!

Dudurandil

**Comment by nwai90** [comment]
Hi @Dudurandil When was this game created?

The likely cause is due to a previous bug where event cards were counted for Tactician as noted by @jijiqw. In this case, Crash Site Cleanup would have been incorrectly included.

This issue has been fixed as of 15 July: https://github.com/bafolts/terraforming-mars/wiki/Changelog#15-july-2020

**Comment by jijiqw** [comment]
There are some cards‘s  hasRequirements  prop need  be  false , I would create a pr later to fix it ,

**Comment by jijiqw** [comment]
It seems  have been fixed by pr #1006

**Comment by Dudurandil** [comment]
Hi @nwai90 , the game was created yesterday (17 July) :)

**Comment by Dudurandil** [comment]
A little precision: at the time the player claimed Tactician, he hadn't played Crash Site Cleanup yet, only 
Subterranean Reservoir, Mineral Deposit and Lava Flows

**Comment by nwai90** [comment]
@Dudurandil There was a patch on 17 July as well, some of the cards here incorrectly counted for Tactician. Do you remember if any of these were played?

https://github.com/bafolts/terraforming-mars/pull/1006/files

If yes, we can close this issue as it has been fixed

**Comment by Dudurandil** [comment]
Yes! I remember that he had played Subterranean Reservoir before claiming Tactician, so you can close this issue, thanks!
