### ISSUE TITLE
bug:  srr

### ISSUE THREAD

**Issue by jijiqw** [bafolts/terraforming-mars#1016]
![image](https://user-images.githubusercontent.com/16096558/87855581-ee8a6980-c94b-11ea-84a4-e8d94fafaa6a.png)

play  a  card  linked with srr after someone undo or  game server  restart

**Comment by nwai90** [comment]
The object is missing the type, e.g.:

```
{
  name: 'Interplanetary Trade',
  cost: 27,
  tags: [ 'space' ],
  cardType: 'green'
}```

Should be

```InterplanetaryTrade {
  name: 'Interplanetary Trade',
  cost: 27,
  tags: [ 'space' ],
  cardType: 'green'
}```

**Comment by jijiqw** [comment]
Similar to #888

**Comment by vincentneko** [comment]
I though I had tested the info feature After the change. Could it be a saved game before the change. If yes, the json is not compatible between versions.

**Comment by jijiqw** [comment]
> I though I had tested the info feature After the change. Could it be a saved game before the change. If yes, the json is not compatible between versions.

It's  a new game  created today,  I would create a pr to fix it later

**Comment by nwai90** [comment]
@jijiqw Can we close this one?

**Comment by jijiqw** [comment]
@nwai90  I think so , it should be solved now
