### ISSUE TITLE
bug:  CometAiming 

### ISSUE THREAD

**Issue by jijiqw** [bafolts/terraforming-mars#1019]
1. can select action 1 even if  there are already 9 oceans .  this happens when player can perform action2.

2. action 2 don‘t  decrease player's  titanium amount  if  CometAiming has one or more resouces on it already. 

![image](https://user-images.githubusercontent.com/16096558/87857930-264ddd00-c95d-11ea-9c85-27dc7fca293a.png)

**Comment by nwai90** [comment]
@jijiqw Do you want to submit a PR for this? I can look into it in a day or so as well.

**Comment by jijiqw** [comment]
> @jijiqw Do you want to submit a PR for this? I can look into it in a day or so as well.

 May be better if you can handle this one

**Comment by nwai90** [comment]
Ok, will look at it. Should be a fairly simple fix

**Comment by nwai90** [comment]
Resolved in https://github.com/bafolts/terraforming-mars/pull/1020
