### ISSUE TITLE
Astrodrill - wrong activation power

### ISSUE THREAD

**Issue by vsrisuknimit** [bafolts/terraforming-mars#1026]
Astrodrill has essentially 3 possible actions:

1. Gain an asteroid to any card
2. Gain a standard resource
3. Spend an asteroid here for 3 titanium.

As the card is currently implemented, action 1 and 2 is combined. That is not correct.

https://ssimeonoff.github.io/cards-list#CORP39

**Comment by alrusdi** [comment]
It's a bug indeed. Thank you for reporting!
![astrodrill](https://user-images.githubusercontent.com/394311/87923280-acba0a00-ca96-11ea-9e66-a5b4005fd0b0.png)

**Comment by jijiqw** [comment]
Prefer the combined version personally

**Comment by vincentneko** [comment]
Do we have the full card text somewhere ?
IMO it make more sense actions 1 & 2 are combined...

**Comment by alrusdi** [comment]
I saw it on bgg https://boardgamegeek.com/thread/2449277/lets-discuss-astrodrill
(Action: Either add 1 asteroid to ANY CARD **or** gain any standard resource **or** remove 1 asteroid from this card to gain 3 titanium)
But it can be just interpretation.

**Comment by vsrisuknimit** [comment]
Unless Slash (/) is used to mean PER (jovian tag, earth tag, etc), the slash symbol (/) always mean OR in this game.

Example: https://ssimeonoff.github.io/cards-list#069#074#128#131#C03#T06

AND would have no symbol at all. Just pictures of asteroid and standard resource.

Example: https://ssimeonoff.github.io/cards-list#163#C09#X26

**Comment by nwai90** [comment]
> I saw it on bgg https://boardgamegeek.com/thread/2449277/lets-discuss-astrodrill
> (Action: Either add 1 asteroid to ANY CARD **or** gain any standard resource **or** remove 1 asteroid from this card to gain 3 titanium)
> But it can be just interpretation.

Yes, I saw this too. The original poster edited his post from "and" to "or" here: https://boardgamegeek.com/thread/2449277/article/35125663#35125663

Could not find any official confirmation yet though. Should we change it or wait?

**Comment by alrusdi** [comment]
I think it is pretty safe to change. Logic with / symbol (by @vsrisuknimit) sounds very solid

**Comment by vsrisuknimit** [comment]
It is possible the designer might change the design later on since these cards are still being developed after all. That was the case for Lakefront Resort, Pristar, and Terralabs. Their current forms are slightly different from when they were first revealed in Turmoil Kickstarter (https://www.kickstarter.com/projects/strongholdgames/terraforming-mars-turmoil)(https://imgur.com/h2yoe5M)

In the end, over nine generations, the difference is not that big. Just 1 resource (probably titanium) on gen 4,6, and 8.

**Comment by nwai90** [comment]
Resolved in https://github.com/bafolts/terraforming-mars/pull/1064
