### ISSUE TITLE
Saturn Surfing bug

### ISSUE THREAD

**Issue by mloballer** [bafolts/terraforming-mars#1028]
We started a game the other day, and in my starting hand I had Saturn Surfing, even though we had promo cards off, we still got it. We were playing with Preludes, Colonies, Corporate Era and Venus. You can see in the image, in a 3 player game it's showing 284 cards, but with all the expansion I mentioned we played, there should be 283 cards remaining after the first 3 players get dealt there 10 cards for the above-mentioned expansions. Thanks.

![image](https://user-images.githubusercontent.com/10591526/87911534-a8eba080-ca20-11ea-9f8d-ec2cc80644e7.png)

**Comment by nwai90** [comment]
Resolved in https://github.com/bafolts/terraforming-mars/pull/1029
