### ISSUE TITLE
Cultural Metropolis Requirements wrong

### ISSUE THREAD

**Issue by duckmammal** [bafolts/terraforming-mars#1030]
Currently, on your server, in order to play Cultural Metropolis you need to have 2 free delegates, and to place them. 
In reality the delegate placement is a bonus for playing Cultural Metropolis. The number of free delegates you have should not impact whether or not you are allowed to play the card.

**Comment by nwai90** [comment]
I believe the current implementation is correct, as per this thread: https://boardgamegeek.com/thread/2201860/article/32015727#32015727

An official clarification is provided at https://boardgamegeek.com/thread/1705209/article/24723217#24723217. All effects are mandatory when playing a card, with only 3 allowed exceptions (raising maxed out global parameters, removing resources from other players, or adding resources to a card).

Placing 2 delegates is a mandatory effect, hence you must have 2 free delegates to be able to play the card.

**Comment by duckmammal** [comment]
Whoa, sorry! I think you're completely right! This issue had come up in a friendly game and I thought I had looked up the ruling at that time, but the links you're pointing at are pretty indisputable! So sorry to have wasted your time!
