### ISSUE TITLE
Bug : Helion failed to spend heat as MC and can reach negative MC in some rare case

### ISSUE THREAD

**Issue by charlielam** [bafolts/terraforming-mars#1036]
Refer to the image below, when a player want to spend heat as MC when his MC is not enough, he spend his MC instead and his MC become negative.

![image](https://user-images.githubusercontent.com/6376909/88158589-d31aa980-cc3e-11ea-8746-87f5ebdadaba.png)

**Comment by nwai90** [comment]
@charlielam Could you provide more information about when this rare case happens? What was the action that the player was trying to perform?

**Comment by SliceOfBread** [comment]
This might be similar to #1043.

**Comment by nwai90** [comment]
@charlielam This should be resolved with the recent patches for Helion, will close the issue. Feel free to reopen it if you encounter it again
