### ISSUE TITLE
Bug: Playing Magnetic Field Generators Promo while Reds are ruling may result in negative MC

### ISSUE THREAD

**Issue by sccblazer** [bafolts/terraforming-mars#1037]
After playing Magnetic Field Generators Promo card while Reds party was ruling one player in our game temporarily ended with -3 MC. He placed the tile near 1 ocean, so he was at -1 MC after all. 
I can't remember whether he could place the tile near 2 oceans (that would be the legal play, since he would never have negative MC).
Maybe there should be tile placement restriction in case player doesn't have enough money, or the card shouldn't be playable at all.

**Comment by nwai90** [comment]
This is indeed a bug. We missed out this card when checking whether player can pay for Reds tax. Thanks for highlighting!

**Comment by nwai90** [comment]
Resolved in https://github.com/bafolts/terraforming-mars/pull/1039
