### ISSUE TITLE
Bug: Pristar + Global Government and Mud Slides Global Event

### ISSUE THREAD

**Issue by bluesleona** [bafolts/terraforming-mars#1040]
Bug : Pristar do not get resource if you are first player and act as Global government
Also it will stop gaining resource after this happen. Even if you play a game without get any TR you can only have maximum three time activate it effect in one game.

Bug : Mud Slides count tile aside EMPTY ocean. Even if there is no ocean placed, u will get MC reduction.

Thank you for fixing them. Great work

**Comment by nwai90** [comment]
Mud Slides should have been fixed by @jijiqw

**Comment by jijiqw** [comment]
Pristar's bug should also be fixed some days ago , and  it's caused by someone undo action or game server restarts,   you can pull these recent changes from  bafots and check again .

**Comment by nwai90** [comment]
@bluesleona Will close this issue for now, do let us know if you still encounter those bugs with the latest version of the code and we'll reopen it then
