### ISSUE TITLE
Teractor + Business Empire

### ISSUE THREAD

**Issue by Zolib80** [bafolts/terraforming-mars#1041]
I have just started a game and I have found out that Business Empire (Prelude: 6 M€ production & -6M€) give only 6M€ production.
![Bug](https://user-images.githubusercontent.com/68651711/88189014-7c0dd800-cc30-11ea-9ab2-1c19f3cbd470.PNG)

**Comment by duckmammal** [comment]
if you're playing the solo variant with preludes, you normally start with -2 income, so your income afterwards will be (-2) + 6 = +4 income.

**Comment by Zolib80** [comment]
Hm, I have missed this bit. It is working correctly then. :)
