### ISSUE TITLE
Loading finished games

### ISSUE THREAD

**Issue by mloballer** [bafolts/terraforming-mars#1045]
I have been running mars on my own server. When I stop the server, update code, and start it again, it only looks for the games that are running, not finished to load. It would be nice to also load the finished games in case I wanted to go back and look at the results from that game, thanks.

**Comment by vincentneko** [comment]
I'm afraid we cannot do this right now, because of memory constraints.
(having every game loaded would eventually wreck havoc server memory)
I'm planning to create another table in the database to store game results.
