### ISSUE TITLE
Bug: Turmoil global event "Corrosive Rain" appear in games without colonies expansion

### ISSUE THREAD

**Issue by charlielam** [bafolts/terraforming-mars#1056]
When a game is created with turmoil expansion but without colonies expansion, "Corrosive Rain" can be appeared in global events

**Comment by nwai90** [comment]
I saw that this card is part of the Turmoil promo pack here: https://boardgamegeekstore.com/products/terraforming-mars-turmoil-promo-card-pack

Should it not appear in games with Turmoil expansion?

**Comment by charlielam** [comment]
the problem is that card is with a black triangle icon on bottom left, which means it only applies to game with colonies exp added.
If the game is created with turmoil exp but without colonies exp, it shouldn't appear

**Comment by nwai90** [comment]
It could be that the icon is wrong. Can anyone confirm if this is a Turmoil card or a Colonies card?

**Comment by charlielam** [comment]
![IMG_20200725_014500](https://user-images.githubusercontent.com/6376909/88419935-9acec300-ce18-11ea-972d-d3fc8ddf7901.jpg)

**Comment by charlielam** [comment]
FYR, there are total 4 global event card within colonies exp

**Comment by vincentneko** [comment]
I've noticed we forgot to implement Microgravity Health Problems global event !

**Comment by vincentneko** [comment]
> I've noticed we forgot to implement Microgravity Health Problems global event !

I will add it asap.

**Comment by vincentneko** [comment]
Bug fixed and missing event added.
