### ISSUE TITLE
Bug: Beginner corp does not receive prelude cards

### ISSUE THREAD

**Issue by mloballer** [bafolts/terraforming-mars#1058]
When starting a game, we had preludes on, and someone wanted to be a beginner corporation, but they were not dealt any prelude cards.

**Comment by nwai90** [comment]
@vincentneko I was attempting to address this issue, but the below approach seems to fail intermittently. Could you have a look at it?

```
private pickPreludeCardsForBeginner(player: Player) {
      if (this.preludeExtension) {
        for (let i = 0; i < 4; i++) {
          player.dealtPreludeCards.push(this.dealer.dealPreludeCard());
        }
        
        player.setWaitingFor(new SelectCard(
          "Select 2 Prelude cards", player.dealtPreludeCards,
          (preludeCards: Array<IProjectCard>) => {
            player.preludeCardsInHand.push(preludeCards[0], preludeCards[1]);
            this.playerIsFinishedWithResearchPhase(player);
            return undefined;
          }, 2, 2
        ), () => {});

        return;
      } else {
        this.playerIsFinishedWithResearchPhase(player);
        return undefined;
      }
    }
```

With this approach I noticed that some Beginner players sometimes don't get to select Preludes at all, and it also seems to intermittently produce `unsupported waitingFor`

**Comment by vincentneko** [comment]
Beginner corp is not letting you choose anything so changing it's behavior might be a lot of tedious work.
I suggest we disable beginner corp if any option is selected.

**Comment by nwai90** [comment]
https://boardgamegeek.com/thread/2268219/article/32891016#32891016
https://boardgamegeek.com/thread/2130044/article/30959133#30959133

Agree with the suggestion. I think it is fine to leave beginner corp just for the base game without any expansions. Modifying this seems to open up more problems and it is also recommended against by the game designer.

**Comment by mloballer** [comment]
I agree, a person should not be using the beginner corporation in an expansion, I will let him know he shouldn't be using it, thanks.

**Comment by vincentneko** [comment]
We will update the UI so this will not be possible in the future.

**Comment by vincentneko** [comment]
Fixed and merged
