### ISSUE TITLE
Bug: First player receive map bonus when performing world gov action

### ISSUE THREAD

**Issue by charlielam** [bafolts/terraforming-mars#1059]
refer to the pic
![IMG-20200725-WA0008](https://user-images.githubusercontent.com/6376909/88449770-20d02580-ce7c-11ea-8edd-409da4eba36b.jpg)

**Comment by vincentneko** [comment]
Just tested it in a solo game with world gov activated, it did not occur.
Were you playing with Turmoil option and it was a global event that required to add an ocean maybe ?

**Comment by charlielam** [comment]
that game is played many days ago and i can't remember the details, but yes it's with turmoil exp i'm sure

**Comment by vincentneko** [comment]
Just tested turmoil global event that add an ocean to the board, did not got bonus heat.
I'm closing this one as it is not reproductible.
