### ISSUE TITLE
Award "Excentric" did not calculate when end game

### ISSUE THREAD

**Issue by charlielam** [bafolts/terraforming-mars#1060]
For unknown reason, award "Excentric" (Player with most resources on cards) did not calculated when end game. Not sure if this problem can be reproduced.

![80415ffa-761d-44ca-a05c-51a334269f8f](https://user-images.githubusercontent.com/6376909/88459328-24d56500-cec7-11ea-803e-ee170cbef9ad.jpg)

**Comment by vincentneko** [comment]
Fixed and merged, thanks for reporting !
