### ISSUE TITLE
Awards UI

### ISSUE THREAD

**Issue by mloballer** [bafolts/terraforming-mars#1066]
Thanks for the new awards interface that show you how much each player has. I was wondering, maybe it's already being worked on, but after someone funds an award, it gets gray, and then it's hard to tell which color is which. If you could still see the colors well after the award is funded would be nice, not sure what is the easiest way to do that. thanks.

**Comment by duckmammal** [comment]
yeah, the funded milestones being greyed out makes sense, but not the funded awards.

**Comment by nwai90** [comment]
Resolved in https://github.com/bafolts/terraforming-mars/pull/1068
