### ISSUE TITLE
bug: red policy 

### ISSUE THREAD

**Issue by jijiqw** [bafolts/terraforming-mars#1067]
![image](https://user-images.githubusercontent.com/16096558/88497921-5730b080-cff4-11ea-9a10-abfe0813fe41.png)
![image](https://user-images.githubusercontent.com/16096558/88497944-61eb4580-cff4-11ea-8747-031c030af8e2.png)
![image](https://user-images.githubusercontent.com/16096558/88497952-657ecc80-cff4-11ea-9634-7db09c67a02a.png)

The player canot play  "NITROGEN FROM TITAN"  with 25+6-2 = 29 MC

**Comment by nwai90** [comment]
Hi @vincentneko I took a look at this, seems we have to replace all cases where REDS_RULING_POLICY_COST is involved in determining `canPlay()`. E.g. for NitrogenFromTitan:

```
const calculatedCost : number = player.getCardCost(game, this) + REDS_RULING_POLICY_COST * 2;
return player.canAfford(calculatedCost, game, false, true);
```

**Comment by vincentneko** [comment]
Hi @nwai90 , yes I work on it today.

**Comment by nwai90** [comment]
Resolved in https://github.com/bafolts/terraforming-mars/pull/1069
