### ISSUE TITLE
2 Awards not show info when cilck

### ISSUE THREAD

**Issue by Ronnoc** [bafolts/terraforming-mars#1072]
![image](https://user-images.githubusercontent.com/5140023/88566296-66e9dc80-d068-11ea-890c-1b9f03c8896c.png)

**Comment by vincentneko** [comment]
This is a client side related bug. Awards descriptions are passed to the vue js component.
I'm wondering if it's related with the award name being 2 words instead of one...

**Comment by SliceOfBread** [comment]
I think I can fix this, if you want.

**Comment by vincentneko** [comment]
Sure please go ahead !

Le lun. 27 juil. 2020 à 19:36, SliceOfBread <notifications@github.com> a
écrit :

**Comment by SliceOfBread** [comment]
@vincentneko I updated component Award.ts and check failed a Turmoil test and I have no idea how that might be related. But I updated Milestone.ts also (as it had the same bug) and check passed.
I have not yet built local server but fix is simple enough and easy for someone to check before I can get my local server going.

**Comment by ssimeonoff** [comment]
@Ronnoc , what browse/os do you use?

**Comment by Ronnoc** [comment]
Chrome in mac/Linux

**Comment by vincentneko** [comment]
@SliceOfBread Thanks for fixing !
