### ISSUE TITLE
Feature request: Random Milestones/Awards toggle

### ISSUE THREAD

**Issue by mloballer** [bafolts/terraforming-mars#1074]
Hello, my game group is wondering if it would be possible when choosing Random Milestones/Awards to be able to toggle some milestones off. We find that in our game Tycoon is never ever going to get claimed in a 3 player game. Also, I am sure many may disagree with me, but I hate planner, although I can see how in some rare strategies it's viable. But either way would be nice to remove some of them from the random pool, thanks!

**Comment by kevinb9n** [comment]
I would suggest closing this and, if it is ever important enough to anyone, consider reopening #1697 instead.
