### ISSUE TITLE
Heroku site was unresponsive but did not crash.

### ISSUE THREAD

**Issue by bafolts** [bafolts/terraforming-mars#1076]
Around 00:50 UTC on July 28th the heroku service became unresponsive. The response time seemed to cap out to 30 seconds and no throughput was happening. I assume an infinite loop of some kind has been introduced which locked up the node process. Has anything gone out recently which could have introduced this? I have not been paying full attention to the commits. I restarted the server but if the action which caused the infinite loop is reached again it will lock up the node process again.

**Comment by bafolts** [comment]
@vincentneko or someone else who has been watching stuff go in. I assume some recent change on the server introduced this infinite looping. I may start checking out recent pull requests that have gone in. If someone stands out that may have caused this please chime in. If this is something common it could continue to take down the heroku site. I will monitor and keep manually restarting it if I see it happen again.

**Comment by vincentneko** [comment]
@bafolts Right now I have no idea of what could cause the issue. Did you notice an increase in the number of games created ?

**Comment by nwai90** [comment]
I think there is a small chance that the while loops in this PR could go on indefinitely.

12/61 spaces on the board are ocean spaces. The odds of drawing an ocean space repeatedly are extremely low, but it is still present.

It may be better to set a MAX_RETRIES variable and definitively exit the loop once this limit is reached.

https://github.com/bafolts/terraforming-mars/pull/1015/files#diff-d7b67b82365015f361593b6a2d1d3f28R85

**Comment by bafolts** [comment]
The server was hung for 30 minutes straight which would have had to draw an ocean space a very large number of times in the millions. Seeing that `while (true)` merged recently it is worthwhile to attempt to leave that while loop. I am assuming there is an unseen issue which leads to infinite looping here.

**Comment by Ronnoc** [comment]
I got it...
sorry for bug
let idx = Math.floor(this.mulberry32() * (land_list.length + 1));

here land_list should be is_ocean

**Comment by Ronnoc** [comment]
I will create a PR to solve this

Sorry for that...

**Comment by bafolts** [comment]
I am also going to put up a PR to throw an error if these loops iterate more than 1000 times so the heroku site can stay up.
