### ISSUE TITLE
Bug: Solo neutral cities placed next to each other

### ISSUE THREAD

**Issue by SliceOfBread** [bafolts/terraforming-mars#1080]
When placing the neutral cities in solo mode, only legal spots are counted. After the first city is placed, the hexes adjacent to it are illegal and should be skipped.

![Screenshot from 2020-07-28 11-21-47](https://user-images.githubusercontent.com/13003705/88721318-449da080-d0f4-11ea-9dfe-d298833f4515.png)

**Comment by vincentneko** [comment]
Fixed and merged
