### ISSUE TITLE
Why did I lose?

### ISSUE THREAD

**Issue by Zolib80** [bafolts/terraforming-mars#1081]
I have played a solo game, and I have reached the maximum of every global parameter, but the games say 'Sorry, you lose'
Can someone explain this, please?
![Bug](https://user-images.githubusercontent.com/68651711/88727180-fbb30f80-d126-11ea-931b-786b073fff37.PNG)
Game id was 1957f56780fd

The same issue happened with the next game too: abed8ed213c4
![bug 2](https://user-images.githubusercontent.com/68651711/88729105-066fa380-d12b-11ea-9a2f-5cc723631c71.PNG)

**Comment by nwai90** [comment]
Did you select TR solo mode? If this option is selected you need to obtain 63 TR to win the game

**Comment by vincentneko** [comment]
Maybe we could rename the option from TR solo mode to 63 TR solo mode.

**Comment by Zolib80** [comment]
Yes, I have selected TR solo mode, however, I thought its only an option to win. My bad...
Thank you for the quick answers.

**Comment by nwai90** [comment]
We've updated the option text to make it clearer. Will close this issue
