### ISSUE TITLE
Player resources are not protected from removal

### ISSUE THREAD

**Issue by alrusdi** [bafolts/terraforming-mars#109]
We need a common solution for all the card resources (Animals and Microbes) and Plants to not be removed or stolen if someone has played a Protected Habitats card.

Solution should include an ability/function to select unprotected cards and players for aggressive actions and exclude protected cards and players.

There is also a Pets card disallowed to remove animals from it by any way. Final protection solution should include an option for it.

I think, best person to give us this solution is @bafolts 
What do you think?

**Comment by vincentneko** [comment]
I'm not sure if there is a real problem with Protected Habitats and Pets cards (I agree UI could be improved by not being able to select cards from protected players)

In the code I can see this for animals, so it seems that the player is protected.

---------------------------
Message for alrusdi : would you be interested in playing a game with me and another friend ?
If yes, drop me an email here : vincentneko@gmail.com
-------------------------------------------------

```
    public removeAnimals(
        removingPlayer: Player,
        card: IProjectCard,
        count: number): void {
      if (removingPlayer !== this && this.hasProtectedHabitats()) {
        throw new Error('Can not remove animals due to protected habitats');
      }
      if (card.name === new Pets().name) {
        throw new Error('Animals may not be removed from pets');
      }
      if (this.getResourcesOnCard(card) === 0) {
        throw new Error(card.name + ' does not have animals to remove');
      }
      this.removeResourceFrom(card, count);
    }
```

**Comment by alrusdi** [comment]
Ok, then it is probably false negative warning) I am closing an issue.
