### ISSUE TITLE
Feature request: warning for discard

### ISSUE THREAD

**Issue by vsrisuknimit** [bafolts/terraforming-mars#1095]
This situation happens to me a lot, not sure if that happen to you too. When Mars University or Pluto is in play, you may be prompted to discard a card. Too often, I did not realize the action is to discard; I thought it would be to play. So I will accidentally discard something that I mean to play.

Suggestion:

A) At the top right of the screen, floating so it follows as you scroll up and down, has a box that says the current action: "play", "discard", "gain floater", "place a city".

or

B) When discard action is selected or prompted, the save button changes color to red or change the text from simply "save" to "save to discard".

**Comment by ssimeonoff** [comment]
It would be nice the button "save" to change label based on the action that is being confirmed:
- play
- activate
- discard
- keep
- sell

**Comment by chosta** [comment]
I'll work on that. Seems like a nice improvement.

**Comment by chosta** [comment]
#1122

**Comment by chosta** [comment]
@vincentneko I think we can close this one

**Comment by vsrisuknimit** [comment]
either Mars U or Pluto, don't remember which one, still says save at the button instead of discard. I will try to verify.

**Comment by vincentneko** [comment]
> either Mars U or Pluto, don't remember which one, still says save at the button instead of discard. I will try to verify.

Yes, this will be fixed in an incoming MR, I'm closing this one.
@chosta Great addition to the game !
