### ISSUE TITLE
Helion Corp game breaking bug

### ISSUE THREAD

**Issue by numaanrally** [bafolts/terraforming-mars#1099]
When playing Helion, I chose to put a tile on Helis location that requires -6 loss to place a Water. At the time, I had $0, but 6 heat. The game allowed me to place the tile, but then deducted $6 from my account, giving me -$6. At first I thought I had lucked out! But then I got stuck trying to play my next turn. When trying to play an action from a card that I have enough heat to pay for, I tried but an error message prevented me from executing. I believe this is because a check is failing. 

![image](https://user-images.githubusercontent.com/19717045/89131872-03cfce00-d4de-11ea-9912-bf000b317e2c.png)

This broke the 4-player game not allowing me to continue or go back in any way.

**Comment by nwai90** [comment]
This is a bug indeed. It should remove 6 heat in this case since there is no MC available but Helion is still able to afford the -6 cost of placing the tile.

**Comment by vincentneko** [comment]
Fixed and merged
