### ISSUE TITLE
No check for steel or titanium amounts

### ISSUE THREAD

**Issue by vincentneko** [bafolts/terraforming-mars#11]
The game does not check the steel or titanium amount sent by player. I was able to pay with more steel that I had in stock and it resulted with a negative steel amount.

**Comment by bafolts** [comment]
An error will have to be thrown here:

https://github.com/bafolts/terraforming-mars/blob/master/src/Player.ts#L448

There are probably quite a few places where this not checked when paying with heat as Helion. I will do a subsequent pull request to fix all the places you can pay with heat when Helion.

**Comment by bafolts** [comment]
This has been fixed and will check steel, titanium, and mega credits amount passed. More work will need to be done to check this for heat.
