### ISSUE TITLE
Negative megacredits on Hellas

### ISSUE THREAD

**Issue by etiennepetit** [bafolts/terraforming-mars#1107]
I had 18 megacredits, playing on Hellas. Then, I played Lava Flows (cost: 18M) on the southmost tile with ocean and -6M as placement bonus. I was actually allowed to place the tile there and ended up with -6M, after placing the ocean.

**Comment by vincentneko** [comment]
EcologicalZone may be subject to the same bug.

**Comment by nwai90** [comment]
Closed as resolved in https://github.com/bafolts/terraforming-mars/pull/1108
