### ISSUE TITLE
Is there any way to know what building card Factorum draw?

### ISSUE THREAD

**Issue by charlielam** [bafolts/terraforming-mars#1114]
as title, when a player decide to use Factorum's corp action, he reveals the top deck until he find a building card, it seems that we can only know what cards he discarded, but no way we can know what building card did he get.  Are we missing a message that show what card did he get?

**Comment by nwai90** [comment]
@charlielam I'll take a look at this

**Comment by nwai90** [comment]
Fixed and merged in https://github.com/bafolts/terraforming-mars/pull/1115
