### ISSUE TITLE
Turmoil Global Event "Revolution" counting player with Earth tag+ Influence "at least 1"?

### ISSUE THREAD

**Issue by charlielam** [bafolts/terraforming-mars#1116]
as title, we are having a game which one players have 1 (EarthTag + Influence), other 3 players have 0 (EarthTag + Influence), it turns out other 3 players was being reduced TR even the total of (EarthTag + Influence), as the description on the event card said (at lease 1), does it means player with 0 (EarthTag + Influence) will not reduce TR?

**Comment by vincentneko** [comment]
Looks like a bug. Just checked the code, there is no check that (EarthTag + Influence) should be greater than 0.
Will submit a PR for this.
Thanks for the feedback.

**Comment by nwai90** [comment]
Fixed and merged in https://github.com/bafolts/terraforming-mars/pull/1117
