### ISSUE TITLE
Options for standard project display incorrectly when helion

### ISSUE THREAD

**Issue by bafolts** [bafolts/terraforming-mars#112]
When playing as helion the included extra options of how to pay leads to an incorrect display for at least standard project.

```
Pay for a standard project
Select how to pay for power plant
Select how to pay for asteroid
Select all
Select all
Select all
```

**Comment by vincentneko** [comment]
The "Select all" dislay is the AndOptions default title.
I tried to add another constructor with a title parameter but got the 
"multiple constructor implementations are not allowed" error message.

So my question is should we modify AndOptions constructor with a title parameter and update all call or is there a better way to do it ?

**Comment by bafolts** [comment]
Setting the `title` property after the `AndOptions` object is instantiated will work fine. Most of the `AndOptions` should eventually go away. More specific components would be helpful. Having to click `Save` multiple times while filling out the generic `AndOptions` is not a great experience. For the time being setting the `title` property after instantiating the object is simple and quick fix.

**Comment by vincentneko** [comment]
Fixed and merged
