### ISSUE TITLE
TR increase when Red is ruling

### ISSUE THREAD

**Issue by etiennepetit** [bafolts/terraforming-mars#1121]
As far as I know, the 3MC cost of a TR increase when the Red party is ruling is optional, you can choose not to pay it and not get the TR while still increasing temp/oxygen/other stuff. I would suggest to add a textbox when increasing your TR while Red is ruling to ask if you're willing to pay 3MC.

Forgetting that Red is ruling and still increasing your TR is a common thing, this addition would let you notice your mistake.

**Comment by nwai90** [comment]
> As far as I know, the 3MC cost of a TR increase when the Red party is ruling is optional, you can choose not to pay it and not get the TR while still increasing temp/oxygen/other stuff. I would suggest to add a textbox when increasing your TR while Red is ruling to ask if you're willing to pay 3MC.
> 
> Forgetting that Red is ruling and still increasing your TR is a common thing, this addition would let you notice your mistake.

Is there an official ruling on this? As far as I'm aware, it is mandatory for all effects have to be applied other than the famous three exceptions (gaining card resources, raising a maxed out global parameter, removing other players' resources / production): https://boardgamegeek.com/thread/2009076/article/29316424#29316424

Maybe it will be helpful to add a confirm popup to warn the player that he/she will have to pay 3 MC more for each TR step raised while Reds are ruling.

**Comment by SliceOfBread** [comment]
It is mandatory.
https://boardgamegeek.com/thread/2196388/article/31885882#31885882

**Comment by etiennepetit** [comment]
> It is mandatory.
> https://boardgamegeek.com/thread/2196388/article/31885882#31885882

Wow, I'm sorry for the wrong infos.. I remember reading something in the rulebook stating that it was possible to deny the TR increase if you didn't feel like paying 3MC, I guess my memory failed me this time!
