### ISSUE TITLE
Strange card selecting bug on initial hand

### ISSUE THREAD

**Issue by mloballer** [bafolts/terraforming-mars#1127]
So I was playing a game, selected all my cards and hit save. There was an orange outline around them, so I know they were all selected. I got the error message not enough cards selected, so I thought I forgot to select a prelude or corp, but I saw that it was selected, so I decided to unselect and reselect my cards, and then I decided to change my mind and select capital ( didn't chose this one in the first try). After I selected, it somehow bought 5 cards, and doubled local shading and research outpost (the two cards I originally chose), not sure how.

![image](https://user-images.githubusercontent.com/10591526/89851654-d7e9c380-db41-11ea-86f3-7706c4fb968f.png)

**Comment by chosta** [comment]
Thanks for the nice description. I'll try to recreate this.
We have to add a backend exception to not allow card duplication in the initial selection IMO anyway.

**Comment by Lynesth** [comment]
Was able to reproduce. Will submit a fix.
