### ISSUE TITLE
"Smaller cards" selection problem 

### ISSUE THREAD

**Issue by chosta** [bafolts/terraforming-mars#1130]
@ssimeonoff 
It seems that "smaller cards" options breaks the new (and awesome) card highlighting

![smaller-cards](https://user-images.githubusercontent.com/836179/89868440-7a925880-dbbb-11ea-9ab5-b8158ac08010.png)

Also I noticed that in the initial phase the board is showing NaN for oceans.

![nan](https://user-images.githubusercontent.com/836179/89868578-b3323200-dbbb-11ea-85be-e9fea50648bf.png)

**Comment by chosta** [comment]
Also, I think the yellow that we used to mark the already terraformed global parameters looked good. It gives the feeling that you've made progress. The new marker is awesome but I'd suggest we add the coloring back :)

**Comment by ssimeonoff** [comment]
ugh, yes, please remove the 
`transform` property for selected cards.

**Comment by chosta** [comment]
We can close this one
