### ISSUE TITLE
Funded awards to show winner at a glance

### ISSUE THREAD

**Issue by chosta** [bafolts/terraforming-mars#1132]
it might be nice to see, without opening the Awards tab, who is winning the funded awards, because now we only get the award name, and the cube of the person who funded it. But it could just show the stat tracking bubbles (like when you open the tab) but only for the funded awards.

(as suggested by Krivis in discord)

**Comment by alrusdi** [comment]
There are possible more than one winner, and second place is also important. Too hard to fit this info in small box. Let's reject this FR?

**Comment by nwai90** [comment]
@alrusdi I'm good with that. The full info is available when the awards tab is opened
