### ISSUE TITLE
Board issue during turmoil initial phase

### ISSUE THREAD

**Issue by chosta** [bafolts/terraforming-mars#1133]
During the initial draft, when you open the ">Board" tab, and under the turmoil board, press the "Policies" tab, it closes the whole ">Board", but inside it remembers that you opened the policies, so you have to open board again to see them

(as suggested by Krivis in discord)

**Comment by Lynesth** [comment]
@chosta Is that still an issue ?

**Comment by chosta** [comment]
@Lynesth was fixed but can't find the PR
