### ISSUE TITLE
Wiki: adding instruction on how to run the web app on Heroku to this repo Wiki

### ISSUE THREAD

**Issue by vsrisuknimit** [bafolts/terraforming-mars#1136]
Can someone add this to the wiki? https://www.notion.so/TM-web-app-on-Heroku-6e0e700d889b473c9b36f0b214f1bbca

**Comment by nwai90** [comment]
Done at https://github.com/bafolts/terraforming-mars/wiki/Heroku-Setup. You'd need to make the objects in the S3 bucket public for the images to display correctly though

**Comment by vsrisuknimit** [comment]
How can I edit the wiki page? Here are the images but on IMGUR: https://imgur.com/a/zKJgNHO

**Comment by vsrisuknimit** [comment]
I would also like to fix line 5 on the installation part to just git clone https://github.com/bafolts/terraforming-mars.git. Remove the url link tag.

**Comment by nwai90** [comment]
@vsrisuknimit Done, will close this
