### ISSUE TITLE
Turmoil Reds party policy terraforming bug

### ISSUE THREAD

**Issue by KrivisLTU** [bafolts/terraforming-mars#1144]
I increased temperature by paying 8 heat, and the Reds party policy took me to negative MC:

![image](https://user-images.githubusercontent.com/69604652/90069172-97817580-dcfa-11ea-9f4d-fdd24f71e9c6.png)

**Comment by vsrisuknimit** [comment]
Another bug to add to Reds. I had 16 mc left and Black Polar Dust. The app does not allow me to play this card while the Reds is ruling, thinking that I don't have enough mc to pay. However, that 3mc loss is an effect, which I must be able to resolve and I can resolve at any time, including after putting the ocean (from Black Polar Dust) next to other oceans to gain the extra mc for payment.

Source: https://boardgamegeek.com/thread/2352956/question-about-turmoilreds

![download (4)](https://user-images.githubusercontent.com/14239220/90078894-4e1e2f80-dcd4-11ea-99ea-8696a71df19e.png)

**Comment by vsrisuknimit** [comment]
The resource dashboard does not show up on screen capture, sorry.

**Comment by nwai90** [comment]
Fixed and merged in https://github.com/bafolts/terraforming-mars/pull/1145. Also fixed same issue that occurs when spending 7/8 plants to place a Greenery that raises oxygen.

**Comment by nwai90** [comment]
@vsrisuknimit The issue you raised is related to https://github.com/bafolts/terraforming-mars/issues/931.

We'd need to implement a way to check total MC gained from each possible tile placement and decide whether the spot is valid or not. This will be more complicated though

**Comment by vsrisuknimit** [comment]
@nwai90 should I open my issue separately? I have suggestions to make as well.

**Comment by nwai90** [comment]
@vsrisuknimit Sure, let's do that. It is quite different from Manutech's edge case IMO and should be handled as a separate issue
