### ISSUE TITLE
UI suggestion: Add "MAX" option next to all increment box options

### ISSUE THREAD

**Issue by duckmammal** [bafolts/terraforming-mars#1147]
There are so many times throughout the game you need to use tiny arrows and click lots of times to remove a bunch of cubes because you're not sure how many are on a card, like Titan Shuttles, or Sulfur Eating Bacteria. 

Or Philares getting resources for placing next to someone.

Whatever the option is, having a max button, to make the number go as high as possible (but still be able to be adjusted) would make life a lot easier.

**Comment by nwai90** [comment]
Fixed and merged
