### ISSUE TITLE
Luna Governor Interactions

### ISSUE THREAD

**Issue by duckmammal** [bafolts/terraforming-mars#1148]
Earth Office (and probably Terractor too) should have 2x 3 MC = 6 MC total discount for Luna Governor, making it be free, not 1 MC.

**Comment by vincentneko** [comment]
Effect: When playing an Earth **card**, you pay 3 MC less for it

It's not per badge, it's per card, so it is working as expected.

**Comment by nwai90** [comment]
@vincentneko I saw that the designer gave a thumbs up to agree that Teractor and Earth Office should give discount per Earth tag here: https://boardgamegeek.com/thread/2173302/article/31568994#31568994

It's also discussed in a few other threads like this one: https://boardgamegeek.com/thread/2070625/two-tags-and-discounts

This was a non-issue before Luna Governor was released; it seems that the wordings of Teractor and Earth Office are actually misleading as they are intended to count per Earth tag.
