### ISSUE TITLE
Red Policy Bug: cannot play card if no mc left to pay Reds policy despite placement bonus

### ISSUE THREAD

**Issue by vsrisuknimit** [bafolts/terraforming-mars#1152]
**Bug**: The app does not allow you to play a card if you are left with too little mc to pay the Reds policy -3mc/TR, even though you could potentially get some mc back from tile placement next to oceans.

**Example scenarios**: 

(1)start with 16 mc, play a card Black Polar Dust costing 15 mc, 1 mc left, place ocean next to another ocean, gain a TR, gain 2 mc back, now has 3 mc left, pay 3mc to the Reds policy.

(2)start with 10 mc, play Nuclear Zone, 0 mc left, place the nuclear zone tile next to three oceans, gain 6 mc back, raise temp 2 steps, pay 6 mc to the Reds policy

This situation could also apply to gaining mc back from rebate: Media Group, Optimal Aerobraking. I have not tested. Those should be easier to fix though.

**Suggestion**: It would be very hard to check all possible ways to gain mc for this situation. While Reds are running, make a special case for cards that give TR AND allow tile placement. Give the user a warning of much they have to pay at the end of this action. At the end of their action, ask them to pay (with mc or heat if Helion). Also give the user of the option, "cannot pay". If the user pick this option, just force undo the action.

Source: https://boardgamegeek.com/thread/2352956/question-about-turmoilreds

**Comment by nwai90** [comment]
One other possible approach is to precompute the MC gain from each tile placement spot, and use this info to decide (1) whether a card is playable / whether an action can be performed, and (2) filter out the spots that don't meet the criteria.

So a card could be playable but only have one or two valid placement spot that give sufficient bonus MC from adjacent oceans to cover any required cost/tax. In general I see three scenarios:

- Player's remaining MC + placement MC bonus < 9 for Hellas bonus ocean tile while Reds are ruling and there are oceans remaining
- Player's remaining MC + placement MC bonus < 6 for Hellas bonus ocean tile while Reds are not ruling or Turmoil expansion is not selected
- Player's remaining MC + placement MC bonus < 3 * TR steps raised for other cards/actions that place any type of tile while Reds are ruling

**Comment by vsrisuknimit** [comment]
@nwai90 Things to consider with your solution:
(1) For Giant Ice Asteroid or Ice Asteroid: will you precompute all possible combos for the two ocean placement?
(2) On Hellas map, Helion could gain heat (near south pole or center ocean) from tile placement and also use that as mc to pay back the Reds.
