### ISSUE TITLE
Search for Life improvements

### ISSUE THREAD

**Issue by nwai90** [bafolts/terraforming-mars#1153]
- Iconography should be "3:science", not "3/science" as it is always 3 VP regardless of number of resources
- Move SearchForLife action to end of list if it already has at least 1 science resource

**Comment by vsrisuknimit** [comment]
![image](https://user-images.githubusercontent.com/14239220/90120702-0b3a7700-dd29-11ea-868b-a993c306dce6.png)

**Comment by chosta** [comment]
I'm on it

**Comment by chosta** [comment]
@nwai90 we can close this one I think
