### ISSUE TITLE
(Minor) Incorrect implementation of rules regarding Mons Insurance

### ISSUE THREAD

**Issue by HubrisW** [bafolts/terraforming-mars#1158]
Mons Insurance ability triggers when a player "steals" his own resources, for example by using Ants on his own microbes or Predators on his own animals. In other words: moving around your own microbes nets you 3MC from the Mons Insurance player. Witnessed in a game on our own server, if necessary logging can be provided. 

The wording for Mons Insurance is a bit ambiguous, so I asked the maker of TFM for his ruling. He clearly states that the player receiving the hurt, must be another player than the one dealing the hurt. 

![TM_ruling_Mons](https://user-images.githubusercontent.com/69674185/90237585-cc89e700-de24-11ea-8c9b-91619fb8eee6.jpg)

**Comment by nwai90** [comment]
@HubrisW This has been raised in https://github.com/bafolts/terraforming-mars/issues/1150 and patched in the recent commit https://github.com/bafolts/terraforming-mars/commit/1b8ba1ce723341d5e94a274d11c5b383d186dbd7. Could you pull the latest version?

**Comment by HubrisW** [comment]
> @HubrisW This has been raised in #1150 and patched in the recent commit [1b8ba1c](https://github.com/bafolts/terraforming-mars/commit/1b8ba1ce723341d5e94a274d11c5b383d186dbd7). Could you pull the latest version?

Ah very sorry, I thought I looked thoroughly, but it seems I still overlooked #1150. We will pull the latest version.

Thanks for the quick response.

**Comment by nwai90** [comment]
👍 Will close this issue
