### ISSUE TITLE
Add Event Log to Solo Mode

### ISSUE THREAD

**Issue by duckmammal** [bafolts/terraforming-mars#1162]
I'm sort of confused as to why you can't see the event log in Solo Mode.

There are many times when you, e.g., look at the top cards of the deck until you see a card of type X, and knowing which cards are out of the game is often important.

Is there a reason it's not in the solo game?

**Comment by chosta** [comment]
You are correct. It is sometimes important to see which cards got discarded and by not having the log its impossible to know.
@vincentneko Do you think an option in start screen to toggle log for solo-mode is appropriate? We can organize the start game options a bit better by grouping them. @ssimeonoff ideas?

**Comment by vincentneko** [comment]
An option in game preference panel should be better imho.

**Comment by chosta** [comment]
Yes, that would do it. I'll see if I can add this.

**Comment by vincentneko** [comment]
Done and merged
