### ISSUE TITLE
Confirm Button for Standard Power Plant has no text

### ISSUE THREAD

**Issue by duckmammal** [bafolts/terraforming-mars#1163]
It's a Purple button that works, but has no text on it.

It's a bit confusing.

**Comment by chosta** [comment]
I couldn't recreate this.
Tried it in solo and multiplayer. It would be great if you can be more specific as how it happened.

**Comment by SliceOfBread** [comment]
I had this happen. Forgot to submit. Here's a pic. (This was in solo.)
![image](https://user-images.githubusercontent.com/13003705/90316936-c57dda00-def3-11ea-8036-9f7deeae498f.png)

**Comment by nwai90** [comment]
Resolved in https://github.com/bafolts/terraforming-mars/pull/1169
