### ISSUE TITLE
Great dam discrepancy

### ISSUE THREAD

**Issue by KrivisLTU** [bafolts/terraforming-mars#1173]
Playing Great Dam displays it in the 'Last Actions' section as 'Great Dam Promo'.

**Comment by vincentneko** [comment]
Great Dam now have 2 versions, do you have another idea on how to distinguish them ?

**Comment by nwai90** [comment]
@KrivisLTU I recall that making both the same name caused some issues

**Comment by KrivisLTU** [comment]
good point, didn't even realize there were two cards with the same name.
