### ISSUE TITLE
Funded award UI improvement

### ISSUE THREAD

**Issue by KrivisLTU** [bafolts/terraforming-mars#1177]
@chosta 

![mockup](https://user-images.githubusercontent.com/69604652/90372381-00f5e100-e079-11ea-90f5-dde9cbeafb75.png)

**Comment by chosta** [comment]
@pierrehilbert lets try assignment again :)

**Comment by alrusdi** [comment]
@chosta isn't it complete? Can we close this issue?

**Comment by chosta** [comment]
@alrusdi not yet. It's at the bottom of my list at the moment :)

**Comment by chosta** [comment]
@alrusdi  I think this needs to be closed again as #1322 replaces current design and does not allow for this implementation.
