### ISSUE TITLE
Bug: red policy

### ISSUE THREAD

**Issue by jijiqw** [bafolts/terraforming-mars#1195]
![image](https://user-images.githubusercontent.com/16096558/90914469-8f1eee00-e410-11ea-89da-cadcee63f1c8.png)

![image](https://user-images.githubusercontent.com/16096558/90914460-86c6b300-e410-11ea-890d-bf91e47b0476.png)

![image](https://user-images.githubusercontent.com/16096558/90914488-96de9280-e410-11ea-94ea-c075eb2bacca.png)

![image](https://user-images.githubusercontent.com/16096558/90914499-9c3bdd00-e410-11ea-805a-6553fe78dfde.png)

Can't play the "SULPHUR EXPORTS" with 20MC + 5 floats  when  the Reds is ruling. I guess the "Psychrophiles" has a similar 
 problem

**Comment by vincentneko** [comment]
Fixed and merged
