### ISSUE TITLE
Main page improvements

### ISSUE THREAD

**Issue by vincentneko** [bafolts/terraforming-mars#121]
Current main game page is quite big and requires a lot of scrolling when playing, specially with multiplayer game.
Here is a draft for a more compact page, with buttons that would toggle display for corporation, cards in hand, played cards and milestones / awards and also other players (same as what we have now but located here along with player turn order)

Please let me know your opininion about that.

![tfm_main_screen](https://user-images.githubusercontent.com/56086992/71305622-fe05fc00-23d6-11ea-857a-3957302ae4ab.jpg)

**Comment by alrusdi** [comment]
I want resources widget to be horizontal and to stick it to the top of the window. Like this but without trademarked images and "Resources" caption
![res](https://user-images.githubusercontent.com/394311/71306999-f7dd4300-2409-11ea-88b5-824785456355.png)

**Comment by vincentneko** [comment]
This looks great !

**Comment by alrusdi** [comment]
Also i dream about black/thematic background like ssimeonoff done on his respective cards list https://ssimeonoff.github.io/cards-list

And css framework to change to something futuristic to get UI like this:
https://creativemarket.com/clusterx/714946-Futuristic-user-interface-elements

But i think we should do small steps to make it real.

**Comment by alrusdi** [comment]
If you agree with my idea with resources bar, then in the place of resources on your blueprint we can show "Tags breakdown", "Turn order" and toggles. Feel free to start markup for them. I can help you if some element will bee too time-consumpting to implement

**Comment by vincentneko** [comment]
Yes I agree. And I also agree smalls steps are better.
Tag breakdown is also a good idea that will lead to less time spent on counting them !
About the markup, I'm not sure what you mean. If it's graphics design I'm afraid I'm very bad at this.

**Comment by bafolts** [comment]
I have no strong opinions about the user interface. I think what @alrusdi has put up so far is great. All the user actions now which show up at the bottom would probably be better performed in a modal of some kind instead of having to scroll down to the bottom.

**Comment by bafolts** [comment]
The resource bar looks great!

**Comment by alrusdi** [comment]
Next step - floating sidebar with links and preferences dialog

**Comment by vincentneko** [comment]
This is awesome !

**Comment by vincentneko** [comment]
@alrusdi thanks a lot for all the enhancements !
May I close this issue ?
