### ISSUE TITLE
Potential bug with Pristar corporation

### ISSUE THREAD

**Issue by bafolts** [bafolts/terraforming-mars#1214]
I received an email from a player with a potential bug

> I think I noticed a bug with Pristar corp yesterday (played with Turmoil) in which no resources were added to the card even though conditions were met. Are you guys aware of that one? I hate to think that it cost me the game, but at the very least, if you can verify that, I can go and amend our scoring that we keep track of :)

**Comment by Lynesth** [comment]
Did you get more info about this ? I don't see how I could try reproducing the problem.

**Comment by kevinb9n** [comment]
One possibility: Might have been gen 1 and the player had terraforming preludes.....

**Comment by kevinb9n** [comment]
Maybe it was already fixed or was a mix-up. I am sure we would have heard about it again by now,
