### ISSUE TITLE
Feature request: Fast mode - remove option to end turn.

### ISSUE THREAD

**Issue by vsrisuknimit** [bafolts/terraforming-mars#1220]
Fast mode: remove the option to end turn. Players now must take two action, one action and pass for the generation, or just pass. (The player will have to sell a card for one action if they want to stay in for longer.)

Suggested by Kyshantry.

**Comment by markanarmi** [comment]
I like it as an option. I like all the options!

**Comment by chosta** [comment]
I like it too. It takes away the original rule but adds a strategical element as you might want to increase your free actions count if you want to be the last to act.

**Comment by vincentneko** [comment]
Done and merged.
