### ISSUE TITLE
Minor feature request: an option to cancel trade with colonies

### ISSUE THREAD

**Issue by vsrisuknimit** [bafolts/terraforming-mars#1224]
Currently once you pay for the trade (mc, energy, or titanium), the game offer you choices of which colonies to trade but with no way to back out. Occasionally users realize too late that their desired colonies have been traded and want to back out of trading.

![image](https://user-images.githubusercontent.com/14239220/91611087-6d5dc380-e948-11ea-839e-b8e720c774d7.png)

**Comment by vincentneko** [comment]
Fixed with rework
