### ISSUE TITLE
Feature request: side bar short cut for colonies

### ISSUE THREAD

**Issue by vsrisuknimit** [bafolts/terraforming-mars#1232]
I propose adding a short cut to move the page to colonies. The shortcut can be between cards shortcut and option setting. The image of the shortcut can be a rocket or shuttle that we already have colony trading.

![image](https://user-images.githubusercontent.com/14239220/91663464-f430ae80-eab6-11ea-83b0-7d11b48f5ec7.png)

**Comment by ssimeonoff** [comment]
colonies should be reworked so you dont have to scroll to the bottom at all

**Comment by vsrisuknimit** [comment]
Disagree. I prefer that it is not hidden and requiring a click to get there.

**Comment by vsrisuknimit** [comment]
@ssimeonoff I see what you mean now with your design, not having to scroll just before the trade. I don't think the colonies should be hidden to require a click to show though.

**Comment by alrusdi** [comment]
It is seems to be done
