### ISSUE TITLE
Bug with cards that remove other players' production

### ISSUE THREAD

**Issue by Maelstrom1** [bafolts/terraforming-mars#1234]
When someone plays a card that decreases another player's production by a set amount and no one has that production, it reduces that person's production. No option is given to not decrease a player's production, which is allowed by the rules, and simply allowing this would solve the issue. Some screencaps of the offending logs:
https://i.imgur.com/sibUL66.png
https://i.fiery.me/6bxSn.jpg

**Comment by nwai90** [comment]
@Maelstrom1 This is not correct. Production decreases are mandatory; in this case if your opponents don't have it you must target yourself. See the following:

https://boardgamegeek.com/thread/1665700/production-reduction-another-player-red-border-squ
https://boardgamegeek.com/thread/2152809/remove-production-any-player-optional
https://boardgamegeek.com/thread/1802890/great-escarpment-consortium-requirement-any-player

**Comment by Maelstrom1** [comment]
aaaaaaaaaaaaaaaaaaaaa I could have sworn it said "may decrease"
How did I miss this in 50+ games of TFM?
