### ISSUE TITLE
Start values for oxygen and temperature not highlighted

### ISSUE THREAD

**Issue by nwai90** [bafolts/terraforming-mars#1239]
Minor CSS issue: Only Venus start value is highlighted on initial card selection screen

<img width="709" alt="Screenshot 2020-08-31 at 9 26 34 PM" src="https://user-images.githubusercontent.com/2408094/91725274-1585bd80-ebd1-11ea-9c2e-7ce70240c290.png">

**Comment by kberg** [comment]
![image](https://user-images.githubusercontent.com/413481/97131253-08d99d80-171a-11eb-823a-257d73a2fc19.png)
Looks fixed to me.
