### ISSUE TITLE
Confirm Tile Placements

### ISSUE THREAD

**Issue by B0Bftl** [bafolts/terraforming-mars#1240]
When Placing a Tile, a click or tap on the Map instantly places the Tile. In Combination with the automatic selection of "Place Greenery" if you have sufficient plants, this is a constant source for misclicks. Happened to me multiple Times :( 

It would be a lot user friendlier, if you had to confirm your Placement. It would also be more consistent with other actions, as you have to confirm everything else.

My proposed UI: After Selecting a space, the placed tile flickers on the selected spot. Below the map, you can press "Confirm". Until Confirm is pressed, you can reselect any other (valid) space.

**Comment by alrusdi** [comment]
If someone will do this - please make it optional (via Preferences). It can slowdown the game.

**Comment by K-Hartmann** [comment]
The Problem ist paticulary frequent wenn using a mobile device, scince scrolling and zooming requires clicks on the map, but without scrolling it is hard to precisely click on the rather small map.

As an additional idea, if the placement of greenerys would not be the default option whenever you have sufficient plants, it would at least be required to actively choose to place a greenery. This would remove the annoying situation where you scroll down from the top of the page, and accidently place a greenery bevor even realising that the option is active.

**Comment by kevinb9n** [comment]
My wife got hit with that yesterday (the auto-selection of the greenery option). She had, or believed she had, chosen to place a city, but then inadvertently clicked somewhere else (?) before clicking the map and suddenly a greenery was there.

**Comment by VanderLeal** [comment]
I would suggest that instead of making this "mandatory OR optional" to use a processual roll-back to be available. 
This would cover both bases.

Example: 
1. You pick the action.
2. You're asked to place a tile.
3. You place the tile (by choice or by accident). 
4. An "Undo Tile Placement" button shows up (as the undo turn). 
5a. If you choose any other action then you move on (go to step 6). 
5b. If you click Undo Tile Placement, you're asked to place the tile again (go to step 2).
6. End

**Comment by B0Bftl** [comment]
An 'Undo' Method is impracticle, as there are Card draw bonuses. Once you've drawn the card, undoing is quite like cheating.

I think a simple confirmation is the cleanest solution. Its only downside is one additional click, which imo does no harm. It rather increases intuitivity and robustness

**Comment by kberg** [comment]
I agree, optional confirmation seems the way to go.

**Comment by VanderLeal** [comment]
> An 'Undo' Method is impracticle, as there are Card draw bonuses. Once you've drawn the card, undoing is quite like cheating. It also does not work, if the tile placement is your second, hence last action.
> 
> I think a simple confirmation is the cleanest solution. Its only downside is one additional click, which imo does no harm. It rather increases intuitivity and robustness

B0B, is not an "undo" per se... It's a passive "cancel button" for you to cancel the placement, but if you click somewhere else (like next action) it would settle the placement and move on. Point was to avoid a "Confirm Tile Placement? Yes/No" mandatory, when majority of times you place it properly (yet allowing a "omg moment, where you can ask to undo the placement and be asked again where to).

Cheers

**Comment by kberg** [comment]
Given how often I place tiles on the board, active confirmation isn't much of a cost. But I wouldn't mind if confident people wanted to turn it off.

**Comment by Lynesth** [comment]
This has been implemented.
