### ISSUE TITLE
Feature request: Improve trading with colony action

### ISSUE THREAD

**Issue by vsrisuknimit** [bafolts/terraforming-mars#1246]
As @ssimeonoff suggested 
![image](https://user-images.githubusercontent.com/14239220/91881959-4b1dbb80-ec50-11ea-9c96-812f02133127.png)

- reorder the trade options by popularity (an old suggestion) energy > tit > mc
- replace colonies text with the actual colony cards
- colony cards are selectable as the other cards

The priority should be the reordering of the trade option first. Replacing the colonies text with cards could come later.

**Comment by markanarmi** [comment]
Very nice

**Comment by vsrisuknimit** [comment]
So before this is done, we could still do another minor improvement in writing what you would gain for the trading with colonies.

Spend 3 energy
Spend 3 titanium
Spend 9 mc

To trade with

Ceres for 6 steels
Triton for 2 titanium (+1 colony bonus)
Europa for energy production (+1 mc bonus)

**Comment by chosta** [comment]
Where would the text go?
I think it gets too cluttered this way. It should be either an image or text description.

**Comment by vsrisuknimit** [comment]
It should be the image that is the ultimate goal. I don't know how difficult that would be, so I am suggesting this as a stepping stone.

So rather than saying ganymede (plant), it should say how many plants and perhaps colony bonus if you have colony.
Rather saying europa (production), it says energy production.

![image](https://user-images.githubusercontent.com/14239220/93208055-f1c28b80-f729-11ea-8ece-1bb7dca1eaf5.png)

**Comment by vincentneko** [comment]
Done and merged ! Yeah !
