### ISSUE TITLE
Major bug: board suddenly changes mid game.

### ISSUE THREAD

**Issue by vsrisuknimit** [bafolts/terraforming-mars#1248]
Today I saw two games where the board suddenly changed in the middle of a match.

In one game: it changed from Elysium to Tharsis. This change happened during a server update.
In another game: it changed from one randomly tiled board to another randomly tiled board.

**Comment by vincentneko** [comment]
I think it's related with a rework of game options pushed yesterday. I will look into it tomorrow.

**Comment by leggupdown** [comment]
This happened to me as well in two games before I gave up. I was playing solo and it happened when I went to place oceans in both cases, 4th and 7th gen.  The vocanic labels stayed the same but in both cases the board switched from Elysium to Tharsis.

**Comment by bafolts** [comment]
May be worthwhile rolling back https://github.com/bafolts/terraforming-mars/pull/1223 for time being.

**Comment by bafolts** [comment]
I have reverted the game options change hoping that this resolves the issue for time being. I don't believe the game options change was serializing data for the database. An undo operation or load of game from database would most likely have caused a game to go to default state when no game options were found.

**Comment by bafolts** [comment]
I believe this is resolved for time being. @vincentneko will have to consider storing the game options to database. With the game options change rolled back I can no longer recreate this issue easily. Was easy to recreate this by creating a game with any board besides tharsis and the undo action enabled. Upon performing one undo the board would then go to tharsis the default board.

**Comment by bafolts** [comment]
Games which were played and saves state with this bug are most likely a loss.
