### ISSUE TITLE
Game settings glitched out during a gen6 draft reload

### ISSUE THREAD

**Issue by turtler7** [bafolts/terraforming-mars#1252]
Returning to a turn based game during a draft sometimes snaps backwards.  That is fine and I assume is part of the undo feature.
This time suddenly the game was playing without draft, venus track was disabled (but playing a venus terraforming effect still gave terraforming), colonies suddenly stopped moving forward, realtime VP dropped off, and when someone played a card that dropped a colony (to get an ocean placement bonus) the error was unrecoverable.
the placed colony critical death moment:
https://cdn.discordapp.com/attachments/742721510376210583/750794280590639254/unknown.png
colonies frozen:
https://cdn.discordapp.com/attachments/750115828027883520/750794480608608286/unknown.png
game state right before the snapback:
https://media.discordapp.net/attachments/750115828027883520/750460828251062332/unknown.png?width=1395&height=1371
game state after the snapback (with a milestone claim and some venus pushing for experiment before taking screenshot)
https://cdn.discordapp.com/attachments/750115828027883520/750793363589955655/unknown.png

Game player links:
http://terraforming-mars.herokuapp.com/player?id=21c076f81247
http://terraforming-mars.herokuapp.com/player?id=a96df7d4cb5
http://terraforming-mars.herokuapp.com/player?id=575fa4bae8d5

**Comment by vincentneko** [comment]
Thanks for the report.
I think it's a side effect of a recent update that changed game options behavior.
