### ISSUE TITLE
Feature request: solo mode game id

### ISSUE THREAD

**Issue by vsrisuknimit** [bafolts/terraforming-mars#1261]
Solo mode game ID is currently not available until the end of the game. This id should be available right away so that two people can play solo games with the exact same hand at the same time without requiring one to finish a game first.

**Comment by vsrisuknimit** [comment]
Perhaps it should be available at the bottom of the screen? Not sure.

**Comment by alrusdi** [comment]
Why do you need it? To enter it to Set Predefined Game option?

**Comment by vsrisuknimit** [comment]
@alrusdi That is correct. In case two people want to play the same solo game at the same time.

**Comment by SliceOfBread** [comment]
It would also be handy if there is a bug that crashes the game (or the user decides not to continue) so that the game id can be reported.

**Comment by vincentneko** [comment]
Done
