### ISSUE TITLE
Bug: drafting to yourself while playing solo

### ISSUE THREAD

**Issue by vsrisuknimit** [bafolts/terraforming-mars#1263]
Recent server update (about 30 min ago) causes a solo game player to draft to themselves.

This happened mid game. There was no drafting until generation 7.

![image](https://user-images.githubusercontent.com/14239220/92407118-bca1b200-f107-11ea-9d9e-bc78de3df4a4.png)

**Comment by vincentneko** [comment]
This must be a glitch related to server restart with game options reworked.
Just started a solo game, this issue is not occuring

**Comment by vsrisuknimit** [comment]
Sounds good. I will close the issue.
