### ISSUE TITLE
Css broken for german word in StartScreen

### ISSUE THREAD

**Issue by moviedo** [bafolts/terraforming-mars#1264]
#1265  
German workd `Solo-Herausforderung` is overflowing into next anchor tag section.

<img width="406" alt="Screen Shot 2020-09-07 at 12 50 17 PM" src="https://user-images.githubusercontent.com/1228801/92415409-fbd6ff80-f115-11ea-87c4-5be31764e45c.png">

**Comment by nwai90** [comment]
Fixed and merged
