### ISSUE TITLE
Major bug issue - cards disappeared during initial draft

### ISSUE THREAD

**Issue by vsrisuknimit** [bafolts/terraforming-mars#1266]
During first pack - everything is shown

![image](https://user-images.githubusercontent.com/14239220/92417165-d60a2480-f12e-11ea-9fe4-6dc7a3582faa.png)

During second pack - preludes and corporations are gone.

![image](https://user-images.githubusercontent.com/14239220/92418239-7a429a00-f134-11ea-9b37-aac84a01ee9c.png)

During prelude draft - all project cards and corporations are gone.

![image](https://user-images.githubusercontent.com/14239220/92418296-c7267080-f134-11ea-9e66-23b048b7db03.png)

It is vital to know these cards to make a drafting decision.

**Comment by nwai90** [comment]
Fixed and merged
