### ISSUE TITLE
Helion is not working

### ISSUE THREAD

**Issue by vincentneko** [bafolts/terraforming-mars#127]
Cannot buy cards after reasearch phase (can input heat but MC are used instead)
Cannot use heat to play project cards (no input shown for heat)

**Comment by vincentneko** [comment]
I tried to debug this.
It seems that this.playerinput.canUseHeatAsMegaCredits is not defined in component SelectHowToPayForCards,

I've added a console log here:


```
        canUseHeat: function () {
            console.log("Inside canUseHeat "+ this.playerinput.canUseHeatAsMegaCredits + " " +this.player.heat);
            return this.playerinput.canUseHeatAsMegaCredits && this.player.heat > 0;
        },
```

Result is below:

Inside canUseHeat undefined 0

**Comment by alrusdi** [comment]
I hope this is fixed now
