### ISSUE TITLE
Start multiplayer issue

### ISSUE THREAD

**Issue by xaxablyat** [bafolts/terraforming-mars#1276]
Hi, I'm not sure if this is the right place to post but I am not able to start a multiplayer game. I've downloaded the game locally and managed to open port 8080 but I don't understand how to invite my friend. I've tried to send my public ip adress on the form http://xxx.yyy.zzz.ttt:8080/ and I've also tried to invite with different links like http://xxx.yyy.zzz.ttt:8080/player?id=d072d4b10e7.  When my friend tries to join I get these kind of error messages in my terminal
 Not found GET /?fbclid=IwAR0qk-PerqxAWGLjhN_hdFgTGuSZTmR4gM05X9uouE7NOaBSGO8xYsW24O4
Not found HEAD /game?id=426ebf2a74d2
no match with regexp
Not found GET /api/game?id=426ebf2a74d2&fbclid=IwAR0qk-PerqxAWGLjhN_hdFgTGuSZTmR4gM05X9uouE7NOaBSGO8xYsW24O4
Not found GET /api/player?id=d072d4b10e7&fbclid=IwAR0qk-PerqxAWGLjhN_hdFgTGuSZTmR4gM05X9uouE7NOaBSGO8xYsW24O4

and for my friend it usually From http://xxx.yyy.zzz.ttt:8080/ (but with my ip) unexpected server response. 

Does anyone know what to do?

**Comment by chosta** [comment]
Hi,
we highly recommend using Heroku setup for multiplayer games that are not in the same network. There is a very nice description on how to set it up here:
https://github.com/bafolts/terraforming-mars/wiki/Heroku-Setup

**Comment by vincentneko** [comment]
It's not really the right place to post this.
You can try to get help on the discord or review the documentation.
