### ISSUE TITLE
Minor feature request: cards in own hand indicator

### ISSUE THREAD

**Issue by vsrisuknimit** [bafolts/terraforming-mars#1290]
Next to the section title "Cards in Hand", add the number of the cards the player has, so it becomes "Cards in Hand (13)" for example.

This will help players keep track of cards in hand when they don't want to open up tags overview. There are some horizontal space there anyway.

![image](https://user-images.githubusercontent.com/14239220/93035472-0ceaa980-f60b-11ea-88a1-9f908af65bd4.png)

**Comment by nwai90** [comment]
Fixed and merged
