### ISSUE TITLE
Bug: influence tracker

### ISSUE THREAD

**Issue by vsrisuknimit** [bafolts/terraforming-mars#1295]
In the picture shown below, red player has two influence. This is incorrect.

Normally, you can achieve a maximum of 3 influence (1 for Chairman, 1 for Party Leader of the Dominant Party, 1 for any amount of non-Leader delegates in the Dominant Party).

The player confirmed that they did not have Event Analysts.

I believe there is a bug in the third case of influence. It should only count non-Leader delegate.

![image](https://user-images.githubusercontent.com/14239220/93080423-acd02380-f65b-11ea-844c-9b796effe033.png)

**Comment by nwai90** [comment]
Fixed and merged
