### ISSUE TITLE
Feature request: who won

### ISSUE THREAD

**Issue by kevinb9n** [bafolts/terraforming-mars#1298]
We just played a game -- really fun! -- and we were sorta curious to know who won. It seems like useful information that other people might want to have.

https://terraforming-mars.herokuapp.com/the-end?id=af0cbb3c6fd

It knows our names so perhaps it could include a message like "CR won!" or (my preference) "KB won!".

**Comment by vincentneko** [comment]
Good idea !

In this game you (KB) won. (in a tie with victory points, the one with the most MC win)
Players are sorted this way.

**Comment by kevinb9n** [comment]
Okay, it seems MC is the only tiebreaker, so there can (rarely) be multiple winners. So maybe instead of a "X wins!" heading, a simpler way is to just put a "winner!" icon/message of some sort on each winner's row. Just thinkin out loud.
