### ISSUE TITLE
Clicking on own name beneath "turn order" does nothing.

### ISSUE THREAD

**Issue by kberg** [bafolts/terraforming-mars#1299]
Underneath "Turn order (click on player name to see details)" I click on my opponent's name which expands their details.

I click on my own name and expect to see something, but in fact nothing happens. This is a surprising aspect. I would at least expect when hovering over my own name it didn't do anything. But I'd also like to to close my opponent's view.

**Comment by alrusdi** [comment]
It should be irrelevant with new UI
