### ISSUE TITLE
Mining Expedition doesn't show a minus sign before the red-bordered plant icons

### ISSUE THREAD

**Issue by kevinb9n** [bafolts/terraforming-mars#1303]
It should, right?

**Comment by alrusdi** [comment]
No, it shouldn't
https://ssimeonoff.github.io/cards-list#063

**Comment by kevinb9n** [comment]
Would you mind explaining why not?

The link seems to answer the question "does it", but I was asking "should it".

**Comment by kberg** [comment]
I think @kevinb9n has got a point, @alrusdi. 

https://ssimeonoff.github.io/cards-list#009
https://ssimeonoff.github.io/cards-list#010
https://ssimeonoff.github.io/cards-list#011
https://ssimeonoff.github.io/cards-list#039
