### ISSUE TITLE
Split Dealer's large card repo to projects

### ISSUE THREAD

**Issue by kberg** [bafolts/terraforming-mars#1305]
I'm proposing a change very much like this one

https://github.com/kberg/terraforming-mars/compare/master...kberg:card-refactor?expand=1

which moves package-level cards to their directories. Ares is a new one, which will also be impacted. Your thoughts?

**Comment by kberg** [comment]
Needs more work -- Game.ts for example, but lmk if this approach is something you like.

You can get the gist of this from CardManifest.ts, Dealer.ts, and any one or two of the specialized card manifests.

**Comment by nwai90** [comment]
@kberg I like it; it gives the project better structure re the card lists for different expansions. Let's wait for feedback from the other developers as well

**Comment by chosta** [comment]
@kberg I'm all for this. I also started making structure changes for the frontend. Players Overview module has its own dir `overview`.
We should try and keep things sorted in a logical way. This is extremely helpful imo.
There will be a bit of pain when merging these changes so lets keep them in small increments.
I'd like to hear from @bafolts on this too if possible.

**Comment by kberg** [comment]
Great. I don't like the term CardManifest, but Deck kind of causes some small problems I'd like to avoid. But if it were Manifest, then I could see starting to add some other pieces into it, shrug. But I've learned the hard way that turning Javascript code into generic callbacks can sometimes impact performance.

Two separate thoughts peripherally related.

**Comment by kberg** [comment]
I've made a very large update which changes a fair bit of stuff. Everything builds, nothing passes. I'd like a little more confidence that this change will be generally accepted (with appropriate comments) before I spend that much more time on it. I'm not quite sure who the primary deciders are on this team, but I'd like to hear that the direction is good and would welcome it.

**Comment by kberg** [comment]
(Naturally I'll fix the tests if I get an okay.)

**Comment by nwai90** [comment]
@bafolts @vincentneko

**Comment by vincentneko** [comment]
This is great !

**Comment by kberg** [comment]
This is fixed.
