### ISSUE TITLE
Undo after all other players pass

### ISSUE THREAD

**Issue by jrbarronumd** [bafolts/terraforming-mars#1309]
It seems like the undo function does not work after the first action taken by the last active player in a gen.  As example, in a 2-player game if one player passes and the other player has 8 actions left, that player cannot undo any actions after the first of those 8.

**Comment by alrusdi** [comment]
Indeed. It is reproducible

**Comment by bafolts** [comment]
The undo operation is of interest to me as it is also related to how we restore games from database. I may take a look at this after finishing serialization upgrade.
