### ISSUE TITLE
Feature request: separate big box promos from other promos

### ISSUE THREAD

**Issue by vsrisuknimit** [bafolts/terraforming-mars#1310]
I believe that the big box promo cards will be changed when they are officially released after more play testing.

It might be good to separate the big box promos from the already released promo cards.

**Comment by kevinb9n** [comment]
FYI, I haven't even be able to find hard evidence of what the exact altered versions of the three altered cards are going to be (Deimos Down, Great Dam, Magnetic Field Generator). That is, i know the changes made here are correct ones, but I don't know if there are other changes, or for example what tile placement restrictions might exist for the new special tiles.
