### ISSUE TITLE
During initial card choice, opening "milestones" deselects all project cards

### ISSUE THREAD

**Issue by kevinb9n** [bafolts/terraforming-mars#1316]
During initial card choice, opening "milestones" deselects all project cards.

**Comment by vsrisuknimit** [comment]
I believe @chosta is working on having boards/milestones/awards revealed by default during initial selection.

**Comment by chosta** [comment]
Yes, this one is being worked on atm.

**Comment by pierrehilbert** [comment]
@chosta, correcting this one should be pretty easy for you, you juste have to switch the toggle system to the "accordion" one (take a look at the board part in PlayerHome.ts to have a working example).

**Comment by chosta** [comment]
We can close this one.

**Comment by pierrehilbert** [comment]
The problem isn't solved, if we close the milestone part, it still deselects cards.

**Comment by chosta** [comment]
@alrusdi @pierrehilbert sorry about that. I thought the problem was in keeping the milestones and awards open during initial selection. Will work on the fix for "deselecting" now.

**Comment by chosta** [comment]
@pierrehilbert can you please confirm that this was fixed. Feel free to close the issue if so.

**Comment by kevinb9n** [comment]
Can confirm
