### ISSUE TITLE
Bug?: cannot see your own VP when real-time VP is off with the new UI

### ISSUE THREAD

**Issue by vsrisuknimit** [bafolts/terraforming-mars#1323]
With the new UI, when real-time VP is off, you cannot see your own VP. With the previous UI, you know your own VP regardless of whether real-time VP is on or off.

![image](https://user-images.githubusercontent.com/14239220/93652894-af78a300-f9e4-11ea-98e7-63ebe42578fb.png)

**Comment by nwai90** [comment]
Fixed and merged
