### ISSUE TITLE
bug. Undo makes crash server

### ISSUE THREAD

**Issue by AlexBurkov** [bafolts/terraforming-mars#1331]
After pressing "Undo" our server was crashed. I can attach some files if you need it

**Comment by AlexBurkov** [comment]
It is repeating after every undo action

**Comment by chosta** [comment]
Hi, how do you store your data in the backend:
SqLite or Postgres?
We have issues with the undo functionality and are trying to figure them out.

**Comment by AlexBurkov** [comment]
> Hi, how do you store your data in the backend:
> SqLite or Postgres?
> We have issues with the undo functionality and are trying to figure them out.

Wow, I don't know. I use "npm install" and "npm run start". So we use default settings

**Comment by kberg** [comment]
sqlite.

**Comment by kberg** [comment]
It's sqlite -- You can see this in the source file database/SQLite.ts

**Comment by AlexBurkov** [comment]
> It's sqlite -- You can see this in the source file database/SQLite.ts

But why can't I continue my game after crash?

**Comment by chosta** [comment]
You can, you need to delete the last turn record manually. @pierrehilbert can help
Also, we know about the crashes but its never the same thing. So we have to work on eliminating all of the problems.

**Comment by AlexBurkov** [comment]
> You can, you need to delete the last turn record manually. @pierrehilbert can help
> Also, we know about the crashes but its never the same thing. So we have to work on eliminating all of the problems.

That's great news. @pierrehilbert can you help me with it? How can I open sqlite connection and remove last record?

**Comment by AlexBurkov** [comment]
I tried continue game after restarting server without crash. But I couldn't. I can't find current game_id in table "games". What am I doing wrong?

**Comment by alrusdi** [comment]
> I tried continue game after restarting server without crash. But I couldn't. I can't find current game_id in table "games". What am I doing wrong?

Game restart skips error prone records. And your game is not restored as result

**Comment by pierrehilbert** [comment]
Hello @AlexBurkov, 
Have you any records in the games table (for other game_id)?
If you create a new game and play three turns, do you have them in the database?

**Comment by AlexBurkov** [comment]
> Hello @AlexBurkov,
> Have you any records in the games table (for other game_id)?
> If you create a new game and play three turns, do you have them in the database?

Yes, there are a lot of records in this table with other game_ids. And I am going try to create new game now and to play three turns for checking

**Comment by AlexBurkov** [comment]
> > Hello @AlexBurkov,
> > Have you any records in the games table (for other game_id)?
> > If you create a new game and play three turns, do you have them in the database?
> 
> Yes, there are a lot of records in this table with other game_ids. And I am going try to create new game now and to play three turns for checking

I tried to do it. But there aren't any records with that game_id

**Comment by pierrehilbert** [comment]
Did you check for the record after closing and reopening your connection on the sqlite?
If yes, please try to change rights on the file (chmod 777) and please try again to create a game and play three turns.

**Comment by bafolts** [comment]
This could be related to #1339 which seems something introduced JSON which is circular. At one point we were always storing a player as only the id of the player. If somewhere we have added storing a full player and not the id of the player that would cause this behavior.

**Comment by AlexBurkov** [comment]
I dropped file game.db and tried to repeat it. And it's working. My game was loaded.
So if our server is crashed we should remove the last record from "games" and it will work? Am I right?

**Comment by pierrehilbert** [comment]
Maybe it's just the circular that prevented to save.
If you reproduce the problem, we will be able to test other things.

**Comment by AlexBurkov** [comment]
Thank you very much for your help.

**Comment by alrusdi** [comment]
Please reopen this issue if you hit this problem again
