### ISSUE TITLE
Default option in radio button

### ISSUE THREAD

**Issue by AlexBurkov** [bafolts/terraforming-mars#1332]
When I am choosing option "Trade with colony", system sets first colony as default in radio button. I think it may be better if no option would be chosen by default.

**Comment by kevinb9n** [comment]
I feel like very few options should have any default choice selected at all.  Only when there is good reason behind it...

**Comment by bafolts** [comment]
Most likely no design reason behind the default selection and it is only there as a by product or how vue works.

**Comment by nwai90** [comment]
For blue card actions (and many other options) a default choice is good as it saves many clicks for the user. We would be effectively doubling the number of clicks required if there were no defaults.
