### ISSUE TITLE
Venus turmoil card while not playing with venus expansion

### ISSUE THREAD

**Issue by GJonatan** [bafolts/terraforming-mars#1338]
It's a very minor thing but I just played a game with all expansions except for Venus next. We got a turmoil card that gave MC based on venus tags.

**Comment by alrusdi** [comment]
Do you mean Global event not project card from Turmoil?
I mean... Was it:

Venus Infrastructure
Gain 2 MC per Venus tag (max 5) and influence.
?

**Comment by GJonatan** [comment]
It was on the form that you wrote, something like "Gain 2 MC per Venus tag (max 5) and influence."

**Comment by Maelstrom1** [comment]
this has happened _multiple_ times in the games I've played and it's impossible to remove without removing all the promo (I think). It's kind of infuriating.

**Comment by alrusdi** [comment]
this should be fixed now
