### ISSUE TITLE
Create a Spanish Translation

### ISSUE THREAD

**Issue by pocc** [bafolts/terraforming-mars#1346]
This is per a discord request/someone volunteering.

**Comment by keros17** [comment]
Hello people!

I'm doing the translation from the fanmade gigaexpansion and after that I could help with the translation from the program to the spanish language.

If the developer wants also the fanmade content translated there is no problem to giving you that ^^

Best regards,
Gerard

**Comment by alrusdi** [comment]
@keros17 great! Ask me if you will need any help

**Comment by keros17** [comment]
Thanks @alrusdi ^^
