### ISSUE TITLE
Bug: Negative titanium or energy after trading.

### ISSUE THREAD

**Issue by vsrisuknimit** [bafolts/terraforming-mars#1348]
A few people have reported seeing negative titanium or energy after trading.

![image](https://user-images.githubusercontent.com/14239220/93820357-0ec7f480-fc2b-11ea-9a2f-d0b1a647dedf.png)

A few information I gathered:
- The negative number does not disappear after a browser refresh.
- ~~The negative number seems to affect just the display. Negative energy was observed to not carry over to negative heat.~~
- This issue can happen to a player with NO double colony and NO double trading fleet.
- ~~It is difficult to reproduce.~~ I can now reproduce it consistently. See below.

**Comment by vsrisuknimit** [comment]
Addition information.
- This can happen in solo games.
- The negative number persists after the end of the generation. So not just display.
- If you have negative titanium, it will prevents you from playing any card even if the card cannot be paid with titanium.

![image](https://user-images.githubusercontent.com/14239220/93821733-fd7fe780-fc2c-11ea-86f9-389a06d9b03a.png)

- I can now reproduce the problem consistently. Here are the steps:
1) Click trade with colony but DO NOT SELECT any colony. Just click trade.

![image](https://user-images.githubusercontent.com/14239220/93821806-21dbc400-fc2d-11ea-96f9-aa3aadf2f248.png)

2) Receive an error

![image](https://user-images.githubusercontent.com/14239220/93821827-2bfdc280-fc2d-11ea-93dd-8726f99e9d45.png)

3) Trade again but this time select a colony to trade with

![image](https://user-images.githubusercontent.com/14239220/93821862-3fa92900-fc2d-11ea-96e7-28f3c6c8d1b9.png)

**Comment by vsrisuknimit** [comment]
The number of times you repeat step 1 and 2 results in the number of resource you have to spend.

You can easily get -12 energy by repeating the process 5-6 times.

![image](https://user-images.githubusercontent.com/14239220/93827442-4472da80-fc37-11ea-888b-1db9f818825f.png)

**Comment by vincentneko** [comment]
@vsrisuknimit great feedback thanks ! Will try to look into this asap.

**Comment by vincentneko** [comment]
Fixed and merged
