### ISSUE TITLE
Exclude all of .vscode/

### ISSUE THREAD

**Issue by kberg** [bafolts/terraforming-mars#1350]
I've made a change to .vscode/tasks.json to run prebuild by command-line. I now have three options: 1) commit that change, 2) add all of .vscode/ to .gitignore, or 3) manage that file myself.

(Global .gitignore isn't an option because I'm using mingw on top of windows. Perhaps stop using that is an option, too.)

The subject of the bug lists my preference. Please advise!

Thanks.

**Comment by alrusdi** [comment]
Best practices says to not distribute any IDE specific settings. I vote to remove .vscode folder from repo

**Comment by chosta** [comment]
I second @alrusdi

**Comment by alrusdi** [comment]
Fixed by @pierrehilbert
