### ISSUE TITLE
Minor bug: Pharmacy Union card text in game is incorrect.

### ISSUE THREAD

**Issue by vsrisuknimit** [bafolts/terraforming-mars#1357]
Science card draw should be upon corp reveal not first action.

Card from the web app

![image](https://user-images.githubusercontent.com/14239220/93877848-247aff80-fca7-11ea-8183-2654212d9bc8.png)

Card from Simon's db.

![corp40-pharmacy_union](https://user-images.githubusercontent.com/14239220/93877893-3bb9ed00-fca7-11ea-9176-c227baacff11.png)

**Comment by alrusdi** [comment]
May be it is time to introduce an interactive description widget here? I mean some kind of stylish questionmark symbol, it shows that huge description text when clicked

**Comment by nwai90** [comment]
Fixed and merged
