### ISSUE TITLE
Setting up crowd-sourced translation platform.

### ISSUE THREAD

**Issue by vsrisuknimit** [bafolts/terraforming-mars#1360]
We should have a platform for crowd-sourcing translations.

@alrusdi suggested Pontoon https://github.com/mozilla/pontoon.

Weblate is another alternative. https://weblate.org/

Poeditor is free with Open Source Intiative license.

**Comment by alrusdi** [comment]
Weblate is kinda 17€/mo
I can't manage Pontoon to work on localhost. it is installable on heroku, but requires paid account

**Comment by vsrisuknimit** [comment]
Weblate can be self-hosted, right? I am not sure how that will work.

Should we ask @bafolts to set up Pontoon since the demo server is already running on paid heroku?

**Comment by alrusdi** [comment]
i don't see self hosted variant of weblate. Can you give me a hint?

**Comment by alrusdi** [comment]
I give up on it. Weblate does not provide all the features we need too:
1) Can't edit once created translation key
2) Does not provide a simple way to export en_string => loc_string. It breaks the original strings by sentences

**Comment by vsrisuknimit** [comment]
@alrusdi back to Pontoon then?

**Comment by alrusdi** [comment]
> Pontoon then?

 Only if somebody other than me will do it. I can't figure out of how to deploy it to VDS
