### ISSUE TITLE
Bug: colony.endGeneration not a function

### ISSUE THREAD

**Issue by vsrisuknimit** [bafolts/terraforming-mars#1364]
Playing seeded solo. Aridor. Removed and then added a colony.

Finished first generation. Trying to do WGT and then received this error.

![image](https://user-images.githubusercontent.com/14239220/93998683-df1c0800-fd62-11ea-89ea-1fcef27d0923.png)

**Comment by vsrisuknimit** [comment]
Here is the seed: dbbae2037a5c

**Comment by vsrisuknimit** [comment]
![image](https://user-images.githubusercontent.com/14239220/94001174-25bf3180-fd66-11ea-8377-efe7036b1897.png)

**Comment by vincentneko** [comment]
Could be related with a server restart with trade colony bugfix.
Is it reproductible ?

**Comment by vsrisuknimit** [comment]
@vincentneko That seed was gone. I will try to see if I can reproduce it.

**Comment by bafolts** [comment]
Looking through the colonies improvement PR and seeing what stands out to me as potential source of bugs.

https://github.com/bafolts/terraforming-mars/blob/master/src/Player.ts#L690

I would think this would be `undefined` and not `null` if the value were not found.

**Comment by vsrisuknimit** [comment]
Not reproducible any more. Closing this.

**Comment by vsrisuknimit** [comment]
Still a problem. Reported by Boris on Discord.

![image](https://user-images.githubusercontent.com/14239220/95665116-2d7b2600-0b1b-11eb-9386-cf06399925dd.png)

**Comment by vsrisuknimit** [comment]
@vincentneko @bafolts same problem with Aridor.

**Comment by bafolts** [comment]
Fascinating. :detective: :bug: :male_detective: :bug: :female_detective: I will check out this one as well.

**Comment by vsrisuknimit** [comment]
With a given seed, it is specific to Aridor. Whichever colony is removed or added does not seem to matter. Error happens even with no card played.

**Comment by bafolts** [comment]
With seeded games we pull the value from JSON. JSON can not store functions. For this game the colonies start with:

```
[ Ceres {
    isActive: true,
    visitor: undefined,
    colonies: [],
    trackPosition: 1,
    name: 'Ceres',
    description: 'Steel' },
  Europa {
    isActive: true,
    visitor: undefined,
    colonies: [],
    trackPosition: 1,
    name: 'Europa',
    description: 'Production' },
  Miranda {
    isActive: false,
    visitor: undefined,
    colonies: [],
    trackPosition: 1,
    name: 'Miranda',
    description: 'Animals',
    resourceType: 'Animal' },
  Pluto {
    isActive: true,
    visitor: undefined,
    colonies: [],
    trackPosition: 1,
    name: 'Pluto',
    description: 'Cards' } ]
```

**Comment by bafolts** [comment]
:warning: colonies are most likely broken when serializing games as well during undo operation or during server restart. We will need to move `endGeneration`, `increaseTrack`, and `decreaseTrack` to functions that can take in `IColony` and operate on them.

**Comment by bafolts** [comment]
We actually do this right when de-serializing. Just have to copy what we are doing there. :+1: I can get fix together.
