### ISSUE TITLE
Better default selections for how to pay for things?

### ISSUE THREAD

**Issue by kevinb9n** [bafolts/terraforming-mars#1367]
When it asks how I want to pay for something, it seems that the default selection is to prefer spending MC, and then only spend metals or spendable card resources (e.g. Psychrophiles) when I don't have enough MC.

That seems backwards to me as a default? Except in the case of Helion/Heat, these resources *usually* aren't good for any other purpose. I think you would usually want to spend these resources first (short of overpaying) - or, say, to only have to click once to hold back a single resource for something like Space Elevator.

As a result, whenever I get this prompt, the first thing I do is blindly mash the up arrow on the metals until they top out - but being careful not to go to far (and for example end up using a titanium worth 4 as a single MC). The state I end up in is what seems like should have been the default.

**Comment by vsrisuknimit** [comment]
@kevinb9n I disagree with always spending steels and titaniums. As you said Space Elevator, Jovian Lantern, Security Fleets and other cards require metals to activate. It would be more annoying to have to deduct titanium every time you play space card until you activate Jovian Lantern. You might accidentally forget to do that. Even in the case of psychrophiles, sometimes you want Ants to eat them instead of keep them to win Eccentric.

Perhaps an alternative is to have a MAX button next to steel or titanium (and microbe/floater/heat payment). This will use (1) as much metals as you have, but (2) not overpay.

**Comment by nwai90** [comment]
**Current logic:**
1. No auto selection of other resources if user can afford with MC alone
2. Auto select to spend other resources (e.g. steel/titanium) if user cannot afford with MC alone
3. Will never overpay by default

I agree with @vsrisuknimit that a MAX button would be a good idea as long as we maintain condition (3) - the default selection should never result in overpayment

**Comment by kevinb9n** [comment]
Whatever you want to do here is fine but let me just plead my case a wee bit :-)

The fact that we're here enumerating interesting cases where you don't want to use up resources first, I think actually *supports* my point: that these are indeed the *special* cases.

(Another special case might be the interval between when you acquire Advanced Alloys until you play it.)

Certainly either default behavior can be dangerous when that default is accepted carelessly. I'm here because I *think* that leaving these resources unspent is *more* often the dangerous mistake. There are always other cards/standard-projects/milestones/etc. that you want to buy that generation that won't accept the resources, and it's sad to realize you could have had them if you'd remembered to use your metals etc. earlier.

This could be a toggled preference of some sort. But, given that there is always a confirmation step, a configurable default might be overkill.

**Comment by nwai90** [comment]
@kevinb9n After some thought, it seems less intuitive to try and compute values based on specific restrictions and edge cases. I will implement this as a MAX button that sets the maximum possible value for that resource, for all payment resources except MC. This way the MAX button will behave exactly as the user would expect, and it also works well with the overpayment warning.

<img width="439" alt="Screenshot 2020-10-01 at 11 50 32 AM" src="https://user-images.githubusercontent.com/2408094/94763571-2c404f80-03dd-11eb-9348-a5b1b64744ea.png">

**Comment by nwai90** [comment]
Implemented

**Comment by kevinb9n** [comment]
I was quite happy to see it! Thanks!

**Comment by kevinb9n** [comment]
Hmm, I expected it to select the max amount of steel without overpaying, but it seems to be trying to spend al of my steel whether it's all needed or not.

**Comment by nwai90** [comment]
@kevinb9n Yes, it's implemented to set the highest possible value so that the "MAX" button does exactly what it says.

It will be more complex and error prone if we constrain it to "highest value without overpayment" as this also involves recomputing "good" values for adjusting all other resources (think of scenarios where you can use 3-4 types of resources for payment). This might involve some kind of resource priority as well which is subjective and highly context-specific.

**Comment by kevinb9n** [comment]
Okay. I'm just gonna rescind my "quite happy" then :-) That is, if I encountered the site today with its present behavior I think I would still file this issue.

Approximately 99% of the time, I follow the same simple policy to always use as much steel as I can get full value from. (Even when I have Space Elevator, I tend to get that done early each gen.) I would still be glad if I had a way to make that my default behavior.

Separately, the current implementation of MAX seems surprising. Is it really setting the highest "possible" value? Am I *allowed* to spend 8 steel on a 5-cost card? That seems dangerous but also unsupported by game rules (and Factorum illustrates that the game does not expect players to be able to discard resources voluntarily).

**Comment by kevinb9n** [comment]
Actually, I'm going to

(a) file a separate issue about the behavior of the MAX button as it stands
(b) work on an actually complete proposal for how to address the things I've brought up here.

We can just let this issue here die.
