### ISSUE TITLE
Simple visual indicator when you are "overpaying" for something

### ISSUE THREAD

**Issue by kevinb9n** [bafolts/terraforming-mars#1368]
For example, if a card costs 10, and I select to pay 4 titanium for it, it would be very helpful if the UI changes in some small way to show that I am not getting the current full value out of the final titanium. 

Suppose my goal is to avoid doing more mental math than I have to (which fair, because you only have so much brain power to use). Right now, suppose I have 5 titanium and 0 MC selected. I lower the titanium to 4 and the MC becomes 3, so it sounds good like I'm not overpaying. But I lower the titanium one more time and the MC becomes 7. What? Oh, Unity party in ruling this generation. So now I know that I was overpaying, and I can make an intentional choice about whether I want to or not.

Would be cool if the UI just illustrated this somehow!

**Comment by chosta** [comment]
Some good suggestions here. They coincide with some of the interfaces that we are working on at the moment. The new Log a.k.a. actions screen is going to be the focal point of the app and we will try to make it as informative as possible but not too cluttered too. Hard task :)

**Comment by nwai90** [comment]
@kevinb9n Did you enable in-game alerts in Preferences panel? There is a simple alert that will give an overpayment warning right now. UI will likely be improved at some point in future

**Comment by kevinb9n** [comment]
oh that's hot, I will try that!

**Comment by kevinb9n** [comment]
I did have that enabled - I'm not sure what it does. I didn't see anything in this case.

**Comment by Lynesth** [comment]
This is enabled via the "in-game alerts" preference.
