### ISSUE TITLE
Auto pass

### ISSUE THREAD

**Issue by ap3h3ad** [bafolts/terraforming-mars#1370]
I think it would be a nice enhancement to have an option to auto pass the next turn. Because sometimes you know that the only thing you will do next turn is to pass while others may play some rounds. Instead of forcing them to wait for your move which is only passing the round a checkbox ore something like that would be nice that I can check e.g. if I go to sleep so the other players can proceed with the game because I told the game that my next move will simply be a pass.

**Comment by chosta** [comment]
It could definitely be done, but I'm a bit conservative about auto actions. Users usually get confused when things happen without any warning.

**Comment by ap3h3ad** [comment]
Hi!

Well, the user would actively click that radio button and it could be done in such a way that the checkbox gets deactivated after the auto pass. And it also could be implemented as optional (like the fast mode and many other features).

**Comment by nwai90** [comment]
One interesting possibility here is to build a game option to "Enable pre-plays".

This is an "expert" feature I saw on https://hanabi.live that enables you to preselect your actions for the next turn (and very importantly, to also cancel them) while other players are taking their turns. Implementation will require some effort though. We could put it in `#vote-on-issues` if this direction is worth exploring.

**Comment by kevinb9n** [comment]
I think #1502 is addressing this now.

I think a more generalized pre-play feature is prooobably too complex to be worth the effort for now, just my 2 cents.

**Comment by jholm117** [comment]
I would very much like this feature. Being able to automatically pass before my turn comes up would save me precious seconds in games with a short escape velocity.

**Comment by kberg** [comment]
I don't know escape velocity perfectly well, but don't you get a few seconds for each turn anyway?

**Comment by nwai90** [comment]
> I don't know escape velocity perfectly well, but don't you get a few seconds for each turn anyway?

There's a "rebate" of 2 seconds given to compensate for network RTT from what I recall

**Comment by jholm117** [comment]
https://github.com/terraforming-mars/terraforming-mars/wiki/Escape-Velocity#escape-velocity
> EV Penalty
In the example above, a player has 30 minutes to complete the game. Once a player reaches 32 minutes, their final score will include a -1VP penalty.
>
> EV Bonus
However, every action you take also gives you an additional 2 seconds. (This is currently not configurable, but shouldn't it be?) So in the example above, if a player has taken 60 actions, they will have received 120 seconds of extra time, so they wouldn't get a penalty u ntil their timer reaches 34 minutes.

Yes there is a rebate as @nwai90 describes, but each millisecond spent hunting for the pass button on your turn will subtract from that allowance which can be all we have to work with in 0 minute escape velocity games.

**Comment by ap3h3ad** [comment]
This would be incredibly helpful for long lasting games such as the games I usually participate in. These games go over days or sometimes weeks and are played by people with different day routines. So when I do my last action at 11pm and go to bed and I'm able to auto-pass my next turn then the other players don't have to wait for me and can continue selling 2 patents each turn (so annoying...) until late night - plus I don't accumulate so much time on my timer.
