### ISSUE TITLE
Giant Ice Asteroid vs Arctic Algae

### ISSUE THREAD

**Issue by kevinb9n** [bafolts/terraforming-mars#1371]
Lost the game id, but a couple nights ago I played Giant Ice Asteroid on my wife, who owned 3 plants. It seems to have tried to deduct 6 plants first (actually removing all 3 that she had), and *then* process Arctic Algae to give her the 4 plants from my two ocean placements. So she ended up with 4 plants, when I thought she should have ended up with only 1.

I believe the official rule is that the active player gets to choose the order, but the game can easily guess which order I'd want, or it could handle each step of the action card one by one.

I suppose the current behavior is consistent with an approach of executing an entire action atomically, then checking for any effects. And that could be intentional. A bummer in this case though!

**Comment by kberg** [comment]
Checking the rulebook, page 9, A, 2. 

"Then the lower panel of the card shows you any immediate effects. These effects (and other effects triggered by the card you just played) are performed in any order you choose."

**Comment by kberg** [comment]
I would imagine getting that to work in a way you expect would require a meaningful change to the way the code is structured (from declarative to storing a list of effects, and then changing the UI to ask for resolution order. Probably not trivial, but a fundamental change to game structure.

**Comment by kevinb9n** [comment]
Just to be clear, I'm also okay with it picking an order itself, if it could pick one more obviously favorable to the active player.

**Comment by vsrisuknimit** [comment]
@kevinb9n from #703 It was fixed. The current order is temp, ocean, ocean and plant destruction. 

See https://github.com/bafolts/terraforming-mars/blob/95a79236dee9857b863d0bd357642fb39d66cc74/src/cards/GiantIceAsteroid.ts#L31

Are you sure about what you saw?

**Comment by kevinb9n** [comment]
Well, I feel about as sure of it as anyone feels about anything. :-) We stared at it for a while. I fairly distinctly recall the log even saying explicitly that 3 plants were removed.

**Comment by kevinb9n** [comment]
Yup, just saw it again. I think this screencap proves it?

![image](https://user-images.githubusercontent.com/934551/94335795-c6923480-ff92-11ea-86a2-1fcb1111faf9.png)

**Comment by kevinb9n** [comment]
Just to be very clear, Deimos Down *did* take 6 plants, leaving me with zero, then I had 2/4/6 from Arctic Algae as she placed her oceans, and then... nothing, I just got to keep them!

**Comment by nwai90** [comment]
Confirmed - this issue is reproducible.

**Scenario:**
- P1 has Arctic Algae and 0 plants
- P2 plays GIA

**Expected:** P2 should be able to remove 4 plants from P1 after oceans are placed

**Actual:** P1 gains 4 plants, P2 is not prompted to remove them. The check for targets seems to be done before the oceans are actually placed onto the board (hence there are no valid targets at that point). Not sure if this is a regression or new issue.

**Comment by bafolts** [comment]
We could consider displaying the "interrupts" to the user and allowing them to order them and work through them.

**Comment by vsrisuknimit** [comment]
> You would have to work through the interrupts before taking your next action, which today is FIFO but should be easy enough to display with an `OrOptions` and have user work through them one at a time.

That should solve also the problem with Mons. #1046
