### ISSUE TITLE
Helion and Reds policy

### ISSUE THREAD

**Issue by vsrisuknimit** [bafolts/terraforming-mars#1375]
If Helion has 8 heat and zero mc, then raises the temperature while Reds is ruling, the game is irrevocably stuck since it cannot pay the 3 mc to the Reds policy.

![image](https://user-images.githubusercontent.com/14239220/94192605-2eeef200-fe7d-11ea-9cea-666b835387c3.png)

**Comment by nwai90** [comment]
Fixed and merged
