### ISSUE TITLE
Improve VP breakdown

### ISSUE THREAD

**Issue by vincentneko** [bafolts/terraforming-mars#138]
VP breakdown is a great feature.
I would like to list all cards that have a variable VP contribution like security fleet, or animals cards along with the VP associated to them on the endgame page.

This will need updating all onGameEnd methods to return the value.

**Comment by bafolts** [comment]
Renaming the `onGameEnd` method to `getVictoryPoints` would make sense. I am fairly certain most `onGameEnd` implementations are use for victory point calculations anyway.

**Comment by vincentneko** [comment]
I did not saw your changes and I tried to upload my changes, the branch is a mess now, sorry.
I will try to revert my changes.

**Comment by alrusdi** [comment]
Implemented and merged
