### ISSUE TITLE
Feature request: indicator for protected plant resource and metal bonus

### ISSUE THREAD

**Issue by vsrisuknimit** [bafolts/terraforming-mars#1391]
- Tiny shield icon next to plant resource box for Protected Habitat and Asteroid Deflection System.
- One white dot for each metal resource bonus. For example, two dots next to titanium if a player has both Advanced Alloys and Mercurian Alloys. Don't think it should take Unity into account here.

![Untitled-1-01](https://user-images.githubusercontent.com/14239220/94340696-c2393c00-ffd1-11ea-9daf-49b0d50b1037.png)

**Comment by vsrisuknimit** [comment]
![Untitled-1-01](https://user-images.githubusercontent.com/14239220/94342731-0122be00-ffe1-11ea-97e7-7360b9e89d76.png)

Alternative with + symbol instead of white dot.

**Comment by kevinb9n** [comment]
I don't think I get any votes here :-) but I like it!

I think the titanium bonus dots will be confusing/misleading if they don't factor Unity in, though. You'll end up getting bugs filed about it.

Might as well also show the shield next to "RES: N" on a card? Pets would always have it. Pretty useful.

**Comment by vsrisuknimit** [comment]
![image](https://user-images.githubusercontent.com/14239220/94351157-1cfb8380-0024-11eb-9084-51c197928f13.png)

Something like this?

If you are already looking at the opponent's animal cards, would you not already see their protected habitat?

**Comment by kyshantry** [comment]
Yes, excellent! I like the pluses or the value of the resource; I feel like the value of the resources will be a bit noisy though. I agree don't include unity. And per the example with strat birds: yes, just like that. Sometimes folks have a billion blue cards and if you're just checking for animals you might miss protected habs :)

**Comment by kevinb9n** [comment]
I can think of two arguments against accounting for Unity:

a) it's not necessary for some purposes, like deciding which player to decrease the titanium production of
b) the user who sees it might accidentally think it's permanent, remember that, then be surprised later

Are there others?

(a) doesn't seem like an actual disadvantage, and for (b), the whole point of this feature is users not having to rely on their faulty memories but being able to see the information in black and white.

Here's an idea: you could show permanent bonus as solid dots and temporary bonuses as hollow dots.

My personal feeling is that not showing the Unity bonus at all may be actively misleading.

**Comment by kevinb9n** [comment]
Oh, and re: "would you not already see their protected habitat?"

That relies on your knowledge that Protected Habitats is the only card that can have this effect, or your searching through all their cards. And perhaps also remembering to read their Pets card fully.

**Comment by vsrisuknimit** [comment]
@kevinb9n protected habitat is the only one card that protects animals and microbes.

Asteroid Deflection System protects plant resources only.

**Comment by kevinb9n** [comment]
That is what I believed to be true. My point above is that it would be better not to *depend* on users having that information. Sometimes we crazed TM fans want to play against our friends who don't have the encyclopedic knowledge. And sometimes new expansions come out.

**Comment by kevinb9n** [comment]
[Just a very minor footnote about Pets: I do think the shield icon should always be displayed there, even though one still has to read the card text to learn that YOU also can't remove your own pets yourself. I think that's fine, because what the shield communicates is still 100% true.]

**Comment by kberg** [comment]
Something to keep in mind: Ares also has an animal card you can't remove from, ref https://github.com/kberg/terraforming-mars/blob/3573414169bcdcf465d90a08d7f463ae45f0245d/src/cards/Virus.ts#L33

Such a generic indicator would be welcome. (Say, a card attribute, eg `resourcesProtected`) that could drive this annotation.

**Comment by kevinb9n** [comment]
(note that I've commented on the PR to explain why I think the current solution is a mistake.)

**Comment by Lynesth** [comment]
I think the current implementation is fine.
Please open a new issue if you think there's room for improvement please.
