### ISSUE TITLE
Don't let buttons be re-clickable, and make them not look clickable

### ISSUE THREAD

**Issue by kberg** [bafolts/terraforming-mars#1396]
I've been spending my entire time using this app on a very slow network connection. Time between my clicks and response are in seconds. Please provide some visual cue that action button was clicked - I have no idea. Also, please prevent clicking a second time.

**Comment by alrusdi** [comment]
It is seems to be easy task. Let me try do do it

**Comment by kberg** [comment]
Oh, thank you. I'll be grateful.

>

**Comment by Lynesth** [comment]
Fixed in #1490
