### ISSUE TITLE
Incorrect game end loss

### ISSUE THREAD

**Issue by hinrik** [bafolts/terraforming-mars#1405]
Just played this for the first time (solo game), and as I started generation 12, the game ended and told me I lost. How is that possible? I thought you had 14 generations to terraform. In fact, as I started generation 12 I already had enough resources (42 heat, 56 MC) to max out the remaining oxygen and temperature during that generation.

https://terraforming-mars.herokuapp.com/the-end?id=da2a738f320a

![Screenshot from 2020-09-27 18-12-28](https://user-images.githubusercontent.com/43533/94369958-0f5e0080-00ed-11eb-8998-13e2a271ba9c.png)
![Screenshot from 2020-09-27 18-12-35](https://user-images.githubusercontent.com/43533/94369959-12f18780-00ed-11eb-9965-e091c3b2c1e9.png)

**Comment by kberg** [comment]
Did you play with Prelude? With Prelude you only get 12 generations.

**Comment by hinrik** [comment]
Oh, I see. But with 42 heat resources (enough for 5 increases) and 56MC (enough for 2 asteroids and a greenery) that's enough to max out the resources, so I should have won, right?

**Comment by hinrik** [comment]
Maybe I misunderstood and I was actually finishing generation 12's production phase rather than starting that generation.

**Comment by SliceOfBread** [comment]
Perhaps, for Solo, it could say "GENERATION 1 of 12" or "GENERATION 1 of 14" as a reminder to people who sometime play one or the other and may forget to scroll to the bottom to see if there are prelude cards? (Yes, I just did this!) I will see if I can do this.

**Comment by kberg** [comment]
That sounds reasonable.

**Comment by SliceOfBread** [comment]
I don't know Vue well enough (hardly at all) to make this change. I think it needs something like:
`{{ game.players.length === 1 ? " of " + (game.gameOptions.preludeExtension ? 12 : 14) : "" }}`
added to src/components/PlayerHome.ts (on line 128 of the version I'm looking at)
but it is not clear to me how to get those variables visible. Hopefully someone will make this change and I will learn a bit from it.
