### ISSUE TITLE
Give the user a little help calculating requirements?

### ISSUE THREAD

**Issue by kevinb9n** [bafolts/terraforming-mars#1407]
It would be awesome if we could visually distinguish a requirement that is currently satisfied from one that is not, somehow.

And it would be *amazing* if I could hover on a requirement and see both what my own current modified version of that requirement is, and what my current progress toward is. For example, perhaps the temp requirement is min -10 C, and when I (as Inventrix) I hover I see "Current: -18 C / Min: -14 C".

All the above goes for my hand/robots, any draft pool, or discard selection. On a played card it would be nonsense (though perhaps arguably harmless).

Just an idea.

**Comment by chosta** [comment]
Not a bad idea, just FYI we avoid hovers as if the floor is lava because of no hover on mobile.

**Comment by kevinb9n** [comment]
Ah right. Well, at least for "Cards in Hand" tapping on the card has no other action assigned right now, so maybe it could use that? It would be nice-ish to still use hover for desktop, but I'd be happy to have this information available no matter what the UI.

And to be clear, even if the only part we get is the visual indicator of "currently met or not" that's already a big help especially while drafting etc.

**Comment by kevinb9n** [comment]
For what it's worth, I have a simply *ridiculous* habit of purchasing cards whose max long since passed. I have no idea why I do it. But some kind of visual indicator that the requirement is unmet might save my bacon the next time I try to do this.

**Comment by kevinb9n** [comment]
This and #776 are of a piece – cost and requirements, requirements and cost.

Comment I just left there:

It may be hard to include both pieces of information (printed cost and effective cost) without it looking bad, so another option might be a toggle button somewhere (preferably not hidden away in settings?) between seeing cards-as-printed and cards-as-modified-by-effects. I think this should include cost mods and requirement mods. We should have a convention that the info is styled slightly differently (e.g. cost in dark green characters instead of black?) whenever it's modded. And maybe hovering on the cost or requirement should show the opposite mode......
