### ISSUE TITLE
Discovery of microbial life in the Martian soil is a major event, surely worthy of being mentioned in the game log :-)

### ISSUE THREAD

**Issue by kevinb9n** [bafolts/terraforming-mars#1408]
I think it should output a message in the game log saying something like "Life has been found!"

**Comment by nwai90** [comment]
@kevinb9n It's a minor change yes. I'll add it in as `{PLAYER} found life!`

**Comment by nwai90** [comment]
Implemented

**Comment by kevinb9n** [comment]
Thanks!
