### ISSUE TITLE
Feature request:  Custom card selection highlight

### ISSUE THREAD

**Issue by ssimeonoff** [bafolts/terraforming-mars#1413]
## Reason 
Some people (experienced players) prefer the selected card label as it is now - big and obvious, without caring if it covering text on the card. For other players though, this is a game-breaking flaw as they are new to the game and don't know the cards. 

## Suggestion 
Add options in Settings to toggle between various selected card designs.
Identify few desired designs and add them as options. 

Examples: 
- label shape and position
a - big one (as it is now)
b - small ( a small one on the side)
c - none (no label at all)
- colour 
a - orange (as it is now) 
b - blue (e.g. as the submit button's blue)
c - green

**Comment by kevinb9n** [comment]
I imagine the difference between who selects this preference and who doesn't might boil down to "I know the cards well" vs "I'm still learning them". In the experienced mode maybe they would want a streamlined icons-only view without the (mixed-case) text so there's less to get covered up in the first place?
