### ISSUE TITLE
[Bug] Some icons missing after icon update

### ISSUE THREAD

**Issue by Maelstrom1** [bafolts/terraforming-mars#1418]
Not all of the new icons seem to have imported properly....
Can't confirm that this happens to more than this, but I found this in the current heroku version
![chrome_kvWyDvFDN4](https://user-images.githubusercontent.com/20371049/94621230-f042a880-027d-11eb-9af1-bbed5123b233.jpg)
Seems to be fine on the cards list area.

**Comment by vsrisuknimit** [comment]
Colony, trade fleet, and trade still use the old icons.
![image](https://user-images.githubusercontent.com/14239220/94676138-dee2b600-02e8-11eb-852d-0beafa55b691.png)

**Comment by vsrisuknimit** [comment]
Venusian plants, thermophiles, freya biodomes have venus icons significantly raised.

![image](https://user-images.githubusercontent.com/14239220/94676166-e86c1e00-02e8-11eb-9e02-4940b999a6f8.png)

![image](https://user-images.githubusercontent.com/14239220/94676233-020d6580-02e9-11eb-95e0-ee58371da4da.png)

![image](https://user-images.githubusercontent.com/14239220/94676257-0afe3700-02e9-11eb-8b0f-8c5cc028d179.png)

**Comment by vsrisuknimit** [comment]
These cards use black venus V instead of white on blue.

- Airscrapping expedition
- Hydrogen to Venus
- Stratopolis

![image](https://user-images.githubusercontent.com/14239220/94676308-22d5bb00-02e9-11eb-8ae1-3177d8d43498.png)

![image](https://user-images.githubusercontent.com/14239220/94676322-2701d880-02e9-11eb-82f9-6526d5c68363.png)

**Comment by vsrisuknimit** [comment]
Atmoscoop icons are all messed up.

![image](https://user-images.githubusercontent.com/14239220/94676625-a2fc2080-02e9-11eb-949e-dd3c1bbcbbb5.png)

**Comment by vsrisuknimit** [comment]
Rotator Impacts misses the titanium icon for the cost of action

![image](https://user-images.githubusercontent.com/14239220/94676675-b27b6980-02e9-11eb-808f-66f30f39dc89.png)

**Comment by vsrisuknimit** [comment]
Asteroid resource cards have both A and asteroid icon, overlapping.

- Asteroid Hollowing
- Asteroid Deflection System
- Comet Aiming
- Directed Impactors
 
This card only has A and not asteroid icon.

- Rotator Impacts

![image](https://user-images.githubusercontent.com/14239220/94676993-2c135780-02ea-11eb-9e03-7bab1be6a250.png)

**Comment by vsrisuknimit** [comment]
Give more space between number and resource icons. They are too close.

![image](https://user-images.githubusercontent.com/14239220/94677629-397d1180-02eb-11eb-8fb8-9b35db2eba60.png)
![image](https://user-images.githubusercontent.com/14239220/94677643-40a41f80-02eb-11eb-93de-6519e7bf72a6.png)

**Comment by vsrisuknimit** [comment]
These cards are badly misaligned.

![image](https://user-images.githubusercontent.com/14239220/94677459-ec00a480-02ea-11eb-9428-ae499e467018.png)

![image](https://user-images.githubusercontent.com/14239220/94677728-63cecf00-02eb-11eb-8bfd-c8cf6a8aa681.png)

![image](https://user-images.githubusercontent.com/14239220/94677823-8b259c00-02eb-11eb-95e6-4d37658f844b.png)

![image](https://user-images.githubusercontent.com/14239220/94677889-a1335c80-02eb-11eb-83f8-27722ccd5d0c.png)

![image](https://user-images.githubusercontent.com/14239220/94677973-be682b00-02eb-11eb-9930-214294b8fb38.png)

**Comment by vsrisuknimit** [comment]
These jovian are too close after slash (/).

![image](https://user-images.githubusercontent.com/14239220/94679019-6c280980-02ed-11eb-9f3e-ed29e759023f.png)

![image](https://user-images.githubusercontent.com/14239220/94679076-806c0680-02ed-11eb-9359-b16e0f88bc60.png)

**Comment by vsrisuknimit** [comment]
The production box should be lighter. It is hard to see -/+ signs, red border, and number.

![image](https://user-images.githubusercontent.com/14239220/94679773-a8a83500-02ee-11eb-8110-9cd95dee64f4.png)

![image](https://user-images.githubusercontent.com/14239220/94679829-ba89d800-02ee-11eb-9564-41fb60e6d8d1.png)

**Comment by vsrisuknimit** [comment]
The parameters could all be in one line. 

![image](https://user-images.githubusercontent.com/14239220/94680236-67645500-02ef-11eb-9b60-a2242513475c.png)

**Comment by vsrisuknimit** [comment]
Turmoil parties: Reds and Kelvinists icons are a bit messed up.

![image](https://user-images.githubusercontent.com/14239220/94681321-38e77980-02f1-11eb-892f-97ab26fb4158.png)

**Comment by vsrisuknimit** [comment]
For colony trade income, move the x a bit to the left.

![image](https://user-images.githubusercontent.com/14239220/94681463-7d731500-02f1-11eb-8ebe-7ea26843c154.png)

**Comment by chosta** [comment]
@vsrisuknimit the Colonies should be fixed with this #1424 
It was not only the X.
Grids, cubes, colonies, cards animals all over the place :)

**Comment by alrusdi** [comment]
Plus and minis signs are rendered as gray on MacOS

**Comment by vsrisuknimit** [comment]
@alrusdi Also thermophiles. I forgot to include it with Freya above.

![image](https://user-images.githubusercontent.com/14239220/94721001-34d44f80-0323-11eb-958e-98f130cda0cf.png)

**Comment by pocc** [comment]
These cards are misaligned 1) horizontally 2) vertically

![image](https://user-images.githubusercontent.com/10995145/94740749-ff7e3080-0327-11eb-8c09-162bfc02b2f1.png)
![image](https://user-images.githubusercontent.com/10995145/94740786-0ad15c00-0328-11eb-8d44-7e02d2c18b7b.png)

**Comment by alrusdi** [comment]
Most of these seems to be fixed
