### ISSUE TITLE
"Mining guild get no bonus when placing ocean #6" issue still persists in solo

### ISSUE THREAD

**Issue by andystager** [bafolts/terraforming-mars#1420]
I just confirmed this again, but mining guild steel rate bonus is not applying when an ocean is placed in solo.

**Comment by kberg** [comment]
Hey I just happen to be looking at Mining Guild right now. What specifically about playing in solo should activate mining guild's  steel bonus?

**Comment by andystager** [comment]
There should be nothing unique about the expected outcome in solo, it just isn't working.

If I place an Ocean tile onto a location with steel or titanium, it should result in +1 steel rate. It's the same rule in standard play.

**Comment by kberg** [comment]
I'm not familiar with all maps, which map? I'll take a look at the code.

>

**Comment by andystager** [comment]
The resource exists on all three, but I tested on Tharsis.

**Comment by kberg** [comment]
You're right, I'm dense! I'll look later - Wifeberg has me for a game.

**Comment by alrusdi** [comment]
@nwai90 fixed it
