### ISSUE TITLE
FAQ / Readme / Setup

### ISSUE THREAD

**Issue by nivaivax** [bafolts/terraforming-mars#1425]
Would be great to have some more info on how things work. Perferably in the wiki?

Added a few things, mostly around linux and setup, in this google doc, if there's anything worth using or changing, feel free to do so. It's editable.

https://docs.google.com/document/d/1p4u6yHnmlAPHWZUsZoWqPVd6P2427HTWtUeoZKm9OQ8/

**Comment by nivaivax** [comment]
This is the content of the file if you can't access it...



Server
Installing on Linux

Should be as simple as installing git, node.js and npm.

sudo apt-get update
sudo apt-get install node.js
sudo apt-get install git
sudo apt-get install npm
git clone https://github.com/bafolts/terraforming-mars.git
cd terraforming-mars
npm install
npm start

Starting daemon to keep the server running (try it on non-root)
npm install -g pm2
pm2 start dist/server.js (in that folder, absolute paths seem to mess it up)
pm2 startup
pm2 save

Some additional commands
pm2 ls to list processes
pm2 logs to show logs (for example to see server key!)
pm2 flush to flush logs

Common problems
Some versions of npm/node.js might not work on your setup, or certain requirements, eg. sqlite3 and node-gyp, or your architecture (eg. 32bit). Try and install them manually, or another version, or compile. I 
Also node.js might be called node, nodejs on your system.

A couple of examples that you can google/explore
curl -L https://npmjs.org/install.sh | sh
npm install -g less
npm install -g node-pre-gyp node-gyp
npm install sqlite3
curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -

Some people had success with 
npm install xx -g --unsafe-perm or running as root or sudo
sudo apt-get install -y nodejs

Other common problem would be permissions, I had most success running as a non privileged user, but might need to do 
chown -r user.user terraforming-mars
Upgrade, backup
You should be able to upgrade to a new version into the same folder. Don’t forget to backup the game.db or any other files you might have changed


Example update script
#!/bin/bash
now=$(date +"%Y-%m-%d+%R")
cp  db/game.db db/game$now.db
git clone https://github.com/bafolts/terraforming-mars.git
cd terraforming-mars
npm install
cp db/game.db db/game.db.empty
cp db/game$now.db
npm start


Server settings

Server key is var serverId = in dist/server.js on line 18. Set it to something permanent if you want to, ie.  var serverId = "password";

Server port server.listen(process.env.PORT || 8080); on line 902 (and log on 898) in server.js


Game database
In folder db/game.db sql file if you need to edit it.
It’s saved once per turn, after player switching (after draft)
Only running games are reloaded into the live database after server restart

**Comment by nivaivax** [comment]
And this would be the update script I use

`#!/bin/bash
now=$(date +"%Y-%m-%d+%R")
pm2 stop tm
cd /opt
cp  terraforming-mars/db/game.db terraforming-mars/db/game$now.db
##git clone https://github.com/bafolts/terraforming-mars.git
cd terraforming-mars
git pull
npm install
cp db/game.db db/game.db.empty
cp db/game$now.db db/game.db
node make_locales.js
lessc src/styles/common.less styles.css
tsc --build tsconfig.json 
webpack --config webpack.config.js
sed -i 's/var serverId = generateRandomServerId();/var serverId = "password";/' dist/server.js
pm2 start tm
`

**Comment by bafolts** [comment]
> Server key is var serverId = in dist/server.js on line 18. Set it to something permanent if you want to, ie. var serverId = "password";

This could be integrated into `server.ts` if it is common to change this ID. It is generated by default as a rudimentary attempt at avoiding people getting a copy of it.

The postgres dependency is not critical, we should move it to `optionalDependencies`. For most users they will most likely use sqlite. If postgres fail that shouldn't block install. If later trying to use postgres we can error if the dependency isn't available.

**Comment by nivaivax** [comment]
That makes sense, and it's probably a wise choice to randomise it. I couldn't find that information anywhere though, so had to go through a lot of files to find that info.

I suppose this entire "issue" is around putting more info in the wiki. Might be as easy as taking some of the stuff in the gdoc and other faq and integrating into the wiki

**Comment by nivaivax** [comment]
I'm happy to just copy this into the wiki, but it seems I don't have permission. Maybe someone could?

Let's not forget that when you first see this page, it's quite intimidating getting it setup :)
