### ISSUE TITLE
Small feature request: rearrange tags in summary table

### ISSUE THREAD

**Issue by vsrisuknimit** [bafolts/terraforming-mars#1426]
- Move none closer to wild tag since it is still a tag, somewhat.
- Event to the right since it is not really an on-going tag at all.
- Small thin line between separating None and Event from the rest of tags. Good to know how many tags you actually have.

![image (10)](https://user-images.githubusercontent.com/14239220/94685457-70592480-02f7-11eb-879c-e1c1ca74ba51.png)

Tagging @chosta

**Comment by alrusdi** [comment]
I want a toggle tags view widget to be redone toooo.
Visually implement it like arrows on the right side. And keep tags in concise view in columns but hide the columns if each player has no tags in it

**Comment by kevinb9n** [comment]
This would subsume #1392 - you could dup that for this if you want.

I believe the so-called "wild tag" is definitionally not a tag either, and should also be right of the line.

**Comment by vsrisuknimit** [comment]
@kevinb9n , I agree. It is technically not one of the 11 possible tags. It also does not count toward global events during the Turmoil step.
