### ISSUE TITLE
Dirigibles + Venusian Birds interaction incorrect

### ISSUE THREAD

**Issue by duckmammal** [bafolts/terraforming-mars#1430]
If dirigibles is your only card with floaters on it, and you want to play venusian birds, you can pay all of the floaters from dirigibles and then not have to pay any floaters for the birds.

I guess the game is checking to see if you have floaters before payment, and then tries to remove floaters after payment. When this fails to work, you get to keep your card anyways.

**Comment by kevinb9n** [comment]
Stratospheric Birds?
Sounds like in this situation the payment dialog should only allow you to select up to N-1 of your dirigible floaters.

**Comment by duckmammal** [comment]
Yeah, strat birds. 

Your solution would work only if that's the only card with floaters.

**Comment by kevinb9n** [comment]
That seemed to be the scenario we were discussing. 
Is there a problem in the other scenario too?

**Comment by duckmammal** [comment]
no, i was just making sure we have both levels of checks.

**Comment by nwai90** [comment]
> If dirigibles is your only card with floaters on it, and you want to play venusian birds, you can pay all of the floaters from dirigibles and then not have to pay any floaters for the birds.
> 
> I guess the game is checking to see if you have floaters before payment, and then tries to remove floaters after payment. When this fails to work, you get to keep your card anyways.

@duckmammal The game is checking to see if you can afford Stratospheric Birds + 3 by adding total floaters on Dirigibles + MC.

Current logic: If all floaters on Dirigibles are spent and there are no other floaters to remove, 3 MC will be deducted from the player so that the net result is the same (i.e. player cannot avoid cost of paying the floater)

**Comment by nwai90** [comment]
Fix implemented by @Lynesth
