### ISSUE TITLE
Make visible who is not drafting

### ISSUE THREAD

**Issue by ap3h3ad** [bafolts/terraforming-mars#1433]
Hi,

in the old design the players wo haven't drafted yet were marked. In the current design this mark is missing. Sometimes people forget to draft and to have the possibility to remind the specific player would be very nice to have. Especially because we had it before.

Cheers!

**Comment by chosta** [comment]
You are correct that it used to exist but I think it was not 100% correct. We want to add  some visual identifiers when people are in-between turns when drafting, hopefully soon.

**Comment by kevinb9n** [comment]
This was just done eh?
