### ISSUE TITLE
Feature request: Live-VP to count Turmoil points after end game is triggered.

### ISSUE THREAD

**Issue by vsrisuknimit** [bafolts/terraforming-mars#1435]
Once the main three parameters are maxed out, live-VP tracker should immediately take in Turmoil points into account and automatically update the changes.

**Comment by kevinb9n** [comment]
Meaning the 1 VP per party leader? I was under the impression that the Live-VP count would account for everything just as if the game were to end immediately.

**Comment by chosta** [comment]
Not for party points at the end of the last generation. It's still not
implemented.

**Comment by kevinb9n** [comment]
Sorry, I didn't ask my question clearly. I do get that filing a bug tends to mean the thing isn't implemented yet. :-)

I'm just asking about *when* the points should be accounted for in the live-VP total. Do Awards also wait until the endgame is triggered? What is the rule for when to begin accounting for points, etc.

**Comment by kevinb9n** [comment]
(my presumption and my "vote" would be that ALL points are accounted for "as if the game were to end immediately". So even though I could lose my 8th Tardigrade and get out-Scientisted before it ends, it still shows me the points first and then shows them going away if I *do* lose those.)

**Comment by nwai90** [comment]
@kevinb9n It will be implemented soon. The pending patch will add Turmoil points to the VP count when the game is in its last generation (i.e. once all global parameters have been maxed out).

In my view it would not make sense to show Turmoil points in real-time VP prior to that as they do not strictly "exist" before game end and could be misleading,  but this is of course a matter of opinion. It's not difficult to include Turmoil points in the count permanently; let's see what others think about it as well.

**Comment by kevinb9n** [comment]
I talked about my "vote" but really I'm more interested in consistency so that people can understand and remember what the number does and doesn't count. For example, if the principle is something like "the points don't 'strictly exist' yet", then that would be true of Awards too, right?

**Comment by nwai90** [comment]
That's a good point 👍 We can certainly go either way on this.

Another thing to consider is that Turmoil points tend to change very often, e.g. at the end of every generation. It might not give an accurate picture of who is leading as a result. Awards are usually less "swingy" in this regard and also something you build towards throughout the course of the game.

**Comment by kevinb9n** [comment]
I'd also like to know what others think, not just on the question of party leaders only, but on what is the *entire* set of VP sources that they think should only be accounted in the VP tracker once game end is triggered, or perhaps should not at all.

(Is this the first source of VPs that's being proposed to treat this way, or are the other precedents?)

1st place for Awards might not be highly swingy as people tend to only fund safe ones, but I wouldn't be surprised if the 2nd place points swing quite a bit, and that's still 2 points vs. 1 here.

My "vote" isn't the important part, but just to express it: I think a party leader is 1 victory point "in the bank" at any point in the game, it's your victory point to lose just like your 4 Tardigrades are in the presence of Ants. I think the VP tracker should have the simple meaning that "if somehow the game could end at this instant, this is exactly what your score would be" (unless that is already unattainable for other reasons I don't know).

**Comment by nwai90** [comment]
Fixed and merged
