### ISSUE TITLE
Feature request: Pharmacy Union should be grayed out once it is flipped

### ISSUE THREAD

**Issue by vsrisuknimit** [bafolts/terraforming-mars#1437]
Currently it is not possible to tell if Pharmacy Union is already flipped or not.

We should gray out the corp card when it is already flipped.

**Comment by kevinb9n** [comment]
Claim: a flipped Pharmacy Union is "not in play" in the very same sense as flipped event cards, so perhaps the same visual cues are appropriate for both.

Could gray out entire card, or perhaps gray out just tags and action.

**Comment by alrusdi** [comment]
It is done. Thanks to @nwai90
