### ISSUE TITLE
"Exclude some cards": support the list being pasted in

### ISSUE THREAD

**Issue by kevinb9n** [bafolts/terraforming-mars#1440]
Currently you can exclude individual cards by name.

Suppose we had defined, named, community-curated groupings of cards, spanning projects/preludes/corps/events and across expansions. And that these groups can be +'d or -'d to any game by name. It would support some use cases like

* In a colonies+turmoil+corpera game (no venus), remove all floater cards, as they're too hard to synergize
* Remove all attack cards (yeah, it makes plants too strong)
* Remove cards that are considered useless in solo play
* Remove cards considered to be complex
* *Include* the cards from &lt;expansion-not-in-use&gt; that have no hard dependencies on any other component of that expansion (for example the 7 project cards and 4 of the corps that come along with Prelude)

Other ideas?

**Comment by kberg** [comment]
Not sure I'd define card groupings -- everyone's going to have their preference. But, what I could see is changing the card-removal screen from inserting a bunch of names one at a time to a comma-separated list of card IDS.

**Comment by kevinb9n** [comment]
Would any solo players out there ever miss any of these cards if they never came up again?

These are either unplayable or seem to have no purpose (sans Media Group):
https://ssimeonoff.github.io/cards-list#050#066#099#121#173#X06

These seem to just be uniquely bad in solo, maybe?:
https://ssimeonoff.github.io/cards-list#178#124#C02#T02#X16#P29#P09

These have benefits that seem to scale linearly with player count:
https://ssimeonoff.github.io/cards-list#007#038#096#099#107#129#189#200#214#C13#C31#C27#T04

**Comment by kberg** [comment]
Would I miss them? No. Would I omit them? No - cards that are useless in solo become part of the challenge of filtering through the deck. If a player wants to omit it themselves, that's their option.

**Comment by kevinb9n** [comment]
The comma-separated card ids list is a pretty good compromise, because then a wiki page can have any number of such lists. I now think that's the most we should do here.

**Comment by kevinb9n** [comment]
showing that pasting doesn't work, and even that it looks to the uninitiated like maybe it did work.

Why the heck these are the three names that came to mind I can't say.

![image](https://user-images.githubusercontent.com/934551/102526743-fe1ff280-4050-11eb-8142-0fba6a48e958.png)

**Comment by alrusdi** [comment]
Why not to use load game settings feature instead of this?

**Comment by kevinb9n** [comment]
You can only load an entire game configuration all at once, and this may be fragile as options change.

Also this is how a user expects a box where they can type to work. Pasting is supposed to be just easy typing.

**Comment by bafolts** [comment]
This seems important to fix. At a minimum if someone pastes into that box we have to do something. This looks like a bug to me.
