### ISSUE TITLE
Bug/Question: Calculation of temperature?

### ISSUE THREAD

**Issue by Buheda** [bafolts/terraforming-mars#1463]
After using DEIMOS DOWN PROMO temperature increased to 4 (from -26 to -22), but should be 3.
After spending 8 heat temperature increased from -22 to -20. But should be 1

Or It should be steps but not degrees?

![map-28](https://user-images.githubusercontent.com/5812181/94992507-15435e00-0593-11eb-88aa-541171f8fe9c.jpg)
![log-28](https://user-images.githubusercontent.com/5812181/94992505-14123100-0593-11eb-88c2-edcb7f623b78.jpg)
![map-22](https://user-images.githubusercontent.com/5812181/94992511-1b393f00-0593-11eb-9d41-02c66f699678.jpg)
![log-22](https://user-images.githubusercontent.com/5812181/94992545-5d628080-0593-11eb-8775-5856f2f9c31c.jpg)
![all-20](https://user-images.githubusercontent.com/5812181/94992513-1d9b9900-0593-11eb-945e-46a5f72e9d3f.jpg)

**Comment by nwai90** [comment]
@Buheda It refers to steps :) In this case, 1 step is 2 degrees

**Comment by Buheda** [comment]
@nwai90  Thank you ) In Russion translation there are no word "step" in most of cards.
