### ISSUE TITLE
Payment widget should not permit a state in which any resource is being discarded for no value

### ISSUE THREAD

**Issue by kevinb9n** [bafolts/terraforming-mars#1464]
Proposal: the payment widget should at all times obey the invariant that each amount selected is a local minimum: you cannot decrement any value by 1 and still be able to purchase the card. Put another way, you can never change a single value by itself; something else must always change in response. That makes sense because what you're choosing is not really the amounts, but how to divide up a cost into various buckets. Making one bigger should always make another smaller.

It's not stated clearly in the game rules or FAQ, but I think everyone understands that when a card says "spend 3 energy" you cannot just voluntarily spend 4 instead (and thus get your Factorum to kick in that way). I don't think the payment widget ever deals with energy, but the principle should be the same - you don't just throw stuff away for no reason.

I think you shouldn't be able to get the widget into this state, whether by typing, up-arrowing, or hitting max.

**Comment by nwai90** [comment]
Fixed and merged

**Comment by kevinb9n** [comment]
As #1466 states, it only "partially" addresses this issue. See:

![image](https://user-images.githubusercontent.com/934551/95024209-7c661e80-0636-11eb-85b1-2e4c0b949fa1.png)

**Comment by kevinb9n** [comment]
Verified still not fixed.

**Comment by kevinb9n** [comment]
If it's not bad behavior, I'd like to broaden this request slightly:

It would be really fantastic if the payment widget simply never permitted ANY invalid states to exist: either the "you are unnecessarily throwing away resources" state already described, or the "you haven't paid enough" state.

It would be a big relief to just be able to mess with the value and submit. Right now I often feel uneasy like I have to check carefully what it's doing.

One thing that might help: consider making the megacredits box special, and not permit any direct changes to it at all. Users only change the other resources and it always calculates the MC in reaction to that. If not that, consider at least not allowing any TYPING, so that arrowing can simply skip over invalid values.

**Comment by kevinb9n** [comment]
It was shown on discord maybe a week ago or so that at least the backend is preventing such payments from occurring, with an error message.

Today it was claimed this error is perhaps not working for Stormcraft. Screenshot was shown of selecting 7 Heat 1 Floater but it's not clear whether the game accepted that payment.
