### ISSUE TITLE
FR: use deck-based random initial city selection for solo.

### ISSUE THREAD

**Issue by kberg** [bafolts/terraforming-mars#1467]
The official solo rules [ref](https://www.fryxgames.se/TerraformingMars/TMRULESFINAL.pdf) for placing random initial tiles is

> 1) Before you choose your cards, place 2 neutral city tiles on the map with an adjacent greenery tile each (these tiles are not yours, and do not increase the oxygen level): reveal and discard the 4 top cards of the deck and use their cost numbers to determine the positions of the tiles. The first city is placed counting from top left to right and down, like reading. Skip any illegal placements (like areas reserved for ocean). For the second city you step backwards from bottom right in the same fashion. Then you place the two greeneries by counting the cost numbers and stepping clockwise around each city, starting from top left, skipping illegal placements.

The current design doesn't do this, it relies on a random number generator in `Board.getRandomCitySpace().`

Ares needs similar behavior, but instead I wrote code that matches the intent of the game rules:
```
public getAvailableSpaceByOffset(distance: number, direction: -1 | 1) {
    // By doing an additional filter on space.tile, it skips over hazards.
    var spaces = this.getAvailableSpacesOnLand(undefined).filter(space => !space.tile);
    var idx = (direction === 1) ? distance : (spaces.length - (distance + 1));
    return spaces[idx];
}
```
If people would prefer it I can replace Board.getRandomCitySpace with this algorithm (and the other half, which draws a card and computes that distance accordingly.)

```
function randomlyPlaceHazard(game: Game, tileType: TileType, direction: 1 | -1) {
    var card = game.dealer.dealCard();
    game.log(
        LogMessageType.DEFAULT,
        "Dealt and discarded ${0} (cost ${1}) to place a hazard",
        new LogMessageData(LogMessageDataType.CARD, card.name),
        new LogMessageData(LogMessageDataType.STRING, card.cost.toString())
    );

    var distance = card.cost - 1;
    distance = Math.max(distance, 0); // Some cards cost zero.
    var space = game.board.getAvailableSpaceByOffset(distance, direction);
    if (space === undefined) {
        throw new Error("Couldn't find space when card cost is " + card.cost);
    }
    AresHandler.putHazardAt(space, tileType);
    return space;
}
```

If there's interest I will assemble a PR to bafolts/master.

**Comment by bafolts** [comment]
I prefer your implementation to what exists today as it is a better reflection of the rules. I remember this board setup being one of the first things written early on! The unit tests create a lot of one player games which at one point would run through this board setup logic. We had a flew flaky tests show up when our current logic would loop indefinitely depending on which spaces it happened to draw first.
