### ISSUE TITLE
Cards titles are not translated in the game log

### ISSUE THREAD

**Issue by Lynesth** [bafolts/terraforming-mars#1486]
Uses the proper translation when clicking on it to show the card, but the name in the log is not good.

**Comment by Lynesth** [comment]
@alrusdi This may not be directly related to that so you might prefer to open a new issue. Let me know.

How can we translate game log lines' parameters?

Take this translation for example:
`"${0} used ${1} standard project": "${0} a réalisé le projet standard ${1}",`

In english:
`Bob used Power Plant standard project`
becomes in French:
`Bob a réalisé le projet standard Power Plant`

"Power Plant" doesn't get translated (to "Centrale" in this case).

Is it a bug?
If not, is it possible to make it translatable?

**Comment by alrusdi** [comment]
Yes it is a bug. This problem has the same root as untranslatable card titles.

**Comment by Lynesth** [comment]
Fixed with #1541.
