### ISSUE TITLE
Inventrix gets +/- 2 steps on venus

### ISSUE THREAD

**Issue by Maelstrom1** [bafolts/terraforming-mars#1489]
Incredibly self explanatory. Inventrix was allowed to play cards that should not have been playable because its ability does not include Venus; that's exclusive to Morning Star.

![](https://media.discordapp.net/attachments/692836080323526698/762474620317859860/chrome_RZ2t8UheAr.png)

![](https://media.discordapp.net/attachments/692836080323526698/762474622872190976/chrome_uhXUQ4865X.png)

![](https://media.discordapp.net/attachments/692836080323526698/762474625736114197/chrome_QSvRNEmZa8.png)

**Comment by alrusdi** [comment]
Not a bug actually
https://boardgamegeek.com/thread/1850152/question-authors-adaptation-technology-special-des
**"..Adaptation Technology, Special Design, Inventrix also affect Venus requirements."**

**Comment by kevinb9n** [comment]
Can we call this a display bug then? Either we can

* change the card to say "global params" instead of calling out 3 of the 4, or
* dynamically make the card add "/ Venus" only when Venus is in use?

**Comment by nwai90** [comment]
@kevinb9n Yes, what's not possible on the physical print version can be done on the web app 👍  Agree that stating "global parameters" is a more generic and clearer term.

**Comment by alrusdi** [comment]
Let's reopen it then

**Comment by kevinb9n** [comment]
Thanks! Oh, I said "the card" but I believe we are really talking about three cards.

**Comment by nwai90** [comment]
Implemented
