### ISSUE TITLE
Toggle for turning on all official expansions

### ISSUE THREAD

**Issue by vsrisuknimit** [bafolts/terraforming-mars#1493]
Many users play with all expansions. It would be useful to have a small toggle next to the word Official for turning on all the official expansion.

Tagging @kberg .

![image](https://user-images.githubusercontent.com/14239220/95114913-a7be3b80-0712-11eb-94a3-6f0912e96cf9.png)

**Comment by kberg** [comment]
Take a look at the PR. Try it out.
