### ISSUE TITLE
Helion order of operations for payment

### ISSUE THREAD

**Issue by andystager** [bafolts/terraforming-mars#1510]
When trading with the Luna Colony as Helion, the MC I collected from the Colony was available to spend before the game asked how I wanted to pay (MC vs. heat).

I was able to spend the MC I collected from the transaction (I was low on MC and should have been forced to spend heat).

**Comment by kevinb9n** [comment]
Assuming this is reproducible it sounds like Helion has revealed an underlying issue. Costs should always be fully processed before any effects of paying the cost. (An effect like that of Moss which requires you to lose resources is different from a "cost".)

**Comment by kberg** [comment]
I've been looking a lot at order of payment operations, though related to tiles and not colonies. Happy to own this, though I might not get to it soon.

**Comment by bafolts** [comment]
Helion is a continual frustration. Most places this happens the property for `canUseHeat` is usually forgotten.

**Comment by kberg** [comment]
Yeah, no, this is a different sort of beast. And a nasty one. I'll still have a passing interest, though.

**Comment by Lynesth** [comment]
I have a fix for most (maybe all, didn't check) of those interactions that I can propose after the merge of the new interrupts.

**Comment by nwai90** [comment]
@Lynesth Assigned as requested~

**Comment by Lynesth** [comment]
@nwai90 This can be closed now that https://github.com/bafolts/terraforming-mars/pull/1789 is merged.
