### ISSUE TITLE
Add language (& more) to debug-ui

### ISSUE THREAD

**Issue by Lynesth** [bafolts/terraforming-mars#1515]
Could it be possible to add the "language-xx" class to the body of the debug-ui please?

Also if you could add all the prelude and corps cards in there as well, that would be awesome.
Edit: Also add the `RES: X` in the bottom left of the card as well please, as if it was in the game.

**Comment by alrusdi** [comment]
Corporations and preludes are already there.
I will add language switcher.
Unfortunately **Res: x** is almost unachievable

**Comment by Lynesth** [comment]
> Unfortunately Res: x is almost unachievable

Oh really ? Since the related cards already have the `hover-hide-res` class I thought it would be pretty easy to add.
I guess I can use a bit of javascript in-browser to add it to those if I want to check I suppose. It's not a very important issue.
