### ISSUE TITLE
No end game page in solo play

### ISSUE THREAD

**Issue by vincentneko** [bafolts/terraforming-mars#153]
Just finished a single player game (I've lost it), the game did not displayed end game page, just this message on main page :

![image](https://user-images.githubusercontent.com/56086992/71488894-4e3fec80-2823-11ea-910a-2462ae536dcb.png)

**Comment by alrusdi** [comment]
I will take it. There are also some issues with player cubes crop and notifications

**Comment by alrusdi** [comment]
Fixed
