### ISSUE TITLE
Page is blinking on any action

### ISSUE THREAD

**Issue by alrusdi** [bafolts/terraforming-mars#1531]
Now we load log messages from the server on each update and they are loading slower than other parts of the page. When log is loaded page is "blinking" because new block is appearing on it

**Comment by kberg** [comment]
Related to https://github.com/bafolts/terraforming-mars/pull/1428 I assume

**Comment by bafolts** [comment]
The `log-panel` has a `max-height` but no defined `height`. Setting a `height` and `max-height` should solve problem. After the first few actions logged the `max-height` should be reached anyway. The log messages are loading asynchronous so will always come in after page has loaded. Eventually this separation should allow a user to go back and see logs from previous generation or more than 50 messages back in the log component.
