### ISSUE TITLE
Communal corp selection by all players

### ISSUE THREAD

**Issue by kevinb9n** [bafolts/terraforming-mars#1546]
Hello! This barely even qualifies as a "variant" at all. It's an extra step during game setup.

Call the number of corporations players will choose from "N". (Rules say 2, we like to do 3.)

Here's how it works:

* When each player first opens their link, the game hasn't actually begun yet. *Optionally*, the chosen milestones/awards/colonies/map *could* be available at this time, but no player-specific information such as turn order.
* Each player sees 2N randomly dealt corps. 
* Each simultaneously chooses N that will be in the game and N that will be out. They submit and wait for others.
* The ones that are kept in are all shuffled together and this becomes the entire corporation deck for that game.
* The players' pages refresh and the game begins exactly as prescribed. You may or may not get the corps that you chose to put in the game.

This addresses some of the same reasons that today a game creator might exclude a smattering of corps, but allows all players to share in the decision.

What incentives do players have in making this selection?

* Choose a corp I think just *makes the game better*, knowing I have equal chances to get it as anyone
* If I think a corp is overpowered with this player count, throw it out to reduce luck of the draw
* Keep corps I think are interesting
* Throw out corps I've just seen too much lately
* Keep a corp I haven't seen played in a while, or ever
* Express my personal dislike of using fan corps
* Throw out corps that I know others are better at playing than I am (arguably this is sad, removing the challenge to improve at playing that corp, but I'll still have to face it in future games when others keep it in)

We've used this process for at least a dozen over-the-table games and it seems to work out really well. If a certain corp is universally loathed by all in your regular group, cool, you'll never see it in a game again. If it's loathed heavily by ONE player, you'll just be *less likely* to see it. Etc etc.

Variations

* Have each player choose N+1 or more to be kept. Then the choice to keep no longer guarantees that someone gets it in their opening hand.
* Vary the total number to choose from (more or less than the 2N used above)

**Comment by nwai90** [comment]
@kevinb9n Excluding certain corps or selecting a fixed set of corps is already possible with `Custom Corporation list` option

**Comment by kevinb9n** [comment]
@nwai90 yep

**Comment by kevinb9n** [comment]
So this is really just about sort of "democratizing" that choice to all the players.

**Comment by vsrisuknimit** [comment]
Some people already do that in the chat rooms.

**Comment by kevinb9n** [comment]
This got only 3 votes in the chat room (including me), so it probably wouldn't be used much.
