### ISSUE TITLE
Mining Guild shouldn't activate credit during WGT.

### ISSUE THREAD

**Issue by kberg** [bafolts/terraforming-mars#1564]
Bug report:
> Bug: mining guild increase steel prod 1 step   when other players  place a tile and  gain steel/titanium placement bonus
> if anyone want to fix this , don't forget : MiningGuild places an ocean act as the WG shouldn't increase his steel prod too

**Comment by kberg** [comment]
(The first half seems not a bug, and this bug is just for WGT.)

**Comment by kberg** [comment]
I wonder whether onTilePlaced just should be called *at all* during WGT. Probably not. Ugh,which means fixing this one card at a time.

**Comment by nwai90** [comment]
@kberg I was looking through the old logic. Turns out that the left and right sides of https://github.com/bafolts/terraforming-mars/commit/28e0551c9eda75a754678a35f11c27173d5f2f4b#diff-e8b30ddd4350a1c8673e916ee71ebd4eR1497 are not equivalent.

A safer approach that would not break existing games might be to reorder the steps to keep the original logic. Will send a commit that you can take a look at shortly

**Comment by Lynesth** [comment]
> I wonder whether onTilePlaced just should be called _at all_ during WGT. Probably not. Ugh,which means fixing this one card at a time.

Actually you can get plants from Arctic Algae and M€ production from Lakefront Resorts, so not all of them :)

**Comment by nwai90** [comment]
@kberg See https://github.com/bafolts/terraforming-mars/commit/0d94e05602535c44b90bc5c3ac1125fdb4acfc11. The crux of the previous logic was that onTilePlaced should be run before `space.player is set to `undefined`. I've added unit tests to cover the WGT scenario as well.

**Comment by kberg** [comment]
Huh! Where's the break? If you reorder the steps, it runs the risk of breaking a lot of Ares. I look forward to your PR, but if you can explain what you mean that would help a lot.

**Comment by nwai90** [comment]
Not sure if this would work with Ares; feel free to check on local and use it if you see fit

**Comment by kberg** [comment]
Whew, that looks a lot less invasive than I feared. :D -- let me read this a bit. (Also go see what I suggested for addressing WGT in #1566

**Comment by kberg** [comment]
(Happy to chat on discord if this is easier.)

**Comment by kberg** [comment]
> @kberg See 0d94e05. The crux of the previous logic was that onTilePlaced should be run before space.player is set to undefined`. I've added unit tests to cover the WGT scenario as well.

/headslap. Yeah, that makes sense! OK, I'll spend some time on this tonight.

**Comment by nwai90** [comment]
@kberg This introduced a new bug: Other players placing ocean tiles now also give Mining Guild a steel production bonus. I will merge https://github.com/bafolts/terraforming-mars/pull/1567 which fixes this issue and adds unit tests to cover all Mining Guild scenarios.
