### ISSUE TITLE
Aerospace mission not showing colony names

### ISSUE THREAD

**Issue by GJonatan** [bafolts/terraforming-mars#1574]
Had issue with the prelude card Aerospace mission not showing the names of the colonies, had this issue in two different games.
![121167630_836840773792493_1074447198855088789_n](https://user-images.githubusercontent.com/71512380/95682180-32f07300-0be4-11eb-8ce1-c91209468fa5.png)

**Comment by Lynesth** [comment]
This has been fixed yesterday. Ask your server administrator to update to the latest version :)
