### ISSUE TITLE
With a corp-mandated first action, let the player play it voluntarily

### ISSUE THREAD

**Issue by kevinb9n** [bafolts/terraforming-mars#1576]
Better if the mandated first action doesn't just happen automatically while I'm not looking.

Then I'll be more aware that it happened, and more aware that I have either 0 or 1 actions left, not 1 or 2 as usual.

For Vitor it's the same "Fund an award" option we already have, just for no money. Possible verbiage for the others:

* Draw 3 cards (Inventrix)
* Draw 3 Venus cards (Morning Star)
* Draw 2 floater cards (Celestic)
* Draw a microbe card (Splice)
* Choose and play a Prelude card (Valley Trust)
* Choose an additional colony tile (Aridor)
* Place a city tile (Tharsis Republic)
* Place a greenery tile (Philares)
* Place a colony (Poseidon)
* Place a community (Arcadian)

In fact, the current behavior is actually a rules error. A player with one of these corps is allowed to pass. If so, in gen 2 they remain in the same state: only two choices, special action or pass. When you have no other plans for gen 1, having this ability to defer can sometimes be helpful. A corp like Vitor or even Tharsis might prefer to wait and see what other players do during the first generation before deciding.

**Comment by kberg** [comment]
How are the the corp-mandated first actions for Tharsis Republic, Philares, et cetera not played voluntarily? I seem to recall that you are told to choose a space.

**Comment by kevinb9n** [comment]
Sure, it's only the first four in the list that completely run themselves, but that's not really the point.

I think if the player can be in control of whether to initiate it, it's more correct rules-wise and also a less confusing experience.

**Comment by kberg** [comment]
Just to make sure I get it -- you're saying that in those cases the first
action shouldn't happen automatically, but just be a single option
available "execute this starter corp action?"

>

**Comment by kevinb9n** [comment]
Yes, that's how I think it should be in all ten cases - that option, and "pass this generation".

**Comment by Lynesth** [comment]
@kevinb9n I wanted to take a look at this today and add relevant buttons, but was not able to find an official comment saying you can pass your first generation and not take your first action. While it does make sense to me, do you have a source for that please ?

**Comment by Lynesth** [comment]
Nevermind, I found it just after commenting: https://boardgamegeek.com/thread/1784175/ocean-adjacency-and-first-actions#25942959

**Comment by kevinb9n** [comment]
Should have included that the first time, sorry!
