### ISSUE TITLE
Biomass Combusters doesn't message targeted player

### ISSUE THREAD

**Issue by ASayre** [bafolts/terraforming-mars#1578]
When playing biomass combusters, which decreases another player's plant production, there is no message in the game log about who was targeted.

**Comment by Lynesth** [comment]
I am not able to reproduce this bug on the latest version.

**Comment by bafolts** [comment]
This should have logged

https://github.com/bafolts/terraforming-mars/blob/master/src/Player.ts#L303

This was most likely user error of some kind.

**Comment by ASayre** [comment]
Very possible, though I swear I have witnesses! :) Anyways, can no longer repro either.
