### ISSUE TITLE
Venus Next

### ISSUE THREAD

**Issue by vincentneko** [bafolts/terraforming-mars#159]
I've started working on Venus Next extension.

This will be a big task, I think I could use some help, at least with the UI part.

**Core tasks done:**
Venus board (Thanks alrusdi !)
Word Gov terraforming phase
Air scraping standard project
Venus Scale parameter (server side)
New cities on board (server side)
New award (venuphile)
New Milestone (hoverlord)

**Corps + tests done 5/5:**
Aphrodite
Viron
Manutech (yeah !)
Celestic
Morning Star Inc.

**Cards + tests done 49/49:**
Giant Solar Shade
Deuterium Export
Aerial Mappers
Ishtar Mining
Aerosport Tournament
Air Scrapping Expedition
Comet For Venus
Dirigibles
Atmoscoop
MaxwellBase
Dawn City
Corroder Suits
GHG Import From Venus
Atalanta Planitia Lab
Extractor Balloons
Extremophiles
Floating Habs
Freyja Biodomes
Gyropolis
Hydrogen To Venus
Io Sulphur Research
Jet Stream Microscrappers
Luxury Foods 
Minning Quota
Neutralizer Factory
Omnicourt
Orbital Reflectors
Local Shading
Luna Metropolis
Rotator Impacts
Sister Planet Support
Solarnet
Spin-Inducing Asteroid
Sponsored Academies
Stratopolis
Stratospheric Birds
Sulphur Eating Bacteria
Sulphur Exports
Terraforming Contract
Thermophiles
Venus Governor
Venusian Animals
Venusian Insects
Venusian Plants
Venus Magnetizer
Venus Soils
Venus Waystation
Water To Venus

**Comment by alrusdi** [comment]
I can make Venus board. Did you start new branch for it?

**Comment by vincentneko** [comment]
Yes but on my repo, do you want to work on bafolts repo ?

**Comment by alrusdi** [comment]
Yes, i think it will be better

**Comment by vincentneko** [comment]
Ok, I've created venus-next branch on bafolts repo.
I've added the 4 colonies in OriginalBoard, ids are 70 to 73, I've made some tests with Maxwell Base
4th parameter is venusScaleLevel, it's server side implementation should be ok
Word Gov terraforming phase should work as well

**Comment by alrusdi** [comment]
Board for Venus is added

**Comment by vincentneko** [comment]
> Board for Venus is added

Thanks, it's great !

**Comment by vincentneko** [comment]
@alrusdi , I played Maxwell base and the hex on the board went black (the border disapeared) and no token was placed on the tile.

**Comment by alrusdi** [comment]
@vincentneko yes, i forget about tile placement. Will do it next

**Comment by alrusdi** [comment]
Added tiles placement to Venus board, merged master branch

**Comment by vincentneko** [comment]
@pierrehilbert thanks for the last 5 cards, all is complete, MR incomming !
