### ISSUE TITLE
New game selection UI hides (i) text when clicked.

### ISSUE THREAD

**Issue by kberg** [bafolts/terraforming-mars#1593]
![image](https://user-images.githubusercontent.com/413481/95796366-ab296800-0cba-11eb-8a4a-ead96b87ccdf.png)

Up close that contrast doesn't seem so bad, but lining it up with the text makes this a nice starter issue.

**Comment by vsrisuknimit** [comment]
- after the users select an option, they probably do not need the link anymore
- the color is from <a> tag style in common.less, it currently overwrites the font color of label that is selected.

**Comment by kberg** [comment]
> after the users select an option, they probably do not need the link anymore
And if they do they have to unselect it? That's not a good UX reason. Put the (i) outside of the box instead?

**Comment by kberg** [comment]
![image](https://user-images.githubusercontent.com/413481/95799928-2e9b8700-0cc4-11eb-9179-00a2b9cdeaa4.png)
