### ISSUE TITLE
Request: on initial card selection screen, tell all players what game options are in effect

### ISSUE THREAD

**Issue by kevinb9n** [bafolts/terraforming-mars#1598]
On initial card selection screen, it would be nice to tell all players what game options are in effect.

**Comment by kberg** [comment]
I agree. It's lost once you share a link.

**Comment by kevinb9n** [comment]
I've had a few solo games recently where halfway through the game I suddenly couldn't remember whether I was in TR63 mode or not!  Also when replaying existing seeds this can be an issue. From both the cards selection screen and the main game interface there should be some way to discover all the options that were in effect.
