### ISSUE TITLE
Make UI update interval configurable

### ISSUE THREAD

**Issue by Lynesth** [bafolts/terraforming-mars#1602]
Default interval between server calls is set to 5000ms.

I wanted to make it configurable by adding a environment variable but the Vuejs component is not able to access it.
At least I didn't manage to make it work (process.env is empty), but note that I did not install any dependency (someone mentioned dotenv-webpack).

The idea was to do (in src/components/WaitingFor.ts):
```ts
ui_update_timeout_id = (setTimeout(askForUpdate, Number(process.env.UI_UPDATE_INTERVAL) || 5000) as any);
```

@bafolts @vincentneko is that a correct approach or should it be done differently ?

**Comment by alrusdi** [comment]
process.env.UI_UPDATE_INTERVAL is not available on the client side

**Comment by bafolts** [comment]
For situations like this the data needs to get to `src/components/App`. I recently put in a change that was very hacky at best trying to solve a similar problem.

https://github.com/bafolts/terraforming-mars/blob/master/index.html#L15

Thinking about this again we should have webpack create a `settings.json` that we import into `src/components/App.ts` to make available to the application.
