### ISSUE TITLE
Adding player links back to end game page

### ISSUE THREAD

**Issue by vsrisuknimit** [bafolts/terraforming-mars#1619]
This was removed after #1521 . The links are quite functional. Please consider adding them back. 

Tagging @bafolts @pocc

**Comment by bafolts** [comment]
A player's color is used as their public id during game play. Once the game has ended we should be able to send the private player id in the model so that we can provide these links. On `PlayerModel` the `id` property would be `undefined` unless the game phase is `Phase.END`.

**Comment by pocc** [comment]
@vsrisuknimit The links were not functional and clicking was a noop. See https://github.com/bafolts/terraforming-mars/issues/1518.
