### ISSUE TITLE
Possible issue with gardener milestone

### ISSUE THREAD

**Issue by chosta** [bafolts/terraforming-mars#1621]
From discord `@smallman`
`minor bug:  After about 30 games of random milestones, I have NEVER seen the gardener milestone.  Some devs mentioned they already suspected this wasn't truely random.  Atleast half have been on Hellas map.  Would also love an option to have no milestones at all, they are way too luck dependant for my liking.`

Can we somehow make a dry run of lets say 10k randomizations and get some statistics on the frequency of each M or A?

**Comment by bafolts** [comment]
Using the `tests/MilestoneAwardSelector.ts` one could call to `getRandomMilestonesAndAwards` multiple times. I am not sure if the logic can guarantee that 3% of the time one sees the gardener milestone. I would assume after 10k games we would expect to see it.

**Comment by chosta** [comment]
Well, the real question is whether we have a milestone (or more) that is heavily underutilized.

**Comment by bafolts** [comment]
> I am not sure if the logic can guarantee that 3%

I had to say 3%.....LOVE this chart :-)

**Comment by Lynesth** [comment]
Well, Gardener Cultivator and Tycoon all have 7 or more pairs of synergy higher than 1.
Estate Dealer, Desert Settler, Landlord have 6.
Planner, Tactitian, Generalist and Legend have none.

This explains that.

**Comment by kberg** [comment]
This graph shows that each milestone/award has a nearly equal chance of occurring: 
![image](https://user-images.githubusercontent.com/413481/96198096-d3ff6680-0f21-11eb-9c82-fc03eeb60b3e.png)

(Minor code hack just to test that assumption.)

**Comment by kberg** [comment]
I did synergies 1-9. Unsurprisingly they converge: 
![image](https://user-images.githubusercontent.com/413481/96200243-7110ce00-0f27-11eb-83e5-c2c4044c965c.png)

Hard to see -- I tried making a 3d graph but no luck. Anyway, the raw data is here https://docs.google.com/spreadsheets/d/1TwB1yF9USTlZt4egbqHx0uE4Fs8luuTNnh0R3y31NC0/edit#gid=323909500

**Comment by Lynesth** [comment]
We pick 10 Milestones and Awards out of a total of 30.

If Gardener is in there, there's 32% chance that there's also another MA that has a score of 2+ with it. So when you add the chances that the others end up with a bad pair as well, I'm not surprised that we get a ~3% chance of getting Gardener.

**Comment by vsrisuknimit** [comment]
Please check #1311 as well. I believe the simple algorithm I proposed is quite reasonable and will allow more chance for Gardener to be used. But also check a different synergy matrix on that issue as well.

**Comment by Lynesth** [comment]
Without changing anything to the synergies or the constraint (nothing above 1) we can get a "flatter" curve by adding miletones and awards to the array 1 by 1 instead. It is also faster to compute.
![firefox_2020-10-16_12-57-53](https://user-images.githubusercontent.com/5318258/96204177-61d56300-0faf-11eb-9768-ffd2f839f0df.png)

Increasing the maxSynergyAllowed to 2 or 3 - see both graphs below - would give "better" results (which we wouldn't get with the current implementation anyway).
![firefox_2020-10-16_13-04-48](https://user-images.githubusercontent.com/5318258/96204587-69e1d280-0fb0-11eb-9b62-22f853fb8238.png)
![firefox_2020-10-16_13-06-23](https://user-images.githubusercontent.com/5318258/96204591-6b12ff80-0fb0-11eb-8bf4-eeae3674a0b3.png)

**Comment by chosta** [comment]
Thanks for the graphs! This is exciting engineering work :)
I am also here for my 'I told you so' moment. Had a feeling we might have some big discrepancies with our approach from the very start. 3% is very low IMO, we have to readjust.

**Comment by vsrisuknimit** [comment]
Here is the distribution of my proposed algorithm in #1311 .

![image](https://user-images.githubusercontent.com/14239220/96245478-5bc29080-0f75-11eb-87f1-4df687866bec.png)

**Comment by chosta** [comment]
Much better imo.

We were discussing this with @nwai90.We think a slider in the game creation page, that allows for synergy change is the only correct answer to this issue.
@vsrisuknimit do you want to try do it with our help :)?

**Comment by vsrisuknimit** [comment]
@chosta let me try a few more ideas to balance this out even further. I prefer to have a good algorithm and then options for limited vs unlimited synergy. I don't want to overload users with choices. They might not understand what is synergy and what is a good value.

**Comment by chosta** [comment]
Ok.Makes sense.

**Comment by vsrisuknimit** [comment]
If I were to pick each M or A one by one as @Lynesth suggested. Here are the results:

Picking Milestones first. (You can see many high-synergy awards being last, but look at how Gardener moves up to 30.72%!)

![image](https://user-images.githubusercontent.com/14239220/96265711-caaee200-0f93-11eb-8b08-f4f8c31696c7.png)

Picking Awards first. (Now you see Gardener go back to being last, but here high synergy milestone like Builder is not tailing too.)

![image](https://user-images.githubusercontent.com/14239220/96265787-e4e8c000-0f93-11eb-89ac-66b63d0916e3.png)

**Comment by vsrisuknimit** [comment]
Algorithm
- Add one by one, alternates between award and milestone
- Add successfully if all the rules still obeyed

Rules
- no pair that is 7+ in synergy score (prohibit landlord & desert settler or terraformer & benefactor)
- not more than two pairs that is 5+ in synergy score (allow two mayor & landlord or gardener & polar explorer)
- total less than or equal to 20 in synergy score

![image](https://user-images.githubusercontent.com/14239220/96273227-174aeb00-0f9d-11eb-8f04-f9e3d3651e40.png)

**Comment by kberg** [comment]
I've been thinking about this -- such a slider could go from 1-9 (synergy),
say, 10-100 (represents the *sum of synergies.)* In either case, the
highest value means each option is just as likely to be selected.

>

**Comment by duckmammal** [comment]
You could always just have an "advanced options" section where you decide the algorithm for how you deal with synergies. Giving people reasonable options is good value, even if you have to hide them a bit.

**Comment by samyelias** [comment]
As I commented in #1311, there is a way to better equalize the chances, using weighting in the selection process. This is what I've done on [my fork of the MA randomizer](https://samyelias.github.io/ma-randomizer), [code here](https://github.com/samyelias/samyelias.github.io) . I optimized it for the case where you limit synergy to 3 or less (and my synergy values are a little [tweaked from the original](https://docs.google.com/spreadsheets/d/1dRpa9eUXjvPWg9-xyvaWrnD24I8ROXntFxRnswNBg40/edit?usp=sharing)). It would not be hard to figure out weights for other synergy values.

Before the weighting, this is what I was getting:

![random goals before weighting](https://user-images.githubusercontent.com/10133229/96401044-51380f00-11a0-11eb-8a85-2d74ff77e8d7.jpeg)

And this is after the weighting:

![random goals after weighting](https://user-images.githubusercontent.com/10133229/96401066-59904a00-11a0-11eb-85c4-82cd34074230.jpeg)

If you're curious about the weights they can be seen near the top here: https://github.com/samyelias/samyelias.github.io/blob/master/js/ma.js

**Comment by chosta** [comment]
This one has already been discussed and resolved (kinda)
