### ISSUE TITLE
Show player's VP without showing all VPs?

### ISSUE THREAD

**Issue by puuj** [bafolts/terraforming-mars#1624]
Once upon a time, the default was to see your own total victory points during the game. The current releases don't seem to do that, although the realtime VP does show everyone's VPs. 

I think this is a bug, and as near as I can find the issue is with getIsActivePlayer in playerInfo.ts -- this.player.id seems to return the player color rather than the player ID, although I can't figure out how that's happening.

**Comment by chosta** [comment]
#1630

**Comment by nwai90** [comment]
Fixed and merged
