### ISSUE TITLE
Aquifier and WaterImportFromEurope bugs?

### ISSUE THREAD

**Issue by rzulian** [bafolts/terraforming-mars#1632]
I've noticed this 8e4710503a429bbe54ac7e2554b6a3e825e9f821 from @nwai90.
What's the reasoning behind? If `oceanMaxed` is true,  you shouldn't have the option.

**Comment by Lynesth** [comment]
Increasing a global parameter or placing an ocean tile isn't mandatory.
You can take the action in that case even if it ends up doing nothing.

**Comment by rzulian** [comment]
I've found this FAQ on the blue actions https://www.boardgamegeek.com/thread/2270815/article/32879610#32879610, and you are correct.
Is it the standard project  "Add an ocean" always available accordingly?

**Comment by Lynesth** [comment]
According to the FAQ, the 3 exceptions rules is only valid for blue card actions and card play.
So I would I guess that standard projects (Asteroid / Aquifer) probably are not (the difference being that they are not limited to once per generation while other options mentioned are).

**Comment by rzulian** [comment]
Jacok said "Also, the same applies to any action at all, including standard projects, converting plant and heat, trading with a colony tile etc.".
I'm still not understanding the need for this rule. It can only be used to do a dummy and costly move and pass.

**Comment by Lynesth** [comment]
Having ways to stall for time is always good in late game Terraforming Mars. If Jacob said Standard Projects are included, then I guess that's how it is.

(Jacob's comment for reference: https://boardgamegeek.com/thread/2270815/activation-blue-cards-no-benefit#32879610)

**Comment by rzulian** [comment]
WAD

**Comment by kevinb9n** [comment]
(This rule is also the reason you're, for example, still allowed to play Nitrogen-Rich asteroid when the temp is maxed. To keep that but address the issue here would require more weird special-casing.)
