### ISSUE TITLE
Solo game rules

### ISSUE THREAD

**Issue by vincentneko** [bafolts/terraforming-mars#164]
According to the rules book, which is not compatible with our implementation (see "Should finish solo game before last generation if Mars is already terraformed" test)

5) You always play 14 generations (marked ’solo’).
In order to win, you need to complete terraforming (i.e
making the three global parameters reach their goal) before
the end of generation 14. After generation 14, you may
convert plants into greenery tiles, following normal rules
but without raising the oxygen, and finally you score VPs
to get as high a score as possible. If you have not completed
terraforming by the end of generation 14, you lose.

If prelude is used, it is 12 generations.

**Comment by alrusdi** [comment]
I've misread this rule, sorry. Will fix it ASAP.
