### ISSUE TITLE
Bugs while playtesting

### ISSUE THREAD

**Issue by alrusdi** [bafolts/terraforming-mars#165]
1. MiningExpedition unplayable if no one have plants
2. Ecology Experts prelude card needs check, we were failed to play it
3. Eccentric Sponsor  prelude card needs check, we were failed to play it

**Comment by vincentneko** [comment]
I think 2 and 3 are linked.
I'm able to play Eccentric Sponsor without issue but then when I play ology Experts I cannot choose a card to play

**Comment by vincentneko** [comment]
There is a bug in getRequirementsBonus function, will try to find it

**Comment by vincentneko** [comment]
The bug is related to number of actions perfomed.

It will go into this code 

```
      if (this.actionsTakenThisRound >= 2) {
        this.actionsTakenThisRound = 0;
        console.log("set lastCardPlayedThisTurn to undefined");
        this.lastCardPlayedThisTurn = undefined;
        game.playerIsFinishedTakingActions(this);
        return;
      }
```

and then set this.lastCardPlayedThisTurn = undefined therefore ecology Experts bonus will not work.

There is something not working properly in takeAction method, I guess it is related to recursive call to takeAction with prelude cards.

**Comment by vincentneko** [comment]
I think I got it, PR incomming

**Comment by alrusdi** [comment]
@vincentneko can you please explain how to reproduce it? When we were playing real game - bug stopped us. But while testing i can play both prelude cards with no problems. Should i do some specific steps or play some specific cards?

**Comment by vincentneko** [comment]
The bug I was able to reproduce was:
Choose both Eccentric Sponsor and Ecology Experts
Play Eccentric Sponsor first, then Ecology Experts
>> Ecology Experts no requirement bonus will not work

I can't reproduce the bug that stopped your game. Do you remember what was the other cards you had ?

**Comment by alrusdi** [comment]
The card i wanted to play was "Extreme-Cold Fungus" but it has nothing special for "Ecology Experts" because it is playable even without the bonus.
I tried different combinations trying to catch that bug but had no luck. Now i think it can be some weird browser caching problem...

About a bug that you fixed. What card exactly  was unplayable? Any? I want to make unit test to cover this problem, but can't found a proper steps leading to the problem. In my case all the cards are playable.

Also, i faced strange situation when even the "Beam from a Thorium Asteroid" with "jovian tag" requirement was playable. Will try to reproduce it to be sure that i didn't something wrong/

**Comment by vincentneko** [comment]
> The card i wanted to play was "Extreme-Cold Fungus" but it has nothing special for "Ecology Experts" because it is playable even without the bonus.
> I tried different combinations trying to catch that bug but had no luck. Now i think it can be some weird browser caching problem...
> 
> About a bug that you fixed. What card exactly was unplayable? Any? I want to make unit test to cover this problem, but can't found a proper steps leading to the problem. In my case all the cards are playable.
> 
> Also, i faced strange situation when even the "Beam from a Thorium Asteroid" with "jovian tag" requirement was playable. Will try to reproduce it to be sure that i didn't something wrong/

About a bug that you fixed. What card exactly was unplayable? Any? No, only those with a requirement

**Comment by vincentneko** [comment]
This has been merged, can we close this issue ?

**Comment by alrusdi** [comment]
I think so
