### ISSUE TITLE
Importable Custom Setups

### ISSUE THREAD

**Issue by duckmammal** [bafolts/terraforming-mars#1657]
Every solo game I play I have about 3-5 mins of setup time because I have to do a lot of typing and button presses.

I set my color and select the basic options of the game format I'm interested in playing.
![image](https://user-images.githubusercontent.com/4755233/96371842-b2b49b00-1118-11eb-894b-6cedc48be47a.png)

I choose which corps I think are no fun to play, either because they are generally too weak or too strong to be compared with the other corps, or because they are inappropriate for the single player variant.
![image](https://user-images.githubusercontent.com/4755233/96371918-14750500-1119-11eb-8b30-621d05571291.png)

And I filter out 7 cards that I don't think are appropriate for solo games.
![image](https://user-images.githubusercontent.com/4755233/96371940-48502a80-1119-11eb-9bea-48c69b60620f.png)

I also sometimes forget to do one (or several) of these steps appropriately, and have a less enjoyable game.

It would be nice to have some sort of JSON file that I can upload to make my custom setup be implemented much more quickly. It also feels like it shouldn't be too hard to implement. This would also make setting up tournament play much more consistent, because players would only have to upload a file to have all the pre-defined game settings, and wouldn't be able to make many mistakes.

**Comment by kevinb9n** [comment]
I've held off on filing this because I want it so much it scares me. :-)

**Comment by alrusdi** [comment]
I've did it https://github.com/bafolts/terraforming-mars/pull/1634
Waiting for approve now...
