### ISSUE TITLE
Ruling Party Icon on Sidebar

### ISSUE THREAD

**Issue by vsrisuknimit** [bafolts/terraforming-mars#1662]
It would be very useful to play the icon of the ruling party to the sidebar. @ssimeonoff any suggestion for design? Watching the semi-final right now. This feature would help a lot.

**Comment by ssimeonoff** [comment]
Exactly identical to the ruling policies displayed under the turmoil board?

**Comment by vsrisuknimit** [comment]
@ssimeonoff I think the party icon is good enough. Smaller and consistent size. Where is a good location? Just directly below Mars / Gen tracker icon?
