### ISSUE TITLE
When the app auto-chooses because of a single option, log it.

### ISSUE THREAD

**Issue by kberg** [bafolts/terraforming-mars#1668]
I played Eos Chasma National Park, which lets me place an animal on a card. I was not informed of whether it played an animal on my card or not. Even if I, as an experienced player, should know that my Small Animals card is my only animal card, the app relies on me to know the difference between the game not telling me about the one animal token it placed, versus the game not telling me about not placing any animals at all.

**Comment by Lynesth** [comment]
It's more of an issue regarding missing logs here and there which we already improved quite a bit. I'll close this.
Feel free to reopen if I misunderstood the issue.
