### ISSUE TITLE
It's confusing to inexperienced players that there's a MC number in between all the VPs and the sum total.

### ISSUE THREAD

**Issue by kberg** [bafolts/terraforming-mars#1676]
![MC-embedded](https://user-images.githubusercontent.com/413481/96400391-94917e00-119e-11eb-9f01-c6894e01aefd.png)

Recommended solution: Move MC to the right of Total, add a small visual separator, and + and = signs, which could appear just in the header.

**Comment by kevinb9n** [comment]
(I'd also love for it to identify who the winner/s were - #1298 - but if not that, maybe somehow have it explain that MC is the official tiebreaker?)

**Comment by ssimeonoff** [comment]
Suggestions: 
- completely remove the MC column - it is obsolete in 90+% of the cases
- if there is a tie between players, show for them the MC values in the Total column
Example: 3 players, ending with 79,66,66. 
Total column to show: 
79
66 (50MC)
66 (40MC)
