### ISSUE TITLE
X34 Asteroid Rights

### ISSUE THREAD

**Issue by kevinb9n** [bafolts/terraforming-mars#1678]
![image](https://user-images.githubusercontent.com/934551/96404493-ec74b880-118f-11eb-8158-1c9199a093dc.png)

found at https://boardgamegeek.com/thread/2522417/asteroid-rights-new-promo-spielbox-magazine

**Comment by kberg** [comment]
Request for clarification: this is a request to add this card?

**Comment by kevinb9n** [comment]
I was thinking we might want to add the card, yes.

**Comment by nwai90** [comment]
Fixed and merged
