### ISSUE TITLE
Saturn Systems bug

### ISSUE THREAD

**Issue by vincentneko** [bafolts/terraforming-mars#168]
Opponent played ColonizerTrainingCamp, it did not increase my MC production.

**Comment by bafolts** [comment]
This issue will happen whenever an opponent plays a jovian tag. The `onCardPlayed` method for this corporation is only invoked when the owner of the corporation plays the card. All player corporations `onCardPlayed` will need to be called. This bug will exist for other `onCardPlayed` methods where the effect happens regardless of which player played the card.

**Comment by vincentneko** [comment]
Fixed and merged, thanks bafolts.
