### ISSUE TITLE
Add Colony, Corps, and Card bans to custom JSON

### ISSUE THREAD

**Issue by duckmammal** [bafolts/terraforming-mars#1683]
#1634 did a great job of remembering the basic information for a game, but didn't track the (much more important) bans / includes for Colonies, Corps, and Cards.

It'd be great to have the JSON expanded to include these.

**Comment by duckmammal** [comment]
Note: I only tried this for a solo game

**Comment by supahotjovs** [comment]
It is working for me for banned cards and custom corps list. Haven't tested colonies. After you load the json, the UI doesn't update with the list of cards and corps, unlike the other game options. However the game gets created with the correct settings from the json. Would be nice to see the UI get updated though.

**Comment by duckmammal** [comment]
Ah, thanks for pointing out that maybe it is working but the UI isn't updating properly. This is probably what is happening. I had just assumed it wasn't working because I didn't see the UI showing my selections.
