### ISSUE TITLE
Current MC total in sidebar

### ISSUE THREAD

**Issue by samyelias** [bafolts/terraforming-mars#1685]
While looking at my cards I found myself wishing I could have my current MC available displayed in the sidebar, rather than jumping to another part of the page. Maybe your current steel and titanium tokens should also be in the sidebar?

The image for the MC number could double as a link to jump to your player display.

**Comment by duckmammal** [comment]
i feel like all of that box could be pinned to the top (or right) side of the screen.

**Comment by vsrisuknimit** [comment]
Player's own resource summary box used to be pinned. It was not easy to do with the new resource summary table design, but it is being worked on.

**Comment by kberg** [comment]
I think the sidebar as a global parameter option is useful. A topbar? I like the way Scythe manages player stats, could be a good model.

**Comment by chosta** [comment]
While adding every possible parameter to the screen seems to be a good idea, it will also meet intense resistance from the UI/UX devs :) a.k.a. too many things on screen = clutter. Also repeating elements = bad UX.
I think the sidebar info is useful for small resolutions (mobile + tablets + laptops) but filling it up can become a problem at some point. 
I like the idea of top bar. For me the best would be to have a sticky top bar with global params, res count, ruling party, etc. and the side bar to be used only for navigation purposes and settings.

**Comment by alrusdi** [comment]
Let me try to implement top bar. I am missing it too

**Comment by vsrisuknimit** [comment]
I think this can be closed with your top bar. @alrusdi

**Comment by alrusdi** [comment]
Sure!
