### ISSUE TITLE
Show parties when sending delegates 

### ISSUE THREAD

**Issue by duckmammal** [bafolts/terraforming-mars#1689]
The way colony implementation has been updated is amazing. We should do the same for parties when sending delegates.

Instead of words and descriptions, just copy the entire party section whenever a player is sending / removing delegates. This would speed things along and not make the player look in two different locations when they're trying to make their decisions.

**Comment by ssimeonoff** [comment]
![Untitled](https://user-images.githubusercontent.com/6917565/96595662-35da1a80-12ec-11eb-96bd-75b356ccfd53.png)
- The size is 0.8 of the original
- the whole party cell is clickable
- clicking a party, selects it
- selected party has similar UI as selected card (orange highlight with a checkmark)

**Comment by chosta** [comment]
Digging it.

**Comment by nwai90** [comment]
This is great! When the action menu layout becomes horizontal eventually there will be a lot of vertical real estate freed up. Outline around the selected party (similar to cards) would be nice too but it is too much effort to achieve imo as the entire Turmoil board is one image file.

**Comment by PedroRCSequeira** [comment]
Really cool!
And being able to do it directly on the static delegate zone would be the icing on the cake :D

**Comment by kevinb9n** [comment]
> And being able to do it directly on the static delegate zone would be the icing on the cake :D

Like map tiles. I agree. Current change is definitely an improvement, but perhaps we can keep an issue open about doing it that way.  Fodder from leggup:
"I only care about where I place my delegates based on the global events ... so you have to go up to the top anyway."
