### ISSUE TITLE
MANUTECH implementation - getters / setters for production variables

### ISSUE THREAD

**Issue by vincentneko** [bafolts/terraforming-mars#169]
MANUTECH corp from Venus Next extention may require a big overall change for the game and will impact a lot of files.

Card effect is:
For each step you increase the production of a resource, including this, you also gain that resource.

Right now production counters are public and therefore directly manipulated.

I suggest we make them private and access them with getters / setters methods. This should trivialise MANUTECH implementation, and Venus Next will not change too many files.

Can you give me your opinion on this ?

**Comment by bafolts** [comment]
Creating accessor methods makes sense. Adding an optional `onProductionIncrease(player: Player, game: Game, resource: Resource)` and then calling it whenever the resource is increased would work. There isn't a `Resource` enum but it would cover `MEGACREDIT`, `PLANT`, `TITANIUM`, `SPACE`, `STEEL`, and `HEAT`. Similar to what happens in other functions the function will be called if it is defined.

**Comment by vincentneko** [comment]
Merged
