### ISSUE TITLE
Can Turmoil panel depict directionality of dominance shifts in some way

### ISSUE THREAD

**Issue by kevinb9n** [bafolts/terraforming-mars#1694]
Can *something* in the UI portray which direction dominance shifts in? By now I can remember it's to the left, but I'm sure it's a real stumbling block for new players.

**Comment by nwai90** [comment]
Perhaps triangle arrows like this or something similar (but it doesn't account for the wrap-around at the end)

![turmoil_ui](https://user-images.githubusercontent.com/2408094/97315629-dcea2380-18a3-11eb-8c14-ba47d8292170.png)

**Comment by kevinb9n** [comment]
That'd get it done

**Comment by vsrisuknimit** [comment]
Closed by #2588
