### ISSUE TITLE
Help text for ruling policy and ruling bonus, like it does for milestones and awards?

### ISSUE THREAD

**Issue by kevinb9n** [bafolts/terraforming-mars#1696]
Being able to pop up textual explanations of each milestone and award is awesome. Can it do the very same thing for ruling policies and ruling bonuses?

For bonuses you have text already from the radio buttons. If you want suggested concise verbiage for the policies here's a draft

Mars First – Effect: When you place any tile on mars, gain 1 Steel
Scientists – Action: Once per generation, pay 10 MC to draw 3 cards
Unity – Effect: Titanium is worth +1 MC
Greens – Effect: When you place a Greenery tile, gain 4 MC
Reds – Effect: All actions require losing 3 MC per TR increase
Kelvinists – Action: Pay 10 MC to raise Energy and Heat production one step each

**Comment by kevinb9n** [comment]
@nwai90 This seems even much more useful now with Political Agendas, no?

**Comment by nwai90** [comment]
@kevinb9n Yes, agree
