### ISSUE TITLE
Ban all the things

### ISSUE THREAD

**Issue by kevinb9n** [bafolts/terraforming-mars#1697]
Saw this in discord:

"hmmm i assume there is no way to undo a turn easily, he bought 2 milestones that we banned"

And I was thinking. All the objects in this game - corps, cards, colonies, milestones, awards, etc. – all seem to live in a single namespace. (If exceptions exist they're rare.) So if users care about banning things, could there just be one big ugly text box where you can paste in a comma-separated list of any old strings you feel like.

I don't have a dog in this race, it's just that situations like that are kinda sad.

Hell, someone wants to ban a damn standard project, who am I to care.....

**Comment by nwai90** [comment]
Agree with @kevinb9n - I don't think allowing ban of core aspects of the game is a good idea. If someone wants to develop that it would probably be fine as an option though.

**Comment by kberg** [comment]
Or just let people fork their own branch.

**Comment by kevinb9n** [comment]
My real point is just that it's happening in a piecemeal manner anyway, so maybe just treat it all in one simple way.

**Comment by kevinb9n** [comment]
also: the word "just" really cannot be put before "fork their own branch" in this way. :-)

**Comment by vsrisuknimit** [comment]
Such option is so far out of the default settings that those users should 'just fork their own branch'. There is really no need to include that in the main branch.

**Comment by kberg** [comment]
> also: the word "just" really cannot be put before "fork their own branch" in this way. :-)

You're right, I know.

**Comment by kevinb9n** [comment]
I respect that view @vsrisuknimit, but then why are colonies even bannable?

**Comment by vsrisuknimit** [comment]
@kevinb9n many folks do like to ban pluto in multiplayer games. Many solo players banned Miranda,Enceladus,Titan in solo games.

**Comment by kevinb9n** [comment]
I don't really care much about banning things. I'll close this but if we start considering more piecemeal requests to ban this or that in the future then maybe come back and consider offering one simple general approach then.
