### ISSUE TITLE
first player hardcoded in game settings json export when random first player is enabled

### ISSUE THREAD

**Issue by supahotjovs** [bafolts/terraforming-mars#1705]
When "Random First Player" game setting is enabled, exporting game settings json via #1634 will set the "first" parameter to "true" for one of the players:

    "players": [
        {
            "index": 3,
            "name": "p3",
            "color": "yellow",
            "beginner": false,
            "handicap": 0,
            "first": false
        },
        {
            "index": 1,
            "name": "p1",
            "color": "red",
            "beginner": false,
            "handicap": 0,
            "first": false
        },
        {
            "index": 2,
            "name": "p2",
            "color": "green",
            "beginner": false,
            "handicap": 0,
            "first": true
        }
    ],

When creating a new game with this JSON, that player will always go first. 

Currently this can be easily worked around by manually editing the json and setting "first" parameter to "false" for all players. Would be nice to get an official fix though.

**Comment by cdekker** [comment]
I think there are some more issues with the JSON. I just created a game from a saved JSON: random board, fixed milestones/awards, and it still gave me random milestones/awards.

```
{
    "players": [
        {
            "index": 1,
            "name": "p1",
            "color": "red",
            "beginner": false,
            "handicap": 0,
            "first": false
        },
        {
            "index": 2,
            "name": "p2",
            "color": "green",
            "beginner": false,
            "handicap": 0,
            "first": false
        }
    ],
    "corporateEra": true,
    "prelude": true,
    "draftVariant": true,
    "showOtherPlayersVP": false,
    "venusNext": true,
    "colonies": true,
    "turmoil": true,
    "customCorporationsList": [],
    "customColoniesList": [],
    "cardsBlackList": [],
    "board": "random",
    "seed": 0.6254902152962543,
    "solarPhaseOption": false,
    "promoCardsOption": true,
    "communityCardsOption": false,
    "undoOption": false,
    "fastModeOption": false,
    "removeNegativeGlobalEventsOption": false,
    "includeVenusMA": true,
    "startingCorporations": 2,
    "soloTR": false,
    "initialDraft": false,
    "randomMA": false,
    "shuffleMapOption": false
}
```
