### ISSUE TITLE
Standardize on eslint?

### ISSUE THREAD

**Issue by kberg** [bafolts/terraforming-mars#1718]
A standard formatter? If it was good, yes. If enough of the senior people in this group could agree, then yes. chosta and I find ourselves disagreeing at times, and that in and of itself isn't a reason to define a formatter, let's chat?

**Comment by alrusdi** [comment]
Yes! Let's make an agreement/validation about formatting rules for all file types (ts, html/templates, css)

**Comment by chosta** [comment]
Well `eslint` is pretty much set imo. @bafolts introduced the `prefer-const` and I feel like its already doing a good job in improving the code. Here are the current `es-lint` settings, I wouldn't change anything atm but feel free to suggest adding / removing anything useful:
```
module.exports = {
  'env': {
    'browser': true,
    'es6': true,
  },
  'extends': [
    'plugin:vue/essential'
  ],
  'parserOptions': {
    'ecmaVersion': 2018,
    'parser': '@typescript-eslint/parser',
    'sourceType': 'module',
  },
  'plugins': [
    'vue',
    '@typescript-eslint',
  ],
  'rules': {
    'eqeqeq': ['error', 'always'],
    'quotes': ['error', 'double'],
    'no-var': 'error',
    'prefer-const': 'error'
  },
};
```

For formatting, I do like the default esprettier settings but they can be tweaked the way we like it. @kberg mostly disagrees with 80 columns `printWidth` and breaking + separated strings to new lines. Here are the default esprettier settings, we can tweak them too and add overrides in `.prettierrc.yml`

   ```
// Include parentheses around a sole arrow function parameter
  "prettier.arrowParens": "always",

  // Controls the printing of spaces inside object literals
  "prettier.bracketSpacing": true,

  // Path to the prettier configuration file
  "prettier.configPath": "",

  // A list of languages IDs to disable this extension on
  "prettier.disableLanguages": [],

  // A list of [glob patterns](https://code.visualstudio.com/api/references/vscode-api#GlobPattern) to register Prettier formatter
  "prettier.documentSelectors": [],

  // Control whether Prettier formats quoted code embedded in the file.
  "prettier.embeddedLanguageFormatting": "auto",

  // Controls whether prettier is enabled or not.
  "prettier.enable": true,

  // Specify the end of line used by prettier
  "prettier.endOfLine": "lf",

  // Specify the global whitespace sensitivity for HTML files.
  //  Valid options:
  // - `css` - Respect the default value of CSS display property.
  // - `strict` - Whitespaces are considered sensitive.
  // - `ignores` - Whitespaces are considered insensitive.
  "prettier.htmlWhitespaceSensitivity": "css",

  // Path to a .prettierignore file
  "prettier.ignorePath": ".prettierignore",

  // Prettier can insert a special @format marker at the top of files specifying that the file has been formatted with prettier. This works well when used in tandem with the `--require-pragma` option. If there is already a docblock at the top of the file then this option will add a newline to it with the @format marker.
  "prettier.insertPragma": false,

  // If true, puts the `>` of a multi-line jsx element at the end of the last line instead of being alone on the next line
  "prettier.jsxBracketSameLine": false,

  // Use single quotes instead of double quotes in JSX
  "prettier.jsxSingleQuote": false,

  // The package manager you use to install node modules.
  "prettier.packageManager": "npm",

  // Path to the prettier module
  "prettier.prettierPath": "",

  // Fit code within this line limit
  "prettier.printWidth": 80,

  // (Markdown) wrap prose over multiple lines
  "prettier.proseWrap": "preserve",

  // Change when properties in objects are quoted
  "prettier.quoteProps": "as-needed",

  // Require a prettier configuration file to format. See [documentation for valid configuration files](https://prettier.io/docs/en/configuration.html).
  // 
  // > _Note, untitled files will still be formatted using the VS Code prettier settings even when this setting is set._
  "prettier.requireConfig": false,

  // Prettier can restrict itself to only format files that contain a special comment, called a pragma, at the top of the file. This is very useful when gradually transitioning large, unformatted codebases to prettier.
  "prettier.requirePragma": false,

  // When enabled, this extension will attempt to use global npm or yarn modules if local modules cannot be resolved.
  // > _This setting can have a negative performance impact, particularly on Windows when you have attached network drives. Only enable this if you must use global modules._
  "prettier.resolveGlobalModules": false,

  // Whether to add a semicolon at the end of every line
  "prettier.semi": true,

  // If true, will use single instead of double quotes
  "prettier.singleQuote": false,

  // Number of spaces it should use per tab
  "prettier.tabWidth": 2,

  // Controls the printing of trailing commas wherever possible. Valid options:
  // - `none` - No trailing commas
  // - `es5` - Trailing commas where valid in ES5 (objects, arrays, etc)
  // - `all` - Trailing commas wherever possible (function arguments)
  "prettier.trailingComma": "es5",

  // Whether or not to take `.editorconfig` into account when parsing configuration. See the [prettier.resolveConfig](https://prettier.io/docs/en/api.html) docs for details.
  "prettier.useEditorConfig": true,

  // Indent lines with tabs
  "prettier.useTabs": false,

  // Whether or not to indent the code inside `<script>` and `<style>` tags in Vue files. Some people (like the creator of Vue) don’t indent to save an indentation level, but this might break code folding in your editor.
  "prettier.vueIndentScriptAndStyle": false,

  // If true, this extension will process files in node_modules
  "prettier.withNodeModules": false,

  // Enables / disables the solidity formatter (prettier solidity default)
  "solidity.formatter": "prettier"

```

**Comment by kberg** [comment]
Ugh, I meant formatting.

**Comment by bafolts** [comment]
The rules in place today I don't think are enforcing _style_. Most the ones today are meant to catch bugs. For the _style_ based rules it may make sense to go with some pre-defined rules. Taking one off the shelf avoids any personal feelings except that we picked some pre-defined styling rules.

Examples of off the shelf rules:

https://github.com/google/eslint-config-google
https://www.npmjs.com/package/eslint-config-airbnb
https://github.com/standard/eslint-config-standard

There are probably more.

In terms of rules which may help to catch bugs I would like to enable:

https://palantir.github.io/tslint/rules/strict-boolean-expressions/

For some reason javascript developers often coalesce to check variables.

```
var someVar = false;
if (!someVar) {

}
```

In this situation javascript will first have to run the `!` operator on `someVar` and then javascript will check if `someVar` is _any_ truthy value. It is both more efficient and most likely easier to read to use `if (someVar === true)`. This rule also checks places where your conditional would always be true. This is helpful when changing a property from optional to always being defined. This rule will find the places where we were checking for something being `undefined` which can no longer ever be `undefined`.

**Comment by Lynesth** [comment]
@bafolts Does that strict boolean thing means no more `if (var)` if `var` isn't a boolean ?

**Comment by bafolts** [comment]
Yes. That is a good thing. `if (var)` may be less code to type but it means that `var` could be any value besides `null`, `undefined`, `false`, `""`, or any other falsey value.

**Comment by alrusdi** [comment]
Let's use gts as a starting point? https://github.com/google/gts

**Comment by chosta** [comment]
Yes to gts

**Comment by bafolts** [comment]
gts works for me.

**Comment by bafolts** [comment]
I will put together PR that uses gts

**Comment by chosta** [comment]
Can we please allow for space after function() as `prettier` does not provide an option for it and it makes auto-formatting kind of useless for me. https://joshuatz.com/posts/2020/prettier-function-parenthesis-spacing-opinionated-is-key/
 
`Unexpected space before function parentheses.eslintspace-before-function-paren`

Otherwise it works pretty well but the printwidth for esprettier should be increased to a very big number.

**Comment by kberg** [comment]
There's a GTS formatter -- that ought to solve this problem, right?

>

**Comment by chosta** [comment]
They say `prettier` is used for formatting and I got the recommended settings from their `.prettierc` file.
`Under the covers, we use eslint to enforce the style guide and provide automated fixes, and prettier to re-format code. To use the shared eslint configuration, create an .eslintrc in your project directory, and extend the shared config:`

The problem is as I mentioned earlier. Prettier just does not allow for a non blank space `function ()` unless some hacking is done.

**Comment by bafolts** [comment]
I didn't realize that GTS had it's own prettier that must have been conflicting with our file as I was trying to officially put it in the first time. I can try it again now that I know the `.prettierc` file exists. I would like to just go with whatever rules they have in place to leave any of our opinions out of it. The only overrides I have in the eslintrc file were to ease the transition.
