### ISSUE TITLE
Nuclear Power unplayable with -4 MC production

### ISSUE THREAD

**Issue by duckmammal** [bafolts/terraforming-mars#1720]
I don't know why lowering MC production further wouldn't be allowed, so I'm guessing this is somehow an oversight. I dunno if -4 MC production is the threshold or there's something else coded to make it now work properly. I'd also suggest looking at Cloud Seeding to see if the same issue exists there.

**Comment by vsrisuknimit** [comment]
@duckmammal it is the rule that the lowest your mc production can go is -5.

**Comment by alrusdi** [comment]
No bug here

**Comment by duckmammal** [comment]
oh, good to know

**Comment by kevinb9n** [comment]
Sadly I can't think of a way that this minimum could be made apparent in the UI; how the player boards do it just won't translate.

At some point I'd like to think about a section of "rules reminders for new players" at the bottom of the help page.
