### ISSUE TITLE
UI on Insulation is wonky

### ISSUE THREAD

**Issue by andystager** [bafolts/terraforming-mars#1724]
I played Insulation, pressed "MAX" and observed that the only buttons available were "MAX" and "Decrease." Upon pressing decrease, the action carried through as if I had pressed a confirm button.

**Comment by SliceOfBread** [comment]
That's the way it works. Decrease your heat production...and increase your MC production the same number of steps.
If you don't want MAX then either type in how many you want or, on Chrome at least, the number box has little up/down arrows to adjust it. Click 'DECREASE' to execute. (But I agree, CONFIRM or EXECUTE or something similar would be clearer.)

**Comment by andystager** [comment]
D'oh. Thanks for clarifying.
