### ISSUE TITLE
Self-Replicating Robots resources not resetting for new card

### ISSUE THREAD

**Issue by andystager** [bafolts/terraforming-mars#1725]
I played a couple of cards after adding resources from self-replicating robots. It appears that new cards have the resources from the previously played card applied to them

Example, in my most recent turn I selected a new card to add resources to, but instead of adding 2, the log showed it increasing from 4 to 8.
![image](https://user-images.githubusercontent.com/72101041/96918386-37384e00-1478-11eb-9e09-dca85bcab57f.png)

**Comment by Lynesth** [comment]
If anyone else can check this, I wasn't able to reproduce the issue after many tries.

@andystager was Space Port the only card on it at that time ?
Was it added after you played the previous one from SRR ? Before ?

**Comment by andystager** [comment]
It was my 3rd card played with SRR. It was the only card at the time, and I never had more than a single card with SRR resources on it.

I will try and pay closer attention to it the next time it comes up in my game to make sure I'm remembering the sequencing correctly. Thanks for looking into it.

**Comment by andystager** [comment]
I wasn't able to replicate either. Will close for now.
