### ISSUE TITLE
Game going back in time?

### ISSUE THREAD

**Issue by Durandil** [bafolts/terraforming-mars#1726]
Hi,

I was playing when suddenly, the website is a bit slow to take into account my action (was playing Venus Mining Rights if I recall correctly), so I tried to refresh and the game goes back to Gen 1 (we were in Gen 3). 

Here is my player id https://terraforming-mars.herokuapp.com/player?id=9e7f81a2157a

PS : I swear I'm not drunk, my opponent refreshed on her side and it was the same for her, back to Gen 1

Thanks for your help

**Comment by SliceOfBread** [comment]
I saw something similar in solo today but had to run out and didn't get to document it. I was in Gen 11 or 12, got some kind of timeout error and when I refreshed I was in gen3.

**Comment by bafolts** [comment]
If this was on `terraforming-mars.herokuapp.com` the restore logic in place on a server restart would exhibit this behavior. The server is being used for long running games and was originally intended as a demonstration site. If possible you should host game locally if possible.

**Comment by bafolts** [comment]
I am curious for those using `terraforming-mars.herokuapp.com` for single player games. Do you play through one game in a session or come back to it later? All of this code is javascript so I am assuming getting it to run all client side without need for a server would be feasible. For single player games that would be fine and then server changes wouldn't impact the single player games.

**Comment by SliceOfBread** [comment]
@bafolts - I will switch back to my local version. I just need to remember to start it. :)

As for the second question (client-side solo), I play straight through. Usually only takes 20-30 minutes. I was, when I first found this project, working on a solo-only, 100% client version. If I ever wrap up my current project, I might look at this next.

**Comment by bafolts** [comment]
The server side javascript will run on the client. Could be worth using for all single player games. All one would need to write is a different mechanism for passing data between what is the server side code today and client side code.

**Comment by peonmodel** [comment]
> All of this code is javascript so I am assuming getting it to run all client side without need for a server would be feasible.

yes, if possible, prefer client-side only for solo games

heck, let me access the game code from the browser console and cheat, sometimes i just want to try out new combo and i want to manipulate the deck

**Comment by Durandil** [comment]
Oh I see, thanks for your answer!
