### ISSUE TITLE
Improve the End game screen

### ISSUE THREAD

**Issue by ssimeonoff** [bafolts/terraforming-mars#1732]
![Untitled](https://user-images.githubusercontent.com/6917565/97032282-db49f400-1561-11eb-99df-f2de0fb036a9.png)

- table row has the player colour from the game
- table with is auto with total column a bit bigger
- Player points are in multiple columns
  - colums are 400px wide, so the text "Victory points details for" and the player name are on 2 rows 
  - vertically align to top
  - width is auto with column total with bigger/fixed width
- backlog is removed (I find it obsolete for the purpose of the screenshots)

**Comment by ssimeonoff** [comment]
@vsrisuknimit

**Comment by kberg** [comment]
How strongly do you feel about the backlog? I found it pretty useful.

**Comment by ssimeonoff** [comment]
if not remove, then inline-block it right to the map, so it doesn't add extra height.
