### ISSUE TITLE
Add 'Game Will End After This Generation' Warning

### ISSUE THREAD

**Issue by StefanWinters** [bafolts/terraforming-mars#1736]
As the title suggests, add a warning when all global requirements are fulfilled so that the game will end after that generation. That warning could either be a message in the game log or a pop-up like when not choosing a card when doing a card action.

**Comment by nwai90** [comment]
@StefanWinters This warning already exists. Did you "Enable in-game alerts" under Preferences (settings icon)? There is a popup which says "Mars is terraformed"

**Comment by StefanWinters** [comment]
If it exists, it seems like it doesn't work, see picture.
all requirements fulfilled with the last asteroid, and in-game alerts on. no message

![image](https://user-images.githubusercontent.com/73371968/97095483-d49da880-1657-11eb-930f-51d36e86659f.png)
