### ISSUE TITLE
Notify people if they have to discard for Pluto although it's not their turn

### ISSUE THREAD

**Issue by funkybaboon** [bafolts/terraforming-mars#1740]
Yesterday and on several games more I have witnessed that people do miss that they have to discard a card because someone flew to pluto and they have a colony there. They're probably doing something else, f.ex. in my game yesterday someone played another game at the same time 🙃.

Suggestion: If it's currently not your turn, but you have to discard, play the "It's your turn" sound and in the favicon show that their attention is required.

**Comment by nwai90** [comment]
@funkybaboon Duplicate of https://github.com/bafolts/terraforming-mars/issues/1647 ?

**Comment by funkybaboon** [comment]
Indeed 👍
