### ISSUE TITLE
Random map is not random

### ISSUE THREAD

**Issue by vsrisuknimit** [bafolts/terraforming-mars#1744]
Random map select Tharsis unless you click Elysium and Hellas just before switching to random map.

**Comment by Lynesth** [comment]
Are you sure about that ? I cannot reproduce this issue.
I tested it multiple times and got different boards.

Also I check that selecting `Random` properly sends `board: "random"` to the server (where the random choice is then made). This worked properly as well.

**Comment by nwai90** [comment]
Tested. It seems to be working fine

**Comment by vsrisuknimit** [comment]
It seems to be working. I must be very unlucky when I rushed to test it this morning.
