### ISSUE TITLE
Ishtar Mining available at 4% Venus.

### ISSUE THREAD

**Issue by kberg** [bafolts/terraforming-mars#1761]
![image](https://user-images.githubusercontent.com/413481/97126398-13da0100-170d-11eb-984e-e56de8fd36c5.png)

**Comment by nwai90** [comment]
@kberg This is happening because MSI corporation is selected. It gives +/- 2 steps on cards with Venus requirements

**Comment by kberg** [comment]
Thanks. I'd never played Venus before.
