### ISSUE TITLE
Solo game setup can loop infinitely while setting up the board.

### ISSUE THREAD

**Issue by bafolts** [bafolts/terraforming-mars#177]
Unit tests are intermittently failing while running the build. There is an issue with setting up a solo board that leads to looping indefinitely.

https://github.com/bafolts/terraforming-mars/blob/master/src/OriginalBoard.ts#L168

During some random setup we get left looping indefinitely with either no adjacent spaces found or an issue with calculating adjacent spaces.

If you add the following unit test to `Game.spec.ts` you can recreate the issue frequently.

```
it.only("Can start solo games", function () {
  for (var i = 0; i < 1000; i++) {
      const player = new Player("test", Color.BLUE, false);
      new Game("foobar", [player], player);
  }
});
```

Throwing an error when there are no spaces makes this easier to debug than having to kill the process once it is looping infinitely.

```
diff --git a/src/OriginalBoard.ts b/src/OriginalBoard.ts
index b176d65..97e509b 100644
--- a/src/OriginalBoard.ts
+++ b/src/OriginalBoard.ts
@@ -166,6 +166,9 @@ export class OriginalBoard {
     public getForestSpace(spaces: Array<ISpace>): ISpace {
         spaces = this.shuffle(spaces);
         while (true) {
+        if (spaces.length === 0) {
+            throw "NO SPACES";
+        }
```

When running this test it will fail very often with `NO SPACES` thrown. If this happens when someone is starting a game on the game server no one else will be able to play as the node process will be stuck.

**Comment by vincentneko** [comment]
My bad, getRandomCitySpace function did not check if space returned was a colony space, which obviously cannot have adjacent spaces.
