### ISSUE TITLE
Prevent single click "no cards buy" action

### ISSUE THREAD

**Issue by ssimeonoff** [bafolts/terraforming-mars#1770]
![Untitled](https://user-images.githubusercontent.com/6917565/97154836-b6799a80-1774-11eb-9da0-6aca0192b819.png)

Very basic confirmation to prevent misclicking and buying 0 cards. 
Even with the extra padding around the button, there is s high chance of misclick on mobile when aiming for the first card.

- if no cards are selected and "buy" is clicked, show a 2nd button (button "buy" become disabled)
- if the 2nd button is displayed, selecting a card removes it

**Comment by funkybaboon** [comment]
Yes Yes Yes please 👍 Lost a game yesterday because of this, even though I wasn't playing on a mobile phone.

**Comment by chosta** [comment]
I was thinking about the same problem today. I had a different UX in mind.
How about just a skip buy button (which is not a button but grey underlined text) next to the buy WITH confirmation for skip buy.

[Buy]    _skip buy_

With this approach we don't have to add a second button on confirm.
Both approaches require two clicks. Benefit of your approach is that you don't see the skip button text, the drawback is that if a person doesn't know how to skip buy, she will be wondering how to do it as it says `Buy` which means you buy :)
The advantage of my approach is that both actions are available for the user to choose from, drawback is it adds a bit more clutter on the page.

**Comment by Lynesth** [comment]
We could use the in-game alert for that so that, much like confirming overspending.

**Comment by chosta** [comment]
@Lynesth that is great but we still have to be able to guide the user w/o making them think about what could go wrong.
Optimal solution to this is:
- State A - no selected card => A disabled button with label "Buy" (this will hint the player that an action needs to be taken)
- State B - one or more selected cards => Button becomes enabled and text is "Buy 1* cards"
! additional "skip buy" as I explained above next to the Buy button ( I still think it will be less confusing to the user if represented with all the actions) - this "skip buy" can be added to other elements instead of "Do nothing" radio button for example

**Comment by Lynesth** [comment]
Why not the same button, "Don't buy cards" / "Buy X card(s)" ?

**Comment by chosta** [comment]
Or that :)
The only difference is that not buying cards would only be possible if all of them are deselected and "skip buy" lets you do it anytime.
I like your solution and I've always imagined dynamic labels for the buttons as their meaning does change on many occasions based on previous actions. Feel free to open another issue on how to approach this on a higher level and we can discuss who and how to do it.

**Comment by SliceOfBread** [comment]
I vote for -> Buy 'n' Card(s)

**Comment by vsrisuknimit** [comment]
+1 for dynamic label. Especially if it change color to red for action that player should double check like "discarding" or "buying no card".

**Comment by kevinb9n** [comment]
I like the "n cards" text on the button. Several times I have sold 2 patents when I only meant to sell 1 (because in some contexts selecting a card automatically deselects the previously selected card, but in that one it (duh) doesn't).

**Comment by bafolts** [comment]
I will implement this.
