### ISSUE TITLE
New build is broken

### ISSUE THREAD

**Issue by andystager** [bafolts/terraforming-mars#1798]
I've tried three solo games in a row, all with the same effect - MC is not displaying properly and I can't play project cards. See discrepancy in 'How to pay?' window:
![image](https://user-images.githubusercontent.com/72101041/97585706-d48f0700-19cf-11eb-95d1-f2e821cc4aca.png)

**Comment by nwai90** [comment]
<img width="580" alt="Screenshot 2020-10-29 at 9 53 05 PM" src="https://user-images.githubusercontent.com/2408094/97586492-4c434d00-1a35-11eb-8b16-058f91cb4f6c.png">

(Vue-related error)

**Comment by bafolts** [comment]
I added type checking and threw this error. Something must not being passed in as expected type.

**Comment by bafolts** [comment]
All of these front end components are a mine field jenga tower type situation to update. Looks like the type checker didn't catch this update. Putting together fix for this and then update to the type checker in separate PR.

**Comment by andystager** [comment]
Thank you for the quick response!

**Comment by chosta** [comment]
We can have these changes tested on a separate server before merging to master. You can @ me next time to try them out manually, I'm also still understanding how it works.

**Comment by bafolts** [comment]
I manually ran through and made sure I could still pay for one card. I didn't realize this logic ran when you switched between cards.

**Comment by nwai90** [comment]
Working locally; merged

**Comment by bafolts** [comment]
I saw `v-model` show up and I put in a type of `any` to work around the issue. The internal functions that `v-model` uses needs to be checking types for us. That would have caught this situation. I wont progress until `v-model` is type checking.
