### ISSUE TITLE
Drafting option

### ISSUE THREAD

**Issue by vincentneko** [bafolts/terraforming-mars#18]
Drafting option is currently missing and would be a great addition to the game.
Below is a extract from rule book:

Draft variant:
If more interaction is desired, the Draft variant
may be used. During the Research phase the players draft 4
cards to buy from instead of just drawing 4 to buy from:
Each player first gets 4 cards and chooses one to
draft, putting it aside and passing the rest to the next player.
Then you have 3 cards; set aside 1 of them and pass the rest
to the left. Then set aside 1 of the 2 you receive, pass the last
card, and finally receive your last card.
Then examine the 4 cards you’ve set aside (drafted)
and choose which to buy (3 M€ each) and which to discard.
Drafting is not used during the first generation
since the first Research phase is skipped (see setup). Cards
are passed clockwise during even-numbered generations
and counter-clockwise during odd-numbered generations.
This variant allows players to affect which cards
other players get access to, and increases your ability to
pursue a certain strategy, or predict which parameter will
rise first.
The Draft Variant adds some extra game time and
is not recommended for players new to Terraforming Mars.

**Comment by alrusdi** [comment]
I need this option too. There few notes about implementation.
1) After each round draft direction must change
2) Each drafting turn you should be able to see which opponent will receive your cards

**Comment by vincentneko** [comment]
First try to implement drafting (not as an option yet), please test it on branch draft-option and let me know if it's ok for you.

**Comment by vincentneko** [comment]
Done and merged
