### ISSUE TITLE
Feature request: offer Titan Floating-Launchpad as a trading option.

### ISSUE THREAD

**Issue by vsrisuknimit** [bafolts/terraforming-mars#1807]
During colony trading (not blue card activation), if the player has Titan Floating-Launchpad that has floater and is not yet activated, the app should offer that as an option for trading. Rank that as a top option.

- Trade with Titan Floating-Launchpad as the top option if available

![image](https://user-images.githubusercontent.com/14239220/97758035-6b44ec00-1ad4-11eb-98a7-5dc479b43f48.png)

**Comment by kevinb9n** [comment]
Would have a saved me a :headdesk: or two.

Perhaps wording such as

"Play 1 Floater (use Titan Floating-Launchpad action)"

?
