### ISSUE TITLE
Feature Request: more player color options

### ISSUE THREAD

**Issue by BoratBorat** [bafolts/terraforming-mars#1810]
I'd like to see more options for player colors. Orange especially, maybe pink, white, light blue, and light green would all work.

**Comment by chosta** [comment]
Hi Chad,
This has been discussed many times. It is certainly a possibility BUT it is not a trivial task as it might seem. A couple of issues include issues with contrast (like black that is actually grey, you know what I mean), hardcoded cube tiles (we need new ones). @ssimeonoff proposed new cubes with contrasting border so we can give it a try. There is a technical concern that needs to be handled too. The enum holding the player colors is hardcoded and adding new colors would need some additional work in the game creation form and also in the backend (I think).
```
export enum Color {
    BLUE = "blue",
    RED = "red",
    YELLOW = "yellow",
    GREEN = "green",
    BLACK = "black",
    PURPLE = "purple",
    NEUTRAL = "neutral",
    BRONZE = "bronze",
}

```

**Comment by BoratBorat** [comment]
I don't know anything about programming, but memories90 has his own server and he was able to add orange.

https://tfm-legacy.herokuapp.com/

**Comment by chosta** [comment]
Adding is not a problem. Consistency is. But ok, we can find someone to do it. I am also a fan of this improvement.

**Comment by kberg** [comment]
(BTW, that bronze is actually a 1MC bronze cube.)

Agreed. There will be some rough edges ("neutral" isn't a color.) And so on.

**Comment by vsrisuknimit** [comment]
@kberg @chosta @nwai90 Can I give this a try?

What I really want to do though is an option under preferences that you can select the color that you want to see yourself as.

Let's say we have the following.
PlayerA: red
PlayerB: blue
PlayerC: green

PlayerA and B both want to play red. Player B can go to the preferences panel, check a box to see themself as red. Their color will be come red (only from Player B's computer) and PlayerA will become a neutral color (not-pickable during game creation) for Player B's perspective. Player B still see PlayerC as green and everyone else's as their server-side colors.

Player A and Player C will still see everyone's colors as normal.

Is that possible to do? Worth doing?

**Comment by kberg** [comment]
It would be a fair amount of work, since colors are tightly coupled to
players and noted so in the game, but not impossible. yucata.de does this.
You can choose your own color, and the other players' colors are chosen for
them. And I'll tell you, my experience with that site makes that weird and
confusing. "Darn, blue took my spot." "What do you mean? You're blue."
Laughter ensues, and by that I mean sighing.

So, I wouldn't suggest it.


>

**Comment by nwai90** [comment]
Agree with @kberg on this. The feature is possible but it introduces additional complexity that will need to be maintained subsequently

**Comment by vsrisuknimit** [comment]
> It would be a fair amount of work, since colors are tightly coupled to players and noted so in the game, but not impossible. yucata.de does this. You can choose your own color, and the other players' colors are chosen for them. And I'll tell you, my experience with that site makes that weird and confusing. "Darn, blue took my spot." "What do you mean? You're blue." Laughter ensues, and by that I mean sighing. So, I wouldn't suggest it.
> […](#)

In my proposal, that would not happen. You would say neutral color takes my spot. But neutral color (say pink) is not a selectable color, so you know pink stands for your own color.

**Comment by kevinb9n** [comment]
> In my proposal, that would not happen. You would say neutral color takes my spot. But neutral color (say pink) is not a selectable color, so you know pink stands for your own color.

Interesting, but what about the case when three players all like the same color?

I think it is best if the game appears the same way to everyone.

**Comment by vsrisuknimit** [comment]
@kevinb9n not a problem.

Red: see himself as red, see green as green, see blue as blue, see black as black
Green: see himself as red, **see red as pink**, see blue as blue, see black as black
Blue: see himself as red, see green as green, **see red as pink**, see black as black
Black: see himself as red, see green as green, see blue as blue, **see red as pink**

**Comment by ssimeonoff** [comment]
Wouldn't that cause more confusion? If there are really 2 stubborn players fighting for a colour, you can simply toss a coin and deal with it. #commonsense

**Comment by Lynesth** [comment]
I don't think it's worth it. If they can't come to an agreement regarding colours... nevermind.
Let's remove colour choice and randomize them when the game start. Everybody will be at the mercy of luck then.

On a more serious note though, adding a few new colours shouldn't be hard. Let's pick a few that are easily distinguishable from the others, like the ones Borat proposed.
