### ISSUE TITLE
Get vue-test-utils working

### ISSUE THREAD

**Issue by kberg** [bafolts/terraforming-mars#1811]
I tried to create a DOM-type test but strugguled, so I guess this is just asking for help.

I did all the right `npm install` stuff though it's not my area of expertise. But when introducing this line

`import { shallowMount } from "@vue/test-utils"`

I got this error:

```
///terraforming-mars/node_modules/mocha/node_modules/yargs/yargs.js:1172
      else throw err
           ^

TypeError: Cannot read property 'split' of undefined
    at Object.<anonymous> (.../terraforming-mars/node_modules/@vue/test-utils/dist/vue-test-utils.js:1683:37)
```

**Comment by bafolts** [comment]
I had no idea this tool exists. I would assume the utils I had put in place are conflicting with this.

https://github.com/bafolts/terraforming-mars/blob/master/tests/utils/Vue.ts#L3

Here I am mocking the `vue` require. That tool may be doing the same thing. I wouldn't be surprised if you removed that line if you got past this error.

**Comment by kberg** [comment]
/shrug

>

**Comment by bafolts** [comment]
I was messing around with this today. I will keep wrestling with it. I think it is something to do with out tsconfig used with the unit test files.

**Comment by bafolts** [comment]
Getting closer to having this run. Now getting a separate error. Seems very difficult to get this setup considering the time I have put in thus far. Now getting.

```
     TypeError: Cannot read property 'child' of undefined
      at createWrapper (node_modules/@vue/test-utils/dist/vue-test-utils.js:11332:32)
      at Object.mount (node_modules/@vue/test-utils/dist/vue-test-utils.js:14031:10)
      at Context.<anonymous> (dist/tests/components/Award.spec.js:21:34)
```

Seems to not find the root of some kind.

**Comment by kberg** [comment]
Yeah, I agree it's a pain. :/

>

**Comment by bafolts** [comment]
I have it working. I will update the unit tests we have in place to use it. Have to provide a virtual DOM with jsdom and wire it in all just so with mocha. Now that it is in place seems to be working well.

**Comment by kberg** [comment]
Ooooh. The sooner you send it to me the sooner I can ensure some of the
Ares components continue to work. Thank you!
