### ISSUE TITLE
Ares: Oceans placement and hazards

### ISSUE THREAD

**Issue by meussiebeaucoup** [bafolts/terraforming-mars#1816]
In the Ares expansion, placing an ocean next to a hazard requires you to decrease your income.  

This is **not** in line with the rules, which state that placing oceans does not trigger the penalty.

Screenshot from the rules pdf :

![image](https://user-images.githubusercontent.com/68510105/97883697-7f335c80-1d25-11eb-8823-d2e93d19f2b8.png)

**Comment by kevinb9n** [comment]
Interesting. So it's like this?

placement bonus - is for the placer
placement cost - is for the placer
adjacency bonus - is for the placer (of the new tile)
adjacency cost - is for the owner (of the new tile), if any

**Comment by kberg** [comment]
Thanks for the report. I'm sorry - I did not understand that rule at all!
