### ISSUE TITLE
Bug: Turmoil event `AQUIFER RELEASED BY PUBLIC COUNCIL`

### ISSUE THREAD

**Issue by vsrisuknimit** [bafolts/terraforming-mars#1830]
AQUIFER RELEASED BY PUBLIC COUNCIL asks first player place an ocean.

This ocean is currently placed as if done by the player. So the player gains both TR and the placement bonus. This is wrong. The placement should be like WGT ocean placement.

![image](https://user-images.githubusercontent.com/14239220/98172066-b38e5080-1ebe-11eb-8c63-cb0d41f50973.png)

<img width="1037" alt="Screen Shot 2020-11-04 at 3 53 20 PM" src="https://user-images.githubusercontent.com/14239220/98172253-05cf7180-1ebf-11eb-9441-1e6bddc0ab1c.png">

<img width="491" alt="Screen Shot 2020-11-04 at 3 53 40 PM" src="https://user-images.githubusercontent.com/14239220/98172261-08ca6200-1ebf-11eb-817d-49c6337ed387.png">

**Comment by kevinb9n** [comment]
It's weird that I can't find anything that officially states this rule.
But it seems like it just *has* to be what the designer intended.

**Comment by vsrisuknimit** [comment]
@kevinb9n Turmoil rulebook.

![image](https://user-images.githubusercontent.com/14239220/98192369-e64d3e80-1ee8-11eb-919b-df4ae5cb56e7.png)

**Comment by kevinb9n** [comment]
Ah jeez, I was just one section down from there, where they put all the other special cases.
I suppose they might have intended this to apply to more than one card, originally...
