### ISSUE TITLE
Bug - wrong corporation

### ISSUE THREAD

**Issue by sienmich** [bafolts/terraforming-mars#1836]
Hi,
I was able to choose INCITE corp while playing without the goverment and turmoil expansion. 
https://terraforming-mars.herokuapp.com/player?id=15c05301eaf1
Cheers!

**Comment by nwai90** [comment]
@sienmich Not a bug. You can also choose Morning Star Inc when playing without Venus, Poseidon when playing without Colonies, etc. We could possibly add a warning confirmation before creating the game if an expansion-specific corporation is selected without that expansion
