### ISSUE TITLE
Make it "impossible" to peek the contents of the deck (whether by undo or server rollback)

### ISSUE THREAD

**Issue by kevinb9n** [bafolts/terraforming-mars#1846]
I have no doubt this has been thought about and that it's Hard, and that cheating *per se* is not a rampant problem at the moment. But I didn't see a bug tracking it and it seems like folks would want to get there *eventually*.

In competitive play it should be impossible to regress the game state across any information-revealing event. In TM, those events would be (a) card draws and (b) any nontrivial opponent decisions triggered during your turn (e.g. Philares). The game should refuse to undo an action in which these things happened.

In fact a player should not be permitted to see a card until the commitment to the action that drew it has been written to the database – for the same reason.

Again, I assume it's hard, just filing it.

**Comment by kevinb9n** [comment]
This also affects the idea of making more actions cancelable before completing them, another major convenience feature; if information was revealed then the action has to be uncancelable.

**Comment by kevinb9n** [comment]
Complication: as a general rule, players want the information-revealing events to happen early in the course of carrying out the action, before as many of their own decisions as possible. And that's been/being implemented e.g. #1692 ... because it makes sense.

But it will render a great many actions uncancelable and un-undoable, even if the player was okay with not seeing the card.

A satisfying but sadly complex solution would be to display only card backs in hand from the time they are drawn until whenever the commitment to draw them is irrevocably committed to the database. The player could then click to reveal them, but would know that by doing so they are ceding their right to ever cancel or undo the action.

**Comment by jijiqw** [comment]
![image](https://user-images.githubusercontent.com/16096558/98447881-4bac6400-2163-11eb-93fa-2cf9a88d0d8b.png)
log every undo action is my solution in my folk

**Comment by kevinb9n** [comment]
If we did this, what valid reasons would remain for allowing players to disable undo?

**Comment by Lynesth** [comment]
> If we managed to solve this, what valid reasons would remain for allowing players to disable undo?

Game speed. Also, in competitive plays, whatever the game, you usually can't undo a move.

**Comment by kberg** [comment]
> Game speed. Also, in competitive plays, whatever the game, you usually
can't undo a move.

>
I think that's probably an observation that falls apart depending on your
definition of competitive.

> A satisfying but sadly complex solution would be to display only card
backs in hand from the time they are drawn until whenever the commitment to
draw them is irrevocably committed to the database. The player could then
click to reveal them, but would know that by doing so they are ceding their
right to ever cancel or undo the action.

IMO this is precisely the approach to take.

**Comment by Lynesth** [comment]
> I think that's probably an observation that falls apart depending on your definition of competitive.

I think the word has a proper definition which is "involving competition". And I cannot think of any sport or game that allows you to undo a move you made in a competition environment.
You cannot take back a move you made when you play Chess, MTG, Tennis, Starcraft or whatever else. That is, unless you're not playing to win (casual play) which, by definition, is not competitive.

> A satisfying but sadly complex solution would be to display only card backs in hand from the time they are drawn until whenever the commitment to draw them is irrevocably committed to the database. The player could then click to reveal them, but would know that by doing so they are ceding their right to ever cancel or undo the action.

This is complex and involves even more clicks.
The way I see it, there's 2 solutions:
- If you want to play with `undo` available, you should do it with rules properly layered amongst players. And if someone cheats, well, then you know who not to play with again.
- We simply don't allow undoing actions that drew or revealed from the deck, but then solo players which try to get some high score will be angry with the change so we'll have to make a difference if game is solo or not.

**Comment by kevinb9n** [comment]
> And I cannot think of any sport or game that allows you to undo a move you made in a competition environment.
> You cannot take back a move you made when you play Chess, MTG, Tennis, Starcraft or whatever else. That is, unless you're not playing to win (casual play) which, by definition, is not competitive.

I understand the meaning here, and have an answer to my question, thanks.

Note that the discussion here is phrased in terms of undo, but applies equally to both undo and cancellation. The ideal form of cancellation – for a user who wants it – is that I always get to see the full immediate consequences of the choices I make – on the game boards, in the log, etc. – before I click to commit my move and make it visible to other players. I think this is all that most players (who describe what they want as "undo") really want. We don't want too many clicks, but this approach of an extra click at the end makes it safer to completely streamline all the individual clicks that make up a flow; I have no doubt that this can be done in fewer total clicks than we have today.

(When cancellation is a thing it's definitely a trick to settle on the right granularity for each interaction flow from commit to commit. It could be a single interaction all the way up to every single thing a user does until some other user gets to act. Of course it wants to be somewhere in the middle. Too granular is a pain for that player; too coarse is boring for everyone else sitting there seeing nothing happen.)


> > A satisfying but sadly complex solution would be to display only card backs in hand from the time they are drawn until whenever the commitment to draw them is irrevocably committed to the database. The player could then click to reveal them, but would know that by doing so they are ceding their right to ever cancel or undo the action.
> 
> This is complex and involves even more clicks.

Since I wrote this, it has started seeming less weird to me each time I come back to it in my mind. Can we just not dismiss it yet? Note that this line above is trying to dismiss it by only stating that it has a disadvantage, which is even the same disadvantage I'd acknowledged up front.

It does have some real disadvantages, but I think the *biggest* disadvantage is probably that it's crazy. I've never heard of a game doing that.

It is just very interesting, though, whenever you find a candidate solution that ticks all the boxes this one does:
* It seems to solves the exact problem
* It doesn't take away the user's choices
* Users can actually understand it. "Click to see / disables undo."

This makes it compelling to consider, but of course, it might really just be way too hard.

(To reiterate, users only have to actually click on the card backs in the special cases where they want to see them *before* their action is committed in the some way; once they're past the cancel point, either in the normal way or because they clicked any one fo the card backs, then they'd all be revealed. Again, crazy. I know.)


> The way I see it, there's 2 solutions:
> 
> * If you want to play with `undo` available, you should do it with rules properly layered amongst players. And if someone cheats, well, then you know who not to play with again.

What does the "rules layered" part mean? (I'm going to take "cheat" out of the headline here, because it's misleading; this is just about any way that a player ends up peeking the deck no matter what their intentions.)

> * We simply don't allow undoing actions that drew or revealed from the deck, but then solo players which try to get some high score will be angry with the change so we'll have to make a difference if game is solo or not.

When replaying a solo game from a seed, honestly it seems like we might as well just make the entire deck open information and be done with it. (The other day I scared myself by having the thought, "oh, maybe I'll just write down a list of every card I see so I can refer to it the next time through!") Maybe I'll just file that separately.

**Comment by kevinb9n** [comment]
(I refocused the title on the deck. Should I file another one for the other half, "Prevent undo if an opponent had an opportunity to act during my turn"? Philares is the only case that comes to mind, and if it is allowing undo in this case then that's just annoying to the Philares player on a whole other level. :-)

**Comment by Lynesth** [comment]
@kevinb9n I do agree with you that seeing what a specific play will do is important. But isn't that already the case ?
I mean, cards do tell you exactly what's going to happen when you play them or use their action.

**Comment by kevinb9n** [comment]
> @kevinb9n I do agree with you that seeing what a specific play will do is important. But isn't that already the case ?
> I mean, cards do tell you exactly what's going to happen when you play them or use their action.

This is all about the very big difference between "the user has the capacity to correctly predict the consequences" and "the interface *shows* the user the consequences".

In my family we have "oh, I didn't realize that was going to happen" moments *constantly*. "I forgot it was Reds, I forgot I was Pharmacy, I did the math wrong on whether I'd have the money left I need, I could have sworn I had a two-plant spot to put this, where is it?," the list goes on and on. I just did "I forgot you just went down to 1 plant prod 10 seconds ago and so I just Birded myself in the face."

A sentiment that goes like, "Well part of the game is getting used to tracking that kind of stuff" is attractive, except that what it really means is "you shouldn't be a casual; we don't want casuals."

I'm a casual. I try to win, but it always detracts from my fun every time any player (me or otherwise) gets stuck with a decision they immediately knew was not what they wanted to do. It means we're playing out an alternate universe game we never would have played across the table. (I just can't imagine being the kind of person who tells a friend "I'm sorry, I saw the Birds card hit the table, you can't take that back now....")

**Comment by EricARD2000** [comment]
Dear all,
Just to understand the undo effect after a 'card draw' scenario. Once a player draw´s a card and does the undo action. Would that spesific card stay "on top of the deck" meaning that it could go to an other player who next would draw a card or would it stay in 'reserve' for that same player whom did the undo action.
