### ISSUE TITLE
Debug a possible bug on the setup phase

### ISSUE THREAD

**Issue by rzulian** [bafolts/terraforming-mars#1847]
I've to investigate a possible bug during the setup phase. The bug seems to be that the player with PointLuna is taking six cards, plus the two free cards (one from PointLuna and one from a Prelude card). He should have 38 - 6*3 = 20, but he is getting 23.
Is there a way do debug a specific game?
![PHOTO-2020-11-06-12-48-39](https://user-images.githubusercontent.com/29941924/98372561-3ee22000-203e-11eb-9750-46e9b22de1c4.jpg)

**Comment by nwai90** [comment]
@rzulian Yes, it's a bug. Will submit a patch

**Comment by rzulian** [comment]
@nwai90 Oh, I see. the starting MegaCredit is 41 ;)
