### ISSUE TITLE
Ares Disaster placement bug

### ISSUE THREAD

**Issue by Indzasa** [bafolts/terraforming-mars#1859]
I was placing a City with Standart Project, only 7 MC left. I was playing Tharsis Republic and had Rovers project in play.
I was able to pick disaster tile to place a city, but then i had popup telling i dont have MC to place a tile here (need 8), and no option to continue playing. It was solo game.

**Comment by kberg** [comment]
Thanks for the report - sorry about that. This has been reported again with a slightly different circumstance. @Lynesth and I are trying to work out a good solution.

**Comment by kberg** [comment]
This is a duplicate of #1823
