### ISSUE TITLE
Possible to trade using Titan Floating Launch-Pad when already used

### ISSUE THREAD

**Issue by meussiebeaucoup** [bafolts/terraforming-mars#1866]
It is possible to trade using Titan Floating Launch-Pad, even though the card's action has already been used that turn, whether it's trading or adding a floater).

This is possible when using the 'trade with a colony' player action, not when using the 'perform action from a played card' player action.

![image](https://user-images.githubusercontent.com/68510105/98530223-ef3e6700-227e-11eb-8467-f2a09ce14e5e.png)

Taking a quick glance at the code, it doesn't seem to check if the action has been used already, only if the player owns the card and it has resources on it.
```           
 } else if (payWith === Resources.ENERGY) {
              this.energy -= (3 - this.colonyTradeDiscount);
              colony.trade(this, game);
            } else if (payWith === Resources.TITANIUM) {
              this.titanium -= (3 - this.colonyTradeDiscount);
              colony.trade(this, game);
            } else if (payWith === ResourceType.FLOATER && titanFloatingLaunchPad !== undefined && titanFloatingLaunchPad.resourceCount) {
              titanFloatingLaunchPad.resourceCount--;
              this.actionsThisGeneration.add(titanFloatingLaunchPad.name);
              colony.trade(this, game);
            }
```

**Comment by nwai90** [comment]
@meussiebeaucoup Did you pull latest version? This is fixed in https://github.com/bafolts/terraforming-mars/commit/899282c852489bf78494ebda6ce8b353b7926e43

**Comment by meussiebeaucoup** [comment]
Hmm, my bad then. It looks like my pull failed. Apologies
