### ISSUE TITLE
minor: "trade with a colony tile"

### ISSUE THREAD

**Issue by kevinb9n** [bafolts/terraforming-mars#1870]
I only just noticed this! Should say "trade with a colony tile" and "select a colony tile for trade".

No colonies exist yet in this game.

![image](https://user-images.githubusercontent.com/934551/98619211-9f2fc680-22b7-11eb-8de0-a119929362fc.png)

**Comment by bafolts** [comment]
To whomever makes this change. It will require updating the translations file as `Trade with a colony` is a translation key.
