### ISSUE TITLE
Heroku instance down

### ISSUE THREAD

**Issue by chosta** [bafolts/terraforming-mars#1873]
@bafolts 
build is successful but starting it not so much

```2020-11-10T13:35:33.709739+00:00 app[web.1]: > node make_static_json.js && lessc src/styles/common.less styles.css
2020-11-10T13:35:33.709739+00:00 app[web.1]: 
2020-11-10T13:35:37.111284+00:00 app[web.1]: 
2020-11-10T13:35:37.111305+00:00 app[web.1]: > terraforming-mars@1.0.0 compile /app
2020-11-10T13:35:37.111305+00:00 app[web.1]: > tsc
2020-11-10T13:35:37.111306+00:00 app[web.1]: 
2020-11-10T13:36:24.217295+00:00 heroku[web.1]: Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 60 seconds of launch
2020-11-10T13:36:24.241793+00:00 heroku[web.1]: Stopping process with SIGKILL
2020-11-10T13:36:24.351977+00:00 heroku[web.1]: Process exited with status 137
2020-11-10T13:36:24.391904+00:00 heroku[web.1]: State changed from starting to crashed```

**Comment by chosta** [comment]
[This](https://appuals.com/how-to-fix-error-r10-boot-timeout-on-heroku/) might help

**Comment by bafolts** [comment]
Looking at that log I don't think it finishes `tsc` within this 60 second time limit. The entire `npm run start` must be taking 60 seconds.

**Comment by bafolts** [comment]
When I ran a manual build I saw the `lint` task run which was unexpected. Heroku appeared to run `npm run build` instead of `npm run start`. It seems to have propped up `97fbedf`. I may disable the automatic deployment until I see what is going on.

**Comment by bafolts** [comment]
So if this time includes the `npm install --production` we have to download 250 megabytes. I have seen `npm start` take 30-40 seconds on some of my older linux laptops. The server is back up but I am going to move some of the `devDependencies` from `dependencies` which should cut down on how much heroku downloads each time.

**Comment by chosta** [comment]
> So if this time includes the `npm install --production` we have to download 250 megabytes. I have seen `npm start` take 30-40 seconds on some of my older linux laptops. The server is back up but I am going to move some of the `devDependencies` from `dependencies` which should cut down on how much heroku downloads each time.

I've noticed that sometimes the build takes much more time when building it locally. I thought it might have been some memory issues on my machine but maybe not. I'd second you on disabling automatic deployment.The app is at a stage where critical bugfixes are not needed as often. One deployment per couple of days should be enough. People in discord are actually more concerned about their current games being stable rather than having some fringe new feature.

**Comment by bafolts** [comment]
I have disabled the automatic builds. I will deploy around 8am Denver time M-F.
