### ISSUE TITLE
Keyboard Shortcuts

### ISSUE THREAD

**Issue by vsrisuknimit** [bafolts/terraforming-mars#1879]
I think it would be helpful to have keyboard shortcuts for moving up and down the page.

Q: Game board
W: Turmoil board
E: Milestones and Awards
R: Tag Overview
T: Game log

A: Action
S: Cards in hand
D: Played cards
F: Colonies

**Comment by vsrisuknimit** [comment]
Or letter coded? 'a' for action. 'c' for colonies. 'b' for board. 't' for turmoil, etc.

**Comment by kevinb9n** [comment]
Consider also two keys for simply jumping up and down through those sections.

**Comment by vsrisuknimit** [comment]
Perhaps "[" and "]" as up and down the section.

**Comment by alrusdi** [comment]
May be we should do it customizable with two predefined schemas? I can do UI part :-)

**Comment by vsrisuknimit** [comment]
@alrusdi Two systems could work. "[" and "]" as up and down for both systems. Let me know if I can help.

Or should we take a vote on the server to see which system the users prefer?

**Comment by funkybaboon** [comment]
I use vimium https://vimium.github.io/ to play tfm almost completely without the mouse.

**Comment by kberg** [comment]
That's fantastic -- I'm start trying to use Vimium.

>

**Comment by bafolts** [comment]
I am a proud VIM user...vimium.....game changer

**Comment by vsrisuknimit** [comment]
Glad that Vimium works well with the app. I think it might still be helpful for typical users to have the keyboard shortcuts that don't require an extension.

**Comment by vsrisuknimit** [comment]
@alrusdi can you help me with this?

**Comment by vsrisuknimit** [comment]
What I hope to use. I am not sure where to put it in? App.ts? PlayerHome.ts?
https://shubhamjain.co/til/vue-shortcuts/
https://michaelnthiessen.com/redirect-in-vue/

**Comment by kberg** [comment]
Why not install an NPM extension? https://github.com/iFgR/vue-shortkey

**Comment by kberg** [comment]
(That's just an example, it hasn't been udpated in a year, for what it's worth.)

**Comment by bafolts** [comment]
I don't think an extension is warranted. I would do this leveraging the hash of `window.location`. If we place an `id="board-panel"` around the board component then when the window location hash is updated to include `#board-panel` the browser will naturally bring the board into focus. If we then want to control this with the keyboard it is as simple as:

```
document.onkeypress = function (e) {
   if (e.keyCode === KeyboardNavigation.BOARD_KEYCODE) {
       window.location.hash = '#board-panel';
   }
}
```

**Comment by vsrisuknimit** [comment]
Where should I put this?

> document.onkeypress = function (e) {
>    if (e.keyCode === KeyboardNavigation.BOARD_KEYCODE) {
>        window.location.hash = '#board-panel';
>    }
> }

Where should I put this? App.ts?

**Comment by bafolts** [comment]
Since we want to navigate `PlayerHome` I would put the listener in `PlayerHome`. This can all be accomplished without an extension and with vue as-is.

```
168   template: `
169         <div v-on:keyup="navigatePage" tabindex="0" id="player-home" :class="player.turmoil ? 'with-turmoil': ''">
```
With that modification in `PlayerHome` you can implement a `navigatePage` in `methods`.

```
methods: {
    navigatePage: function (event) {
        if (event.keyCode === KeyboardNavigation.BOARD_KEYCODE) {
            this.$refs.board.element.scrollIntoView();
        }
    }
}
```
