### ISSUE TITLE
Reordered cards reset after selling patents.

### ISSUE THREAD

**Issue by vsrisuknimit** [bafolts/terraforming-mars#1885]
A user on Discord reported that previously reordered cards are reset after selling patents. I have not tested. @bafolts

**Comment by bafolts** [comment]
I don't think it is getting reset but the ordering when selling patents is not considering the order of the sorted cards. I will include the sort there as well.

**Comment by bafolts** [comment]
I will have a fix that displays the cards sorted on `SelectCard` here in a few.
