### ISSUE TITLE
Issue with windows after forced formatting PR

### ISSUE THREAD

**Issue by chosta** [bafolts/terraforming-mars#1886]
@bafolts
I think we created a problem for windows users after the forced formatting PR. A user in discord complained about getting 60k+ errors after running `npm run build`:
`Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style`

I asked them to try adding `'linebreak-style': ['error', 'windows']` to the eslint rules but it didn't work.
It's probably a result of you making the fix from a unix system.

**Comment by bafolts** [comment]
I am pretty sure they will need to configure GIT to checkout with `LF`. I assume they are checking out and converting to `CRLF`.

https://stackoverflow.com/questions/10418975/how-to-change-line-ending-settings

**Comment by bafolts** [comment]
```
Git will convert LF to CRLF when checking out text files. When committing text files, CRLF will be converted to LF. For cross-platform projects, this is the recommended setting on Windows ("core.autocrlf" is set to "true")
```

Will need to address this for windows users in some way as supposedly windows recommends using their CRLF locally.

**Comment by chosta** [comment]
Thanks, the stackoverflow link helped.
