### ISSUE TITLE
Landclaim checks for 6 mc on Hellas South Pole

### ISSUE THREAD

**Issue by vsrisuknimit** [bafolts/terraforming-mars#1894]
If you have less than 6 mc, the app does not allow you to play Land Claim on the south pole.  This is not a correct behavior. Land claiming that spot should not require 6 mc.

Currently Land Claim that spot checks for 6 mc, but not deduct 6 mc if you land claim successfully.

See this video https://www.twitch.tv/videos/803178482?t=0h38m20s

**Comment by bafolts** [comment]
Good old land claim. In case it took anyone else a moment to realise the issue here, you have to pay for the ocean when placing the tile there. Land claim does not place the tile thus shouldn't have to pay yet.
