### ISSUE TITLE
Auto refresh

### ISSUE THREAD

**Issue by vincentneko** [bafolts/terraforming-mars#19]
Would it be possible to add a refresh mechanism to the game page so there is no need to press F5 ?

**Comment by bafolts** [comment]
This shouldn't be too difficult to add. It would only check for updates if it wasn't a player's turn to take any actions. When a player is waiting to take actions the client side can continually check to get the new game state and wait until it is their turn to take an action.

**Comment by bafolts** [comment]
If I don't get around to this it makes sense to add an `XMLHttpRequest` polling check here, probably checking every minute:

https://github.com/bafolts/terraforming-mars/blob/master/src/components/WaitingFor.ts#L33

If you update the `PlayerModel` the rest of the vue components should update themselves accordingly. When it is your turn the actions list should appear.

**Comment by alrusdi** [comment]
I've done it with notifications task
