### ISSUE TITLE
Change default branch to main

### ISSUE THREAD

**Issue by bafolts** [bafolts/terraforming-mars#1903]
Github has changed the default branch name to `main` from `master`. Will change the default for this repository to `main` on 2020-11-18. I don't think the change will cause any technical issues. People will need to start selecting `main` when creating pull requests and branching from `main`. Can keep both branches around until it seems the transition went fine and no history or code was lost.

**Comment by chosta** [comment]
Hmm, I think we need to have dev guidelines somewhere. I'll try to create something and keep it up to date.

**Comment by bafolts** [comment]
I changed the default branch to main. If commits show up to master I can move them to main. For new changes use main branch.
