### ISSUE TITLE
Venus Terraforming button should be renamed and it needs an explanation

### ISSUE THREAD

**Issue by vsrisuknimit** [bafolts/terraforming-mars#1914]
Need an (i) link to the wiki to explain what it does.

The button should be renamed to "Mandatory Venus Terraforming" or something along that line.

@Starcalc @nwai90

**Comment by vsrisuknimit** [comment]
I actually think it should be moved to a different column for unconventional setting. So few people will use it.

**Comment by nwai90** [comment]
@Starcalc I added a wiki entry https://github.com/bafolts/terraforming-mars/wiki/Variants#venus-terraforming. Name should be fine as is once we have the info button; "Mandatory Venus Terraforming" is too long imo

**Comment by Starcalc** [comment]
@vsrisuknimit Sorry, we were both working on the same issue. Haven't seen your update.
