### ISSUE TITLE
Potential colonies bugs.

### ISSUE THREAD

**Issue by bafolts** [bafolts/terraforming-mars#1915]
Brian, found another bug when playing the new colonies and don't have a github to add so was hoping you could help. We've been loving the Ceres add on btw!:
-Colonies on Titania don't get 3 MC taken away, but get some multiple of additional MC credits as a colony trade bonus. 
-Trading with Mercury yields 1 MC instead of 2 MC, for trade bonus to colony owners.

**Comment by nwai90** [comment]
@bafolts It may be related to the recent colony rewrite. I will take a look
