### ISSUE TITLE
In seeded games, player hand should be linked to seating order

### ISSUE THREAD

**Issue by vsrisuknimit** [bafolts/terraforming-mars#1922]
Currently, when you use predefined game seed, the cards that you will draw is tied to the player box during game creation page.

![image](https://user-images.githubusercontent.com/14239220/99660145-f5c3a000-2a2f-11eb-8e9a-07d30d4ee069.png)

As a result, if you select red to go first OR green to go first, the game will be very different as first player of each game actually will have different hands.

The seed should make the card draw/hands tied to player order on the first gen instead.

**Comment by bafolts** [comment]
For simplicity the cards drawn can always consider which player goes first.
