### ISSUE TITLE
Feature Request: More detailed Game Statistics 

### ISSUE THREAD

**Issue by ATiredVegan** [bafolts/terraforming-mars#1934]
Hi,

First of all, thanks for your amazing work on this game port! 

We've been having a lot of debates about the ideal gold/VP ratio (what things it's worth spending money on), and we thought it would be helpful to receive some extra post game statistics, such as the amount of each resource spent throughout the game. We were able to do some of it ourselves with debugging messages, but we don't have experience with TypeScript. We would love a cleaner version of this feature, and large scale community adoption could help answer statistical questions about viable strategies and corporations.

**Comment by kevinb9n** [comment]
Note that if we eventually have a full game JSON export (like discussed as part of #1110) then it would enable anyone to write analyses of any kind, in any language. And without packing more and more code into a single server.

However, *please* don't anyone interpret that comment as "we shouldn't do anything until we do the long-term thing".

**Comment by bafolts** [comment]
At any time the complete game log is available in it's entirety with a call to:

```
/api/game/logs?id=playerId
```

Where `playerId` is replaced with your `playerId`. This is going to have the only history of the game tracked. Does this suffice for the needs of this issue? Can always add more information to the log to help both the player during the game and analysis after the game.

**Comment by nwai90** [comment]
Agree with @bafolts' proposed direction. Stats are a nice to have but it is likely everyone will want to track different things, and some others have no interest in stats at all. More detailed logging could provide the necessary info (with a proper game option so that the game log doesn't get cluttered for all players). Collecting data via new properties on `Player` and presenting them on the game end screen could also work as long as it is optional to display those stats.

**Comment by nivaivax** [comment]
Something we've discussed in my group of friends would be a graph or table with VP total per turn, so one could see who was in lead when, and what changed.
           
'Turn 
              1   2   3   4   5
Player 1  20 22 23 23 26
Player 2  20 20 24 23 28
'

Or graph like this
https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/Maddison_GDP_per_capita_1500-1950.svg/1200px-Maddison_GDP_per_capita_1500-1950.svg.png

**Comment by ATiredVegan** [comment]
The game log would be sufficient for now I think!
