### ISSUE TITLE
Change default action for Self Replicating Robots

### ISSUE THREAD

**Issue by SliceOfBread** [bafolts/terraforming-mars#1965]
Maybe it is just me but when activating Self Replicating Robots, don't people almost always want to 'Double resources' as opposed to selecting a new card?

I think this can be accomplished with a one line change (but perhaps this screws up something else):
from
orOptions.options.push(new SelectCard(
  'Select card to double robots resource', 'Double resource', robotCards,
to
orOptions.options.**unshift**(new SelectCard(
  'Select card to double robots resource', 'Double resource', robotCards,

![Screenshot from 2020-11-27 14-20-48](https://user-images.githubusercontent.com/13003705/100479808-49338f00-30bd-11eb-9f42-4b8c26271f91.png)
![Screenshot from 2020-11-27 14-28-11](https://user-images.githubusercontent.com/13003705/100479810-49338f00-30bd-11eb-8771-843294c2a1e4.png)

**Comment by nwai90** [comment]
Agree. We can simply swap the order of the two options. In most cases if there is a linked card, players would prefer to double the resources on it.
