### ISSUE TITLE
Venus next cards review

### ISSUE THREAD

**Issue by alrusdi** [bafolts/terraforming-mars#197]
- [x] Atmoscoop - cant get ocean bonus (set temp=-2, play this card. Expected an option to place ocean as temperature bonus, but got nothing)
- [x] Gyropolis - can lock the game if no places for city available?
- [x] Sponsored Academies - you can discard "Sponsored Academies" itself as result of playing this card
- [x] Stratospheric Birds - requirement to remove a floater isn't implemented
- [x] Thermophiles - allows to place microbe to any microbe card but required to place only on Venus microbe card

**Comment by vincentneko** [comment]
Thanks a lot for the review.
About Atmoscoop I'm not sure how to handle it. 
@bafolts may I have your help on this one ?

Thermophiles should be fixed now

**Comment by vincentneko** [comment]
Atmoscoop should be ok now
