### ISSUE TITLE
Can't run interactive vscode debugger anymore

### ISSUE THREAD

**Issue by kberg** [bafolts/terraforming-mars#1975]
This seems to have been related to some of the work around compiling the Vue content -- I noticed it a while ago but decided at the time it wasn't worth the trouble,but now that I need to debug an issue, I'd like to get it working again.

To start with, sometime in the last month or so, output seems to have moved from `./dist` to `./build` which I assume is not a proble, but it does mean I had to change `./vscode/launch.json` to replace `./dist` with `./build`.

Running an interactive test, I get

```
/usr/bin/node ./node_modules/mocha/bin/mocha --notimeout --colors --recursive /home/kberg/git/t2/build/tests/**/*.js
Uncaught TypeError: Cannot read property 'component' of undefined
src/components/Award.ts:4
Process exited with code 1
```

**Comment by kberg** [comment]
I'll own this, I want to look into this.

**Comment by kberg** [comment]
Aha. add
`"--ignore", "${workspaceFolder}/build/tests/components/*.js",`

**Comment by bafolts** [comment]
When I ran `gts` and had issue integrating I noticed they used `build` as the `outDir`. That was when the change was made to bring repository closer to `gts`.

https://github.com/google/gts/blob/master/tsconfig.json#L5

Sorry for any inconvenience!

**Comment by kberg** [comment]
No problem, it was good to catch up.

There's still a ./dist dir, though, what's up with that?

>

**Comment by bafolts** [comment]
The webpack script is still using `/dist`. Should make an issue to have this also use `/build` instead.

https://webpack.js.org/concepts/output/
