### ISSUE TITLE
Remove use of Object.assign in serialization.

### ISSUE THREAD

**Issue by kberg** [bafolts/terraforming-mars#1979]
@bafolts said in https://github.com/bafolts/terraforming-mars/pull/1977#discussion_r532127133

> I wish we didn't use Object.assign as it makes it difficult to know which properties are being set.

Makes sense. So, this is a tracking bug.

**Comment by kberg** [comment]
This has been handled for Turmoil. My notes for Player:

I read the `deserialize` method and mapped every field it populated in `Player` and removed it from a copy of all the fields remaining in `SerializedPlayer`. Here are all the fields it auto-populates:

```
actionsTakenThisRound
canUseHeatAsMegaCredits
cardCost
cardDiscount
colonyTradeDiscount
colonyTradeOffset
colonyVictoryPoints
corporationInitialActionDone
energy
energyProduction
fleetSize
hasIncreasedTerraformRatingThisGeneration
heat
heatProduction
lastCardPlayed?
megaCreditProduction
megaCredits
needsToDraft
oceanBonus
plantProduction
plants
plantsNeededForGreenery
powerPlantCost
removedFromPlayCards
removingPlayers
scienceTagCount
shouldTriggerCardEffect
steel
steelProduction
steelValue
terraformRating
terraformRatingAtGenerationStart
titanium
titaniumProduction
titaniumValue
tradesThisTurn
turmoilScientistsActionUsed
victoryPointsBreakdown
```

**Comment by kberg** [comment]
This is still open, I think.

**Comment by kberg** [comment]
Oh yeah! We can definitely close this. Yay!

**Comment by bafolts** [comment]
Thank you stale bot!
