### ISSUE TITLE
Can we enable "Exclude some cards"?

### ISSUE THREAD

**Issue by JingleCEF** [bafolts/terraforming-mars#1987]
I really need to exclude the "AI" card. It's too strong and whoever has it wins. I remember this option used to work but now is not clickable. Thanks!

**Comment by alrusdi** [comment]
@JingleCEF It seems to be working. But UI to exclude the cards is appearing at the bottom of the page. Did you noticed it?

**Comment by JingleCEF** [comment]
I use http://jaing.me:18001/new-game. And the button of "Exclude some cards" is dark (not clickable).

**Comment by alrusdi** [comment]
It is not official version. Please ask its maintainer to enable that button.
