### ISSUE TITLE
Payment with Dirigibles when a Floater must be lost

### ISSUE THREAD

**Issue by andystager** [bafolts/terraforming-mars#1992]
I think this applies to Stratospheric Birds and Air Raid.

Example, I only have one total floater sitting on Dirigibles, I am still allowed to pay with it. I did not attempt the transaction as I assumed it would be game breaking, but this likely requires a check prior to purchase.

**Comment by Lynesth** [comment]
You shouldn't be able to do it. This was fixed some time ago.

**Comment by andystager** [comment]
Ok, thanks for checking, I'll close.
