### ISSUE TITLE
Error in Asteroid

### ISSUE THREAD

**Issue by SliceOfBread** [bafolts/terraforming-mars#1996]
Pretty sure this was a cut/paste error but here is the code from Asteroid (note the game.getVenusScaleLevel() instead of temperature)
`  public canPlay(player: Player, game: Game): boolean {
    const temperatureMaxed = game.getVenusScaleLevel() === MAX_TEMPERATURE;
    if (PartyHooks.shouldApplyPolicy(game, PartyName.REDS) && !temperatureMaxed) {
      return player.canAfford(player.getCardCost(game, this) + REDS_RULING_POLICY_COST, game, false, true);
    }
`
Compare to Small Asteroid, which is almost identical 
`    public canPlay(player: Player, game: Game): boolean {
      const canRaiseTemperature = game.getTemperature() < MAX_TEMPERATURE;
      if (PartyHooks.shouldApplyPolicy(game, PartyName.REDS) && canRaiseTemperature) {
        return player.canAfford(player.getCardCost(game, this) + REDS_RULING_POLICY_COST, game, false, true);
      }
`

Not that it matters but I did not find this issue while playing.

**Comment by Lynesth** [comment]
Thank you for the report. Fixing this.
