### ISSUE TITLE
Some game issues

### ISSUE THREAD

**Issue by vincentneko** [bafolts/terraforming-mars#2]
Hello Brian,

I just found your Terraforming Mars implementation on github and I gave it a try with a friend of mine.

We ran into a couple of issues that made the game unplayable unfortunately...

First on is a error when we click on the other player name to check the projects cards he has played and his status (see error log bellow) 
The other one is that it is not possible to use steel to pay for a project with Building tag.
Thanks a lot for doing this and sharing it, it is great !

Cheers,
Vincent

[Vue warn]: Property or method "getEventCards" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property. See: https://vuejs.org/v2/guide/reactivity.html#Declaring-Reactive-Properties.

found in

---> <OtherPlayer>
<PlayerHome>
<Root>
warn @ vue.esm.js:629
vue.esm.js:629 [Vue warn]: Error in render: "TypeError: getEventCards is not a function"

found in

---> <OtherPlayer>
<PlayerHome>
<Root>
warn @ vue.esm.js:629
vue.esm.js:1896 TypeError: getEventCards is not a function
at Proxy.eval (eval at createFunction (vue.esm.js:NaN), <anonymous>:3:471)
at VueComponent.Vue._render (vue.esm.js:3545)
at VueComponent.updateComponent (vue.esm.js:4063)
at Watcher.get (vue.esm.js:4476)
at Watcher.run (vue.esm.js:4551)
at flushSchedulerQueue (vue.esm.js:4307)
at Array.eval (vue.esm.js:1988)
at flushCallbacks (vue.esm.js:1914)
logError @ vue.esm.js:1896

**Comment by bafolts** [comment]
Both these bugs should be fixed with the last commit. Thanks for playing! Keep bugs and suggestions coming in.
