### ISSUE TITLE
miscellaneous minor card iconography issues

### ISSUE THREAD

**Issue by kevinb9n** [bafolts/terraforming-mars#2003]
Hey, sorry for all the nitpickery here, just jotting these down. Not bothering to report all the bugs that are also on the print cards (I think it's a longer list). Hooray, bug-for-bug compatibility.

Lakefront has an extra asterisk it doesn't need (print card doesn't have it).

Helion should say x heat "equals-sign" (not colon) x money. (The x's aren't really necessary unless you're just trying to track with the print card.)

Mons Insurance is missing the red border on the minus-production box.

Equatorial Magnetizer, Venus Magnetizer, Energy Market: you spend an energy production, not a negative energy production.

Likewise with Refugee Camp spending a money production.

GMO Contract has extra slash. [EDIT: wait, Decomposers too]

Recyclon's effect icons are slightly garbled, they should be just like Olympus Conference.

Search For Life should picture the microbe tag, not microbe resource icon.

Toll Station, Valley Trust, and Robinson missing their asterisks.

Pharmacy Union needs either some icon representing the flipping situation, or just an asterisk.

Pristar's effect trigger should be a *crossed-out* TR icon.

Ecology Experts icon should be crossing out "Global requirements" rather than "Project requirements".

And lastly there's no such thing in TM as a "Forest". :-)

**Comment by vsrisuknimit** [comment]
@chosta

**Comment by Lynesth** [comment]
Good job gathering them all.
Just for the sake of being clear, _"And lastly there's no such thing in TM as a "Forest". :-)"_, is about **Ecological Zone**.

**Comment by kevinb9n** [comment]
> Just for the sake of being clear, _"And lastly there's no such thing in TM as a "Forest". :-)"_, is about **Ecological Zone**.

Ah, right, that and I think 3 Ares cards too.

**Comment by kevinb9n** [comment]
I'm.... just gonna keep appending a bit more. I'm just reporting, not trying to demand that these are huge bugs that will destroy the world.

Eccentric Sponsor should be text only, just as it is in print; there is no icon that means "play a card from hand".

Martian Zoo and Rad-Suits requirement box should probably say "ANY 2 Cities" (view those side by side with Urban Decomposers).

Field Capped City and Ocean Farm don't need +s inside their production boxes.

Some cards still using a teeny tiny textual hyphen as a minus icon: Impactor Swarm, Insulation, Nitrophilic, Olympus, Potatoes, Sabotage, Sponsored, Stratospheric, Virus, Mons, Pharmacy, Pristar, certainly others

NIT: Freyja Biodomes puts - and + production on the same horizontal line, which, in print, is never done on any card.

SUPERNIT: Prelude cards that lose MC have the minus sign unconventionally outside the MC icon. Sorry to even bring this up.

**Comment by andystager** [comment]
Now I can't unsee the minus sign in the wrong place on the Prelude cards. Plz fix ASAP game is unplayable.

**Comment by kevinb9n** [comment]
Thanks for that :-)

Morning Star's effect appears as if it's triggered by raising Venus; it should look like Inventrix's with s/Global/Venus/.

**Comment by andystager** [comment]
It's not a card issue but I'll add it to the pile here:

When attempting to trade without selecting a colony, the error message reads "ERROR WITH INPUT
Incorrect options provided (nested)" instead of something helpful like "error no colony selected"

**Comment by kevinb9n** [comment]
> It's not a card issue but I'll add it to the pile here:
> 
> When attempting to trade without selecting a colony, the error message reads "ERROR WITH INPUT
> Incorrect options provided (nested)" instead of something helpful like "error no colony selected"

Filed #2080 for that.

**Comment by kevinb9n** [comment]
Aphrodite Venus icon should be red-outlined.

**Comment by kevinb9n** [comment]
Robotic Workforce has lost its "copy a" icon.

**Comment by andystager** [comment]
Rim Freighters lost its negative sign?

**Comment by andystager** [comment]
Poseidon effect shows 2 MC production instead of 1.

**Comment by kevinb9n** [comment]
Hey @chosta, some of the later comments seem to be regressions and seem a little more significant than the kind of small potatoes this issue started off with. Just an FYI.

**Comment by chosta** [comment]
Somehow I missed this...Most of the things will be fixed in an upcoming PR.
Thanks for reporting.

**Comment by chosta** [comment]
Most of the issues have been resolved with the exceptions below. Mainly it's because of limited space on the card. In theory there should be enough but I didn't want to add custom functionality to handle exceptions. I think we can live with them for now. Thanks @kevinb9n for taking the time to find the inaccuracies and report them. Feel free to close this issue once you are satisfied with the results.

> Pharmacy Union needs either some icon representing the flipping situation, or just an asterisk.

There is simply not enough space for an asterix :(

> Recyclon's effect icons are slightly garbled, they should be just like Olympus Conference.

I had a really hard time fitting everything in there. Again it's a space limitation.

> Some cards still using a teeny tiny textual hyphen as a minus icon: Impactor Swarm, Insulation, Nitrophilic, Olympus, Potatoes, Sabotage, Sponsored, Stratospheric, Virus, Mons, Pharmacy, Pristar, certainly others

I think this comment was made in the middle of the card conversion to Vue, so I guess most of the - sign is a proper minus with some exceptions like Insulation where a smaller sign was intentionally used.

> NIT: Freyja Biodomes puts - and + production on the same horizontal line, which, in print, is never done on any card. [EDIT: I've now seen this on several cards and it's fine to break with the print convention on purpose - can ignore.]

Not enough space yet again. I was fighting for every pixel with Freyja Biodomes.

**Comment by kevinb9n** [comment]
That all makes sense, I'll check things out whenever this shows up on the main server!

**Comment by kevinb9n** [comment]
It was a cool surprise to me that these things were actually fixed. :-) Now that's quality...

I verified almost all of these and will add a very small number of stragglers to my next list :-) (which, again, you should only fix if you feel like it).

**Comment by chosta** [comment]
Can you please close this one? We can open new issues if needed. Thanks.

**Comment by kevinb9n** [comment]
Whoops, that's what I meant to do at the time of my last comment, sorry :-)
