### ISSUE TITLE
UX: high-level organization and viewing opponent state

### ISSUE THREAD

**Issue by kevinb9n** [bafolts/terraforming-mars#2008]
(Another element toward a no-scroll UI. I do realize there are both pros and cons to filing these individually rather than presenting one entire design.)

When a game has as little hidden information as TM does, then whatever interface is the best way for me to view my own state is almost automatically the best way for me to view an opponent's state as well.

Here's the idea:

* There is a dividing line on the page, where all global state (map, awards, colonies, etc.) is above the line, and all player-specific state (that doesn't *live on* global state, like my ownership markers) is below the line. (Similar to playing IRL at a table.)
* In between is a row of tabs, one for each player. I'm the first tab. Tabs show who is active and who is start player.
* When I click a tab, everything below that point on the page becomes what I would see if I were that player – with cards in hand/selection/draft being hidden. (Also similar to playing IRL at a table... and sliding your chair around the table)
* Any interface that wants to show information from all opponents *together* (e.g. tag tracker) is therefore "global state" and goes somewhere above the line. (No harm in the same information also appearing redundantly as part of player state when desired.) (This bullet makes more sense if assuming something like I've shown in #1526.)

![image](https://user-images.githubusercontent.com/934551/101211678-666fdc80-362c-11eb-90f8-934e0fcbaee2.png)

The tabs can also show who is start player (in the pic: green), who has passed (red), and either whose turn it is or just which player(s) are currently being waited on (yellow).

**Comment by ssimeonoff** [comment]
This is a big "hmmm" for me. 
I really fancy the boring display of all player boards one under another - yes it takes more space, but it is so easy to get an overview.  Keep in mine I am biased towards UI favouring "the big screen".

**Comment by kevinb9n** [comment]
Ahh, I made a bit of a mistake. This issue is something we could do with or without #1526, but, the *picture* I showed is a picture of how it would look WITH #1526.

I also 100% think seeing all the player boards together is important, often. In the #1526 idea it becomes one of the tabs of global state. (Is it different from other global state?  *Kind* of, imho.)

So if this issue here is being considered *apart* from #1526, then I still agree with most of what I said, but the picture is wrong. We'd still want all the boards, and I'd suggest one could click on one of the boards themselves to switch which player's data is being shown below that line.

**Comment by kevinb9n** [comment]
@ssimeonoff To be very clear: I meant to leave the player boards OUT of this. The idea is to tab between viewing my CARDS and each opponent's cards.

**Comment by ssimeonoff** [comment]
This is also a vague statement: 
"my CARDS" - cards in hand or/and played cards?

**Comment by kevinb9n** [comment]
Right, so the three sets of cards that are hidden information are cards in hand, cards in selection, and cards in draft. These can either all stay above the tabs, or just disappear when you are looking at an opponent. 

Long-term I still like the idea of the tabbed card viewer #2001, and I think that makes things more natural; some tabs just won't be clickable when viewing an opponent. But there's been no real dialogue about any of this giant mess of interrelated ideas.

**Comment by kberg** [comment]
No Stalebot, this is still something I'm itnerested in.
