### ISSUE TITLE
Remove specific cards from the Game class.

### ISSUE THREAD

**Issue by bafolts** [bafolts/terraforming-mars#201]
The Game class currently has a few cards referenced. We should refactor these cards out of the Game class. Ideally the `Game` class will have no reference to any cards. The cards which are included are `Aphrodite` and `ArcticAlgae`. Both these cards are included because they need to have their bonus applied when the world government is terraforming.

Some quick ideas:
Having Player extend a Terraformer class or something similar we could then introduce a WorldGovernment class. This or some other mechanism would then allow us to check if the world government was applying the bonus or not and avoid needing to manually apply the bonus to cards during the world government phase.

**Comment by vincentneko** [comment]
Fixed and merged
