### ISSUE TITLE
Make a timer award for game.

### ISSUE THREAD

**Issue by ltdstudio** [bafolts/terraforming-mars#2011]
When timer #2007 released, I recommend time awards for game. like this
![time awards](https://user-images.githubusercontent.com/39257428/101233869-f2017000-36f5-11eb-9ace-40c0bdb84989.png)

**Comment by kberg** [comment]
I like the thinking, and the scrappy artwork, but I don't think we should
do it. I think it falls outside getting actual value for game-setup options.

>

**Comment by chosta** [comment]
Very controversial. We should ask in discord about the potential. 
I would probably add a -1 VP for the slowest player instead of +2VP for the fastest :)

**Comment by ltdstudio** [comment]
maybe this funtion is belong to "Fan-made" option.
