### ISSUE TITLE
Bug: Virus should be able to remove one animal

### ISSUE THREAD

**Issue by vsrisuknimit** [bafolts/terraforming-mars#2014]
In a game with @nwai90 and @ssimeonoff, we found that Virus could NOT be used on small animals which has 1 animal. Perhaps the card code is too restrictive and only tries to remove 2.

**Comment by vsrisuknimit** [comment]
I had Asteroid Deflection System. Just in case there is a bug there that protects animals instead.

**Comment by bafolts** [comment]
I can't spot this issue in source. Any idea what other cards were played?

**Comment by Lynesth** [comment]
Can reproduce either. Are you sure it wasn't Pets ?

**Comment by nwai90** [comment]
It was Small Animals. Simon had only Asteroid Deflection Systems played. Strangely I cannot reproduce the issue either, think we can close this one.
