### ISSUE TITLE
The X icon represents a *positive* integer of the player's choice

### ISSUE THREAD

**Issue by kevinb9n** [bafolts/terraforming-mars#2016]
My interpretation of this post from @Fryxen is that the X icon represents a *positive* integer of the player's choosing.
https://boardgamegeek.com/thread/1958633/article/28564463#28564463

Applies to: Insulation, Power Infrastructure, Energy Market, Hi-Tech Lab, Sulphur-Eating Bacteria, Titan Shuttles.

This raises the question of what the default value in the widget should be. I would suggest perhaps defaulting to the max, and there isn't really a strong need for a "MAX" button anymore then.

**Comment by Lynesth** [comment]
Should be fixed with latest merge.

**Comment by kevinb9n** [comment]
Fine to leave this closed, just mentioning that I'm not 100.0% sure I've guessed right about Insulation, but the answer ought to hopefully appear here at some point.
https://boardgamegeek.com/thread/2559952/questions-about-what-can-be-zero-spending-zero-etc

**Comment by kevinb9n** [comment]
confirmed, I guessed right, X is defined != 0.
