### ISSUE TITLE
Feature request: Timer repeat reminder that it's your turn

### ISSUE THREAD

**Issue by otolabqu** [bafolts/terraforming-mars#2018]
It happens quite often that a player is not aware that it's their turn and thus delays the game for minutes or more before they realise and return to play another action.

Even with the "your turn" alert sound on, it can happen for example when Pluto trading triggers from another player, or when playing a second card with a science tag, thinking you're done, but you triggered Olympus and need to discard a card to proceed. 

I could come up with more examples. The point is, I think it would be great if an optional reminder could be enabled on the frontend, such that every 1 minute (or configurable) it would alert me again for as long as it's my turn. Making this optional just like the existing alert means it won't bother anyone who doesn't want it. And I know I could use it and I know a bunch of people I played with who would use it as well.

**Comment by kevinb9n** [comment]
Could something just be gently visually pulsating or something?

**Comment by kberg** [comment]
We've since added not only a timer, but a visual cue on the browser tab. This seems safe to close. @otolabqu of course, reopen if you have something you want to add.
