### ISSUE TITLE
Help page seems like it suicided your game

### ISSUE THREAD

**Issue by kevinb9n** [bafolts/terraforming-mars#2024]
Clicked help icon.

Problem 1: it didn't open a new tab, but instead made my game go away. 

Problem 2: There was no button for returning to the game. Hit browser back button.

Problem 3: It took me all the way back to the initial card selection page for the game. I think reload would have fixed it, but it was late so I just decided I was losing anyway. :-)

**Comment by bafolts** [comment]
Looking at the heroku metrics this morning while deploying latest version something happened around 3:30 UTC which seems like it locked up the one node instance on terraforming-mars.herokuapp.com. Around 8:00 UTC it seemed to go away. Did this homicide the server? Was it during 3:30 UTC?

**Comment by kevinb9n** [comment]
This happened first on the community server after 08:00 today and then I repro'd it on the regular one just before filing this.

**Comment by bafolts** [comment]
Most likely unrelated then and may need new issue, but something suicided heroku yesterday at some point.

![image](https://user-images.githubusercontent.com/2707843/101295364-788f7d80-37da-11eb-8741-98dc537245fd.png)

**Comment by vsrisuknimit** [comment]
Can't replicate. Back button always bring the page back to the current game.

**Comment by kevinb9n** [comment]
hmmm. here's something about the back button working differently for different users/browsers:
https://github.com/bafolts/terraforming-mars/issues/1871#issuecomment-726144785

I think the best experience would be if clicking help opens a new tab in any case.

**Comment by bafolts** [comment]
Help opening in a new tab should avoid the issue we know exists and makes sense.
