### ISSUE TITLE
Corporation selection / filtering

### ISSUE THREAD

**Issue by vincentneko** [bafolts/terraforming-mars#204]
Corporation selection / filtering

I would like to add a corporation selection / exclusion widget on the create game page.

It will be optional and will allow to select / exclude the corporations you want in the corporation deck.
For instance, you could exclude Tharsis Republic, which is overpowered, on the classic board at least, in my opinion.

It will also allow to add the followig corporations that are not expansion dependant:
We can store them in a separate pool and they could be added to any game if wanted.

~~Arklight~~
~~Polyphemos~~
~~Stormcraft (Venus restricted)~~
~~Lakefront Resorts~~
~~Pristar~~
~~Terralabs Research~~
~~Utopia Invest~~
~~Factorum~~
~~Mons Insurance~~
~~Philares~~
~~Arcadian Communities~~
~~Recyclon~~
~~Splice Tactical Genomics~~

**Comment by alrusdi** [comment]
Great idea. May be it is the time to make Game Start page more compact? And easier to setup solo game?

**Comment by vincentneko** [comment]
I agree with a more compact game setup page.
Now that we have some options, maybe it's better to move them up and then player names below ?

About corporation selection / filtering, I've created 3 enums that hold Corporation names (currently in cardCostRework branch)

OriginalCorporation
PreludeCorporation
VenusCorporation

I guess these could be used for selection / filtering.

**Comment by vincentneko** [comment]
Yes good idea too !

**Comment by alrusdi** [comment]
@vincentneko can you please describe of how it should look like. All ideas that i have seems to be unusable.

**Comment by vincentneko** [comment]
@alrusdi 
I've set a first draft of corporation selection. It's on selectCorpsWidget branch.
It's working but it lacks a lot of polish.
I've also added Polyphemos corporation.

I think I've messed with objects as the corporations sent by the game creation screen are not full corporations objects, they lack the functions. 

Therefore I needed to add this to re-instanciate a corporation object, I'm sure there is a better way.

```
      for (let corporation of [...ALL_CORPORATION_CARDS, ...ALL_PRELUDE_CORPORATIONS, ...ALL_VENUS_CORPORATIONS, ...ALL_COLONIES_CORPORATIONS]) {
        if (corporation.name === corporationCard.name) {
          corporationCard = corporation;
        }
      }
```

**Comment by vincentneko** [comment]
I've added Utopia Invest as well.
@alrusdi there is something strange when I set checkbox class to nes-checkbox, the checkboxes are not modifiable anymore. Do you have an idea of what is happening ?

**Comment by alrusdi** [comment]
@vincentneko i think it's required to wrap both span and input elements into label tag like this:
`                    <label>
                        <input type="checkbox" class="nes-checkbox" v-model="corporations" :value="corporation"/>
                        <span>{{corporation.name}}<span>
                    </label>`

**Comment by bafolts** [comment]
> @alrusdi
> I've set a first draft of corporation selection. It's on selectCorpsWidget branch.
> It's working but it lacks a lot of polish.
> I've also added Polyphemos corporation.
> 
> I think I've messed with objects as the corporations sent by the game creation screen are not full corporations objects, they lack the functions.
> 
> Therefore I needed to add this to re-instanciate a corporation object, I'm sure there is a better way.
> 
> ```
>       for (let corporation of [...ALL_CORPORATION_CARDS, ...ALL_PRELUDE_CORPORATIONS, ...ALL_VENUS_CORPORATIONS, ...ALL_COLONIES_CORPORATIONS]) {
>         if (corporation.name === corporationCard.name) {
>           corporationCard = corporation;
>         }
>       }
> ```

The selected corporation card must not be getting passed in. We should map the corporation name string to the corporation card when reading the form value. Then we can remove this unnecessary block. I can find where that would be and put the commit in. This is the only part of this pull request which stands out to me.

**Comment by vincentneko** [comment]
> @vincentneko i think it's required to wrap both span and input elements into label tag like this:
> 
> ```
> <label>
>     <input type="checkbox" class="nes-checkbox" v-model="corporations" :value="corporation"/>
>     <span>{{corporation.name}}<span>
> </label>
> ```

Yes that fixed it ! Thanks a lot !

**Comment by vincentneko** [comment]
> > @alrusdi
> > I've set a first draft of corporation selection. It's on selectCorpsWidget branch.
> > It's working but it lacks a lot of polish.
> > I've also added Polyphemos corporation.
> > I think I've messed with objects as the corporations sent by the game creation screen are not full corporations objects, they lack the functions.
> > Therefore I needed to add this to re-instanciate a corporation object, I'm sure there is a better way.
> > ```
> >       for (let corporation of [...ALL_CORPORATION_CARDS, ...ALL_PRELUDE_CORPORATIONS, ...ALL_VENUS_CORPORATIONS, ...ALL_COLONIES_CORPORATIONS]) {
> >         if (corporation.name === corporationCard.name) {
> >           corporationCard = corporation;
> >         }
> >       }
> > ```
> 
> The selected corporation card must not be getting passed in. We should map the corporation name string to the corporation card when reading the form value. Then we can remove this unnecessary block. I can find where that would be and put the commit in. This is the only part of this pull request which stands out to me.

I think it's in Game.ts, here :

```
      // Setup custom corporation list
      if (this.customCorporationsList && this.corporationList.length >= players.length * 2) {
        corporationCards = this.dealer.shuffleCards(this.corporationList);
      }
```

So should we filter all corporations with this list ?

**Comment by vincentneko** [comment]
I've pushed a fix, please let me know if it's ok for you.

**Comment by vincentneko** [comment]
All done !
@bafolts , thanks for the guidelines for Philares
