### ISSUE TITLE
I think Rotator Impacts should be playable in this situation

### ISSUE THREAD

**Issue by kevinb9n** [bafolts/terraforming-mars#2040]
![image](https://user-images.githubusercontent.com/934551/101322458-e9a35500-381b-11eb-8ad4-c4cfcc828c39.png)

See the card, see the Venus %, see the requirement, see my corp, see its cost, see my bank account... I can't come up with a valid reason for it to not let me play this card.

**Comment by nwai90** [comment]
@kevinb9n Venus is at 18%. The card can only be played with max 14% Venus. Rotator impacts is not a Venus card (no Venus tag)

**Comment by kevinb9n** [comment]
I don't think Morning Star requires a Venus tag.

I think `game` is meant to say `game, true` [here](https://github.com/bafolts/terraforming-mars/blob/main/src/cards/venusNext/RotatorImpacts.ts#L24)?

```
return game.getVenusScaleLevel() - (2 * player.getRequirementsBonus(game)) <= 14;
```

**Comment by nwai90** [comment]
Ah yes, good catch! Will update
