### ISSUE TITLE
parameterized map generator

### ISSUE THREAD

**Issue by kevinb9n** [bafolts/terraforming-mars#2048]
Could be a fun project: design a parameterized random map generator to achieve certain metrics in the resulting maps.

The basic parameters would govern how many of a certain tile attribute are present in total (whether exact value or rough target). The next level would be self-affinity or "clumpiness": how likely is an ocean space to be near other ocean spaces; a plant bonus icon to be near other plant bonus icons, etc. A single self-affinity target covering all space attributes would be a start. A full randomization of any set of tiles should score quite near 0 on any affinity metric, but obviously this is what the published maps do have.

You can get fancy with pairwise affinities (plants tend to be near oceans), anti-affinities, and affinities with the board edge.

I'm not suggesting that the game creation interface actually expose all these parameters directly to the user, but values could be chosen in line with the official maps.

**Comment by kevinb9n** [comment]
There is some support, but desire that the current behavior be preserved too.

![image](https://user-images.githubusercontent.com/934551/101837960-b5b68100-3af4-11eb-8186-52537750cef7.png)

**Comment by Ronnoc** [comment]
origin shuffle board example
![origin_1](https://user-images.githubusercontent.com/5140023/101981660-7d0bd880-3ca9-11eb-9a7c-255d6e02c642.png)
![origin_2](https://user-images.githubusercontent.com/5140023/101981661-8006c900-3ca9-11eb-8123-10da9f3cf90b.png)
![origin_3](https://user-images.githubusercontent.com/5140023/101981663-809f5f80-3ca9-11eb-8844-2401bd2ecac4.png)

**Comment by Ronnoc** [comment]
One plan to make ocean closer
![after_1](https://user-images.githubusercontent.com/5140023/101981697-b7757580-3ca9-11eb-872b-3d4721585fec.png)
![after_2](https://user-images.githubusercontent.com/5140023/101981699-b9d7cf80-3ca9-11eb-8db8-37bd858822c4.png)
![after_3](https://user-images.githubusercontent.com/5140023/101981700-bb08fc80-3ca9-11eb-9d8f-5d642bf85074.png)

**Comment by kevinb9n** [comment]
It just hit me that now we'll have

- randomize milestones, with a suboption for less synergy
- randomize map spaces, with a suboption for MORE synergy :-)

This is exciting!
