### ISSUE TITLE
Feature request: a button to hide tiles

### ISSUE THREAD

**Issue by vsrisuknimit** [bafolts/terraforming-mars#2050]
A button next to the main game board. Once toggle, it makes all tiles 25% opacity so that users can look at what are underneath.

**Comment by kevinb9n** [comment]
Occasionally needed (where do I want that dry desert?), and seems like a good UI for doing it. I can't think of a way to not need that button that would still both work for mobile and be discoverable.

**Comment by kevinb9n** [comment]
From @vsrisuknimit in discord:

It is being discussed. Nothing might be done.

Options that are being considered:
1) tie 50% opacity on mouse hover
2) a button next to the board
3) a toggle in preferences.

For (1) we don't like hover effect. It does not work well for mobile. (2) too much to add a button next to the main board if it will be rarely used, (3) a lot of clicks. need to adjust it back afterward

**Comment by CactusFantastico** [comment]
It wouldn’t be utilized often, but when you need it you’d wish it was there. I guess that makes it low on the priority features list, but I don’t see any downsides to having a toggle.

**Comment by kberg** [comment]
Would you be satisfied with a copy of the map for easy access?

**Comment by kevinb9n** [comment]
Yeah, I would say that as long as there is *some* way to find out what the map area underneath looks like then this is basically resolved.
