### ISSUE TITLE
Issues with TR boost

### ISSUE THREAD

**Issue by kevinb9n** [bafolts/terraforming-mars#2051]
First, I think a handicapping convention is a *very* good thing for a gaming community to have, and I would love to see it normalized and popularized here in time, as it is for golf, go, and many other games.

And I'm content with TR adjustment as a decent way to do it. Anything else I can think of seems less effective or more invasive.

Asks:

1. Can we please (please) stop labeling it as a "beginner option"? I want it to be a respectable option for any skill differential at any level. (Plus, it's fair play if you want a shortened game to just give all players the same boost. Beginners or not.)

2. Can we allow the values to be negative? Then, you can handicap with or without speeding up the game. (If not, then FYI, it is currently just ignoring such values rather than rejecting them.)

3. It's a relatively non-invasive tweak but it corrupts the game in a few ways (Benefactor, Reds bonus, a few global events). But the worst way by far (basically a deal-breaker for Turmoil games) is the Terraformer milestone. Still, if using Tharsis with no randomization, you can just price that knowledge in – even in the presence of Turmoil. The problem is more when you don't know whether it will be in. So, my request is: when M&A randomization is on, and any player has any TR adjustment, then just remove the Terraformer milestone from the pool. (I would rather not go so far as try to band-aid the milestone like is done for Generalist in non-CorpEra games.)

**Comment by kberg** [comment]
These seem like good requests. I agree that removing handicap from beginner
options makes sense. I would even go so far as to call them "advanced"
options.
