### ISSUE TITLE
Cards played counter is off-by-one

### ISSUE THREAD

**Issue by kevinb9n** [bafolts/terraforming-mars#2058]
Sorry but I mean it is. :-) 

![Untitled drawing (25)](https://user-images.githubusercontent.com/934551/101455868-102ec200-38e8-11eb-957d-dd3cd9725ac1.png)

**Comment by bafolts** [comment]
This count isn't including the corporation card. This count is only project cards which have been played. Fix should be as simple as adding 1 on server if the corporation card has been played.

**Comment by kevinb9n** [comment]
Thanks – I remember there was a time recently when the interface shifted from the corp just sort of ambiently existing, to it being explicitly played, and I also see there's a count in the "played cards" heading lower down which is accurate. Also, I've found that new players get less confused about the rules once they start thinking of preludes and corps as just regular cards. So, I do think it would be ideal to change this.

**Comment by ssimeonoff** [comment]
Can the counter actually exclude the preludes as well?

**Comment by kevinb9n** [comment]
I'll note we do have the freedom to define this number any way we want. These are all reasonable options:

* project cards played
* project and prelude cards played (current behavior)
* all cards played
* ... those 3 options again but "in play" rather than "played"

I can't think of any decision I might be trying to make where one of those six metrics is the exact useful thing (aside from that one award, where I'm just going to look at the award tracker anyway). There doesn't strictly need to be a number there at all.

Probably the main work it's doing is just to serve as some summary statistic of that portion of the player's open state that's hidden by default in the UI. One useful property is if it always changes whenever the hidden state it represents changes; then you don't have times when it looks every bit like nothing is happening though it is. Ignoring that we don't have actions-left and resources-on-cards trackers, it can at least represent all the rest. But this is a pretty academic point, because game log. Still, "I know how many things I'm going to see when I click Show" is at least *something* with some meaning.

I will claim there's *nothing* special about corporation vs. prelude vs. project cards except just the circumstances of how/when you get/play them (and a handful of conventions). Once played, the difference is already irrelevant (except that – and this is the exception that proves the rule – Tycoon and Magnate just won't count them ).

**Comment by bafolts** [comment]
> I will claim there's nothing special about corporation vs. prelude vs. project cards except just the circumstances of how/when you get/play them (and a handful of conventions). Once played, the difference is already irrelevant (except that – and this is the exception that proves the rule – Tycoon and Magnate just won't count them ).

As a beginner player myself this change makes sense to me. I always separated corporation card as a separate deal but there really is no difference from that or any other played card. I will update this to include corporation card count as well as what we already display today.
