### ISSUE TITLE
Polish version

### ISSUE THREAD

**Issue by Haas888** [bafolts/terraforming-mars#2060]
Hello,
I have zero experience in github/programming, but I love the game and I would like to contribute by helping with translations to prepare a polish version.

**Comment by vsrisuknimit** [comment]
@Haas888 check out the locales folder (
https://github.com/bafolts/terraforming-mars/tree/main/src/locales). I believe the Chinese/Russian ones are pretty complete in terms of translation. You can use those files as a template, and start translating the output text to Polish. When you are done, let us know and the translation files can be integrated to the main repo.

**Comment by bafolts** [comment]
@Haas888 not sure what your extent of github or programming knowledge is but at a minimum will need to understand these JSON files.

https://github.com/bafolts/terraforming-mars/blob/main/src/locales/de/cards.json

Will need a `cards.json` for polish as well as the other json files in that directory. In this files the english value is the left side value and the translation value is on the right side. If you provide equivalents for polish someone can commit them to the repository for you.
