### ISSUE TITLE
"node build/server.js" can't find module "terraforming-mars\build\server.js

### ISSUE THREAD

**Issue by JeremyDietrich** [bafolts/terraforming-mars#2062]
Hi there, I don't know much about how the files and stuff are supposed to work, but last time I downloaded this I followed the simple directions and it worked perfectly. I decided I wanted to get the newest stuff so I deleted my terraforming-mars directory for a fresh set of files, but now when I run the simple directions it breaks on "npm start" with the error message below. Any ideas what to do? Thanks, and sorry for the unhelpful comment!

> terraforming-mars@1.0.0 start C:\Users\me\terraforming-mars
> node build/server.js

internal/modules/cjs/loader.js:969
  throw err;
  ^

Error: Cannot find module 'C:\Users\me\terraforming-mars\build\server.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)
    at Function.Module._load (internal/modules/cjs/loader.js:842:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []

**Comment by kberg** [comment]
Just a guess: did you run npm install?

**Comment by JeremyDietrich** [comment]
Yes, I ran git clone, npm install, npm start. The npm install had a couple of warnings that some optional dependencies were skipped, but no errors or vulnerabilities

**Comment by bafolts** [comment]
You need to run `npm run build` now prior to `npm start`.

**Comment by bafolts** [comment]
Instructions from README.md

https://github.com/bafolts/terraforming-mars#windows-or-linux-game-server-running

**Comment by JeremyDietrich** [comment]
Ahhh, thanks, right missed that at the beginning. But now it says "cannot find module 'dotenv' "

**Comment by JeremyDietrich** [comment]
OK I forgot to run "npm install" first this time, sorry about that. Re-trying now

**Comment by JeremyDietrich** [comment]
Now there are almost 70k errors that seem to be linebreak-style errors...

**Comment by bafolts** [comment]
Can you post what some of them are? I am not sure how many people build on windows machines. Nothing is OS specific as far as I know so this should build on any OS running node. Could be forgetting something though.

**Comment by JeremyDietrich** [comment]
Every single one as far back as I can scroll is "error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style". And it built fine on Windows one or two months ago, when I last updated it

**Comment by bafolts** [comment]
Your windows git is converting LF to the windows CRLF. A linting rule was added that is checking for LF. When checking out with git windows users will need to keep the LF and not introduce CRLF. Seems we may be able to automate this with a configuration file on the repository.

https://www.edwardthomson.com/blog/git_for_windows_line_endings.html

**Comment by JeremyDietrich** [comment]
Ahh OK, so I need to change the setup for my windows git. Thanks!
