### ISSUE TITLE
[Bug] Playwrights removes wrong card

### ISSUE THREAD

**Issue by ap3h3ad** [bafolts/terraforming-mars#2077]
Hi,

we're playing with the Community addon the first time and just encountered a bug with one of the new corporations, Playwrights:

The corporation allows a player to replay any event that any of the players (including himself) played until then. This led to the following situation:

https://abload.de/img/bugplaywrightsrnjtb.png

I played Law Suit on the player with the Playwrights corporation and place the card on his discard pile. Then he uses this corporation to also play Law Suit on my discard pile. Now the corporation obviously just removes the topmost card on HIS discard pile, but this is not Law Suit but another card (in this case as Small Asteroid which the player planned to play at another time).

I guess the corporation mechanism needs to be changed to handle this kind of cards that doesn't go on the own discard pile.

**Comment by KoljaHartmann** [comment]
I want to add that i personally think law suit should not be placed in the discard pile of the targeted player, if it was played a second time by playwrights. Obviously this is a matter of interpretation, since playwrights is just a communitiy addition. But the way it behaves now, palywrights can play law suit over and over again, which does not sound as it would be intended.

**Comment by kevinb9n** [comment]
Re: interpretation, I think the intended behavior seems well-defined enough: the Playwrights action takes and plays Law Suit, Law Suit puts itself in the events pile of the attacked player, then the Playwrights action takes it from wherever it is out of the game.

**Comment by nwai90** [comment]
@ap3h3ad It has been fixed a few days ago. Are you playing on your own server?

https://github.com/bafolts/terraforming-mars/pull/2037

**Comment by ap3h3ad** [comment]
Hi,
yes, we are playing on my own server. I'll do the update asap, thanks!
