### ISSUE TITLE
More space-look-alike design

### ISSUE THREAD

**Issue by alrusdi** [bafolts/terraforming-mars#208]
I've slightly changed colors and added thematic background for all pages.
Is it better than current version?
![black_design](https://user-images.githubusercontent.com/394311/72518680-aba1e900-3877-11ea-9785-4e50eef4371a.png)

**Comment by vincentneko** [comment]
I'm not a big fan of white text and black background, I think it's more difficult to read and is less eye friendly. Is it easy to switch with an preference option ?

**Comment by alrusdi** [comment]
Unfortunately it's not. Okay, then we will stick to previous black-on-white variant

**Comment by vincentneko** [comment]
It's just my opinion, we should wait for bafolts feedback.

**Comment by bafolts** [comment]
The current white background and black text is only due to that being the default colors when no styling is provided and wasn't by any design on my side. For what its worth I think the white text on black looks better. I don't know anything about design though.

**Comment by vincentneko** [comment]
If both of you prefer the white text on black layout we should implement it.

**Comment by dabewi** [comment]
I think there are several options between "black on white" and "white on black". What about some complementary colors like #FF851B on #001f3f?

**Comment by alrusdi** [comment]
I've finished compromise variant
![new_visuals](https://user-images.githubusercontent.com/394311/74541638-cabd9480-4f63-11ea-920a-ab36801f659a.png)

**Comment by alrusdi** [comment]
Merged
