### ISSUE TITLE
Heroku site crashed 2020-12-11....out of javascript heap memory.

### ISSUE THREAD

**Issue by bafolts** [bafolts/terraforming-mars#2081]
Over the past few weeks I have slowly seen the javascript memory climb. Most likely increased traffic reaching the site. Today the demo site tripped the limit and the node process crashed with an error that it was out of heap memory. Will need strategies to decrease memory usage.

**Comment by chosta** [comment]
We've seen an increase of new players in discord. Although we try to
encourage using self hosted instances the newcomers try the demo first. I'm
thinking of encouraging the discord users to use alternative servers. We
have a couple that are running at the moment. I'll also put one of my own
in the next couple of days.

**Comment by bafolts** [comment]
I am going to introduce a caching solution to avoid having to always load every game into javascript memory upon start-up. I will close this issue with that pull request. Encouraging users to host their own is also good. This fix should help any server running in case those also get increased traffic.
