### ISSUE TITLE
Cards bugs

### ISSUE THREAD

**Issue by sienmich** [bafolts/terraforming-mars#2082]
Hi, two small bugs (@chosta?):
No minus sign near the heat and no text info about the placement (next to your tiles). Also the asterix char would be nice imo.
![Screenshot from 2020-12-11 23-23-40](https://user-images.githubusercontent.com/19472604/101960551-f7841c00-3c07-11eb-80d8-fb440741478b.png)
![Screenshot from 2020-12-11 23-21-23](https://user-images.githubusercontent.com/19472604/101960553-f81cb280-3c07-11eb-956d-e5023e15f53a.png)

**Comment by chosta** [comment]
Thanks for reporting, will fix in an upcoming PR.
