### ISSUE TITLE
Restricted Area tile in end game screen

### ISSUE THREAD

**Issue by sienmich** [bafolts/terraforming-mars#2083]
![Screenshot from 2020-12-12 01-07-34](https://user-images.githubusercontent.com/19472604/101965906-8f890200-3c16-11eb-847f-e5dbfa71b26a.png)
All Ares tiles in end game screen have that yellow frame, the Restricted Area has not.

**Comment by vsrisuknimit** [comment]
@kberg

**Comment by kberg** [comment]
I'm finally getting to this. This is weird. OK, I'll take a look.
