### ISSUE TITLE
What is a Route?

### ISSUE THREAD

**Issue by kberg** [bafolts/terraforming-mars#2088]
@bafolts I'm reading the code in src/routes/Routes.ts. What is a Route?

**Comment by kberg** [comment]
Why is it Subclassed for GameLogs but not subclassed in server.ts?

**Comment by bafolts** [comment]
Software entropy. The changing software has led to unmet objectives. Envisioned every API route heading this way. The usage here was intended to be an API route. Ideally something like `GET /assets/` would be in an `AssetRouter`.

**Comment by kberg** [comment]
Gotcha. I started to build on that idea yesterday, and backed off because 1) push only one boulder at a time, and 2) why not expressjs or something similar?

**Comment by bafolts** [comment]
expressjs might make sense at this point. I have no strong feeling against using expressjs. When I started this project I had a co-worker who was adamant that every javascript project quickly ends up with a ridiculous amount of javascript dependencies and a `node_modules` directory over 500mb. Besides typescript my original intentions were to take on no other dependencies and see how far I could take it. That being said, the heroku instances take the size of the `node_modules` directory into account when considering how much total memory a dyno is using. If we were to add expressjs would need to make sure it didn't increase the `node_modules` size by too much as this is memory we will lose that we could give to javascript. I am not sure we need all of the functionality that expressjs would provide but it could help contributors who may only be familiar with expressjs and not with using the node `http` module directly.
