### ISSUE TITLE
Bug: Planner count should be hidden until the game starts

### ISSUE THREAD

**Issue by vsrisuknimit** [bafolts/terraforming-mars#2090]
![image](https://user-images.githubusercontent.com/14239220/101983325-5ff2ed80-3c48-11eb-8dbc-27b9ad1a5bfe.png)

You can see how many cards players keep under Planner. This might influence players who have not picked from going for or against planners.

This count should be hidden until the game starts.

**Comment by kevinb9n** [comment]
Consider just not having the trackers present underneath the Ms/As on this screen at all.

**Comment by Lynesth** [comment]
Linked to #1681.
