### ISSUE TITLE
Vue compile checker

### ISSUE THREAD

**Issue by sienmich** [bafolts/terraforming-mars#2097]
While trying to fix my timers (#2007) after merging to master I have a problem.
`compile-vue-templates.js` should compile my template, but it crashes.

My orginal `PlayerTimer.ts` template looks like this:
```
import Vue from 'vue';
import {Timer} from '../../Timer';

export const PlayerTimer = Vue.component('player-timer', {
  props: {
    timer: {
      type: Object as () => Timer,
    },
  },
  data() {
    return {
      timer_text: '',
    };
  },
  mounted() {
    this.updateTimer();
  },
  watch: {
    timer_text: {
      handler() {
        setTimeout(() => {
          this.updateTimer();
        }, 1000);
      },
    },
  },
  methods: {
    updateTimer: function() {
      this.timer_text = Timer.fromJSON(this.timer).toString();
    },
  },
  template: `<div class="player-timer" > {{timer_text}} </div>`,
});
```

`compile-vue-templates.js` generates this checker:
```
checker: function() { const timer = this.timer;
const updateTimer = this.updateTimer;
return _c('div', {
    staticClass: "player-timer"
}, [_v(" " + _s(timer_text) + " ")]) },
    updateTimer: function() {
      this.timer_text = Timer.fromJSON(this.timer).toString();
    },
  },
```
But in `..._s(timer_text)...` there is an error: `TS2304: Cannot find name 'timer_text'.`
What should I do? I guess the `data` parameter is the problem here (other templates don't use it), but it's quite handy in timer.
Deleting whole checker resolves the problem.

**Comment by sienmich** [comment]
Ok, i'm stupid, there is a `data` parameter in `checkComponent` :)

**Comment by bafolts** [comment]
Manually add the data property when adding the file to the compile vue
templates script.
