### ISSUE TITLE
Please consider adding Turmoil ruling bonus to log

### ISSUE THREAD

**Issue by Jay-Spencer** [bafolts/terraforming-mars#2103]
The running log of game events is helpful, particularly as I am learning the site and the interface. It would make sense to me to include the Turmoil ruling bonus effects in the log as well. Thanks for considering.

**Comment by Jay-Spencer** [comment]
It could look like this:
Player A gained 10 mc from Scientist ruling policy.
Player B gained 5 mc from Scientist ruling policy.

**Comment by kevinb9n** [comment]
FYI, #1976 is one of a few issues trying to capture a longer-term plan which should at last lift users' heavy burden of having to report all these hundreds of individual case-by-case bugs (I'm thankful, Jay).

**Comment by Lynesth** [comment]
Duplicate of #1797
