### ISSUE TITLE
Please consider carefully before adding a "sudden-death" timer

### ISSUE THREAD

**Issue by kevinb9n** [bafolts/terraforming-mars#2108]
No one should ever file a bug this long. If you don't want to read, I don't blame you.

Soon (#2007) we'll have informational count-up timers per player. Tick tick while it wants a decision from you, and pauses once it gets that decision and starts waiting only on your opponents. Hooray! Sunlight being the best disinfectant and all that.

I'd personally be glad if the clock stopped there, but I know that conversations *will* immediately follow all over the place about hey let's make it count down instead, and with what consequences.

And I've heard the idea jump all the way to the most severe consequences: you zero out, you're out of the game, you lose. (What that means for 3+-player games in particular isn't the point I'll be dealing with, so let's just assume 2p games for simplicity here.)

I'm concerned.

**This is not about begging you not to do a thing.** It's about begging you not to do it without fully considering the alternatives, and being willing to talk about whether some of the options have some risk of harm to the community.

This project really should not do waterfall design, and should rather just do simple things and throw them out there and see what works. But a feature like a sudden-death timer is a little different from most. Of course, any time you are creating a way in which some users will have an intensely negative experience, that's always be something to be careful about. Moreover, this kind of feature can end up affecting the culture and inclusiveness of the community we're trying to build. I think these reasons should be enough to take it a little seriously and try to design something we think will be right.

(When I say "intensely negative experience", realize that it is not just the losing, and it's not the game being taken away, but also the miserable experience of trying desperately to get out of time peril for those last however many minutes.)

I need to address the idea that "it's just an option, people who don't like it won't use it." I think this is a very good mindset for us to have – when thinking about *solo games*. It also works for the subset of multiplayer games in which all the players happen to want the same thing. In the rest, you know how it works: the dominant players, by number or personality, will get what they want.

So, creating an option means also considering the experience of the player who really did not want that option. Sure, you can't always get what you want. But when we say things like "it's just an option, people can just not use it", as if it's that simple, that's an explicit stance against inclusiveness.

And please be aware that there really are people in this world, who are fine people and love games, but who simply *cannot* play with a timer. Maybe they have a recognized disability, or maybe they don't, but either way, those brain circuits *you* have, that let you respond to ticking danger by focusing and working a little harder to speed things up – they just do not have that same wiring. Be proud you have it, and all, but they don't. I would ask you to please understand that this is not because they are snowflakes, immature, dumb, crazy, etc. You got cool brain circuits that they didn't. Go you.

I know this will get blowback, whether that blowback appears in black and white below or not. Come on, you will say, just because some people can't use something means we can't have it either? So AGAIN, I want to stress that all I am asking for is a proper consideration of the alternatives and their trade-offs. Why does it *have* to be the most severe consequence? Is it really true that if they were just fined a half a victory point to get a few minutes back on their timer (just a random example) that that couldn't possibly work? There are going to be many possibilities here.

Sometimes this community will make decisions that end up excluding people, sometimes even people I care about. I just think it would be sad if the *reason* that happened was just because it was the easy thing to do in the moment and no one wanted to talk about it. I did try first to talk directly with the dev who suggested he wanted to do this, but he plainly refused the conversation multiple times, even insisting, "I just don't think there's much to discuss."

Given the insane length of this post I thought that would end things on a spot of humor.

**Comment by kevinb9n** [comment]
Just realized it's not clear under what circumstances this bug could be closed. Sorry, don't wanna pollute.

I'd be happy just to know that this was read and understood by a couple devs who will be making these decisions, that's all.  You could close it if you could say that. (I mean, you can close it for any reason, of course, it's your bug database.)

You might do the thing I don't want anyway, but it's okay, it would mean a lot to me just to be heard.

**Comment by chosta** [comment]
At least one dev did read your post :)
I have a short answer though. The timers will be optional. They will also
be marked as experimental. Anything that the players dislike could be
removed or changed/improved based on feedback. The project does care about
all kinds of players - newbies, pros, casuals and competitive players. The
feedback is crucial, so keep it coming.

**Comment by Lynesth** [comment]
I was pretty sure I answered that post yesterday, probably didn't hit `comment`, sorry about that.
A bit lazy to retype everything so a simple summary would be that:
- From the people who wish to have a countdown, no one proposed a "sudden death" at the end.
- Even if it goes in, it would be behind an option so that people can choose to play with or not.

I'll add that there's a draft of a proper countdown timer going on (made with the help of @kyshantry) that will be proposed at a later date.

**Comment by kevinb9n** [comment]
> * From the people who wish to have a countdown, no one proposed a "sudden death" at the end.

That probably makes the intensity of my post quite confusing. :-) All that I knew, from an offline conversation, is that there is one dev who very much wants it to be that way, but was adamant against talking about it. So I just said I would lay out all my concerns in an issue for everyone else to read, and he said that was a good idea.


> * Even if it goes in, it would be behind an option so that people can choose to play with or not.

My feelings on that exact sentiment are hidden in the middle of my wall of text and again I can't blame anyone for missing it. :-)
I worded the end of it a bit too strongly.

"I think this is a very good mindset for us to have – when thinking about solo games. It also works for the subset of multiplayer games in which all the players happen to want the same thing. In the rest, you know how it works: the dominant players, by number or personality, will get what they want.

So, creating an option means also considering the experience of the player who really did not want that option. Sure, you can't always get what you want. But when we say things like 'it's just an option, people can just not use it', as if it's that simple, that's an explicit stance against inclusiveness."

Thanks SO much for hearing me out.

**Comment by kevinb9n** [comment]
Ah, I did say this would be closeable if I felt the concerns were heard.
