### ISSUE TITLE
Some cards render 

### ISSUE THREAD

**Issue by joange** [bafolts/terraforming-mars#2117]
When playing on my old iPad the text of some cards is not displayed properly. I've tried Safari and Chrome and the problem persists in both.

It could be the iOS version (10.3.3.), but I think that the app didn't depend on system libraries.

![IMG_1996](https://user-images.githubusercontent.com/17407457/102103644-8920a300-3e2d-11eb-9e3f-8aec02c64f8e.PNG)

**Comment by chosta** [comment]
Is it possible to check the console for errors?
Also, try clearing the cache.

**Comment by bafolts** [comment]
What version of chrome is running on this device? Best I can tell iOS 10.3.3 is from between 2016 and 2017. FAIK there is some minimum version of chrome needed to run this application. Can make no promises as to how this runs on older versions of chrome. Do you see this on most recent version of chrome? As we are a small operation can only ensure this is going to work on recent versions of chromium or safari.

**Comment by joange** [comment]
Hi, Don't mind about this problem ;)

Chrome version is 71.3578.89, running on iPad 2 with iOS 10.3.3. I can't update to any new version of chrome, due to it requires iOS 11 at least. But the mystery is "Why some cards render correctly and some no"???

**Comment by kberg** [comment]
This is probably something we're just not going to be able to fix.  Feel free to reopen if you have new information.
