### ISSUE TITLE
Input Error with Robinson Industries

### ISSUE THREAD

**Issue by dabewi** [bafolts/terraforming-mars#212]
Hi,

I played against an colleague and he chose Robinson Industries. In turn 3 oder 4 of generation 1 he wanted to use the special ability stated on the corporation card (that one that let's you increase your lowest production) and chose to make an action from a played card. The game correctly displayed his corporation card, but after clicking on "Save" there was an error message stating an input error. From there on he couldn't play any project card and after he ended his turn the game stuck (the known bug that on both player screens is displayed that it is not their turn).

Maybe it's just the corporation card that is bugged or both of us don't know how to play an action from an corporation card correctly.

**Comment by vincentneko** [comment]
Hi,
Thanks for the feedback.
I selected Robinson Industries from the corporation list (with another so the game will have 2 corporations to offer you to choose)
I was not able to reproduce the issue.
Do you remember any detail that could help to reproduce it ?

**Comment by dabewi** [comment]
Hi,

thanks for your effort. I also tried to reproduce the issue, but I couldn't. Maybe there were several strange things going on at the same time. I'll revive this issue if it becomes actual again.

Cheers!

**Comment by alrusdi** [comment]
@dabewi screenshot of the buggy situation may be helpful in this case, because we need to know player's production values at the time. Do you have an url of this game? I mean url that you sent to your colleague after game creation

**Comment by dabewi** [comment]
@alrusdi 

Yes, the URL for the colleague was https://terraforming-mars.herokuapp.com/player?id=2995051c0bb5

Greetings

**Comment by alrusdi** [comment]
Unfortunately it is already expired... Please make a screenshot next time. It will give us more info to catch a bug.

**Comment by bafolts** [comment]
Given the timing I may be able to access the heroku logs and see if anything was logged to the console.

**Comment by bafolts** [comment]
Heroku logs don't seem to give me access to logs that old. If this player never was given the screen to even select their corporation that is perplexing. It reads like they only selected that they wanted to play the action from robinson corporation and then had the error. Nothing stands out that would have thrown an error within the robinson industries action function. If the function did have a runtime exception it would have crashed the node process which then would have led to the node process restarting and any input from the old game leading to a 404 response and error message.
