### ISSUE TITLE
Turmoil corporations from Community expansion are getting displayed without Turmoil in game

### ISSUE THREAD

**Issue by ap3h3ad** [bafolts/terraforming-mars#2128]
Hi,

we're playing with the community expansion and have noticed that Incite (one of the corporations from Community: https://www.notion.so/8c85a57488854ff7a124518e82b83548?v=b0af622e91804a729cfa5b5f77a2cbfe) is displayed in the beginning so that a player can actually choose this corporation regardless of if the Turmoil expansion is even active. That seems rather odd because if effectively decreases the amount of corporations a player can choose from (because a corporation like Incite doesn't make sense to choose without Turmoil in the game).

**Comment by nwai90** [comment]
@ap3h3ad I see, will fix. Thanks for reporting!

**Comment by ap3h3ad** [comment]
May be obvious, but the same goes for Colonial One and Eris.

Thanks for fixing it!
