### ISSUE TITLE
Solar farm iconography

### ISSUE THREAD

**Issue by sienmich** [bafolts/terraforming-mars#2134]
Currently looks like this:
![Screenshot from 2020-12-17 15-51-14](https://user-images.githubusercontent.com/19472604/102503969-8f5a8d80-4080-11eb-87bd-a417964039df.png)
It's bad, because it's about plants resources not tags.
But how should it look like?

1. ![Screenshot from 2020-12-17 15-50-43](https://user-images.githubusercontent.com/19472604/102503971-8f5a8d80-4080-11eb-8ca9-0807e0e3d502.png)
2. ![Screenshot from 2020-12-17 15-53-39](https://user-images.githubusercontent.com/19472604/102503967-8ec1f700-4080-11eb-9584-e9128d9c3f2f.png)
3. ![Screenshot from 2020-12-17 15-56-28](https://user-images.githubusercontent.com/19472604/102503964-8e296080-4080-11eb-8738-41927e40b405.png)

The 1. Looks too much like it involves plants production imo. 2 is great. 3. is kinda clever, nah?
Which one should it be? I can make PR.
Summon @chosta

**Comment by chosta** [comment]
You can haz PR :)
I think @Lynesth also had a comment about the Solar farm Tile icon and the way it represented energy.
2 is just fine
3 might be confusing

**Comment by kberg** [comment]
Preference order 1, 2, 3. I defer to Dani.

>

**Comment by kevinb9n** [comment]
It would be nice to try sticking with TM's (kinda weird) "greedily expanding production boxes" convention (and thus not 2 or 3), but part of how it works is that being surrounded doesn't change the meaning of almost any symbol in the game *except* the six standard resources and the unspecified-resource icon. So I think 1 doesn't work.

If you want a 4... sure, it's still a kinda inexplicable, but so much in the game is.

<img width=300 src="https://user-images.githubusercontent.com/934551/102511470-ac21a180-403d-11eb-9085-ecbe07943b35.png" alt="another option">

**Comment by chosta** [comment]
@sienmich we can try @kevinb9n's suggestion
`emptyTile().secondaryTag(Tags.PLANTS) maybe?`
let's see how it looks like

**Comment by SliceOfBread** [comment]
I think it should look like this as it is power production per plant on empty tile (not empty tile production).
![powerperplant](https://user-images.githubusercontent.com/13003705/102528704-e48ca400-406c-11eb-99f3-57f020ea1476.png)

**Comment by kevinb9n** [comment]
To be clear: I'm only *explaining* the publisher's style guide, such we can reverse-engineer it (I've found only two exceptions in all the cards). Not saying this app has to follow it too.

They may do as you show, but I don't think your specific *argument* for doing it this way holds water, because there is simply no such thing as tile production.

**Comment by kevinb9n** [comment]
I'm trying to not bore everyone :-) but felt I should explain a bit more. Again, either is apparently correct in the grammar, and this is only about style. The actual style rule they implement is "max one production box per instruction set". I can't say I know the reason why, but from my review I don't think they've broken this once yet. 

That style rule in turn promotes this one (the "bring the full expression inside the production box" one), since it's a rule that always works even for cards that *also* produce something else (like if this card also generated +1 MC production).

**Comment by sienmich** [comment]
@chosta 
> emptyTile().secondaryTag(Tags.PLANTS)

It gives this
![Screenshot from 2020-12-18 00-32-26](https://user-images.githubusercontent.com/19472604/102556272-cbb1dc00-40c8-11eb-88eb-2de0c899d198.png)
The tag got shifted to the corner. But I think it must be plant resource, not plant tag.

**Comment by sienmich** [comment]
For me kevinb9n's idea is the best. With current card api we can also create sth like this:
![Screenshot from 2020-12-18 00-44-39](https://user-images.githubusercontent.com/19472604/102556888-40d1e100-40ca-11eb-9145-91e857aa5437.png)

Or is there a way to put the plant resource on the tile? Maybe there should be?

**Comment by chosta** [comment]
I like this one. There is no way to add a plant resourse on top of the tile without adding custom functionality atm. I think it's pretty clear from the image above that you need to read the text since it's kind of an exception on it's own. It makes sense to me.

**Comment by kevinb9n** [comment]
Well, this last one has come full circle to where we were with option 1. There's no way to tell that only one of the resource icons is meant to represent production. This is a bridge too far for the "greedily expanding production box" convention, making that convention have no value. I would say that not doing this (last image or option 1) is sorta important, in a way that the difference between all the other options is not. Just my opinion.
