### ISSUE TITLE
Bug: Standard Project `Buffer Gas` does not increase Venus track

### ISSUE THREAD

**Issue by aragos** [bafolts/terraforming-mars#2138]
While `Buffer Gas` does give TR to the player triggering it, it does not seem to increase the Venus track (not just a UI issue: Refreshing the page does not show any change on the track). This also means that any benefits (i.e. card or extra TR) on the Venus track are not granted to the player.

Observed in Solo TR63 game, server version d025021.

**Comment by kevinb9n** [comment]
The deal is that "Air-Scrapping" raises Venus, and "Buffer Gas" raises TR directly - this is one of the reasons I want to depict standard projects in the UI as though they are cards.

**Comment by aragos** [comment]
Gah, yeah, I was wondering about that. Should have double checked. Thanks for explaining! :D
