### ISSUE TITLE
Have add diy cards questions.

### ISSUE THREAD

**Issue by HagridThick** [bafolts/terraforming-mars#2145]
Hi,i try to add a diy company.
so i create a ts file in src/cards/corporation, 
add its name in  CardName.ts,
and add some code in src/HTML_data.ts
then run the following command:
```
npm run build
npm run start
```
it didn't appear.

i'm not familiar with typescript,if i want add cards,what should i do?

**Comment by Lynesth** [comment]
You also need to add your card to a manifest (`src/cards/community/CommunityCardManifest.ts` for example and then select the `Community` option when creating your game.

**Comment by nwai90** [comment]
@HagridThick Closing this. Feel free to reopen if you still have questions!
