### ISSUE TITLE
Add The Moon fan expansion

### ISSUE THREAD

**Issue by kberg** [bafolts/terraforming-mars#2146]
This is a tracking bug for work on The Moon fan expansion.

I've started working on it at https://github.com/kberg/terraforming-mars/tree/moon. It integrates with all other expansions (has Turmoil-related projects and Colony-related projects.)

While The Moon stretches the game in several dimensions (new tile types, new resource types, new global parameters, additional standard projects, projects that specifically cost steel and titanium,) the single biggest impact on this implemetnation is its additional map.

![EN - The Moon Board resized](https://user-images.githubusercontent.com/413481/102695058-0dd73c80-41f3-11eb-8862-cbabaf1ee3f2.png)

This impacts many parts of the game, including web rendering, selecting adjacent spaces, mouse hovering, and so on. Does this new map become part of Board or should there be a separate board? Does this mean generalizing Board to represent an abstract set of hexes? (Well, that's not a bad idea as something reusbale for other projects, I suppose.)

**Comment by kberg** [comment]
Progess! It's ugly, but I placed something that looks like a board, and something that looks like parameters, that kind of work: 
![image](https://user-images.githubusercontent.com/413481/103068707-bedf2d80-458b-11eb-88a0-cef0b2a093ae.png)

**Comment by kberg** [comment]
Tiles can go on the Moon. I'm working on making the tiles a little prettier, but that'll be up to some other expert.

![image](https://user-images.githubusercontent.com/413481/103112249-2c3d9d80-4622-11eb-9980-41953689f3b0.png)

Actually selecting a space is next.

**Comment by kberg** [comment]
Update: I fixed that tile. You can see it here, where I'm starting to deal with the cards themselves.: 
![image](https://user-images.githubusercontent.com/413481/103112375-f351f880-4622-11eb-93ac-0318ac4d06b4.png)

**Comment by chosta** [comment]
This looks good to me! I can help with tiles and borders. The card is
slick, just maybe add a .nbsp between the titanium and steel.

**Comment by kberg** [comment]
:+1: thanks, I'll let you know!

**Comment by kberg** [comment]
Update: standard projects are (mostly) implemented, as well as selecting a space on The Moon:

![image](https://user-images.githubusercontent.com/413481/103156665-f0691c00-4778-11eb-8469-14bacaaa373a.png)

**Comment by kberg** [comment]
Update: The 45 of the first 50 cards have their behavior and rendering.
![image](https://user-images.githubusercontent.com/413481/103442634-0453c880-4c26-11eb-9df6-2ce3e7c64d75.png)
![image](https://user-images.githubusercontent.com/413481/103442641-16356b80-4c26-11eb-8914-4ba62c7c3ac5.png)
![image](https://user-images.githubusercontent.com/413481/103442650-2d745900-4c26-11eb-844c-3b23aba4a507.png)

As well as one of the corps and all the preludes, and the 3 standard projects:

![image](https://user-images.githubusercontent.com/413481/103442658-4a109100-4c26-11eb-8136-72fbcf05c079.png)

**Comment by kberg** [comment]
Update: I've completed a single pass through of ALL the cards. 

Of the 100 project cards, 84 have behavior, 53 have decent rendering.
Of the 10 corporation cards, 2 have behavior and rendering.
All standard projects and preludes have behavior and rendering.

Cards that don't have behavior are commented-out so as to make the current implementation playable, or something.

Once I've fixed a _pecuiliar_ launch issue, it'll be available for testing.

**Comment by kberg** [comment]
Available for testing. Docs and link to test at https://github.com/bafolts/terraforming-mars/wiki/The-Moon

**Comment by kberg** [comment]
An update: I have added three more cards, reducing the number of unhandled cards to 22. They fall into these groups:

* **Impacting Research Phase** (1): Luna Project Office allows a player to draw one additional card during the research phase for the next two generations. The work involved to special case this isn't terribly difficult, but just needs to be not particularly disruptive. The card opens up  to interpretation what the player is meant to do with that extra card. I am going to build it so the player chooses *two* cards in their first draft.

* **Card Payments** (6): 6 cards in the deck change the way you pay for cards with either a steel, titanium or MC cost. (Actually safely paying for cards with a steel and titanium cost are covered in #2176) but this covers cards of these types:
1. decreased (or even eliminated) steel and titanium costs when playing moon cards.
2. decreased MC cost for Luna standard projects (I'm probably going to follow the Thorgate / Power Plant pattern here.)
3. decreased costs when playing a tile on the moon. (Here I'm going to change the card so these costs are a _refund_.) This expansion and Ares could both use a mechanism where the player might need to unwind a full action because they played a card they can't deal with once it appears on the surface, but this is good enough for now.)

* **Protected steel and titanium** (1): One card protects someone from stealing titanium or steel, just like animals, plants, etc can be protected. I think instead of dealing with card specialization across the app and "hasProtectedPlants" to assemble something slightly different.

* **Double-tile ownership** (2): Two tiles allow a player to put a token on a board space that someone else already owns, and they _co-own_ it. Areas that would need to change because of it:
1. VP calcuation
2. Ares megacredit adjacency bonues
3. Valid spaces for a player to play forests and tiles like MiningArea.
4. Land Claim is mercifully not going to be part of this problem.

* **Compatibility with other expansions** (6): Colonies and Turmoil. I'm just not sure how funny these actions are. Could use some guidance here.

* **Probably simple cards, really** (5): There are five cards I could probably resolve, I'm being difficult / lazy.

**Comment by kberg** [comment]
An update:

The basic feature has been added to the main branch, although hidden by a secret URL. more than half the cards are now in the main branch, with decent t ests, and a big pass through the card rendering is under way.

Still bugs, and a lot of them. Woe to the opponent of a player who gets Titanium Market Monopolists, for example.

**Comment by kberg** [comment]
Strictly speaking I should keep this bug open until it's out of beta, but I'm closing it in favor of tracking progress on https://github.com/bafolts/terraforming-mars/wiki/The-Moon
.
