### ISSUE TITLE
Valley Trust provides two additional prelude cards

### ISSUE THREAD

**Issue by dabewi** [bafolts/terraforming-mars#215]
Hi,

in my game I chose Valley Trust as a corporation and despite the card text that states to chose only one prelude card from the 3 you draw the game let's me choose two prelude cards from two different stacks of three cards (I mean the game draws 3 cards, let me choose one and then draws another 3 cards and again I can choose one card). That leads to a situation where I have 4 prelude cards, which doesn't seem right.

Screenshot: https://abload.de/img/valleytrusthhj8p.png

Or do I misunderstand the corporation text?

Cheers

**Comment by bafolts** [comment]
On the first screen where you selected your corporation you should have selected two prelude cards. Upon clicking save after selecting your corporation, 2 prelude cards, and any project cards you should have been taken to another screen where you then were displayed 3 prelude cards and selected the prelude card you wanted to keep as your initial action in the game since you selected Valley Trust as your corporation. The step of selecting a prelude card when 3 are displayed on the screen should have only happened once, if this happened twice it would be a bug.

**Comment by bafolts** [comment]
The only unique prelude cards are `Eccentric Sponsor` and `Ecology Expert` which has a `postPlay`. I am wondering if one of those are played before the initial action of `Valley Trust` if this in some way causes us to perform the initial action twice.

**Comment by alrusdi** [comment]
I can confirm this error. But can't reproduce it nor provide any additional details. This needs more deep investigation.

**Comment by vincentneko** [comment]
According to the prelude tags of the played cards, they are not Eccentric
Sponsor nor Ecology Expert.

Le ven. 24 janv. 2020 à 03:56, Brian Folts <notifications@github.com> a
écrit :

**Comment by bafolts** [comment]
I enjoy hard to crack bugs. I will keep looking into this issue.

**Comment by vincentneko** [comment]
postAction is a Boolean, I guess it should be a boolean,
Could it be related to this issue ?

**Comment by bafolts** [comment]
The type has only been specified as `Boolean`. The value is set to `boolean` so that should be fine.

**Comment by bafolts** [comment]
Was this seen during a game with more than one player? How many players were in the game?

**Comment by dabewi** [comment]
Hi,

this error occured during a play with another person. I also confirmed it again in a game with two players.

**Comment by bafolts** [comment]
OK. I see what is going on here. This issue could have very well impacted various other situations in the game. The prelude cards made the steps to recreate easy though.

As the actions that can be taken has grown more complex we have hit an edge case that was never covered.

https://github.com/bafolts/terraforming-mars/blob/master/src/Player.ts#L1656

In the situation where there are two `onend` functions set we end up losing one of the `onend`. The one lost in this situation is the one which increments the actions taken for the initial actions.

https://github.com/bafolts/terraforming-mars/blob/master/src/Player.ts#L1525

The short term easy fix here for this unfortunate growth in complexity is to create a lambda function to not lose the original `onend`. I will have a pull request up with a fix in a few.
