### ISSUE TITLE
Visual Bug: Phobolog shows you start with 30 MC

### ISSUE THREAD

**Issue by TomOfTomKat** [bafolts/terraforming-mars#2157]
Phobolog currently has a visual bug on the starting screen where it shows you starting with 30 MC instead of 23. If you select it, you do correctly start with 23 MC.

![image](https://user-images.githubusercontent.com/73961857/102790617-5154b680-436b-11eb-8086-e88abdc6a7f6.png)

**Comment by Lynesth** [comment]
Thanks for the report !
It's already fixed and should be deployed to the main server on the next restart.
