### ISSUE TITLE
Rewrite cloning to effectively just do a database row copy

### ISSUE THREAD

**Issue by kberg** [bafolts/terraforming-mars#2171]
I mean, that's easier, right? That's just as correct? I don't know anything about what game cloning is for -- I'd appreciate a reference.

But if this is OK, I'd like to do this.

**Comment by kberg** [comment]
@bafolts for an opnion.

**Comment by bafolts** [comment]
The clone game I believe only wants to take the game options and potentially starting cards from another game. We should be generating a new game id. Using database row copy would have to change the game id. What we are doing now probably fine.

**Comment by kberg** [comment]
Yeah, I meant something a little more sophisticated than that, but yeah,
it's fine. I'm happy it's closed.
