### ISSUE TITLE
Game creation UI: selecting a predefined game

### ISSUE THREAD

**Issue by kevinb9n** [bafolts/terraforming-mars#2181]
Whenever an existing game seed is selected, it would be very useful if all the game options from the previous game were selected visually, so I know what I'm getting into. It would also make a lot of sense for those option buttons to be disabled. In fact, if the first part isn't easy to do, the second part would still be helpful.

I think that four of the options represent "interface options" rather than "game options" and should be selectable independently of the predefined game: allow undo, show real-time vp, show timers, random first player. (Well, and the player names/colors/handicaps of course); and I know *some* set of options do already work this way, I'm just not sure exactly which. Anyway I think these should not be disabled as described above.

**Comment by bafolts** [comment]
The first part is probably easier than the second part. The first part should only have to load the game options from the dropdown. Second part will have to disable options once first part had ran.
