### ISSUE TITLE
Standard projects as cards

### ISSUE THREAD

**Issue by sienmich** [bafolts/terraforming-mars#2185]
When I'm playing with new players, they don't know what standard projects are doing. Aquifer is not the most common English word. You have to know, that City gives you 1 MC prod. Also you can not check projects prices if you can't afford them.
  
I would like to have standard projects as cards.
Why?
1. They look better than list
2. Better info for new players
3. Cleaner code (`Player.ts` is too big file, it should be split anyway)

Like so:
![Screenshot from 2020-12-25 01-52-48](https://user-images.githubusercontent.com/19472604/103112196-07fab480-4654-11eb-82aa-082ae75e3569.png)
Maybe they can be smaller to better distinguish?
![Screenshot from 2020-12-25 01-55-05](https://user-images.githubusercontent.com/19472604/103112445-bbb07400-4655-11eb-84e1-cb838c8e96d0.png)

Is it a good idea? What do you think?

**Comment by kberg** [comment]
Love it. Riffing on your example, I'd further distinguish it from a card like so.

![image](https://user-images.githubusercontent.com/413481/103112747-5c3a7000-4625-11eb-8a43-99067903b37e.png)

**Comment by kberg** [comment]
Ain't I A Artist?

(Possibly a different color banner, too?)

**Comment by Lynesth** [comment]
https://github.com/bafolts/terraforming-mars/issues/953#issuecomment-711088298

**Comment by sienmich** [comment]
Nice! I like those layouts.
@kberg, all of the standard projects except selling patents have cost in MC, so putting that cost in corner is reasonable imo.
Ok, I'll work on this :)

**Comment by kberg** [comment]
You know, I wrote why I didn't think it belongs in the corner for a reason: it makes it look as if it's a pay once use once card. If your goal is to make it clear to new users, then I think it's worth this extra step. In fact, I'd remove the entire top part of the card up to but not including, the blue line. (Don't make me draw again.)

**Comment by chosta** [comment]
This again :)? I propose a discord discussion before implementing. I
vaguely remember it was a bit controversial. I am all for "card" look but
let's make sure it's the right thing to do.

**Comment by kevinb9n** [comment]
I definitely still favor doing something like this.

I'm aware of two options (that have precedent) for how to depict them visually:

1. as if they are cards – that you don't have to actually have first and that don't go anywhere when played
2. as if they are card-actions (with red arrow) – which magically aren't on a card (i.e., there is nothing to mark as used for the rest of the gen)

some advantages of 1:

* even less new UI design to do; these just fit easily into something like #2001 (where as in #2, what is "housing" all these actions, and where do the names go?)
* when we have something like #776 then the Thorgate effect can be handled in the *exact* same way (but there'd be a way to do it either way)

some advantages of 2:

* same as physical game
* works for the SPs in the Moon expansion that have an additional resource cost
* for that matter, would be usable for a few non-SP standard actions too: 8P --> (greenery+O2); 8H --> (temp); 3E/3T/9MC --> (trade); xMC --> (delegate); of course these would need to be separate somewhere and I'm not suggesting a scope creep
* clearer that 'when you play a card' effects don't apply
* the problem of how to distinguish their repeatability might reduce down to the same problem we already have with scientists vs kelvinists

**Comment by kevinb9n** [comment]
So now I think we should mock up option 2 before starting more discussion, and I'm willing to do that, though it would be both fine with me, and probably easy, for someone else to beat me to it if interested.

**Comment by kevinb9n** [comment]
So option 2 would resemble this in some way:

<image width=250 src=https://user-images.githubusercontent.com/934551/103139328-d0116280-468f-11eb-9bea-f691a78ed8d2.png>

And the way the user knows which are available and selects one could be handled as similarly as possible to #2000.

**Comment by sienmich** [comment]
I agree that 2nd option (red arrows) is better.

I started working on this.
![Screenshot from 2020-12-25 18-16-36](https://user-images.githubusercontent.com/19472604/103139531-76378980-46dd-11eb-8c3f-6e9c6b29d289.png)
The visuals are going to be changed, right now I'm focusing more on those projects implementation.

**Comment by kevinb9n** [comment]
I like. Dang, you work fast.

(As a longer term thing we can think about whether surrounding with something card-shaped is suggesting to novice players that the card might be taken out of commission for the rest of the gen. And if we have some alternative. It is great for now imho.)

(I'm going to file an issue that speaks to the Thorgate issue, among others. For now I don't think you have to worry and can just have one Power Plant that costs 11; it's already the state of things that we have to apply our discounts mentally.)

**Comment by plentyofpaper654** [comment]
I was about to suggest basically this exact thing.
I would like to recommend an expansion however, so that this includes all actions in the game, including  heat and plant conversions, awards/milestones, and "compact" versions of action cards (Regolith Eaters, etc.) in addition to "End Turn" and "Pass for the generation."
Having these actions displayed in rows as cards, rather than nested radio boxes would make play smoother, and avoid the awkward scenario of needing to select "play cards" whenever you want to play cards, but heat conversion is automatically selected for example.

**Comment by kevinb9n** [comment]
1. The "standard actions" part is covered in #2192 - we agree!
2. Eventually it would be good for even end/pass/undo to no longer be text, though I hope they will be *very* clearly distinguished/set apart from the actual *actions*.
3. I'm not sure I am drawn to the idea of compact versions of the action cards. It goes a little bit in a different direction from where I have been advocating, which is increased physicality (treating components more as physical objects that live in one place, and letting users play as much of the game as possible by interacting with those physical objects). I do think that interacting with the cards themselves can be a lot better than it is now. My particular ideas for getting there include #2000 #2001 and #1606.

**Comment by plentyofpaper654** [comment]
I agree that the "compact action cards" would not mesh well with your tabbed interface. If you implement the tabbed interface, compact actions would seem out of place. I believe the tabbed interface offers overall better utility for most users.
