### ISSUE TITLE
Installation issues with Ubuntu 18

### ISSUE THREAD

**Issue by dabewi** [bafolts/terraforming-mars#222]
Hi,

I'm actually trying to install this project on my virtual server, but I'm getting this error:

https://abload.de/img/installationissues9pjx5.png

Since it states that I should inform the devs, I decided to create this issue. Does anyone of you know what the problem here might be?

Cheers!

**Comment by bafolts** [comment]
There must have been a typescript dependency update, although it is surprising the build doesn't fail.

**Comment by bafolts** [comment]
This _should_ work now. I use ubuntu as my daily driver and it now works for me. You must have installed avoiding the package-lock restrictions.
