### ISSUE TITLE
Some clear visual style shared by all reserved map spaces

### ISSUE THREAD

**Issue by kevinb9n** [bafolts/terraforming-mars#2234]
Suggestion: there should be something visual that all reserved spaces clearly have in common:

* the ocean spaces
* Noctis
* spaces off-Mars
* spaces an opponent Land-Claimed
* spaces an opponent Arcadian-claimed

... but which is shared by no other spaces, particularly not the volcanic spaces, as they are "special" but not reserved.

A rough idea is that the hex border looks just like the ocean space's border, just in a different hue (or hues).

(moved here from https://github.com/bafolts/terraforming-mars/issues/2204#issuecomment-752242772)

**Comment by ssimeonoff** [comment]
step one would be the empty hex spots to have less visible borders (less opaque) so whatever colour/shade the reserved ones have, to be more easily recognized. E.g. see the empty spots in the steam apps - quite suble.
