### ISSUE TITLE
Initial Draft Variant: Every player gets a different amount of corporations to choose from

### ISSUE THREAD

**Issue by funkybaboon** [bafolts/terraforming-mars#2238]
https://terraforming-mars.herokuapp.com/game?id=a7ccc5f48287
I created this game with 4 corporations, however one has 2, someone else has 3, and I have 4 corporations

**Comment by bafolts** [comment]
Seeing is believing! Issue not jumping out at me looking at source. Thanks for link to game.

**Comment by bafolts** [comment]
One player seems to have two prelude corporations, one player one prelude corporation, and the other player no prelude corporation.

**Comment by funkybaboon** [comment]
I changed the amount of players multiple times before creating the game, maybe it has something to do with that?

**Comment by bafolts** [comment]
Glad I rolled out a recent change in parts! We are still using `CorporationCard` when passing data to server as well as `IProjectCard`! Will need to update these to CardModel ASAP.

**Comment by bafolts** [comment]
I will re-deploy the demo site again once fix is merged. This should have only impacted initial draft variant as far as I can tell. Pushing out a change to lower the amount of memory used on server. The change for corporation cards went out today.

**Comment by bafolts** [comment]
The fix has been deployed and the linked provided now show 4 corporation cards for each player.
