### ISSUE TITLE
New Standard Projects cards are too small for The Moon

### ISSUE THREAD

**Issue by kberg** [bafolts/terraforming-mars#2241]
![image](https://user-images.githubusercontent.com/413481/103439616-6b648380-4c0c-11eb-887c-7e4775ee7271.png)

I'm not sure what to do about this. @chosta may have ideas. Or, just make bigger SP cards?

**Comment by sienmich** [comment]
I think making them (all SPs) bigger is good solution. They need not that much additional space. It should require changing the width and height in one place only, let me know if sth is breaking after changing those two.

**Comment by chosta** [comment]
I think dynamic height for these 3 only. I quite like the current size, so
these should be an exception. I'll try to find a solution.

**Comment by kberg** [comment]
For now, they can be grossly visualized as is. I'd even accept if the whole
thing was scaled smaller.

**Comment by kberg** [comment]
I think @alrusdi fixed this. Thanks!
