### ISSUE TITLE
Bug: Beginner Corp should NOT be added by default

### ISSUE THREAD

**Issue by vsrisuknimit** [bafolts/terraforming-mars#2242]
Beginner Corp should NOT be added by default. 

![image](https://user-images.githubusercontent.com/14239220/103440015-2f332200-4c10-11eb-97c5-ebe6c04d354e.png)

**Comment by bafolts** [comment]
Oh Beginner Corporation. No love. We used to manually add the Beginner Corporation places when looking up name. Now we will have to filter it when user doesn't need to select.

**Comment by vsrisuknimit** [comment]
@bafolts beginner corps should be given as an only option to everyone who selected them under Beginner Options.
