### ISSUE TITLE
FR: restore logging where a log request came from?

### ISSUE THREAD

**Issue by kberg** [bafolts/terraforming-mars#2251]
```
/usr/bin/node ./build/server.js
Starting server on port 8080                                            node_modules/console-stamp/index.js:38
version 0.X                                                             node_modules/console-stamp/index.js:38
```

Is it possible to replace `console-stamp` with the logging source?

**Comment by bafolts** [comment]
What do you mean by "logging source"? I wasn't aware we took on a dependency of `console-stamp` and was surprised when I saw it show up. Doesn't seem to add much value to take on an additional dependency and it doesn't seem that widely used. I am hoping by "logging source" you mean the file which is logging. We _should_ add something more robust like `log4js` and have logging per class. The `console-stamp` is a dead end as it doesn't have that much functionality. If we logged through `log4js` or similar it appends timestamp as well.

**Comment by kberg** [comment]
It was added https://github.com/bafolts/terraforming-mars/pull/2169 less than two weeks ago. I can't find the discussion on discord.

**Comment by Lynesth** [comment]
I just wanted timestamps and took the easiest way to do it (just adding a dep and nothing more as you can see).
Feel free to modify this as you wish @bafolts as long as you keep the stamps please :)
