### ISSUE TITLE
Philares implementation

### ISSUE THREAD

**Issue by vincentneko** [bafolts/terraforming-mars#226]
Philares
Effect: Each new adjacency between your tile and an opponent's tile gives you a standard resource of your choice (regardless of who just placed a tile)

I think this is the first time in the game where we need a player to make a choice when it's not his turn.

The solution I foresee, which is far from ideal, is :
- Create a new numeric variable bonusResources in player class.
- Increment this variable during onTilePlaced regarding the number of new adjacencies created
- Add a hook inside playerIsFinishedTakingActions in game so that we can "pause" the flow of actions and resolve the choice of Philares player. 
(when a new adjacency is created by another player)
- Add a new action in the takeAction method in player class, to allow Philares player to choose resources. This will not consume an action, and could mimic the Post Action implemented for prelude special cards.
(when Philares player create a new adjacency during it's turn)

Do you have other ideas ?

**Comment by bafolts** [comment]
This feels like an interrupt of sorts where the `Philares` corporation needs to provide input outside of their turn and make a decision which will impact the game. On the `Game` class we could add an `interrupt` property which could be:

```
interface PlayerInterrupt {
   player: Player,
   playerInput: PlayerInput,
}
```

If at any time the `interrupt` property is set on `Game` no player would get their defined `waitingFor` until the interrupt was completed. Once the interrupt is completed the property would be set to `undefined`. If we ever had to perform multiple interrupts we could scale this to be a queue or interrupts. Even bigger thinking we could turn all of our player inputs to work off of this queue.

I don't think we need to store a `bonusResources` if when a tile is placed, and we determine there are adjacencies we create an `OrOptions` with `SelectOption` we can then set `game.interrupt = { player: philaresOwner, playerInput: philaresCard.getPlayerInput() };`.

**Comment by vincentneko** [comment]
Thanks for the feedback.
I think we need to have a philaresResources variable in case another player is placing multiple tiles during his turn so we can update the amount of resources to take an only raise one interrupt.
I've pushed a commit on the branch trying to follow your guidelines, can you please review ?

**Comment by bafolts** [comment]
I left comments on your commit. Your changes look close.

https://github.com/bafolts/terraforming-mars/commit/f0bcb49e0fc9546cf037afa0d2f6df63656aa4b2

**Comment by bafolts** [comment]
What is on the branch for Philares is looking close if not ready to merge. Can you create a pull request? It will be easier to put comments on that.

**Comment by vincentneko** [comment]
Merged
