### ISSUE TITLE
Log cards panel doesn't properly update

### ISSUE THREAD

**Issue by Lynesth** [bafolts/terraforming-mars#2264]
When you open more than one at the time and start closing them without starting by the last one.

https://user-images.githubusercontent.com/5318258/103494209-b5a66880-4e89-11eb-896d-d40ccfd5e7a1.mp4

**Comment by bafolts** [comment]
I think the fix here will involve using a different key for https://github.com/bafolts/terraforming-mars/blob/main/src/components/LogPanel.ts#L182. Not sure what to use as one could potentially introduce duplicate cards.

**Comment by bafolts** [comment]
This is still worth fixing stale bot!
