### ISSUE TITLE
Visual Bug: Corporations have a 0MC icon

### ISSUE THREAD

**Issue by funkybaboon** [bafolts/terraforming-mars#2268]
<img width="424" alt="Screenshot 2021-01-04 at 15 14 15" src="https://user-images.githubusercontent.com/2966599/103543968-a500ed00-4e9f-11eb-9d40-09fee1c36e35.png">

To reproduce create a single player game
https://terraforming-mars.herokuapp.com/player?id=ad519e8071bd

**Comment by bafolts** [comment]
This is fixed now. Growing pain trying to use less memory and CPU on both client and server.
