### ISSUE TITLE
RFC: code for managing player resources

### ISSUE THREAD

**Issue by kberg** [bafolts/terraforming-mars#2269]
Problem: Code for handling player resources varies based on whether it's units of a resource (direct access to fields), or production `.addProduction(Resources.thing)` and I'd like to make it a little more consistent and easier to read.

I'm not quite sure what I'd like to propose yet, but I have a few thoughts. First is the notion of Units:

```
interface Units {
  megacredits: number;
  steel: number;
  titanium: number;
  plants: number;
  energy: number;
  heat: number
};
```

This allows for an API such as `player.addUnits({steel: 1})` and `player.removeProduction({plants: 8})` or even `player.addUnits({steel: 1, energy: 1})`

addUnits could also accept a `Resources` / `number` pair for those dynamic situations.

It also allows the possibility of passing around an abstract structure of units (consider `HowToPay` for instance:

A player with Helion and a card that increases titanium value might have a property such as

```
value = {
  megacredits: 1,
  steel: 2,
  titanium: 4,
  plants: 0,
  energy: 0,
  helion: 1
};
```

All the resources themselves would be hidden behind accessors, but instead of `player.getProduction(Resources.STEEL)` or `player.steel`, it's `player.steelUnits()` and `player.steelProduction`. Look, if you want those to be property accessors, that's also fine with me, I just don't have enough experience with how Typescript does property fields.

I just happen to think this will be easier to read and manage.

**Comment by nwai90** [comment]
This change seems to introduce additional complexity and overhead. `player.steel`, `player.megacredits` etc. are more succinct and an interface might be extraneous here.

Another option is to update to use the existing `player.setResource(Resources.SOMETHING)` function. This makes it similar to `player.addProduction(Resources.SOMETHING)` and ensures consistency but beyond that it is not much better than property accessors which offer simplicity imo. Is it required for some feature?

**Comment by kberg** [comment]
The thing is I HATE player.addResource(Resources.STEEL). `player.addSteel()` would be so much better.

But I also just want to standardize. Yesterday I can't tell you how much time I spent looking for code that deducts resources from a player without just calling "resource--".

Property accessors isn't bad, but addProduction, for instance, has several parameters to deal with global events, stealing, logging, which an accessor couldn't deal with. (That isn't in and of itself a bad thing, I've already communicated my general disdain for overusing function parameters.) Those additional fields could be dealt with via method chaining or something.

Another area I'd like to start to simplify is the vast size of Player. It's 2,200 LOC, and anything to generalize and break it up is good in my book. One of the other things I've been thinking about is replacing resources with some object (for the moment, let's call it `Purse`. The purse holds your standard resources, and moves standard resource handling out of Player. It's the biggest file by far.

I see your point about additional complexity. I think a good, smart API that separates resource handling will make things actually simpler.

I'm happy to write a prototype PR for this one (and in this case, I really mean a prototype for discussion, and not necessarily a PR to submit.)

**Comment by kberg** [comment]
I'm using it a bit here: https://github.com/kberg/terraforming-mars/commit/f58e2c33981e976b9ef72386c16c1b62e68d7405. I could see it expanding beyond this, naturally, which I'll look at in another PR.

**Comment by kberg** [comment]
@nwai90 this is what I had in mind. This seems to work: https://github.com/kberg/terraforming-mars/pull/22/files

Start by looking at Units, then Player, then CorporationCard and LogHelper.

One valuable bit is that all resource transactions are now logged.

![image](https://user-images.githubusercontent.com/413481/104243189-33d8b100-542e-11eb-8404-e2cd7c093562.png)

**Comment by kberg** [comment]
@nwai90 and here's a PR that shows a way to get rid of all the custom code in RoboticWorkforce, moving it to the card itself: https://github.com/kberg/terraforming-mars/pull/22/commits/b1ce3344547eb439ca7619b6ade3f696c1d6dda7

**Comment by nwai90** [comment]
@kberg Thanks! I will look at this later in the week
