### ISSUE TITLE
RFC: Embed game inside Player

### ISSUE THREAD

**Issue by kberg** [bafolts/terraforming-mars#2270]
We pass around `game` and `player` all over the place, when `player` _really_ should be enough. Earlier, when serialization meant that a game couldn't be serialized because game -> player -> game meant a circular loop, well, those times are gone.

This can be managed with an API or property on Player that is hidden from public use: `_game: Game | undefined;`

When Game is either deserialized or initialized (actually, probably in the Game ctor) Game calls an API on `Player` to register the `_game` field:

Game ctor:
```
constructor(players: Player[]) {
  players.forEach(p => p.setGame(this));
}
```

Player.setGame:
```
public setGame(game: Game) {
  if (this._game !== undefined) throw new Error('What are you doing???');
  this._game = game;
}
```

And when code needs a player's game, they just call `player.game()`:

```
public getGame(): Game {
  if (this._game === undefined) throw new Error('Too soon!');
  return this._game;
}
```

This will reduce a lot of API complexity, and we can side-step the serialization issues.

**Comment by kberg** [comment]
An example commit: https://github.com/kberg/terraforming-mars/commit/f8ef235d9e19fe24b3c6e0767cff2ff5578ee496

**Comment by kberg** [comment]
Naturally, first let's finish @bafolts's card rewrite, and then @Lynesth's project. Still, it's possible to embed the property in Player now, and prefer that method.

**Comment by bafolts** [comment]
I can't think of any issues this would cause. A `Player` is going to associated with a `Game`. As the dependency is required could try to pass it in through `newInstance` if possible to avoid having to throw if it were `undefined`. This should also cut down on how often we have to `import {Game} from '../Game'` which will lead to smaller build size as we wont have that string in most files.

**Comment by kberg** [comment]
This is basically done.
