### ISSUE TITLE
Incorrect UI displayed when toggling between cards and standard projects

### ISSUE THREAD

**Issue by nwai90** [bafolts/terraforming-mars#2274]
When toggling between "Play card", "Standard projects" and "Sell patents", the UI seems to be displaying cards as standard projects and vice versa.

<img width="409" alt="Screenshot 2021-01-05 at 8 34 12 AM" src="https://user-images.githubusercontent.com/2408094/103593475-e55c7b80-4f30-11eb-9eb1-a6560be1c8f2.png">
<img width="712" alt="Screenshot 2021-01-05 at 8 34 25 AM" src="https://user-images.githubusercontent.com/2408094/103593476-e68da880-4f30-11eb-928e-78824d41c4d7.png">

**Comment by Lynesth** [comment]
Maybe related to #2264 ?

**Comment by bafolts** [comment]
Are there steps to consistently reproduce? I hit the issue once but struggle to recreate it.

**Comment by bafolts** [comment]
With a lot moving for optimizations I will stop my work on cards until I resolve this and #2264 as I assume I introduced this in some way.

**Comment by sienmich** [comment]
> Are there steps to consistently reproduce? I hit the issue once but struggle to recreate it.

1. Create new game, buy 2 cards at start.
2. Select Standard projects
3. Select Sell patents
4. Select Play project card
5. Select Standard projects

**Comment by bafolts** [comment]
I haven't spotted it yet but thinking this is something to do with storing the card instance now on the `Card` component.

**Comment by bafolts** [comment]
Fix that worked for me is up in #2275. Not entirely sure why that resolved the problem but seems to work and is the right thing to do as we should be providing key.
