### ISSUE TITLE
Request: have dot env file on the repo

### ISSUE THREAD

**Issue by vsrisuknimit** [bafolts/terraforming-mars#2298]
Have an example of the dot env file on the repo, so that when user clone or pull the repo, the file will be there already for the user to change later. Many users asked where to find the env file not knowing they have to make one.

**Comment by kberg** [comment]
Fine with me as long as it's in the .gitignore. Also, could be a wiki page
talking about a sample env file?

>

**Comment by vsrisuknimit** [comment]
@kberg The readme.MD already talks about the env file, but not the wiki.

Could someone add one? I am not sure yet what should be the env file.

**Comment by kberg** [comment]
Happy to do that in the coming day or two.

>

**Comment by chosta** [comment]
There is no need to do it in the wiki imho (although it won't hurt). Usually a `.env.sample` showing the default configuration should be sufficient. A comment inside should mention to remove the `.sample` extension and that `.env` is not going to source control. Pretty common approach. `.env` is gitignored and `.env.sample` is not.

**Comment by kberg** [comment]
That's a better idea!

>

**Comment by vsrisuknimit** [comment]
@chosta Can you make the .env.sample?
