### ISSUE TITLE
Immigrant City doesn't reduce MC production

### ISSUE THREAD

**Issue by dabewi** [bafolts/terraforming-mars#230]
Hi,

my colleague stumbled across a possible bug with the immigrant city. The card reduces the MC production by 2 and increases it every time a city tile is placed. 

In our current game there are three city tiles from which one is played after the immigrant city, so that his MC production should be increased by 2. In fact his MC production IS 2, which leads to the conclusion that the initial -2 MC production were not applied:

https://abload.de/img/bugimmigrantcity5ykqo.png

This screenshot shows the upper part of my screen with the city placements and the lower part, my view of my opponent's cards.

**Comment by vincentneko** [comment]
Hi, 
Thanks for the feedback, I will correct this asap.
