### ISSUE TITLE
Feature request: a button to collapse non-blue cards (outside preferences)

### ISSUE THREAD

**Issue by vsrisuknimit** [bafolts/terraforming-mars#2309]
Currently the button to hide non-blue cards is in the preference. While this is good, users may want to hide and unhide the non-blue cards many times through out the games. Going back and forth to the preference settings requires too many clicks.

**Proposal**

One of the three methods to collapse the stack.
1) Click on any green / red cards to collapse either card stack.
2) A button near 'played cards' to collapse both stack.
3) A button each at the bottom of the green / red stacks to collapse either card stack.

What should be show once the stacks are collapsed
1) Total number of cards.
2) Total number of cards costing more than 20 mc. (Optional, we might not need it.)
3) Total VP from that stack.
4) Variable  VP cards: Immigration Shuttles, Space Port Colony, Jovian Multipliers. (Optional, we might not need it.)

Benefits
The long stack of green/red cards are what is taking a lot of vertical space. We will be able to save a lot of vertical space by being able to collapse and expand these stacks at will.

![bitmap](https://user-images.githubusercontent.com/14239220/104064691-5ec3ca80-51cc-11eb-8c03-166e62eb1c2d.png)

Tagging @chosta for help.

**Comment by bafolts** [comment]
If a UI is agreed upon this should be among the easier of features to implement.

**Comment by vsrisuknimit** [comment]
@bafolts Of all the things I proposed recently? Haha.

Asking @ssimeonoff for help with UI.

**Comment by vsrisuknimit** [comment]
I am leaning toward option 2: having a button saying [collapse 🟩 🟧 cards] next to 'Played cards'. The button change to [expand 🟩 🟧 cards]. But you can also click on the green/orange info cards to expand them.

In terms of what to show. I would focus on just two.
1. Total number of cards.
2. Variable VP cards: Immigration Shuttles, Space Port Colony, Jovian Multipliers. (Optional, we might not need it.)

**Comment by ssimeonoff** [comment]
There was some discussion in pm with kevin time ago. Resharing the images: 
![1](https://user-images.githubusercontent.com/6917565/104120542-fc87d880-5337-11eb-9169-758f06d7d5d0.png)
![2](https://user-images.githubusercontent.com/6917565/104120546-fd206f00-5337-11eb-992c-d41d2696b9d1.png)
![3](https://user-images.githubusercontent.com/6917565/104120547-fdb90580-5337-11eb-9865-ec9da558ef89.png)

- Add simple filters All/Automated/Active/Events
- when "all" is selected, by default, played cards looks as now
- when "active" is selected, corporation and blue cards are displayed as now
- when "automated" is selected, preludes and all green cards are displayed in a list (not stacked)
- when "events" is selected, events are displayed in a list (no stacked)
- the buttons are available and when looking at other player's played cards

The buttons/filters can also show numbers how many cards are displayed under them, but not sure about this if we group the corporation with the blue and preludes with the green.
