### ISSUE TITLE
small issues re: multi-action cards

### ISSUE THREAD

**Issue by kevinb9n** [bafolts/terraforming-mars#2327]
(As always, I just report what I find, but do with it what you wish!)

I like that the descriptions were separated for each action on a multi-action card, and placed each below its related icons. I think it should improve accessibility and makes a lot more sense for doing something like #2000.

I found only a couple tiny bugs:

* Extractor Balloons - second action's text still describes both actions
* Asteroid Rights - is missing OR between the two actions (but I will say that I find the OR to be much less necessary now and it could probably be dropped as needed or dropped across the board to save space)

I assume that Titan Floater Launch-Pad, Red Spot Observatory, and Self-Replicating Robots don't have this change due to space constraints. This is another case where I wonder if there are other solutions to explore that would enable them to be be consistent. 
@chosta

**Comment by chosta** [comment]
Thanks for these.
