### ISSUE TITLE
This sequence of undo steps seems to be bugged

### ISSUE THREAD

**Issue by kevinb9n** [bafolts/terraforming-mars#2328]
I have seen this behavior several times but haven't determined under exactly what circumstances it happens. It doesn't happen every time.

1. Take some action
2. Undo it
3. Reload
4. Take a different action
5. Undo it
6. Reload
7. The first action I did in step 1 has magically returned.

**Comment by kevinb9n** [comment]
Sorry I still don't have exact steps for guaranteed repro, but FYI @Lynesth I have seen this many many times lately. It might be triggered by doing a chain of two or more undos in a row, perhaps. A rabid undoer, I am.

**Comment by kevinb9n** [comment]
This sequence seems to produce the bug every time in a solo game:

1. Do action A
2. Undo action A
3. Do action B
4. Do action C
5. Undo action C
6. Action A has returned to life

**Comment by Lynesth** [comment]
Right, my dumb ass finally found out why.

**Comment by kevinb9n** [comment]
Sounds like your dumb ass is smart then :-)
