### ISSUE TITLE
Increase single game retention to 10 days for single player games.

### ISSUE THREAD

**Issue by bafolts** [bafolts/terraforming-mars#2329]
Back when every game would be loaded on a server restart we introduced a change to delete old games after one day. This makes diagnosing bug reports difficult as we have less than 24 hours to pull any information from the game that may help with troubleshooting. With the updates to minimize how much data we store when serializing and now only loading games when they are needed it should be fine to increase this.

The change is made [here](https://github.com/bafolts/terraforming-mars/blob/main/src/database/PostgreSQL.ts#L145)

**Comment by kberg** [comment]
YES.

>

**Comment by SliceOfBread** [comment]
For those of us that set up their own herokuapp site (and a giant thanks for those instructions!) can you give some idea on the number of games that can be stored? If it is more than a few dozen I'll probably change my deletes to closer to a month.

**Comment by kberg** [comment]
> For those of us that set up their own herokuapp site (and a giant thanks for those instructions!) can you give some idea on the number of games that can be stored? If it is more than a few dozen I'll probably change my deletes to closer to a month.

Storage requirements were recently reduced, optimistically, by about 99%. As long as you haven't run out of space yet, just keep an eye on your heroku storage requirements, and don't worry too much about it. But I just recommend you look at your dashboard and make the decision for yourself. Brian may have a better answer.

**Comment by bafolts** [comment]
I agree with @kberg . When the undo operation and saving game state was introduced there was no effort given to optimizing it. Recently we have improved it so it is about as efficient as it will get while we can still read the logic with relative ease. We have `MAX_GAME_DAYS` environment variable that can be used with SQLite we could also add for postgres. I would use a separate issue if people want to add this configuration for postgres as the query will need to be tested.
