### ISSUE TITLE
Cancel button on actions

### ISSUE THREAD

**Issue by dabewi** [bafolts/terraforming-mars#233]
Hi,

in some situations, e.g. when I play Robotic Workforce and realize that the card that I wanted to copy has no building tag and is not eligible, I think it'd be nice to have a "cancel" button to just undo that I chose the card and can choose another. There are several cards with requirements that a player might realize too late (when the card is already chosen).

This sounds to me as a topic that might already have been discussed, but I couldn't find any discussion on this. Would that require a huge effort?

**Comment by vincentneko** [comment]
Hi,

About your example about Robotic Workforce, I will modify the canPlay function so the situation you describe will not occur anymore.

**Comment by bafolts** [comment]
Assuming the action was not the last action of a turn this could be possible. If the action were the second and final action of a turn and the game progressed to the next player a feature would have to be implemented to request that player to undo your last turn. I don't think these complexities are worth it. Not all of the `canPlay` functions have been implemented. Once all of those were implemented that should avoid a lot of the useless cards being played.

It may be worth adding a feature where we display all cards but show the ones that can't be played as disabled with a message explaining why they are disabled.

**Comment by alrusdi** [comment]
I think we are going to refuse this suggestion.
