### ISSUE TITLE
Cards UI: Blue cards need dividing line between ongoing and immediate sections

### ISSUE THREAD

**Issue by kevinb9n** [bafolts/terraforming-mars#2330]
Print cards have an entire thing of artwork between the two different kinds of content: actions and effects above, immediate instructions (and VPs) below. If we could have just the thinnest dividing line, I think it would make the cards much less confusing for new players.

I noticed that one card, Pets, even interleaves the two types of content:

<img width=200 src=https://user-images.githubusercontent.com/934551/104131941-c4c86300-532e-11eb-8923-6683a6453efb.png>

So we have

1. Effect 1 icons
2. Effect 1 text
3. Immediate instructions icons
4. Effect 2 (self-describing)
5. VP text
6. Immediate instructions text
7. VP icons

**Comment by kevinb9n** [comment]
note that if a dividing line isn't possible for some crowded cards like Asteroid Deflection, I still think that having it inconsistently is better than not at all.

**Comment by kevinb9n** [comment]
@chosta assigning to invite your opinion on this

**Comment by chosta** [comment]
I took Simon's card design for granted. Only later did I realise that there might be some discrepancies from the printed versions. The thing is that I kind of like the artistic representation in some of the cases. Pets for example is something I really enjoy but a rework of these types cards that is more consistent is not out of the question in the near future.

**Comment by kevinb9n** [comment]
Well, this issue is just about a li'l dividing line :-)

**Comment by chosta** [comment]
You'll be surprised how hard it is to add just one line :)
I'll think about it

**Comment by kevinb9n** [comment]
No, I totally believe it. 

My role is just to speak for the positive value it would have. Weighing that against the effort, that part is for you!

I think it would help users understand the cards. There is SO much going on on them that the first thing a reader needs to do is break it down into pieces that can be understood separately.
