### ISSUE TITLE
Natural Preserve decreases M€ production

### ISSUE THREAD

**Issue by terraformerG** [bafolts/terraforming-mars#2339]
Hi all!
It's my first post so appologies if I'm doing something wrong. I recently started playin (so far only solo) and seem to came upon a bug. When playing Natural Preserve project card which should increas M€ production by 1, it seems that production gets decreased by 1 instead.
https://terraforming-mars.herokuapp.com/player?id=e69a2734db1c#board

**Comment by Lynesth** [comment]
When playing Solo with Colonies expansion, you start at -2 MC production.

**Comment by terraformerG** [comment]
Ah, right, my bad.
