### ISSUE TITLE
Getting the same corporations

### ISSUE THREAD

**Issue by dabewi** [bafolts/terraforming-mars#234]
Hi!

I experienced a strange behaviour. Whenever I use the custom corporation list feature (because I don't want to play with Tharsus Republic) and configure it like so:

https://abload.de/img/bug0sjlk.png

The two players are getting the same corporations. Player 1 gets Utopia and Factorum and Player 2 gets Terralabs and Lakefront Resort.

Can anyone confirm that or is it just weird session handling?

**Comment by bafolts** [comment]
This is not strange behavior but in fact a bug. The custom corporation cards are never shuffled prior to dealing them to each player.

https://github.com/bafolts/terraforming-mars/blob/master/src/Game.ts#L121

**Comment by vincentneko** [comment]
Fixed and merged
