### ISSUE TITLE
By Election + Agendas

### ISSUE THREAD

**Issue by sienmich** [bafolts/terraforming-mars#2340]
After I played 
![Screenshot from 2021-01-11 15-21-17](https://user-images.githubusercontent.com/19472604/104193720-b5c1dd80-5420-11eb-9abd-4d9c0ffe05b5.png)
I can see this:
![Screenshot from 2021-01-11 15-20-18](https://user-images.githubusercontent.com/19472604/104193762-c1150900-5420-11eb-86e7-a1c2cc9cbdc4.png)

@nwai90 ?

**Comment by nwai90** [comment]
@sienmich I'll take a look. This card's logic now needs to be updated with PoliticalAgendas

**Comment by nwai90** [comment]
Fixed and merged
