### ISSUE TITLE
Solo (Helion?) buys all cards when only 1+ selected

### ISSUE THREAD

**Issue by SliceOfBread** [bafolts/terraforming-mars#2348]
Not sure if this is Helion only but if I select 1 or more cards, it then defaults to pay 12MC, 0heat. And if I lower the MC, it still gets me all the cards.

The id of this game is b42dde2b9fc. I don't need to finish it (I usually play on my server but occasionally check to see if I should update it).

**Comment by nwai90** [comment]
@SliceOfBread Related to fix in https://github.com/bafolts/terraforming-mars/commits/main. Should be able to close this once the change is deployed to mainserver

**Comment by sienmich** [comment]
Yep, thanks, fixed
