### ISSUE TITLE
More people to update Wiki Changelog

### ISSUE THREAD

**Issue by vsrisuknimit** [bafolts/terraforming-mars#2351]
Hi @bafolts, can you give me and @kevinb9n write access to the wiki changelog? We can help @nwai90 updating it. He does not have enough time to update it lately. It would be nice to have more people to help.

**Comment by kevinb9n** [comment]
I volunteer as tribute, am making the list now. I think I have access already.

**Comment by bafolts** [comment]
I am assuming the access to edit the wiki is given to any collaborator. @vsrisuknimit I sent an invite request to make you a collaborator.

**Comment by vsrisuknimit** [comment]
@bafolts Thank you, I accepted the invitation. Yes, I can edit the wiki now, but probably have too much permission too. I am not at all qualified to review quote and merge PR. Change if you see fit. But this is fine too I will avoid those scary buttons.
