### ISSUE TITLE
Cards cost 6 resources when playing helion

### ISSUE THREAD

**Issue by GJonatan** [bafolts/terraforming-mars#2354]
When playing helion buying card costed 6 resources. This happened to my friend and he think it was like this for every generation but he didn't notice it at first.

![138794046_1016755235485385_1660963788384629787_n](https://user-images.githubusercontent.com/71512380/104370893-cd33c000-551f-11eb-9890-2a4d59b56706.png)
![138532401_4127320003966048_5862319917797999649_n](https://user-images.githubusercontent.com/71512380/104370904-d15fdd80-551f-11eb-9dbd-250ce580e0aa.png)
<img width="1195" alt="Screenshot 2021-01-12 at 21 45 08" src="https://user-images.githubusercontent.com/71512380/104370908-d2910a80-551f-11eb-99b3-c43163b298d4.png">
<img width="1239" alt="Screenshot 2021-01-12 at 21 43 48" src="https://user-images.githubusercontent.com/71512380/104370910-d329a100-551f-11eb-805f-1d26fe5c312b.png">

The first two images shows him trying to by two cards and the last two images shows my view on it, one from before he bought them and one afterwards. He payed 8 heat and 4 MC for two cards

**Comment by vsrisuknimit** [comment]
@sienmich

**Comment by sienmich** [comment]
Thanks for report, fixed, will be live on server hopefully soon
