### ISSUE TITLE
Agricola tag score not included in real-time victory points

### ISSUE THREAD

**Issue by ChrisTheCat** [bafolts/terraforming-mars#2371]
The VP shown does not include the 16 granted by Agricola. 

![B257841A-A1F1-4658-AAFF-370D317E9828](https://user-images.githubusercontent.com/8732435/104574085-7fe04d00-560a-11eb-9f82-160ea144939a.jpeg)

**Comment by Lynesth** [comment]
I think you got it wrong. At the moment Agricola gives you -2 VP.
| Tag | How many you have | Points it gives you |
| --------- | --- | --- |
| building | 3 | 1 |
space | 3 | 1 |
science | 2 | 0 |
power | 0 | -2 |
earth | 5 | 2 |
jovian | 1 | 0 |
venus | 0 | -2 |
plant | 1 | 0 |
microbe | 1 | 0 |
animal | 0 | -2 |
city | 1 | 0 |

_Assuming you are playing with Venus Next_
_Wild tags and Event tags do not count_

More info about that corp [here](https://www.notion.so/8c85a57488854ff7a124518e82b83548?v=b0af622e91804a729cfa5b5f77a2cbfe&p=30d46473f8fc45f280a80396b60605c6).
