### ISSUE TITLE
Bug: Mons, Animals, and Meat Industries

### ISSUE THREAD

**Issue by vsrisuknimit** [bafolts/terraforming-mars#2379]
`I saw an issue in my game yesterday. I was playing as Mons Insurance. I had previously played meat industry. On my turn, I had 12 MC. I used all my 12 MC to buy herbivores, bringing my MC down to 0. I was not able to reduce someone's plant production before I got my 2 MC from meat industry. Therefore, I was forced to give my 2 money to the player I stole from (via insurance). I believe I should have the option to reduce plant production and then get my animal and 2 coins from meat industry` - inte

**Comment by Lynesth** [comment]
This should simply be in #1046.
