### ISSUE TITLE
Bug: Inaccurate log for Turmoil

### ISSUE THREAD

**Issue by vsrisuknimit** [bafolts/terraforming-mars#2380]
![image](https://user-images.githubusercontent.com/14239220/104641026-3d088e80-5677-11eb-812b-9478c0ee532e.png)

The player has no steel production. The log says steel production was decreased.

**Comment by kberg** [comment]
Do you remember which Global Event it was by chance?

**Comment by vsrisuknimit** [comment]
@kberg Sabotage.
