### ISSUE TITLE
Feature request: marking for use of Turmoil Scientists Policy

### ISSUE THREAD

**Issue by vsrisuknimit** [bafolts/terraforming-mars#2381]
Once a player has used the Turmoil Scientists policy, a player cube is put next to the policy on the turmoil board to mark the action has been used for this player.

**Comment by kevinb9n** [comment]
I like this solution very much because it's a good approach for playing "in real life" too.

Note the Agendas expansion would want to put up to THREE cubes per player by some actions - if there is some way to have room for that.
