### ISSUE TITLE
Game crash at midnight (GMT+1)

### ISSUE THREAD

**Issue by Lirkas77** [bafolts/terraforming-mars#2383]
Not sure if it happens due to the time (midnight) or due to playing Cloud Seeding and selecting a player (to lose ressources), but the game crashed ("Unexpected server response"). We were playing in 3.

This was the link to the player's interface/game when it happened.

http://terraforming-mars.herokuapp.com/player?id=c923db8245d2#cards

Btw, thumbs up for such an interface!

**Comment by Lirkas77** [comment]
It did uncrash and let us play after nearly 30 min. Not sure yet if it's due to Cloud Seeding since the game reloaded one action before. We'll test more and let you know :D

**Comment by Lirkas77** [comment]
we played a bit some more actions, then it bugged again. We'll reload it the next day :D

**Comment by vsrisuknimit** [comment]
@Lirkas77 I don't see any problem. Come hang out on Discord if you want less reliable but faster response.

**Comment by Lirkas77** [comment]
We just finished the game. after rebooting it and redoing some 10 actions. It went fine. :)
I don't know then what was the issue. Maybe the server rebooting ?

**Comment by bafolts** [comment]
The hobby basic plan that terraforming-mars.herokuapp.com is using doesn't guarantee 100% uptime. Around 12:00 UTC all requests seem to have started timing out. Usually when heroku is making some change or migration we that would show up in the log. In this circumstance I don't see that in the logs. The load average on the box wasn't that high during this time.

![image](https://user-images.githubusercontent.com/2707843/104666716-c6c55580-5691-11eb-9365-fda148d0905a.png)

It could be worthwhile keeping this open. If we see this pattern continue we could have introduced some issue. Recently we started storing more single player games that we would have to load into memory when the server started up. This would have kept single player games for 10 days. Without checking I think we are getting close to 10 days.

Only 6k games in database which isn't too alarming to me.

```
terraforming-mars::DATABASE=> SELECT count(*) FROM (SELECT DISTINCT game_id FROM games) a;
 count 
-------
  6745
(1 row)
```

If we don't see this happen again in a day or two I would chalk this up to heroku doing something on their end.

**Comment by bafolts** [comment]
The time being midnight does line up with a common thought process for when to run some update script on servers or a cronjob. Run it at midnight!

**Comment by Lynesth** [comment]
Closing this.
Feel free to comment here again if you need it reopened.
