### ISSUE TITLE
How to pay does not default anymore on first card

### ISSUE THREAD

**Issue by vincentneko** [bafolts/terraforming-mars#239]
When selecting "Play project card", the How to pay box is at 0, before it was at the card cost.
If you select another card, the cost is updated.

![Screenshot 2020-02-03 21 16 34](https://user-images.githubusercontent.com/56086992/73687567-9e378c00-46ca-11ea-8303-6309d56400ff.png)

**Comment by alrusdi** [comment]
I take it, to fix

**Comment by alrusdi** [comment]
@bafolts Do you have some suggestions of how we can implement client-side tests for issues like this? May be you know some guidelines of how to test Vue components in general?

**Comment by bafolts** [comment]
I am not familiar with client side testing of Vue components. It is a heavily lacking part of the current testing. It would be something beneficial to add.

**Comment by alrusdi** [comment]
Fixed, merged. Will implement clientside testing someday somehow :-)

**Comment by bafolts** [comment]
At one point I tried to do this and I think it works better if use you the vue files and not the generated components like we do. I need to revisit this when I have time. It is usually always the source of bugs as it has no tests.
