### ISSUE TITLE
How to translate all uppercase cards

### ISSUE THREAD

**Issue by ltdstudio** [bafolts/terraforming-mars#2398]
![how to](https://user-images.githubusercontent.com/39257428/104741401-0e56ea80-5741-11eb-9c83-fd2dd8db7ad6.png)

like this one.

I have translated it , but it doesn't work.
` "Eccentric Sponsor": "奇特的赞助者",`
` "PLAY A CARD FROM HAND, REDUCING ITS COST BY 25 MC": "以降低 25MC 的价格打出一张手牌",`

I think this problem is happening with RU,IT,Other language.

**Comment by alrusdi** [comment]
Source text is:
"Play a card from hand, reducing its cost by 25 MC"
uppercase is applied by css rule

**Comment by alrusdi** [comment]
If you open dev console of your browser and refresh debug-ui you will see a lot of messages like:
Please translate "Spend 11 MC to increase your Energy production 1 step."
text in quotes is actual source string no matter how it looks like on card

**Comment by ltdstudio** [comment]
thanks I'll try it. and how about this?
![car](https://user-images.githubusercontent.com/39257428/104813934-19bf1a00-5804-11eb-9766-a88833a8a356.png)

**Comment by alrusdi** [comment]
The same idea. Source string is:
"1 additional VP for each ocean tile adjacent to this city tile."

**Comment by alrusdi** [comment]
Please reopen this issue if you have further questions
