### ISSUE TITLE
Suggestion for fan made expansion Agenda

### ISSUE THREAD

**Issue by Durandil** [bafolts/terraforming-mars#2403]
I am playing with the fan made expansion Agenda and I have a suggestion to improve it a little in the app. 

During the Turmoil phase, when the Chairman has to choose which ruling bonus does it want to be implemented (for example for Priority Mars : 1 MC / Building Tag or 1 MC / Tile on Mars), could you put into brackets near each bonus how much MC each player would gain? For example : 

1 MC / Building Tag (Red 5 / Green 7 / Blue 10)
1 MC / Tile on Mars (Red 2 / Green 7 / Blue 0)

Instead of Red/Green/Blue it could be small color cubes or the names of the players

So it's easier for the Chairman to choose between the two bonuses

Thanks!

**Comment by kberg** [comment]
I'm removing the label just  because there's a last bit of work to do to update the chairman mode that I've been lazy to deal with.
