### ISSUE TITLE
First card is PRE-selected when choosing 'Play project card' action. This is rather dangerous!

### ISSUE THREAD

**Issue by tjhughes1964** [bafolts/terraforming-mars#2407]
It is too easy to mistakenly press the 'Play card' button, or miss selecting the card you want to play and then press the 'Play card' button. This has occurred numerous times in our games.

In non-undo games at the least, the first card in your hand should *not* be pre-selected.

**Comment by nwai90** [comment]
I would disagree with this. The first blue card and first prelude card should also be pre-selected at some point as per https://github.com/bafolts/terraforming-mars/issues/775. Each player typically has hundreds of turns during a game and having no pre-selection incurs a cost of many more clicks per player.

**Comment by tjhughes1964** [comment]
Sure, if there's only one card playable (which seems to be what #775 is about), pre-select it. But typically there are several and it's unlikely that the first one will just happen to be the one you want to play (unless you have gone to some lengths rearranging the cards, and only then if circumstances have not changed since you did the rearranging).

In the case of Preludes, in almost all cases the order they are played in is unimportant. This is most definitely not the case with project cards.

If you consider the time spent clicking on project cards in order to play them is the limiting factor in your games then you aren't spending as long thinking about which card to play as I am ;)

**Comment by vsrisuknimit** [comment]
![image](https://user-images.githubusercontent.com/14239220/104795751-b7700600-577e-11eb-8473-89a8e3caf0b3.png)

Play project card choice and [Play] button are so far apart I don't see what the problem is. There is no way to misclick play immediately after selecting Play project card.

**Comment by tjhughes1964** [comment]
The usual problem is that one clicks the card to play and then immediately clicks the 'Play card' button. If for any reason the card selection failed, you play the wrong card.

Failed card selection - for me - is usually the result of inadvertently click-dragging on text. Guess I should be more careful.
