### ISSUE TITLE
Ares : Game hangs when trying to place a hazard tile when there is no space

### ISSUE THREAD

**Issue by meussiebeaucoup** [bafolts/terraforming-mars#2416]
We have a game where placing an ocean tile would trigger the placement of hazard tiles on the board. However, there is no place left for a hazard tile, since all free spaces are adjacent to a city tile. This results in the game looping forever trying to find an empty space.

testToPlaceErosionTiles() -> randomlyPlaceHazard() -> getSpaceByOffset() -> getNthAvailableLandSpace() ->
...
    while (idx < 0) {
        idx += spaces.length;
...

Here spaces.length is 0, which means it never gets out of the loop. I guess there should be a check on the spaces to see whether a hazard tile can be placed at all, and if a tile cannot be placed the game should continue as normal.

**Comment by kberg** [comment]
Youch! I'll fix that today. Thanks.

**Comment by bafolts** [comment]
Yes. I am going to fix #2421 . Errors like this will take down a heroku instance as javascript is single threaded.

**Comment by kberg** [comment]
OK. Throwing an error in this case is totally acceptable. If you happen to fix this one in the next 3 hours let me know.
I just can't focus on it for at least another 3-4 hours, but Ic an review a change.
