### ISSUE TITLE
docker image not updated

### ISSUE THREAD

**Issue by edausq** [bafolts/terraforming-mars#2431]
Hello,

The tag "latest" on docker hub: https://hub.docker.com/r/ltdstudio/terraforming-mars/tags is not updated after a commit on main branch.
Could you please enable/fix auto-build on push?

Thank you

**Comment by vsrisuknimit** [comment]
@ltdstudio

**Comment by bafolts** [comment]
This needs to be updated to use `main` branch.

**Comment by ltdstudio** [comment]
plaese use latest. I will update per 5-10 days.

**Comment by edausq** [comment]
Maybe we could have 2 tags, one that is weekly (5-10 days) built and that would be quite stable and another one that would be built on the last commit (trigger can be created from docker hub). What do you think?

**Comment by bafolts** [comment]
Any change that goes to the `main` branch we think works. Inevitable we do end up with some bugs making their way in. An older commit isn't necessarily more stable than a more recent commit. Using the most recent commit I would think is always more stable unless you could spot in commit history where we fixed a bug or reverted a change. We try to roll out new features and expansions slowly so by the time the feature or expansion shows up it shouldn't have that much impact on the game. I don't think we have ever had a major bug up for more than 24 hours.

**Comment by ltdstudio** [comment]
The current situation is that I fork baflots/terraforming-mars to ltd/terraforming-mars, then docker will autobuild to latest version.
but the process is manual.
If my docker hub auto connect to baflots/terraforming-mars, it will update to the latest in real time. But  this process requires Bafolts account permissions for setup, which I think is not safe.

**Comment by edausq** [comment]
A good practice could be to move the repository into a github organization and create a service user in the organization: https://docs.docker.com/docker-hub/builds/#service-users-for-team-autobuilds

**Comment by ltdstudio** [comment]
> A good practice could be to move the repository into a github organization and create a service user in the organization: https://docs.docker.com/docker-hub/builds/#service-users-for-team-autobuilds

I read the instructions and set them up. It doesn't work. It need Baflot to create a Docker Hub account by himself, then create an organization and connect Docker to GitHub (authentication is required), then create a member for me, then I use the member account to manage.
