### ISSUE TITLE
Bug When I Do"Pass for this generation"

### ISSUE THREAD

**Issue by ltdstudio** [bafolts/terraforming-mars#2438]
The newest Version can't  "Pass for this generation"

![bug](https://user-images.githubusercontent.com/39257428/104830329-bd94de00-5875-11eb-9147-21fc85bfece3.png)

So I revert .
 2b2f33b96da13e6509c14ffcda240a96db4bda79  This version works fine.

**Comment by kberg** [comment]
This should be fixed in head. My fault, my apologies.
