### ISSUE TITLE
Tactician milestone miscounting cards with requirements

### ISSUE THREAD

**Issue by puuj** [bafolts/terraforming-mars#2443]
Happening in latest build and seems to be an issue as far as a couple days back. 
<img width="145" alt="image" src="https://user-images.githubusercontent.com/58322/104833159-814c8800-584b-11eb-9296-202c82a52670.png">
<img width="574" alt="image" src="https://user-images.githubusercontent.com/58322/104833172-8e697700-584b-11eb-97fd-473972075b53.png">

**Comment by kberg** [comment]
What five cards do you have? What is this screenshot supposed to show as it pertains to the award?

**Comment by vsrisuknimit** [comment]
@sienmich #2378 and #2404 might have something to do with this. The bug is confirmed by other players.

**Comment by sienmich** [comment]
Yep, sorry, will fix
