### ISSUE TITLE
CEO's Favorite Project should allow adding a resource to any card on Self-Replicating Robots

### ISSUE THREAD

**Issue by kevinb9n** [bafolts/terraforming-mars#2453]
Expected: when playing CEO's Favorite Project, any card currently on SRR (which always have resources on them) should be included in the list of cards I can choose to add a resource to. This doesn't seem to be happening.

Note that Corroder Suits and Maxwell Base should also include cards on SRR that have a Venus tag (am not able to check if this already works).

From FAQ 1.6

<img width=500 src=https://user-images.githubusercontent.com/934551/104853838-4d5b7c00-58b8-11eb-8ba8-039924a78779.png>

**Comment by vsrisuknimit** [comment]
I was looking into this but too much trouble for what it is worth, at least for now. Very rare that someone would like to add 1 resource to cards on SRR anyway. There are many better uses of CEO's.

To handle both CEO and Maxwell and Corroder Suits, we might need a new property of SRR-resources on every card instead. Again that might be too much trouble.

**Comment by kevinb9n** [comment]
Just to add data, the situation came up for me again in solo. In gen 2 CFP popped into my hand. I had no cards that gather real resources, but I had Big Asteroid on SRR. Being able to buy it for only 3 MC in gen 4 (instead of free in gen 5) would have been a great use of the event, so I could get the robots working on something else in gen 5. Just mentioning that it may be rare but not nonexistent.

**Comment by bafolts** [comment]
This makes sense to add. If SRR is an available card we can't neglect it.
