### ISSUE TITLE
Bug: Robotics Workforce.

### ISSUE THREAD

**Issue by vsrisuknimit** [bafolts/terraforming-mars#2466]
![image](https://user-images.githubusercontent.com/14239220/104959708-cc2be400-59a0-11eb-9b61-d89a6e5565b0.png)

With Ares extension in play. 

https://terraforming-mars.herokuapp.com/player?id=c8c52653f83b

@kberg ?

**Comment by kberg** [comment]
Fixing now. Why didn't the unit test catch this?
