### ISSUE TITLE
RFC: Doing right by Robotic Workforce and Reds Policy on cards

### ISSUE THREAD

**Issue by kberg** [bafolts/terraforming-mars#2476]
Robotic Workforce and implementing Reds policy is are two brittle areas of the codebase. In this RFC I am proposing how to deal with both of them, even though they seem very different, I submit that their solutions are very similar, and that solution is to _provide new behaviors directly on cards._

## Robotic Workforce

Robotic Workforce is complicated, and we see it. I'm not going to describe how it works, this assumes you already understand it. But RoboticWorkforce has:
1. A list of all the cards eligible for RoboticWorkforce
2. A copy of all the production deltas for those cards
3. Custom code for cards that have dynamic behavior.
4. A test that ensures all eligible cards are registered with Robotic Workforce.

### Card.produce() and Card.canProduce()
I suggest adding two new optional fields on cards: `canProduce(player)` returns true if the player has enough production to pay for the the negative production units of that card. (and possibly other constraints, for those cards that remove production from other people.) `produce(player)` is the execution version of `canProduce` just like `canPlay` and `play` and `canAct` and `action`.

And now `card.play()` will look (sometimes) like so:
```
public play(player: Player) {
  this.produce(player);
  ...
}
```
so as to eliminate duplication
### Identifying cards eligible for Robotic Workforce
Now, instead of having to keep a list within RoboticWorkforce of all the cards eliglble, they can be determined with a simple test: any card with a building tag and a `produce` method is eligible. For cards that have a building tag but no production, we can add some notation on the card that it doesn't produce. For example, `Omnicourt`
 which has a building tag, and a `play` method:
```
public  play(player:  Player, game:  Game) {
  player.increaseTerraformRatingSteps(2, game);
  return  undefined;
}
```
One way to mark this as ineligible for RoboticWorkforce is to just change the definition of `canProduce` from `() => boolean` to `() => boolean | false` . Cards like `Omnicourt` will have this in their static definitions

```
canProduce: false,
```

### Identifying building tag cards without a `canProduce` method
And finally, we retain our unit test to catch new cards, but it limits it to those without a `canProduce` definition.

### What about all that stuff with `productionDelta`?
I've started to remove some of the pain by introducing a card field called `productionDelta`. It's a bad name. I propose renaming it to `productionBox`, since that is what it is. And it can work right along side of `canProduce` and `produce`

```
canProduce(player) {
  return Units.hasProduction(this.productionBox, player);
}
produce(player) {
  Units.adjustProduction(this.productionBox, player);
}
```

Simple.

## Reds Policy
So many cards have this bit of code in their `canPlay`. In fact, `Omnicourt` works again:

```
canPlay():  boolean {
  const  hasRequiredTags  =  player.checkMultipleTagPresence([Tags.VENUS, Tags.EARTH, Tags.JOVIAN]);

  // This appears EVERYWHERE
  if (PartyHooks.shouldApplyPolicy(game, PartyName.REDS)) {
    return  player.canAfford(player.getCardCost(game, this) +  REDS_RULING_POLICY_COST  *  2, game, true)
       &&  hasRequiredTags;
  }

  return  hasRequiredTags;
}
  
play() {
  player.increaseTerraformRatingSteps(2);
  return  undefined;
}
```

So what's that bit of code doing? `return player.canAfford(player.getCardCost(game, this) + REDS_RULING_POLICY_COST * 2, game, true)`

Well, `player.canAfford(player.getCardCost(game, this))` says "Can the player pay the cost of this card? With all their heat and steel and titanium and microbes, can they?

Isn't that already checked before `canPlay()`? Yes. It's checked in `Player.getPlayableCards`.
```
return  maxPay  >=  this.getCardCost(this.game, card) &&
  (card.canPlay  ===  undefined  ||  card.canPlay(this, this.game));
```
The only reason it's repeating it here is because when Reds are in power, the card's cost has gone up! This card which raises TR 2 steps is now 6MC more expensive. So `canPlay` is repeating what `getPlayableCards` did, only it's adding 6MC. How silly.

So in this case, let's move everything about the Reds policy to `getPlayableCards`.

```
let cost = this.getCardCost(this.game, card);
if (PartyHooks.shouldApplyPolicy(game, PartyName.REDS)) {
  cost += REDS_RULING_POLICY_COST * terraformingRatingBump;
}
return  maxPay  >= cost &&
  (card.canPlay  ===  undefined  ||  card.canPlay(this, this.game));
```
And now nobody has to check for reds policy costs in cards again.

### Wait a minute.
What's that variable `terraformingRatingBump`?

Yep, you caught me. Right. A card that increases their terraforming rating now would identify it. So we add yet another method on `ICard`, `ICard.getTerraformingRatingBump` which returns the expected terraforming rating increase. This would apply to oceans, TR, or anything else that grants TR as part of the card's behavior.
## That's it.
I hope you found this useful. And I am confident this lead to more flexible code that is easier to maintain. It is important that any such changes are well-documented. And I guess this post is a start of some kind.

**Comment by Lynesth** [comment]
#### Robotic Workforce
> Now, instead of having to keep a list within RoboticWorkforce of all the cards eliglble, they can be determined with a simple test: any card with a building tag and a produce method is eligible. For cards that have a building tag but no production, we can add some notation on the card that it doesn't produce. For example, Omnicourt

Just check if they have a `produce` method or not, why add `canProduce` to all cards ?
```ts
if (card.tages.includes(Tags.BUILDING)
    && card.produce !== undefined
    && card.canProduce !== undefined
    && card.canProduce()) {
```

#### Reds
This is what I would call a refactoring (since it doesn't change how cards behave with the policy), so sure, why not.

**Comment by kberg** [comment]
> #### Robotic Workforce
> > Now, instead of having to keep a list within RoboticWorkforce of all the cards eliglble, they can be determined with a simple test: any card with a building tag and a produce method is eligible. For cards that have a building tag but no production, we can add some notation on the card that it doesn't produce. For example, Omnicourt
> 
> Just check if they have a `produce` method or not, why add `canProduce` to all cards ?
> 
> ```ts
> if (card.tages.includes(Tags.BUILDING)
>     && card.produce !== undefined
>     && (card.canProduce === undefined || card.canProduce())
> ) {
> ```

Maybe? I'm trying to wrap your head around the impact of your suggestion. That piece of the suggestion is there so that it's intentionally clear that a building card is either part of the robotic workforce, or it is not.  And .... I think what you're suggesting can work.

> #### Reds
> This is what I would call a refactoring (since it doesn't change how cards behave with the policy), so sure, why not.

Yeah, I'd agree. thanks.
> _Edit: Updated code snippet._

**Comment by sienmich** [comment]
I like this very much, I had similar thoughts.
I'd like to add some things:
1. There are a lot of cards where production varies on some player tags. In your proposed solution we just override the `produce(player)` and skip the `productionBox` then, right? I like this approach.
2. What about the global parameters bonuses? Like extra ocean at °C. Are they somehow currently resolved with reds? I don't think so. We could check that simply by having  the `terraformingRatingBump` split into `terraformingRatingBump`, `temperatureBump`, `oxygenBump`, ... . This approach also leads to further possible `card.play()` automation.
3. You probably won't like this so much, but we could generate both `productionBox` / `produce(player)`  and `terraformingRatingBump` automaticly from the cards metadata. I know that's not the purpose of metadata, but I think that with a bit of those metadata refactor we could easily do it in a elegant way.
4. There is also third part of `canPlay` that repeats a lot - placing tiles, checking it there are free spots, that could be also refactored in the future.
5. Last idea - maybe sometimes instead of having `play()` + `canPlay()` or `act()` + `canAct()` it would be nice to have some kind of a `play()` that can reverse itself and throw exception when for example production < 0. Just a thought this one.

What do you think?

**Comment by kberg** [comment]
> I like this very much, I had similar thoughts.
> I'd like to add some things:
> 
> 1. There are a lot of cards where production varies on some player tags. In your proposed solution we just override the `produce(player)` and skip the `productionBox` then, right? I like this approach.

Correct. Someone (I guess me) should add a comment in Card describing how `productionBox` works and eventually how it could be ignored.

> 2. What about the global parameters bonuses? Like extra ocean at °C. Are they somehow currently resolved with reds? I don't think so. We could check that simply by having  the `terraformingRatingBump` split into `terraformingRatingBump`, `temperatureBump`, `oxygenBump`, ... . This approach also leads to further possible `card.play()` automation.

That is an undoubtedly tricky situation. The player who wants to place 8 plants such to trigger the 3 TR bump. Or the Helion player who raises the reaches 0 degrees. It's probably good to get this edge case right. But also I don't think there is any rush.

The more complicated of these cases is the Hellas ocean space, and also covering an Ares hazard. Not only do you need the cost to cover the hazard tile, but also pay for Reds tax. (Note that all of Ares sidesteps this by not even dealing with Reds at the moment.

In some ways I'd be OK with some of these costs allowing players to go negative for a short time with an end-game penalty of 1 point per MC in debt you might be. (Or something less nasty.)

Obviously there are better alternatives which we should discuss in another issue. So moving along...

> 3. You probably won't like this so much, but we could generate both `productionBox` / `produce(player)`  and `terraformingRatingBump` automaticly from the cards metadata. I know that's not the purpose of metadata, but I think that with a bit of those metadata refactor we could easily do it in a elegant way.

Yep! You're right, sorry. But you know, different ideas and all that. If that's the way all the automation goes, then perhaps, but I wouldn't suggest these lead the way.

> 4. There is also third part of `canPlay` that repeats a lot - placing tiles, checking it there are free spots, that could be also refactored in the future.

For sure.

> 5. Last idea - maybe sometimes instead of having `play()` + `canPlay()` or `act()` + `canAct()` it would be nice to have some kind of a `play()` that can reverse itself and throw exception when for example production < 0. Just a thought this one.
> 
> What do you think?

I think as a nugget in and of itself it's a good idea. But pehaps needs more time to grow into a fuller idea that fits into a bigger picture? Reversing actions is one thing (we have to deal with reversing trade fleets in cards just because of that one card, which is it -- I can't remember.)

**Comment by bafolts** [comment]
@kberg the update for Robotic Workforce and the change for Reds Policy seem unrelated. Making one issue for each should help with the discussion of the issue and closing one issue at a time.

**Comment by kberg** [comment]
As features, yes. As an RFC, I think this is correct.

**Comment by bafolts** [comment]
I think both of these suggestions are great. Is the next step to create one issue for each part?

**Comment by kberg** [comment]
Sure, that makes sense.

**Comment by kberg** [comment]
Yeah, seems reasonable now that you put it that way.

>
