### ISSUE TITLE
Log error: plant production instead of plant ressources

### ISSUE THREAD

**Issue by dabewi** [bafolts/terraforming-mars#248]
Whenever plants are reduced, e.g. by Deimos Down or an Asteroid, the log states that the plant production is reduced. In fact the plant ressources are reduced, not the production:

https://abload.de/img/bug2xnkj5.png

**Comment by bafolts** [comment]
You are running an older commit. This was fixed in https://github.com/bafolts/terraforming-mars/commit/9d9b0cb5efd773c8b56a3faf2703e6ba5ef3f2d5
