### ISSUE TITLE
Bug: cannot see who you are passing cards to

### ISSUE THREAD

**Issue by vsrisuknimit** [bafolts/terraforming-mars#2480]
![image](https://user-images.githubusercontent.com/14239220/105054149-aa356e80-5a3f-11eb-8606-8dbd46c96575.png)

![image](https://user-images.githubusercontent.com/14239220/105053988-840fce80-5a3f-11eb-80e4-c30c7e1507c8.png)

@bafolts problem with new selecInitialCards?

**Comment by nwai90** [comment]
Resolved by https://github.com/bafolts/terraforming-mars/pull/2479
