### ISSUE TITLE
Bug: selectHowToPay is broken

### ISSUE THREAD

**Issue by vsrisuknimit** [bafolts/terraforming-mars#2483]
![image](https://user-images.githubusercontent.com/14239220/105113953-f0b4b880-5a93-11eb-82ee-422b7cb74785.png)

- The amount of metal is not adjusted to max possible by default as it used to be.
- Can't pay for a card with zero cash even with enough Ti.

@kberg ?

**Comment by vsrisuknimit** [comment]
![image](https://user-images.githubusercontent.com/14239220/105114883-cbc14500-5a95-11eb-9517-79ffd2f8838c.png)

In this case, the pre-filled number should be 7 mc 1 steel.

**Comment by vsrisuknimit** [comment]
![image](https://user-images.githubusercontent.com/14239220/105115145-4f7b3180-5a96-11eb-8bf5-4574c5145af7.png)

**Comment by kberg** [comment]
Sorry, I thought I had enough tests, I'll fix this tonight.

**Comment by vsrisuknimit** [comment]
@kberg I cannot replicate the problem (not enough payment) so far. Trying multiple situations. Can't replicate. So don't worry too much about that for now.

For the default value when you have 0 mc. I will leave that up to you. I think if the card is available to select, the pre-filled value should be enough to pay for it.

**Comment by kberg** [comment]
I'm sure it's broken. This was front-end code with zero tests, now there are _some_ I'm on it.

**Comment by vsrisuknimit** [comment]
That PR was also merged 3 days ago and this is the first complaint about it. It might require very specific triggers to cause the problem. Not sure.

**Comment by kberg** [comment]
Do you know if this is on the demo site?

**Comment by vsrisuknimit** [comment]
Lynesth's server. Player link here: (https://terraforming-mars.lemur.nc:8888/player?id=d7c4eabfdedc) Game ongoing. Be careful.

@Lynesth  merged from the main repo this morning or yesterday I believe.
