### ISSUE TITLE
View board, milestones and awards  and starting hand before choosing the corporation

### ISSUE THREAD

**Issue by dabewi** [bafolts/terraforming-mars#249]
I think it would be an improvement if the player is able to see the board (especially now when you can also play on Hellas and Elysium). This also counts for milestones and awards  and the start hand since as a player I want do consider awards, milestones, prelude cards and my starting hand if I choose which corporation I will play.

**Comment by bafolts** [comment]
You should already be able to see the corporation and the cards you are going to start with for the first action phase. Showing the awards, milestones, and board would make sense and could probably show them only if clicked to expand some area for more information.

**Comment by dabewi** [comment]
Yes, the expand option sounds like a good idea.

**Comment by vincentneko** [comment]
I second this.
Colonies will also need to be visible before choosing corporation.

**Comment by alrusdi** [comment]
This is done
