### ISSUE TITLE
Some issues with prelude extension

### ISSUE THREAD

**Issue by dabewi** [bafolts/terraforming-mars#25]
Hi,

first of all: Thumbs up for the project!

Today I started a game with a colleague with prelude extension activated. There were some issues:

1. When I'm able to choose which action I want to perform there is no option to play a prelude card. Apparently I can play prelude cards via the option "play project card". An option to eplicitly play prelude cards would be nice.
2. When I try to play a project card before I've played my prelude cards, the browser gives me an "input" error. It would be nicer if the game would actually tell me what is wrong with playing the project card first
3. After I played my prelude cards my opponent was forced to build his city (he played Tharsis) before he even played his prelude cards - which is not how it works (prelude cards have to be played first). After that he played his first prelude card and passed. Now it was my turn but I couldn't play a project card (presumably because my opponent hadn't played all of his prelude cards) BUT i could play the standard project aquafier, which was weird.

If you have the possibility to look into the game (we played it on your test server), it was apehead vs. DartVader.

Greetings!

**Comment by vincentneko** [comment]
Hello,

Thanks a lot for your feedback 

You are right, prelude rules are not implemented as stated in the rule book.
I will try to get this fixed, I might take some time.
Issue 2 is not related with prelude. You can (which is not correct) play a project card before a prelude card. The "input" error may be related to an unmet prerequisite or a wrong amount.
Issue 3 is also strange and might be related with issue 2.

I will also update solo play to stop at 12 generations instead of 14 when prelude is activated.

**Comment by vincentneko** [comment]
Hello,
This should work as intended now. If you can give it a try, feedback is welcome.

**Comment by dabewi** [comment]
Hi!

Thanks for fixing the prelude issue, that works greatly!

Regarding issue #3 in the start posting - it still occurs. After I played against myself in a private Firefox window the text on both players is "Not your turn to take any actions". The ids are:

https://terraforming-mars.herokuapp.com/player?id=88325f398c9c
https://terraforming-mars.herokuapp.com/player?id=cd87a7bf8619

Both played some prelude cards and one aquifier action and now the game seems to be stuck.

Cheers!

**Comment by vincentneko** [comment]
Hi,

Thanks again for the feedback. I tried to reproduce the issue in a 2 players game but it did not occur.
I'm usually available between 12:30 and 14:00 during the week, if you want we can try to play a game.

Cheers

**Comment by dabewi** [comment]
Hi vincentneko,

I'd glad to play a game. Which timezone do you refer to?

Cheers

**Comment by vincentneko** [comment]
France (GMT+1), about you ?

**Comment by dabewi** [comment]
Same here. :)

**Comment by vincentneko** [comment]
Great !
Please send me an email (vincentneko@gmail.com) so we can setup a schedule

**Comment by vincentneko** [comment]
I guess this issue is fixed.

Btw the new board is awesome, and it's working fine on mobile !
