### ISSUE TITLE
Player board: the so-called "wild tag" should be on the other side of the new dividing line

### ISSUE THREAD

**Issue by kevinb9n** [bafolts/terraforming-mars#2510]
> @kevinb9n @vsrisuknimit can we decide what needs to be before the separator?
> I thought wild tag was counted towards Interplanetary Trade, if not maybe we should move it?

If you have all 10 tag types (Venus: 11), then a "wild tag" will *not* cause Interplanetary Trade to give you 11 mc production (Venus: 12). You can only make it become some real tag type, but you already have all of them.

(If jeep doesn't reply soon, I'll point out that he did seem to agree with this already in the issue comments.)

_Originally posted by @kevinb9n in https://github.com/bafolts/terraforming-mars/issues/2402#issuecomment-761610319_

**Comment by kevinb9n** [comment]
@chosta it's a small thing, but I think the current approach actively feeds a common rules misconception.

I do think it should be first after the line.

**Comment by chosta** [comment]
I have plans to fix that in the next player interface improvement.

**Comment by kevinb9n** [comment]
thanks! just, y'know, wanted to give you the satisfaction of an issue to close :-)

**Comment by chosta** [comment]
#2557 shold close this
