### ISSUE TITLE
Critical Gameplay Bug: Discarded cards become available again before deck reshuffling

### ISSUE THREAD

**Issue by vsrisuknimit** [bafolts/terraforming-mars#2537]
![image](https://user-images.githubusercontent.com/14239220/105614861-3f1acd80-5d9a-11eb-8e94-9f450b37835f.png)

![image](https://user-images.githubusercontent.com/14239220/105614869-4641db80-5d9a-11eb-9904-4d74c57c6e40.png)

@nwai90 and other players I talked to also experience this bug.

I tried to reproduce it in solo mode but could not observe the bug so far.

**Comment by bafolts** [comment]
I am a believer in fixing bugs before writing new code. I will check this out before I write new code.

**Comment by bafolts** [comment]
Thinking out loud. The discarded array and deck array within Dealer are fairly straight forward. What could also be happening here is that we unintentionally load duplicate cards into the deck.

**Comment by Lynesth** [comment]
Another report from Discord:
> I had this happen in a solo game somewhat recently. Didn't draft a card, got it in hand soon thereafter from a pluto trade. No resuffle in between. Thought I was going mad/mixing up cards.

**Comment by bafolts** [comment]
So far I am not spotting any place we introduce duplicates into the deck. Trust this is happening on some way but have yet to recreate the issue.

**Comment by Lynesth** [comment]
I spent quite some time as well trying to find a reason for this, even experimenting restarting the server and so on, to no avail.
I'm proposing to add #2555 for now to maybe help users give us better reports about this.

**Comment by vsrisuknimit** [comment]
I am going to close this for now and reopen later if we get more information. I think we did try hard enough to reproduce the issue although to no avail.
