### ISSUE TITLE
Serialize deferredActions with Game

### ISSUE THREAD

**Issue by bafolts** [bafolts/terraforming-mars#2538]
When we serialize a game we set `deferredActions` to an empty array. We should serialize the deferred actions and deserialize them. This will make the undo operation more reliable and allow us to eventually let the user undo any operation.

https://github.com/bafolts/terraforming-mars/blob/main/src/Game.ts#L394

**Comment by Lynesth** [comment]
There won't be any when we serialize the game since we're saving at times when the deferred actions queue is empty.
Are we planning on saving more often ?

**Comment by bafolts** [comment]
I would like to save more often. Ideally we would save after every player input. During server restarts we then wouldn't lose any data. I am thinking about this in isolation. When `Player` or `Game` is serialized and deserialized we should end up with the same instance.
