### ISSUE TITLE
Ecological Zone / Viral Enhancers

### ISSUE THREAD

**Issue by dabewi** [bafolts/terraforming-mars#254]
Hi,

the combination of Ecological Zone and Viral Enhancers might be buggy:

Viral Enhancers should generate 1 extra animal per tag on another card. Ecological Zone has two tags (animal and plant), so it should get 2 extra ressources from Viral Enhancers. Ecological Zone itself should also get two ressources from it's own two tags. Right know if it is played when Viral Enhancers are already played it only gets two ressources instead of 4 it should get (2 from the card itself and 2 from Viral Enhancers).

Screenshot: https://abload.de/img/2020-02-12_15h39_11qdjgr.png

Maybe the method to grant extra ressources is only triggered once and not per tag?

**Comment by dabewi** [comment]
> Hi,
> 
> the combination of Ecological Zone and Viral Enhancers might be buggy:
> 
> Viral Enhancers should generate 1 extra animal per tag on another card. Ecological Zone has two tags (animal and plant), so it should get 2 extra ressources from Viral Enhancers. Ecological Zone itself should also get two ressources from it's own two tags. Right know if it is played when Viral Enhancers are already played it only gets two ressources instead of 4 (2 from the card itself and 2 from Viral Enhancers).
> 
> Screenshot: https://abload.de/img/2020-02-12_15h39_11qdjgr.png
> 
> Maybe the method to grant extra ressources is only triggered once and not per tag?

**Comment by bafolts** [comment]
Both the `Ecological Zone` implementation and the `Viral Enhancers` implementation do seem wrong.

For `Ecological Zone` we should add one for each tag found which is the easier of the two fixes.

https://github.com/bafolts/terraforming-mars/blob/master/src/cards/EcologicalZone.ts#L41

For `Viral Enhancers` we also need to apply the effect per tag and not overall. In the situation where there is more than one tag that adds to the effect we will have to use an `AndOptions` so the user can select if they want a plant or to add a resource to the card.

https://github.com/bafolts/terraforming-mars/blob/master/src/cards/ViralEnhancers.ts#L17

This will lead to an `AndOptions` with multiple `OrOptions` which should work fine. With the recent change to not show the child save buttons the user should only have to click save once after selection all options.

**Comment by vincentneko** [comment]
Fixed and merged
