### ISSUE TITLE
Suggestion: Expanded end screen

### ISSUE THREAD

**Issue by dabewi** [bafolts/terraforming-mars#255]
Hi,

in think it would be an improvement for the game to have the possibility to expand the end screen to show e.g. the last moves (just show the log), the funded awards and the award rankings of the players. I'd also like to thee the board in the final state.

Right now if one opponent ends the game it's possible to miss the final moves he made because there is no way from the end screen back to the game.

In fact it would be sufficient to add a possibility to return to the game screen.

Cheers!

**Comment by dabewi** [comment]
This is done, isn't it?

**Comment by alrusdi** [comment]
No, i don't have a good solution for returning to the final game.

**Comment by vincentneko** [comment]
Maybe returning to the final game is not required.
Adding the game log could be a nice addition, I'm also in favor of storing award rankings for each players.

**Comment by dabewi** [comment]
I think returning to the game screen is not required. I initially thought that this would be the easiest solution, because any needed information is stated there. But it's not necessary.

The game log would be nice though. And a little bit more information about the award rankings would be neat, too.

**Comment by gomfunkel** [comment]
Created pull request #395 to add the final game log to the end game screen. Award details are still not there.

**Comment by gomfunkel** [comment]
Can someone assign me to this, please? I am going to implement the award part on the end screen as soon as I‘m done with the #286.

**Comment by vincentneko** [comment]
> Can someone assign me to this, please? I am going to implement the award part on the end screen as soon as I‘m done with the #286.

Done

**Comment by gomfunkel** [comment]
Implemented and merged to master with #439. Feel free to close this issue, @dabewi.
