### ISSUE TITLE
Allow custom prelude list

### ISSUE THREAD

**Issue by Maelstrom1** [bafolts/terraforming-mars#2554]
My circle has decided that ecology experts needs to be removed from our games because it always seems to either guarantee victory or is completely ignored. However, preludes aren't included in the "exclude card" list. If they could just be thrown in that drop-down menu or something, that would make life a lot better. 

edit: originally said the wrong prelude name, making for a bad anecdote

**Comment by kevinb9n** [comment]
I was surprised to learn that the existing exclude-specific-cards interface doesn't work for prelude cards too. I think it should.

**Comment by Maelstrom1** [comment]
Bumping this because it would certainly be nice to have and I can't imagine it would take _too_ much work to implement

**Comment by alrusdi** [comment]
@bafolts may i take this task? I want to improve a visual part too (it is kinda broken now)

**Comment by kberg** [comment]
Ok not Brian but I'm pretty sure you can.

**Comment by bafolts** [comment]
Yes. I usually assign these to myself to find them later. Will assign to you @alrusdi .

**Comment by alrusdi** [comment]
This is implemented
