### ISSUE TITLE
Suggestion: Show the active player

### ISSUE THREAD

**Issue by dabewi** [bafolts/terraforming-mars#257]
Maybe it would be an improvement to show the active player.

Under the "Turn order" there could be an extra line with "active player: XXX".

Background: You don't have to look at the log to check which players have already passed. You know directly who you have to address if everybody is waiting for someone to play.

**Comment by alrusdi** [comment]
This is already implemented. Active player shown as underlined in "Turn order" block. Is it working for you?

**Comment by dabewi** [comment]
Ah yes, I just was blind. ;)

Thanks!
