### ISSUE TITLE
Rethinking the Venus Milestone/Award config option

### ISSUE THREAD

**Issue by kevinb9n** [bafolts/terraforming-mars#2577]
Assuming the Venus Next expansion is enabled. There are two different cases:

**When "Random Ms/As" is disabled:**

... Are we sure that users really mind sticking to the published rules? Being able to uncheck "Venus M/A" is a straight nerf to Morning Star, Celestic, Stormcraft, Titan, and expensive cards that add floaters quickly... none of which really need nerfing.

**When "Random milestones" is enabled:**

... In this case, sticking to the published rule (Venus M/A always included) would just feel too weird, so the cards mentioned above will be weakened. However, the Venus M/A should really *always* be in the pool to choose from – I don't think we need an option to turn them off. And it should always just choose 5 because there is no real reason to need 6. So, the cards are debuffed only in *some* games.

If the behavior was as described above, would we really need the option at all?

Some of the above should apply equally to Ares, it just doesn't have the same 'Ares milestone' config option to get rid of.

**Comment by kevinb9n** [comment]
Saw this in #vote-for-issues. Note that removing an option isn't generally something people will vote for. Also this issue is about making things work in a different way so that the option is even less needed, which won't be clear there.

**Comment by kevinb9n** [comment]
Happy to re-grab this if more votes come in, but for now, it's telling a story:

<img width=650 src=https://user-images.githubusercontent.com/934551/107828471-cc1fc980-6d3d-11eb-8bdc-f02c3225040c.png>

This addresses only the random-milestones case. So far it suggests that:

* My predictions that users don't really want 3 or 4 were probably right.
* My prediction that users don't really want 2 was wrong. There is interest in both 5-milestone and 6-milestone games. However, this very unlikely has anything to do with Venus Next specifically; they would just like an option to control the number in general, whenever they use randomization. (I asked for anyone to say otherwise if it was Venus-related, nothing yet.)

I didn't poll about what people want when NOT randomizing. I doubt we'd head hear from many discord users about that. I still think it unlikely that they actually care about banning Hoverlord/Venuphile against the published rules.

All this suggests that users may be happy with:

* NO "Venus Milestone/Award" option
* When randomizing is off, always add them
* When randomizing is on, always have them in the pool, and have an option for whether to pick 5 or 6

I think Ares could work the same way, even though it does mean some games will have *seven* milestones.

**Comment by kberg** [comment]
That makes sense. The Moon will add one more of each.

I envision being able to move milestone and award selection fully to the
client-side when a game is created. Right now they're established during
game instance construction. By making the decision client-side, all of
these difficult decisions can even be put into a visual representation
where the player would be able to randomize and re-randomize if they want
specific results. Or even enter them one at a time.

**Comment by kberg** [comment]
I'm about to add the Moon milestone and award. Those will have their own synergy (high synergy) and unless this gets refactored, it'll just be tagged on like the Ares ones. This doesn't have to resolved beforehand, but it does suggest this ought to be considered.

**Comment by kberg** [comment]
> When randomizing is on, always have them in the pool, and have an option for whether to pick 5 or 6

Or, even a higher value?  Currently with Ares enabled, no matter what it'll be 7 "random" options (one of which will always be an Ares one.)

So I suggest that the number of milestones and awards is just a parameter fed into the machine.

**Comment by vsrisuknimit** [comment]
That is fine. I think it is good to be able to adjust the number of Ms and As. 

For how the selector works with fan-made expansions, I don't particularly care one way or the other as long as:
- Ares and Moon milestones/awards are not used without Ares and Moon.
- The rules for normal milestones and awards selector are the same or close to the same. Make sure the probability is still somewhat even for each milestone.

**Comment by kberg** [comment]
That makes sense.

>
