### ISSUE TITLE
Extend timers to count up to 999 hours?

### ISSUE THREAD

**Issue by puuj** [bafolts/terraforming-mars#2585]
Currently timers will wrap around after hitting 24 hours. This isn't a big deal, but sometimes it's interesting to see how long a player has taken cumulatively. To make timers a bit more transparent, I made a personal mod to use 3 digits for the hours. If this is something others would appreciate, I'd be happy to contribute.
![image](https://user-images.githubusercontent.com/58322/106200284-9985a680-616b-11eb-8dc4-9aec2b4189e4.png)

**Comment by chosta** [comment]
We are actually trying to reduce the space for timers by but this makes sense for games that are played based on availability. The best solution imo is to add days to if it passes the 24h mark. What you currently show is an outdated version of the timer, please get your server updated to check the new design.

**Comment by vsrisuknimit** [comment]
Timer does not make any sense for async games anyway and probably should be turned off. What does it mean if someone (Player A) gets 8 hr added to their timer just because the previous player took an action at midnight when player A already went to bed?

**Comment by puuj** [comment]
It means we get to make fun of them for not being sufficiently dedicated to the game. It's all in fun for now. 
Although if you're interested, I have lots of ideas about how timers could include, for example, a schedule of when timers are running (e.g., M-W, 6p-9p) that would sidestep this issue. Probably overkill, but...

> Timer does not make any sense for async games anyway and probably should be turned off. What does it mean if someone (Player A) gets 8 hr added to their timer just because the previous player took an action at midnight when player A already went to bed?

**Comment by puuj** [comment]
Sure, I update roughly weekly but I checked out the current Heroku implementation. Since the change is simply in how the time string is returned, I don't think it will alter anything in the code. 

Technically, 999 hours will cover ~40 days with one digit (and no separator) whereas supporting that number of days requires adding 2 digits and a separator, so more space. Days might be more user friendly, though. 
 
> We are actually trying to reduce the space for timers by but this makes sense for games that are played based on availability. The best solution imo is to add days to if it passes the 24h mark. What you currently show is an outdated version of the timer, please get your server updated to check the new design.

**Comment by kberg** [comment]
> Timer does not make any sense for async games anyway and probably should be turned off. What does it mean if someone (Player A) gets 8 hr added to their timer just because the previous player took an action at midnight when player A already went to bed?

I've had async games where only until after it was done that on average 3 of the four players took ~8 hours delay, and one took 20 days. It was really useful.

**Comment by vsrisuknimit** [comment]
I am fine with adding days or changing hour count to 999. Just make sure to hide those numbers until the timer count that high. We don't want to overload typical users who play under an hour with those information.

**Comment by kberg** [comment]
Fair. I don't actually have a horse in this race, so whatever you come up
with is fine I'm sure.

**Comment by bafolts** [comment]
I agree with @vsrisuknimit that the digits shouldn't show up until they are needed.

I would use HHH:MM:SS as the format versus days. If I saw 04:42:21:42 I wouldn't know that the 04 was days.

**Comment by puuj** [comment]
I implemented the expanded timer. Currently the template is designed to show hh:mm:ss. Is it preferable to add conditional logic to the template to dynamically show hh: later?


> I am fine with adding days or changing hour count to 999. Just make sure to hide those numbers until the timer count that high. We don't want to overload typical users who play under an hour with those information.
> 
> So go from
> 50:10 (50 min 10 sec)
> to
> 1:10:10 (1hr, 10 mmin, 10 sec).
> 
> Instead of 00:00:50:10 (0day 0hr, 50 min, 10sec).
