### ISSUE TITLE
Allow configurable number of log lines?

### ISSUE THREAD

**Issue by puuj** [bafolts/terraforming-mars#2587]
The current log buffer is 50 lines. On my server, I run with 500 lines which is great for longer games that take several days. It should be fairly straightforward to add a .env variable for this to allow this to be configurable.

**Comment by chosta** [comment]
This is part of #1233 and will be done in the upcoming months.

**Comment by puuj** [comment]
Thanks for the update. I was wondering the development philosophy here (after reading the updated Contribution guidelines). Updating the loglines via an .env parameter only involves updating a couple lines of code. Is there an objection to smaller incremental changes because this may confuse people when the larger update is made?

**Comment by kberg** [comment]
Thanks for asking. I actually don't think there's anything wrong with such
a change, unless @Danimir considers it might be obsolete at some point.

>
