### ISSUE TITLE
Two identical corporations in the beginning

### ISSUE THREAD

**Issue by dabewi** [bafolts/terraforming-mars#259]
Hi,

one colleague of mine came across a bug. In the beginning of our 3 player game when he has to choose his corporation both corporations are the same:

https://abload.de/img/screenshot_20200214-0jbk50.png

Also, this still runs on an old build. So if this issue is already resolved, you may just close it.

Greetings!

Edit: Maybe this is just a simple error like the corporation is twice in the list.

**Comment by vincentneko** [comment]
I confirm this is a bug, and I checked, the corporation  is not listed twice.

**Comment by bafolts** [comment]
Is a custom list of corporation cards selected when this issue is recreated? Are there steps which recreate it?

**Comment by bafolts** [comment]
This issue seems to get worse every time a new game is created. Somewhere we must be growing the list of corporation cards during each new game creation.

**Comment by bafolts** [comment]
I have a fix up for this, we were modifying the array of all corporation cards. This issue would have gotten worse the more games that were played without restarting the game server.

**Comment by vincentneko** [comment]
Thanks for fixing this !
