### ISSUE TITLE
"to place a 2"

### ISSUE THREAD

**Issue by kevinb9n** [bafolts/terraforming-mars#2591]
![image](https://user-images.githubusercontent.com/934551/106238973-aed3f280-61b6-11eb-9ffb-11e74201e330.png)

**Comment by kevinb9n** [comment]
I've been seeing this since I started seeing #2486 - not sure if coincidence.  @daniel-ziegler

**Comment by daniel-ziegler** [comment]
Is this for Ares hazards?

**Comment by kberg** [comment]
I'm asking to reopen the issue so the fix is made on the client-side.

**Comment by kevinb9n** [comment]
Hmm, looks like this is still happening in downloaded log files, if not in the UI.

**Comment by kberg** [comment]
@kevinb9n link to game? I'll take a look.
