### ISSUE TITLE
Discussion regarding Units

### ISSUE THREAD

**Issue by Lynesth** [bafolts/terraforming-mars#2599]
I did not have a chance to actually read it before, because it only concerned the Moon expansion, but since it's now crawling into the base game, I took a look at it and here are my thoughts.

The first issue I have with it is that it is indiscriminately used for both **production** and **resources quantity**.

Second, using `Units.of` (which, after some thougths, probably should have been better named `Units.from`) all the time is a pain.
Functions that deal with `PartialUnits` should be the one to call that function instead if they need it (which they probably don't).
So in the end, a card would only declare `production: {megacredits: 3, energy: -1}` instead of `production: Units.of({megacredits: 3, energy: -1})`.

Next, I think the functions in the `Units` namespace should be non-static methods on `Player` (names are just examples):
| Old | New (non-static) |
| ----- | ----- |
| `Units.hasUnits` | `Player.hasResources` |
| `Units.canAdjustProduction` | `Player.hasProduction` |
| `Units.deductUnits` | `Player.removeResources` |
| `Units.adjustProduction` | `Player.increaseProduction` <br> `Player.decreaseProduction` |

And lastly, a question: Why are we passing around that `Units.EMPTY` thing ? It's probably something we can get rid of ?

-----

So, in the end, I don't think we need an object look-alike to hold those values, but simply one interface to properly frame for TS what's allowed in it or not (maybe two interfaces, one for productions and one for resources) and methods that are able to work with that data properly.

@kberg @nwai90 @sienmich @bafolts

**Comment by sienmich** [comment]
Do we want to have player resource and production as Units?
```ts
class Player {
public resources: Units;
public production: Units;
```
That's an important question, other things kinda depend on it.

I think it's a good idea. It seems natural to me. It creates logical separation between player's resources and other attributes.
We could have some shortcut getters if needed: 
```ts
  public get heat(): number {
    return this.resources.heat;
  }
```

**Comment by sienmich** [comment]
The `Partial<Units>` are just `Units`, where every unit is optional (`Partial` is a TS type). Yep, we should require `Partial<Units>` instead of `Units` most of the times.

I absolutely agree about those function names. Right now they are nonintuitive. I like your names propositions.

**Comment by kberg** [comment]
I agree the function names are bad. I'm not happy with reserveUnits being negative to any ot her use. In my internal discarded prototype, those methods were all in Player. But I didn't want to impose on the Player API until this felt worthwhile. So I agree with a bunch of that. More on this topic later when I'm done working for the day.

**Comment by nwai90** [comment]
Conceptually, I disagree with the way `Units` is currently set up. Taking a step back to look at the use case and why this structure exists it becomes apparent that this is necessary for certain fan-made cards in the Moon expansion. It is a reasonable construct for this purpose imo and should ideally be encapsulated as such, rather than starting to perforate the entire codebase.

The only card in the official game that invokes this notion of a reserved unit is Stratospheric birds (lose 1 floater) which has already been cleanly handled. `production: Units.of({megacredits: 3, energy: -1})` and other current naming either feel verbose and/or unintuitive. In the majority of cases we also do not actually require additional complexity - a `PlayerResource` interface with properties for each of the 6 standard resources could well suffice here.

**Comment by Lynesth** [comment]
> Do we want to have player resource and production as Units?

I guess. Not sure what it would improve right now. In my opinion, it's something to think about once Units has been rewritten.


> `PlayerResource` interface with properties for each of the 6 standard resources could well suffice here.

Yes. This is what I mean. Having a simple interface that goes like this (whatever the name ends up being)
```ts
interface PileOfResources {
  megacredits?: number,
  steel?: number,
  titanium?: number,
  plants?: number,
  energy?: number,
  heat?: number,
}
```
is the way to go for me. It can then be used a the few places to type properties or method arguments.
I think it doesn't need a namespace nor any functions. Just a simple Typescript interface.

I'll propose a small PR of my vision if it helps seeing how things would turn out with it.

**Comment by sienmich** [comment]
I'd call them `StandardResources` - that's how they are called in the game.

Having player resources and production as StandardResources could improve bringing some code out of Player, like even serialization. But it's not a must for me, we can stick to current player.steel as well.

**Comment by Lynesth** [comment]
> I'd call them StandardResources - that's how they are called in the game.

That name looks too much it's going to be like `Resources`, while I think it should make it clear that it's a "bag" (or stack, pile, pouch, whatever) of resources.

**Comment by sienmich** [comment]
So @Lynesth, wanna propose something?
