### ISSUE TITLE
Typo in card name "Titan Floating Launch-Pad"

### ISSUE THREAD

**Issue by kevinb9n** [bafolts/terraforming-mars#2608]
Compare

<img width=350 src=https://user-images.githubusercontent.com/934551/106348064-23229a80-6278-11eb-9e53-0462e24ea922.png>

<img width=350 src=https://user-images.githubusercontent.com/934551/106348035-ece51b00-6277-11eb-82f3-8d63610c6e5d.png>

**Comment by alrusdi** [comment]
Ugh... I thought it it is easy-to-fix bug, but we use card names as their ids to persist the game data. @bafolts @kberg is it reasonable to enable english to english translation for this case?

**Comment by Lynesth** [comment]
Just break ongoing games.

**Comment by vsrisuknimit** [comment]
If we are going to fix this, please fix other card name mentioned here as well: https://github.com/bafolts/terraforming-mars/pull/2482#issuecomment-763522061.

**Comment by kevinb9n** [comment]
> Just break ongoing games.

That's fair, but I would feel a little bad for filing these issues at all if that's the consequence. :-) Maybe there could be a convention that fixes that are known to break existing games happen only at certain times, like around the first of the month every month, or something?

**Comment by bafolts** [comment]
We always look-up the cards in one of two classes. Like we did with other serialization changes we will have to expect both card names during the transition. Then after 10 days (the default time we purge old games) we can remove the old spelling. This is tedious but got us through the serialization changes without a hiccup. 

@vsrisuknimit what is the other card name? May as well get them all with this change.

**Comment by bafolts** [comment]
Oh how far this project has come. Changes such as this used to be dead simple as there weren't many ongoing games to worry about. I think we are at a point now we will always have to consider ongoing games with changes. At least on the terraforming-mars.herokuapp.com I think nearly a thousand games are completed per day. So breaking ongoing games ends up potentially breaking thousands of games.

There was a `game_results` table added a few months back.

```
terraforming-mars::DATABASE=> select count(*) from game_results;
 count 
-------
 65829
(1 row)
```

Almost 66k games have been completed on terraforming-mars.herokuapp.com. This doesn't count games which were never completed.

```
terraforming-mars::DATABASE=> select count(*) from (select distinct game_id from games) a;
 count 
-------
 12596
```

We purge the games table after 10 days. Right now there are nearly 12k games over the past 10 days.

**Comment by kberg** [comment]
> We always look-up the cards in one of two classes. Like we did with other serialization changes we will have to expect both card names during the transition. Then after 10 days (the default time we purge old games) we can remove the old spelling. This is tedious but got us through the serialization changes without a hiccup.
> 
> @vsrisuknimit what is the other card name? May as well get them all with this change.

Thank you. That will be great.

**Comment by vsrisuknimit** [comment]
@kberg @bafolts 

CEOS_FAVORITE_PROJECT = 'CEO\'s Favorite Project',
RAD_CHEM_FACTORY = 'Rad-Chem Factory',

Add apostrophe and capitalize the C.
