### ISSUE TITLE
Cannot place forest in special conditions

### ISSUE THREAD

**Issue by vincentneko** [bafolts/terraforming-mars#264]
Red player cannot place a forest

![Screenshot 2020-02-15 16 28 40](https://user-images.githubusercontent.com/56086992/74591516-f8184a00-5018-11ea-83d9-866e80baa069.png)

**Comment by bafolts** [comment]
The function which gets available spaces for greenery must not take into consideration if there are any spaces available around the greenery in play. In this situation the red play should be able to place a tile on any open land.

**Comment by vincentneko** [comment]
@bafolts thanks for fixing this
