### ISSUE TITLE
Improved client side caching.

### ISSUE THREAD

**Issue by bafolts** [bafolts/terraforming-mars#2665]
We have basic client side caching in place controlled by the `ASSET_CACHE_MAX_AGE` environment variable. This uses a `max-age` and doesn't take into account if the item has changed on the server. Discovered today there is a 2TB bandwidth limit from heroku.

https://devcenter.heroku.com/articles/limits#network

Need to improve this caching to take into account if the item has change on the server. If the item hasn't changed on the server we can avoid setting `max-age` altogether and remove this environment variable. This will improve client side performance and decrease bandwidth used by servers.

**Comment by Lynesth** [comment]
We can add either etag or last-modified: https://developer.mozilla.org/en-US/docs/Web/HTTP/Caching#cache_validation
I'll leave that choice to you.

**Comment by bafolts** [comment]
This was implemented. Any static asset is served through one function in server. The files are only cached when `NODE_ENV=production`. This will allow developers to modify files without having to restart the server.
