### ISSUE TITLE
Is Aerospace Mission's test flaky?

### ISSUE THREAD

**Issue by kberg** [bafolts/terraforming-mars#2689]
I had a test failure today, 

```
  1) AerospaceMission
       Should play:
     TypeError: Cannot read property 'cb' of undefined
      at Context.<anonymous> (build\tests\cards\community\AerospaceMission.spec.js:1:5009)
```

This came from https://github.com/bafolts/terraforming-mars/actions/runs/543427035 which is now hiding that result. :/

**Comment by bafolts** [comment]
It is flaky! Just failed again.

https://github.com/bafolts/terraforming-mars/runs/1891687411?check_suite_focus=true

Was on the windows machine if this gets lost.

**Comment by nwai90** [comment]
Will check. Likely something about test setup (e.g. if there are not 2 valid colonies to place on)

**Comment by kberg** [comment]
Still flaky: https://github.com/bafolts/terraforming-mars/runs/1904365750?check_suite_focus=true

**Comment by bafolts** [comment]
This is duplicate of #3165 . Answer to this question is yes, the aerospace mission's test is flaky.
