### ISSUE TITLE
Suggestion: Keep the opponent's cards visable

### ISSUE THREAD

**Issue by dabewi** [bafolts/terraforming-mars#269]
Hi!

After an opponent made his move his ressources become invisible as his cards are getting collapsed. I'd like to suggest a functionality that keeps the opponents cards visible until the player manually collapses them. Because when I play I want to constantly check which of the drafted cards are beneficial for which opponent.

Maybe this could be made with a small checkbox "Keep the opponents cards visable", so that every player can decide whether he prefers the actual behaviour or not.

Cheers!

**Comment by alrusdi** [comment]
Nice idea. it's little annoying when just opened opponent info collapsing when someone do something.

**Comment by alrusdi** [comment]
Implemented, merged
