### ISSUE TITLE
Suggestion: Update the player boards (again)

### ISSUE THREAD

**Issue by ssimeonoff** [bafolts/terraforming-mars#2690]
The last update added a header height with the agenda the extra height to accommodate the upcoming discounts. 
Well, they were added with a different UI and thus the header only adds more height with no benefit. 
So let's revert it.
Current vs Suggested
![boards](https://user-images.githubusercontent.com/6917565/107125812-3b17a100-68ac-11eb-9795-60d0ac4cd281.png)

1. header is gone
2. played cards icon, count and button show are merged into a single button and moved to the right (dead space on mobile)
3. Player name and corporation are displayed over the status/timer
4. the vp/tr/played icons width, margins and paddings are such so they match the closer the width of the status/timer label (cards in hand icon is also only 50% black)
5. status/timer has always a background
6. 1st player icon is in the top right corner of the status/label - not to overlap with the player name and to mimic how we display the discounts and changed values now (mc icon in a top right corner of a resource/tag icon) 

Regarding 2: 
Since the button is bigger, it will be easier to hit it on mobile.
Maybe it should be blue as a button, but it pops so much, maybe the label "show" (and cursor pointer on hover) are enough to indicated it is a button, so the UI can be more to "blend in". The width of the boards gets a bit bigger because of it, but on desktop, this is not a usually a problem. 
In the future, if needed/desired, the button can get wider and show more detailed info: e.g. played green, played blue, actions on blue cards remaining. again this will add no width to mobile. ¨

PS: chosta, don't hate me.

**Comment by kevinb9n** [comment]
Looks good to me!

For me (widescreen/zoomed-out) the two "cards" icons will now be quite close together. Is it possible we could switch the "cards played" icon to something that looks more like the cards played?

something like this maybe, but better? (I'm not a graphic person)

<img width=100 src=https://user-images.githubusercontent.com/934551/107133532-11577d80-689e-11eb-9505-f80ff694c1aa.png>

But really anything that's *different* from the cards-in-hand icon.

**Comment by vsrisuknimit** [comment]
@ssimeonoff please show what it looks like when the table is not folded. I think the played cards look weird to be there.

**Comment by vsrisuknimit** [comment]
<img width="523" alt="Screen Shot 2021-02-06 at 8 17 03 PM" src="https://user-images.githubusercontent.com/14239220/107133695-ea5a7500-68b8-11eb-89bc-0b7dd1c172b0.png">
<img width="1099" alt="Screen Shot 2021-02-06 at 8 16 47 PM" src="https://user-images.githubusercontent.com/14239220/107133696-eaf30b80-68b8-11eb-8a5a-5ccb68c7e30e.png">

Without Colonies and Turmoil the table folds nicely here. So question is how to add influence and colony count without adding too much width.

**Comment by kberg** [comment]
In general this looks like a net improvement to me.

* Please add a visual cue that "show" is clickable, so that's not lost.
* What does the 'active' area look like when the timer is off? Just make
sure it's not awkward.
* Restore the visual margin between the hand of cards and the tags? I
suspect beginner player will not realize the cards icon is not a tag. (Not
every tag is a circle.)

>

**Comment by ssimeonoff** [comment]
![Untitled](https://user-images.githubusercontent.com/6917565/107141658-95efdd80-692a-11eb-8f3e-16fa05b58b67.png)
Width: 
Yes, the dead spot in mobile when colonies/turmoil/venus are not in is absent, but how many games are played without expansions? The added width on desktop will depend how the show button is displayed and where. Also we don't mind shorter player names and cut corporation's names, the timer/coporation/player column can get thinner to compensate for the extra width. 
Show button position and UI:
My only opinion here is to move it from the front and combine the whole thing (played cards icon, number and show label) in a button. Where we want to move the button and how to actually to display it (solid blue to make it to pop out as much as possible or super toned down) - no strong opinions here.

**Comment by kevinb9n** [comment]
> but how many games are played without expansions?

I've asked this question and heard that @bafolts might be able to look it up.
If your intuition is that it's low, though, you may be thinking about $lfg and tournament games in particular.

**Comment by kevinb9n** [comment]
> Restore the visual margin between the hand of cards and the tags? I suspect beginner player will not realize the cards icon is not a tag. (Not every tag is a circle.)

I have no problem with this suggestion but FWIW I have never seen a tag that isn't round.

**Comment by ssimeonoff** [comment]
![Untitled](https://user-images.githubusercontent.com/6917565/107371180-448b4e00-6ae4-11eb-8557-23a694fef4c9.png)
E.g. keeping the blue for the button and aligning it more towards the tags.

**Comment by vsrisuknimit** [comment]
@ssimeonoff should we close this since #2815 was merged?
