### ISSUE TITLE
Add clue about milestone costs and awards.

### ISSUE THREAD

**Issue by kberg** [bafolts/terraforming-mars#2692]
![image](https://user-images.githubusercontent.com/413481/107127183-61c0e200-6882-11eb-8fe9-24306d3547f9.png)

Some (i) next to Milestones and Awards, perhaps that takes you to a page describing milestones and awards, please.

**Comment by kevinb9n** [comment]
<img width=600 src=https://user-images.githubusercontent.com/934551/107869982-37a28d80-6e49-11eb-8dd1-f37b9cd60fa6.png>

**Comment by kberg** [comment]
Yes, that's good, and simple.
