### ISSUE TITLE
Provide visual cue of default titanium and steel values

### ISSUE THREAD

**Issue by kberg** [bafolts/terraforming-mars#2693]
![image](https://user-images.githubusercontent.com/413481/107127221-a187c980-6882-11eb-8e02-0cafba024ad3.png)

New players just don't remember that steel = 2 and titanium = 3.  If you want it disablable, I suggest adding that.

**Comment by vsrisuknimit** [comment]
Strongly against this. It is the same reason we also don't tell them steel can only be used for building tag cards, Ti for space. It is just some basic knowledge that players should know. We don't have to handhold and baby-proof everything. Adding this will as a default behavior will make the UI really messy and a lot of people angry. More so than the tile placement confirmation. And if not default, new users are not going to preferences to turn it on.

**Comment by kberg** [comment]
I hear you, I really do. But remember that the real-life player boards DO have that information. I've done two teaches of this game in the last two weeks for six different people. None of them remembered, and they are impressively intelligent adults.

**Comment by vsrisuknimit** [comment]
Disagree that this should be a default behavior. It makes the UI messier for a larger audience than the people who need it. If it is not default, then new users will not know how to turn it on anyway.

Here is an alternative suggestion. Add "tutorial" or "beginner" option in Preferences to show this information and other info that are useful for beginners. Make this option on by default if a user picks Beginner Corp.

**Comment by kevinb9n** [comment]
Without needing a whole beginner mode..... if you were willing to *try* @kberg's suggestion for a couple weeks we would find out whether it *really* bothers people or not once they're used to it.

Personally, I find quickly multiplying my titanium amount by 4 when it is worth 4 to be noticeably easier/more-automatic than quickly multiplying it by 3 when it's worth 3, just because the 4 is on the screen and the 3 isn't.

**Comment by nwai90** [comment]
Implemented. @kberg close?
