### ISSUE TITLE
Reorder message about decreasing someone's production

### ISSUE THREAD

**Issue by kberg** [bafolts/terraforming-mars#2694]
![image](https://user-images.githubusercontent.com/413481/107127286-2bd02d80-6883-11eb-86a7-3dc60e2b4d91.png)

I recommend this say "Tatiana decreased Robert's plant production by 1."

**Comment by kevinb9n** [comment]
actual conversation here:

"C, it's your turn!"
"No it's not"
"Uh yeah, E already did 2 actions"
"No I didn't"
"Ohh. The first thing was just her being stolen from. Right."

In other words, +1
