### ISSUE TITLE
Provide visual cue that heat leads to temperature

### ISSUE THREAD

**Issue by kberg** [bafolts/terraforming-mars#2696]
Like this?

![image](https://user-images.githubusercontent.com/413481/107127792-861ebd80-6886-11eb-8ac6-f48eb7107d8a.png)

**Comment by vsrisuknimit** [comment]
Energy becomes heat. But yes, that seems like a good solution.

**Comment by vsrisuknimit** [comment]
Heat leads to temperature would be a different topic, covered by #2192.
