### ISSUE TITLE
Make milestones and awards clickable in the log

### ISSUE THREAD

**Issue by kberg** [bafolts/terraforming-mars#2697]
![image](https://user-images.githubusercontent.com/413481/107127900-63d96f80-6887-11eb-834b-deeaf8a5ca62.png)

**Comment by vsrisuknimit** [comment]
What does it do when click?

**Comment by kberg** [comment]
Like how it shows cards, show the milestone as a card, perhaps? Or show the
milestone's text?

>

**Comment by kevinb9n** [comment]
This wouldn't be bad, but it is a little different from the other cases, being information that's already always on-screen in a well-known place.

**Comment by kberg** [comment]
Fair. And I wouldn't use this option, but there's the option for hiding
milestones and awards in the UI. I'm not sure that's a REAL reason to
include this feature, I'm mostly thinking out loud.

>
