### ISSUE TITLE
Show errors to user

### ISSUE THREAD

**Issue by bafolts** [bafolts/terraforming-mars#27]
Any input error is displayed to the user with a generic error message. The server has a helpful error message which should get displayed to the user so they know what to correct.

**Comment by vincentneko** [comment]
It would be also great to have a .info log that list all user actions, like :

- user xx played Lake Marineis project
- user xx used Water Splitting plant capacity
- user zz played aquifer standard project

and so on...

**Comment by vincentneko** [comment]
This is great and working fine, I think we can close this one
