### ISSUE TITLE
Credicor doesn't work on standard projects

### ISSUE THREAD

**Issue by dabewi** [bafolts/terraforming-mars#271]
Hi,

we are currently playing a 2 player-game on the Elysium board. My opponent plays credicor and he noticed this: While the refund of credicor (4 MC for every card or standard project > 20 MC) works for cities it doesn't work for greeneries.

Can someone confirm that?

**Comment by vincentneko** [comment]
I've just tested it and yes, I confirm I did not get a 4 MC cashback.
But it's also the case with city project, which is a good news imho...
Will investigate this.

**Comment by vincentneko** [comment]
Got it !

`payForStandardProject` is only looping through played cards, not corporations.

Fix incomming

**Comment by vincentneko** [comment]
Fixed and merged !
