### ISSUE TITLE
Problem creating games

### ISSUE THREAD

**Issue by vsrisuknimit** [bafolts/terraforming-mars#2718]
![image](https://user-images.githubusercontent.com/14239220/107417219-58828000-6ae3-11eb-9375-c66ce263376b.png)

This happen frequently after mid-day deployment today. Game can be created after a few tries. Not sure what is happening.

@bafolts

**Comment by bafolts** [comment]
Heroku allows me to deploy a branch from `bafolts` repository with ease. Until we can resolve this issue if someone makes a branch with a working commit from yesterday I can deploy it. Until then this will have to wait until a fix.

**Comment by vsrisuknimit** [comment]
The problem is not always reproducible. Might just be Heroku hiccup thing. Let's observe for now.

**Comment by bafolts** [comment]
Was this re-opened by accident? Nothing unusual stands out in the logs or heroku metrics.

**Comment by vsrisuknimit** [comment]
We can close it. But let's keep watch for now. I experienced it and another user reported it.

**Comment by bafolts** [comment]
The hobby basic plan makes no guarantees for 100% uptime so this could be observed if heroku is doing maintenance of some kind.

```
Expected uptime of 99.5% each month.
Unannounced maintenance and database upgrades.
```

https://devcenter.heroku.com/articles/heroku-postgres-plans#hobby-tier
