### ISSUE TITLE
Timer: hour is sometimes misaligned

### ISSUE THREAD

**Issue by kevinb9n** [bafolts/terraforming-mars#2721]
On chrome/macosx, at some zoom levels the baseline doesn't seem to align.

<img width=350 src=https://user-images.githubusercontent.com/934551/107469193-25111700-6b1e-11eb-869b-7215d3d23647.png>

**Comment by kevinb9n** [comment]
Full disclosure, I mostly filed this hoping that the remedy will be to make all the numbers the same size. To me it will never quite look right otherwise. But that's me.

**Comment by ssimeonoff** [comment]
What hours?
![Untitled](https://user-images.githubusercontent.com/6917565/107520338-9c43bb00-6bb1-11eb-89db-f53b5576d3dc.png)

**Comment by kevinb9n** [comment]
@alrusdi this is fixed right?

**Comment by vsrisuknimit** [comment]
#3257 fixed this

**Comment by alrusdi** [comment]
> @alrusdi this is fixed right?

yes, it is fixed now
