### ISSUE TITLE
Venus Governor Card

### ISSUE THREAD

**Issue by kudlondr** [bafolts/terraforming-mars#2725]
The Venus Governor card can be played when a player has only 1 Venus tag (even thought 2 Venus tags are required)

**Comment by vsrisuknimit** [comment]
@kudlondr screenshot of the hand, board, and the player tags please?

**Comment by kevinb9n** [comment]
I've never noticed this, and have been looking out for it.

It might have been a wild-tag situation. I think if it's a bug it will come up again soon enough.
