### ISSUE TITLE
Cards with wild tags and production can be copied by Robotic Workforce

### ISSUE THREAD

**Issue by SliceOfBread** [bafolts/terraforming-mars#2727]
This is incredibly minor and you can read the view of Jacob Fryx at https://boardgamegeek.com/thread/2599379/article/36978395#36978395

Summary: Research Network (Prelude) has a wild tag. Can Robotic Workforce be used to copy its production?
Answer: Yes.
This is minor because it is unlikely (although not impossible) anyone would want to use Robotic Workforce to copy 1MC production.

FYI, Research NEtwork is the only card in the normal game+expansions that has a wild tag and production. Maybe Ares or Moon or other fan stuff also does.

**Comment by kberg** [comment]
To fix this appropriately, RoboticWorkforce.spec.ts must change. The test
"Has all building cards set up" should change line

if (card.tags.includes(Tags.BUILDING) && card.play !== undefined) {

to
if ((card.tags.includes(Tags.BUILDING) ||
card.tags.includes(Tags.WILDCARD)) && card.play !== undefined) {


>
