### ISSUE TITLE
Improvement: Relocation of RES display

### ISSUE THREAD

**Issue by dabewi** [bafolts/terraforming-mars#273]
Hi!

I think it would be an improvment to reloacte the "RES" indicating the amount of ressources. I think it would be better placed in the bottom left corner (next to the symbol that indicates from which expansion the card comes).

There is plenty of space that is always free and unoccupied.

**Comment by vincentneko** [comment]
I second this.
The "RES" label is completly occulted on some corporations like Arklight or Stormcraft.

**Comment by alrusdi** [comment]
I will do it

**Comment by vincentneko** [comment]
Thanks for fixing this.
