### ISSUE TITLE
Consider a variant filtered-draw mechanic for less divergence between "duplicate" games

### ISSUE THREAD

**Issue by kevinb9n** [bafolts/terraforming-mars#2746]
Celestic, Factorum, ExpForest, etc. have you reveal cards until you find N with a certain property, draw those and discard the rest. The real goal is just to give the player N cards with that property, but the side-effects are

(a) to discard a bunch of cards,
(b) to give public knowledge of those cards and even the ones the player takes, and
(c) to make deck reshuffles somewhat more common.

Here, when multiple groups use the same game seed to get a "duplicate" experience, we also have

(d) if this action gets played in one game but not another, these games can instantly diverge and go down very different paths.

Divergence (beyond natural divergence from different strategies) is inevitable, but this can be a pretty big one.

These side effects happen because there is really no other reasonable way in a physical over-the-table game to accomplish the goal. But here we have other options not possible in the physical game.

We could consider a variant rule: don't reveal or discard anything. Just pluck the right number of matching cards out of the deck according to some set of rules, and leave the rest alone. There's no need to discard anything, and there's no *particular* need to reveal the cards being drawn to all players (which we could consider only an accidental artifact of the over-the-table procedure, or we could reveal them anyway just to be consistent).

But what rules? One rule should probably be to avoid the part of the deck that is *likely* to be needed for remaining research phases. Other than that,

- Picking randomly works okay. It isn't in the "duplicate" spirit, but the damage is more limited than before.
- Plucking out the topmost matches in the deck is more deterministic, but is not great as it creates a short "drought" of that type of card
- Plucking out the bottom-most matches (outside the reserved-for-research zone) at least puts off the drought a while but yeah
- Straw man: at game start, after shuffling the deck, shuffle a second copy of the deck too (using the same RNG). This shadow deck is never used directly. For the rest of the game (even if the main deck reshuffles), the cards that a filtered draw chooses from the real deck are whichever remaining ones which are topmost in the shadow deck. Weird, but I think it provides suitable determinism without causing any clumping in the deck.
- Other ideas?

**Comment by kevinb9n** [comment]
I heard some talk of wanting to actually remove cards like ExpForest for this reason (say by rerolling seeds that deal it). If there are enough players that would actually want to take that step, that's when I think a change like the above may be justified as a better alternative. If people are okay with things as they are, then don't bother doing this.

**Comment by Platinuman** [comment]
What about revealing cards and discarding them from the bottom of the deck? 
By doing this, we get 
- Similar side effects:
  - public knowledge of cards discarded and cards kept is maintained
  - same amount of increased deck shuffling
- No divergence (from reveal cards)
- No "drought"

This can also be extended to all non-draft card drawing effects if we want all drafts to be identical among duplicate TM games.

**Comment by kevinb9n** [comment]
The bottom of the deck is already used for the Research phases. If only there were a way to have a triple-ended queue. :-)

One of your assumptions might be that preserving the "public knowledge" aspect is desirable, but I see it as accidental.
