### ISSUE TITLE
Robotic Workforce doesn't copy prelude cards

### ISSUE THREAD

**Issue by dabewi** [bafolts/terraforming-mars#275]
Hi,

when I play Robotic Workforce the program doesn't show to me preludium cards although they have a building tag as required.

Maybe the method doesn't iterate over prelude cards?

**Comment by bafolts** [comment]
Our implementation of robotic workforce most likely needs to be updated. As far as I can tell from the two forums our implementation is wrong.

https://boardgamegeek.com/thread/1631060/can-someone-please-explain-how-robotic-workforce-c
https://boardgamegeek.com/thread/2029928/does-robotic-workforce-copy-prelude-card

I think we need to do the following improvements, @alrusdi or @vincentneko can double check me as I don't play the game as often as I once did.

Upon attempting to play robotic workforce we should iterate through `playedCards` and show any card that we deem has a production box and `canPlay` returns true. Reading through those two forum posts it seems we can also avoid cards that have you place a space to get the bonus which simplifies things.

1. Update the list of cards with production boxes and building tags in `RoboticWorkforce` that don't include selecting a space.
2. Check with `canPlay` of a card before displaying to a user.
3. Only allow robotic workforce to be played if at least one card is available.

**Comment by vincentneko** [comment]
This is a big one...

First we cannot rely on canPlay for cards filtering, as a condition that was valid when the card was played (like oxygen level) might not be valid when Robotic Workforce is played (and it's valid to copy this production !)
Second, some cards have dynamic production boxes, like Mining Area or Mining rights (it's either one Steel or Titanium), or even worse, Gyropolis that modify MC production depending of the number of Venus and Earth tags you have.

One the brighter side, prelude cards should be easy to add, and I think some negative only productions cards can be removed, like Electro Catapult or IACentral
(I see no point playing a card to reduce my energy production by 1 only)

I think the current implementation is right, we need to rely on a fixed list. Only some cards are missing, and the tile placement part of the cards are just to be ignored as it is now.

A far as I see, the cards to add are :

Mining Area (need special logic to get resource associated with tile placed initialy)
Mining rights (same as above)
Mining Quota
Gyropolis (need special logic to recalculate tags amount)
Heat Trappers (need special logic to select targeted player)
Medical Lab (need special logic to recalculate tags amount)

Dome Farming
Early Settlement
Martian Industries
Mining Operations
Mohole
Mohole Excavation
Polar Industries
Self-Sufficient Settlement

And the cards to remove :

Electro Catapult
Immigrant City 
Rad-Chem factory
AI Central


And lastly, there is a bug here :

[new TitaniumMine().name]: new Updater(0, 0, 0, -1, 0, 0),

Should be 

[new TitaniumMine().name]: new Updater(0, 0, 0, 1, 0, 0),

**Comment by dabewi** [comment]
Hi,

do not recommend to remove cards from the Robotic Workforce scope just because copying them would reduce your production.

Example: With the turmoil corporation "Mons Insurance" in play there might be situations where you actually want to reduce your own production of a ressource. Because the owner of Mons Insurance has to pay 3MC to anyone who's ressources are or ressource production is reduced. So in a situation where I desperately need 3MC I would consider copying one of my cards with a negative production to get the owner of Mons Insurance to pay me.

This might be an extreme edge case but I think it is better to restrict as few things as possible, because you don't really know what a player may want to do. As long it is legal he should be allowed to do ist.

Cheers!

**Comment by vincentneko** [comment]
Hi,

I understand your point but the "Mons Insurance" specify that "When a player causes another player to decrease production..."

And also, the card cost 9 to play...

But it also have a science tag, so yes there might be some extreme cases where you want to play it anyway.

What I wanted to avoid is that a player might think he can copy a non building tag production and because he also have let's say AI Central, the card will be available for play...

**Comment by vincentneko** [comment]
Card updated and merged
