### ISSUE TITLE
Is there a bug in SendDelegateToArea?

### ISSUE THREAD

**Issue by kberg** [bafolts/terraforming-mars#2751]
This is just because I'm visually inspecting SDTA, looking at a bit of refactoring for clarity.

[Line 50](https://github.com/bafolts/terraforming-mars/blob/26975f9deb19bd3d526549397847185656403f1d/src/deferredActions/SendDelegateToArea.ts#L50) sends delegates using this loop:

```
for (let i = 0; i < this.nbr - 1; i++) {
  this.player.game.turmoil?.sendDelegateToParty(this.player.id, party.name, this.player.game, false);
}
```

And [line 54](https://github.com/bafolts/terraforming-mars/blob/26975f9deb19bd3d526549397847185656403f1d/src/deferredActions/SendDelegateToArea.ts#L54) does something a little different

```
for (let i = 0; i < this.nbr; i++) {
```

One conditionial causes the loop to run one more than the other.

**Comment by kevinb9n** [comment]
It looks like they both send `nbr` delegates, considering line 49 as well.
