### ISSUE TITLE
RFC: Make Moon parameters global parameters?

### ISSUE THREAD

**Issue by kberg** [bafolts/terraforming-mars#2765]
I think this isn't a bad idea, it's just a bit of work. Fortunately it's mostly pattern matching.

Venus is a global parameter, and so cards with venus requirements are is subject to the +2/-2 benefits of cards and corps that support it. Consequently, I'd add that.

Along with that would be:
1. Hooking into Turmoil effects
2. WGT effects

I'm confident there's more but it's late. Any thoughts? If you've played The Moon, I'd like to hear your thoughts.

**Comment by kevinb9n** [comment]
Here are 10 behaviors and invariants that came to mind, that pertain abstractly to a Global Parameter (GP), in the official game+expansions+promos. Which clearly apply to the Moon parameters, which clearly don't, which are debatable?

1. All players have the trigger effect "increase some GP 1 step : increase TR 1 step" in play at all times
1. Any apparent instruction to increase one by N steps is actually N independent 1-step instructions (not true of, say, "gain 3 MC")
1. Each GP type has a specific limit (9/14/19/15 steps); once reached, it not only can't be increased further, it can't be decreased either
1. Any instruction to increase or decrease one is implicitly a type 2 "mandatory-if-possible" instruction, like gaining a microbe (not type 1 "mandatory", nor type 3 "optional")
1. Except for Solo, maxed GPs are the only endgame triggers
1. They are player-independent: which player raised one is promptly forgotten after triggers have fired
1. They may have triggers at particular values ("bonus spaces"), which fire only on being _increased_ to that value
1. Any _unmaxed_ GP may be chosen for World Govt Terraforming
1. Nothing but global events will decrease them
1. The effect of Inventrix/AdaptationTech/SpecialDesign applies to all of them

**Comment by kberg** [comment]
This is resolved.
