### ISSUE TITLE
Paying for a non existent card

### ISSUE THREAD

**Issue by MaxHanse** [bafolts/terraforming-mars#2767]
The game has me paying for a 6MC card (which I do not have in my hand).

All other turn options have disappeared (standard projects/pass)

The issue seemed to resolve itself with a refresh but then returned to trying to get me to pay for a nonexistent 6MC card
Another refresh did not fix

**Comment by kberg** [comment]
Thanks for the issue, but this isn't enough information for me to figure out what happened. Can you provide any other data? Which card? How did  it ask you to pay for it? What server was this? Those will help.

**Comment by MaxHanse** [comment]
I never had a 6MC card in my hand to try and figure that issue out

**Comment by MaxHanse** [comment]
Have M46 and M13 in my hand BTW

**Comment by kberg** [comment]
Oh, this is a moon game! Aha. Are you on the discord? I can chat with you
there.

>
