### ISSUE TITLE
What does Mandatory Moon Terraforming mean?

### ISSUE THREAD

**Issue by MaxHanse** [bafolts/terraforming-mars#2768]
Clicked that as a starting option but was unable to figure it out as I was taking moon terraforming cards but there were unavailable to me as were the moon standard projects.

**Comment by kevinb9n** [comment]
To answer the question:  the button is currently missing an info link to here
https://github.com/bafolts/terraforming-mars/wiki/Variants#moon-terraforming

**Comment by kberg** [comment]
Max, can you share a link to the game, please?

By the way, if you're playing a solo game, I have a PR in flight that will
add 2 generations when using The Moon in a solo game.

>

**Comment by kberg** [comment]
I've made some changes to https://github.com/bafolts/terraforming-mars/wiki/The-Moon which should help.
