### ISSUE TITLE
The moon card not showing the correct card discount in the summary bar

### ISSUE THREAD

**Issue by GJonatan** [bafolts/terraforming-mars#2769]
[screencapture-testmatch2-herokuapp-player-2021-02-15-19_44_11.pdf](https://github.com/bafolts/terraforming-mars/files/5983528/screencapture-testmatch2-herokuapp-player-2021-02-15-19_44_11.pdf)

I am red in this game, from the bar it looks like my card are 1MC cheaper but they are 3MC cheaper since I have both Sky Docks (-1) and Moon Tether (-2).
However I pay the correct cost when playing cards.

Great job on the expansion btw, me and my friends really like it so far!

**Comment by kberg** [comment]
Interesting. Good bug report, thanks. Just to reconfirm, you're gaining the
discount, this is just a visualization issue, right?

I'm glad you're enjoying it. Please keep reporting issues.

**Comment by GJonatan** [comment]
Yes from what I could tell it was purely a visual issue.

Will do! :)

**Comment by kberg** [comment]
Yeah I found it. There was code isolated from cards that I just found and
am incorporating into the main card definitions.

>
