### ISSUE TITLE
Flodding allows you to remove MC from "owner" of Ocean tiles

### ISSUE THREAD

**Issue by K-Hartmann** [bafolts/terraforming-mars#277]
Since Ocean tiles don't have any ownership marker or owner, flooding should not work for already placed ocean tiles. It does though, as seen in the screenshot.
![2020-02-19_13h21_00](https://user-images.githubusercontent.com/41374984/74833911-b2aa9400-531a-11ea-92b5-1a19b4b74373.png)

**Comment by alrusdi** [comment]
I will try to fix it

**Comment by alrusdi** [comment]
Should be fixed now
