### ISSUE TITLE
Buffer Gas SP availability should depend only on TR63 mode, not expansions

### ISSUE THREAD

**Issue by kevinb9n** [bafolts/terraforming-mars#2788]
There's no connection between TR63 mode and the Prelude expansion, or between the Buffer Gas standard project and the Prelude expansion.

It just happened that these rules appear physically in the Prelude rulebook, but this fact is of no consequence.

<img width=440 src=https://user-images.githubusercontent.com/934551/108343939-62fee280-7191-11eb-82ed-4708646e4bbe.png>

Currently (as reported by Kowal on discord), the SP is missing when Prelude isn't in use.

**Comment by kevinb9n** [comment]
just to confirm the report

<img width=550 src=https://user-images.githubusercontent.com/934551/108346090-ddc8fd00-7193-11eb-9cc9-2058a55fd091.png>

**Comment by kberg** [comment]
That seems reasonable.
