### ISSUE TITLE
Need better solution for prelude cards that let you play a card.

### ISSUE THREAD

**Issue by bafolts** [bafolts/terraforming-mars#28]
We need a better solution for EcologyExperts and EccentricSponsor. I have disabled them for the time being.

**Comment by bafolts** [comment]
@vincentneko I ended up making a separate ticket for this. Being able to play a card from a card doesn't work well with how the logic in both `Player` and `Game` is currently written. Instead of putting in the quick work around I disabled these cards for the time being. We can do this work in a separate pull request. The rest of the work in #26 looked fine to merge and would rather not put these cards in until there is a better solution.

**Comment by vincentneko** [comment]
I agree.
The duplicate play card / play prelude part was ugly, I'm glad you found a solution to merge those two.
