### ISSUE TITLE
Discounts from corporation effects aren't appearing on player board

### ISSUE THREAD

**Issue by vsrisuknimit** [bafolts/terraforming-mars#2818]
![image](https://user-images.githubusercontent.com/14239220/108635593-2d3a5200-744e-11eb-86b8-156e0b5577c6.png)

#2771 messed it up.

**Comment by vsrisuknimit** [comment]
It does not work for Valley Trust either, so I will presume it is the same problem for Thorgate and Cheung Shing Mars as well.

**Comment by kberg** [comment]
Yeah, I bet I know the exact line. Mea culpa.
