### ISSUE TITLE
Discard pile is missing

### ISSUE THREAD

**Issue by K-Hartmann** [bafolts/terraforming-mars#282]
Apparently when cards are discarded or sold, they do not move to a discard pile, but instead back into the pool of avaliable cards. I noticed multiple instances of cards which were discarded from the starting hand or in the research phase, to be drawn again just a short time after.

**Comment by alrusdi** [comment]
@bafolts  shouldn't we do the same fix as https://github.com/bafolts/terraforming-mars/commit/e3c8f72b242a938bd83f650096fdc77e68d7aa0b
for other (potentialy mutable) cards lists like ALL_PROJECT_CARDS in Dealer module for example?

Also, the bug described by @K-Hartmann may be not a bug. Because discard pile is shuffled to main deck when main deck lasts.

**Comment by bafolts** [comment]
Eventually the cards _should_ end up back in the main deck. Given the description of the bug I was thinking what you are thinking @alrusdi that somewhere we are modifying `ALL_PROJECT_CARDS` to contain duplicates. We should do the same fix and not mutate the dealer's lists.

**Comment by bafolts** [comment]
@K-Hartmann were you using the draft variant? What game options were you using? We have a discard pile which cards should always be going to. This discard pile is then only shuffled into the game once all cards have been played. Were the cards you saw duplicates of prelude cards?

**Comment by K-Hartmann** [comment]
@bafolts We were playing with draft mode with preludium but without venus and saw normal cards soon after they were discarded in the draft phase, again. Since i was not counting cards, i can not rule out that the draw pile was emptied and the discard pile was therefore reshuffled. But I still think that this would be highly unlikely since we were only in around generation 7 and normaly at that state, the draw pile would not be empty.

But I will keep an eye on the issue to see if it happens again.

**Comment by K-Hartmann** [comment]
I will close this, because i did not saw an instance of this happening again.
