### ISSUE TITLE
Replaying a predefined game with colonies skips the step to remove one of the colonies in solo

### ISSUE THREAD

**Issue by andystager** [bafolts/terraforming-mars#2824]
Fun example with Aridor, ready to launch a flotilla to 5 planets:
![image](https://user-images.githubusercontent.com/72101041/108776244-2552de80-7530-11eb-8c03-38803466b87e.png)

**Comment by vsrisuknimit** [comment]
Duplicated of #2362 ?

**Comment by andystager** [comment]
Thanks, didn't see the one.
