### ISSUE TITLE
The app's Pharmacy Union card text is misleading

### ISSUE THREAD

**Issue by kevinb9n** [bafolts/terraforming-mars#2829]
The app is leaving out the "or as much as possible" part, which leads to rules confusion like this:
https://github.com/bafolts/terraforming-mars/issues/2191#issuecomment-765442112

The text from the kickstarter image is something like this:

"(Effect: When ANY microbe is played, including these, add a disease here and lose 4 M€ or as much as possible. When you play a science tag remove 1 disease from here and raise your TR 1 step, OR, if there are no diseases here, you may raise your TR 3 steps and TURN THIS CARD FACE DOWN (lose this card's tags and effects).)"

Since space is tight, we may need to abridge. This is approximately the shortest abridgement that I think can work (while also fixing a couple other issues):

"(Effect: When ANY microbe tag is played, including these, add a disease here and lose as much of 4 M€ as possible. When you play a science tag: if there is any disease here, remove one and gain 1 TR; if not, you MAY put this card face down in your EVENTS PILE to gain 3 TR.)"

EDIT: Ideas if that can't fit:

- drop "including these," because it's only a reminder of how things already work
- drop "here" x2 until some other card can hold disease resources
- change "lose as much of 4 M€ as possible" to "lose up to 4 M€", which is technically ambiguous, but at least has only one *plausible* interpretation (being actually optional would be super weird)

**Comment by kevinb9n** [comment]
(Separately, and less importantly, can we please remove "When this corporation is revealed"? It's an unnecessary addition. If we want to highlight the unique nature of this corp then we can just add the word "now":  "Draw a science card now." I don't tend to think even that is necessary.)

**Comment by vsrisuknimit** [comment]
![image](https://user-images.githubusercontent.com/14239220/108920813-52bc8c80-7603-11eb-87da-e9c4b3ed8a5e.png)

Tagging @chosta

**Comment by vsrisuknimit** [comment]
![image](https://user-images.githubusercontent.com/14239220/108920947-957e6480-7603-11eb-9640-3c16d8763983.png)

There should be enough room. Should I go ahead and change it @chosta ?
