### ISSUE TITLE
Minor: big box replacement cards have wrong/conflicting card ids

### ISSUE THREAD

**Issue by kevinb9n** [bafolts/terraforming-mars#2838]
Looks like the three replacement cards (Deimos Down, Great Dam, Magnetic Field Generators) have the same card ids as the cards they replace. #literallyunplayable

I suspect that when printed they will have the ids X31, X32, and X33 respectively. (Why: the kickstarter image shows them as 32-34 but then Asteroid Rights was given X34 and there is no X31. Seems like they simply moved it from before to after.)

**Comment by kevinb9n** [comment]
(also it looks like maybe Asteroid Rights doesn't have its id set at all.)

@kberg FYI

**Comment by kberg** [comment]
Why are they literally unplayable?

**Comment by kevinb9n** [comment]
> Why are they literally unplayable?

Apologies. "Literally unplayable" is a meme phrase that is always used ironically. 

fwiw the id numbers were indeed as I suspected.

**Comment by vsrisuknimit** [comment]
#3218 closed this
