### ISSUE TITLE
Show all running games per server

### ISSUE THREAD

**Issue by dabewi** [bafolts/terraforming-mars#284]
Hi,

as a server admin I'd like to display all the running games with the corresponding access links. It occurs that access links get lost between mediums (e.g. between laptop and mobile phone) or that someone just forgets to immediately start the game and after a while doesn't have access to the link.

Therefore it would be helpful to list all the running games and the according links.

Cheers!

**Comment by gomfunkel** [comment]
@bafolts I tried myself on this and submitted a pull request. Feel free to check it and either merge or get back to me with questions/comments.

**Comment by gomfunkel** [comment]
Implemented and merged with pull request #393. Feel free to close this issue, @dabewi.
