### ISSUE TITLE
Tactitian Milestone unavaliable

### ISSUE THREAD

**Issue by K-Hartmann** [bafolts/terraforming-mars#285]
As seen in the screenshots, I have 5 requirements in play (2 of them max requirements) but are
 unable to claim the Tactitian Milestone. The milestones claimed so far are Polar Explorer and Energizer.

![2020-02-20_13h19_11](https://user-images.githubusercontent.com/41374984/74933389-21075900-53e4-11ea-8233-073278302b6e.png)
![2020-02-20_13h19_25](https://user-images.githubusercontent.com/41374984/74933414-2b295780-53e4-11ea-9fb1-fc479ef9aa96.png)

**Comment by vincentneko** [comment]
Water Splitting Plant and another card were having a wrong `hasRequirements = false` attribute.
A PR is on the way.

**Comment by alrusdi** [comment]
Fixed and merged. Thanks to @vincentneko
