### ISSUE TITLE
Critical bug: Game home page unaccessible after opening once. Please revert #2810

### ISSUE THREAD

**Issue by vsrisuknimit** [bafolts/terraforming-mars#2852]
#2810 cause the game-home page to be unavailable after opening it once.

![image](https://user-images.githubusercontent.com/14239220/109341317-410ffa80-7838-11eb-9f83-7a67d975248b.png)

![image](https://user-images.githubusercontent.com/14239220/109341333-466d4500-7838-11eb-9ae9-47544cabefce.png)

@kberg @bafolts

**Comment by vsrisuknimit** [comment]
Please test extensively for a big change like this.

**Comment by bafolts** [comment]
Looking at this now.
