### ISSUE TITLE
Suggestion: VP projection

### ISSUE THREAD

**Issue by dabewi** [bafolts/terraforming-mars#286]
Hi,

what do you think about a VP projection during game? I find it rather stressfull to maintain an overview over the points of each player during a match, especially with higher player numbers and more complex networks (ressources on cards with 1 VP per token or per 2 tokens or per 4 tokens), milestones and awards and the TR itself.

I think it would be a great improvement since it really shows the benefits of an online game (while you have to calculate the VP yourself if you play IRL).

What do you think about that? I guess it wouldn't be much work, because there already seems to be a method that calculates the VP. And the change is only that this method is called after each action of each player.

Cheers!

**Comment by gomfunkel** [comment]
I have a working prototype for this feature request.

@bafolts (or someone else): Can you please assign me to this issue?

**Comment by gomfunkel** [comment]
It's working (and looking imho) nicely now. Will open a pull request soonish.

<img width="567" alt="vp-projection" src="https://user-images.githubusercontent.com/547035/76944956-2df36b80-6902-11ea-91ec-e665d59fe1d3.png">

This is not yet in the preferences pane style as suggested by @alrusdi in #407. The foundations for it should be laid now, though.

**Comment by alrusdi** [comment]
I like it - good addition for OtherPlayer info

**Comment by dabewi** [comment]
Very fine, @gomfunkel !

**Comment by gomfunkel** [comment]
Implemented and merged to master with #416. Feel free to close this issue, @dabewi.
