### ISSUE TITLE
Critical Bug: Users cannot see cards

### ISSUE THREAD

**Issue by vsrisuknimit** [bafolts/terraforming-mars#2862]
In the past week, many (5+) users reported that they cannot see their cards, starting from the initial draft step. But when I or some other users open the link, we can see the cards just fine.

![image](https://user-images.githubusercontent.com/14239220/109388123-2dfe3880-78d3-11eb-8a61-5433f8474c81.png)

![image](https://user-images.githubusercontent.com/14239220/109388150-4ff7bb00-78d3-11eb-9ab2-1f0aadb55a5e.png)

![image](https://user-images.githubusercontent.com/14239220/109388185-8cc3b200-78d3-11eb-9a48-b7b98f0dd22f.png)

So far the problem has been reported on:
1) Both mobile and laptop
2) Chrom, IE, and Safari
3) Both Heroku (main and community) and @alrusdi's server. But not on @Lynesth 's server which has not been updated since late January.

There is an error on the browser console. But that might not be related.
![image](https://user-images.githubusercontent.com/14239220/109388231-e3c98700-78d3-11eb-8f07-fafb66e5727e.png)

Tagging @bafolts and perhaps @kberg . It might be something with Handler and API? I have no idea.

**Comment by vsrisuknimit** [comment]
One user solved the problem by using Firefox. Another user had a problem with Safari on one Mac computer but solved it by using another Safari browser on a different Mac.

**Comment by bafolts** [comment]
I am going to change the log route to return only the logs from the generation you are in or have selected. Pretty sure the log route is putting the node instance under extreme CPU load and slowing down response times.

**Comment by bafolts** [comment]
CPU load coming down after #2866 . I am working on remaining fix to still show every generation selector.

**Comment by vsrisuknimit** [comment]
![image](https://user-images.githubusercontent.com/14239220/109512233-e235c580-7a71-11eb-9869-598c93c1176b.png)

@bafolts still on going.

**Comment by bafolts** [comment]
I can recreate in a version of firefox. Will get fix up ASAP.
