### ISSUE TITLE
Bug: Log does not show

### ISSUE THREAD

**Issue by vsrisuknimit** [bafolts/terraforming-mars#2865]
![image](https://user-images.githubusercontent.com/14239220/109399666-2e69f400-7912-11eb-9a1c-f6d6498e117c.png)

This might be related to #2862 but I am not sure.

**Comment by vsrisuknimit** [comment]
Tagging @chosta and @bafolts .

**Comment by bafolts** [comment]
I will put in change to make the log route more efficient. It is putting the box under too much load.
