### ISSUE TITLE
Suggestion: Expandable logging

### ISSUE THREAD

**Issue by dabewi** [bafolts/terraforming-mars#288]
Hi,

in some situations, especially wih 3 or 4 players, when one players passes early it's quite difficult to trace back what the other players have done when the next generation starts, because the log only shows 10 lines.

I think it would be cool to have a button (e.g. with the label "Show more...") that increments the lines shown in the log by a fixed amount (e.g. for every click I get 5 more/older lines of the log).

Another idea would be to make the amount of lines of log dependent of the player count. So, in a 2 player game the log shows 10 lines, in da 3 player game 15, etc. 

But I think the button would be better.

What do you think?

**Comment by dabewi** [comment]
Although I like the new style I have some ideas regarding the logging:

- Wouldn't it be possible to make a small window with a scroll bar and just log the entire game?
- If not, I think it would be nice to reduce the font size of the logging itself to make it more space-efficient
- I also vote for a longer log (at least more than 10 lines)

Greetings

**Comment by vincentneko** [comment]
I agree with you. Now that we have the new css we should be able to look into this, will try to get something.

**Comment by vincentneko** [comment]
Game log is now 50 entries long, and a scrollbar can be used.
@alrusdi thanks a lot for your help on this one
