### ISSUE TITLE
Wrong icon for Entrepreneur award from Ares

### ISSUE THREAD

**Issue by rodrigomp84** [bafolts/terraforming-mars#2898]
The Entrepreneur award from Ares expansion is represented by the same icon/tile as the Networker milestone, including the number 3 in it, which is unrelated to the award. I see a nice different icon in the file terraforming-mars/assets/board_icons_ares.png
but it seems it is not being used. I'd be happy to help but I don't really know how to do it...

**Comment by rodrigomp84** [comment]
I just noted another issue with the tile: it is written ENTREPENEUR in it (and therefore there is an R missing after the P)

**Comment by kberg** [comment]
The icon is one thing, but the typo? /shamecube.

Thanks, this is fixed in #2899
