### ISSUE TITLE
[Ares] Natural Preserve can be placed on top of hazards.

### ISSUE THREAD

**Issue by kberg** [bafolts/terraforming-mars#2900]
![image](https://user-images.githubusercontent.com/413481/110226386-a8731d80-7ebc-11eb-9731-8cf62bbe625d.png)

This raises one of those times when being unable to play a tile could be possible late in the game.

**Comment by kberg** [comment]
I wonder if this is actually a problem, because the more I think about it, the less I think it is.

**Comment by bafolts** [comment]
Is this issue stating that natural preserve should be able to place a tile on a hazard or that the game is allowing to place a tile on top of hazards when we shouldn't be able to? I would let the rules of the game dictate if this is a problem.

**Comment by kberg** [comment]
> I would let the rules of the game dictate if this is a problem.

Well, tile overplacement is different from adjacency. Is a tile adjacent to itself? No, probably not.

But it could be something else.

**Comment by bafolts** [comment]
Ah I now see the issue. On top of is not the same as adjacent to.
