### ISSUE TITLE
Cursor style in the clickable log

### ISSUE THREAD

**Issue by terramai** [bafolts/terraforming-mars#2905]
The cursor takes the "text" style in the log:
![Screenshot from 2021-03-07 16-55-07](https://user-images.githubusercontent.com/20948476/110247861-40791180-7f66-11eb-9d8c-2b3e91d6590a.png)
even though it's clickable. I get that it's also text, but its clickable property seems way more relevant in this case.

As someone who played their first multiplayer game without knowing that the log was clickable (frantically expecting something to happen on hover, but never thinking to click), I really think this could be improved.

I get that this is not an issue for anyone who already found this out, either by themselves, because someone told them, or by watching the tutorial. I did end up watching it after the game finished, and felt very stupid. Still, that was the *only* new bit of information that I took from it. The UI is otherwise very good and intuitive. I think having a more standard cursor symbol here would make it even better.

**Comment by kberg** [comment]
I agree with your general concern that things are not obviously clickable,
and would like to see that bit of UX improved. Thanks for the report.

>
