### ISSUE TITLE
Other players shortcut

### ISSUE THREAD

**Issue by vincentneko** [bafolts/terraforming-mars#291]
We should make the players name in Turn order clickable to toggle other player display, it should reduce scrolling to Other Players section.

**Comment by dabewi** [comment]
I second this!

**Comment by vincentneko** [comment]
Just tested it on the branch, it's great !

**Comment by alrusdi** [comment]
@vincentneko so let's merge it ;-) I need your approval

**Comment by alrusdi** [comment]
Implemented and merged
