### ISSUE TITLE
Fish implementation has incorrect function for determining players with plant production

### ISSUE THREAD

**Issue by bafolts** [bafolts/terraforming-mars#292]
The `getPlayersWithPlantProduction` function in `Fish` is not implemented properly. It is doing a strange coincidental check. This should be refactored. There are other cards that have copied this implementation that should be updated as well.

**Comment by vincentneko** [comment]
Can you please explain what you mean by "coincidental check" ?
I don't understand what is wrong with the `getPlayersWithPlantProduction ` function.

**Comment by vincentneko** [comment]
Can you please explain what you mean by "coincidental check" ?
I can't see what's wrong with the `getPlayersWithPlantProduction `function.

**Comment by bafolts** [comment]
The function does not return every player with plant production. There are checks made before and after calling the function for when there is only one player in the game. If those checks were to ever change this function could introduce a bug. Or if someone were to call the function assuming it would return every player with plant production they would have a bug.

https://github.com/bafolts/terraforming-mars/blob/master/src/cards/Fish.ts#L35
https://github.com/bafolts/terraforming-mars/blob/master/src/cards/Fish.ts#L38

The `getPlayersWithPlantProduction` function should return *all* players with plant production and not attempt to remove the player who happens to be passed in as an argument.

**Comment by vincentneko** [comment]
Thanks for the explanation.

**Comment by vincentneko** [comment]
Fixed and merged
