### ISSUE TITLE
Cannot pay for colonies space tag card with titanium

### ISSUE THREAD

**Issue by lostgrail** [bafolts/terraforming-mars#293]
Playing a solo game with Venus, Prelude, and Colonies
Playing the card Solar Reflectors (C38) ... no option to pay with titanium available

Screenshot attached
![EB6A1CA8-51B2-4900-A38B-0962ACFE1838](https://user-images.githubusercontent.com/7331135/75116929-0d096480-563b-11ea-95b3-eae77074d77e.png)

**Comment by vincentneko** [comment]
Thanks for the report. I confirm this is not working, will try to understand why...

**Comment by vincentneko** [comment]
All colonies cards with space tag cannot be payed with titanium. I don't know yet what is happening (cards have the space tag, like other playable cards)

**Comment by vincentneko** [comment]
ok got this one too !

**Comment by vincentneko** [comment]
Fixed and merged
