### ISSUE TITLE
ASTEROID RIGHTS options fix

### ISSUE THREAD

**Issue by kostya-phoenix** [bafolts/terraforming-mars#2930]
Hi!
How about to split first choice option into separate two? Like we have with Astrodril corporation card.

**Comment by bafolts** [comment]
@kostya-phoenix which option are you looking to split in two? Would the option `Remove 1 asteroid on this card to increase MC production 1 step OR gain 2 titanium` become one option for `Remove 1 asteroid on this card and increase MC production 1 step` and the other option be `Remove 1 asteroid on this card to gain 2 titanium`?
