### ISSUE TITLE
Feature request: Simplify Preference Panel

### ISSUE THREAD

**Issue by vsrisuknimit** [bafolts/terraforming-mars#2936]
![image](https://user-images.githubusercontent.com/14239220/110791748-94bf1280-8240-11eb-81f5-9fa4e646e84b.png)

There are way too many options. Most of these should never be a toggle to begin with. Some options should be grouped together. Perhaps more than one column would be useful.

**Comment by kberg** [comment]
The four examples you have highlighted all make sense to me. (Assuming Hide Tile Confirmation moves into Learner mode.)
