### ISSUE TITLE
Cannot send trade fleet?

### ISSUE THREAD

**Issue by lostgrail** [bafolts/terraforming-mars#294]
Playing with all expansions
Playing on iOS (iPad) - in case it’s a display issue

I don’t see HOW to send a trade fleet. It should be an option in the list (not a standard project). I also cannot tap on a colony to trade.

Also, curiously, there’s four colonies in my game: I should have had to pick three of the four, so may be related to an invalid game state.

Screenshot attached:
![23A75F05-EA73-4B74-91D6-E1B6D473DE84](https://user-images.githubusercontent.com/7331135/75117042-1810c480-563c-11ea-95c7-eb7c1274f701.png)

**Comment by lostgrail** [comment]
If it is an invalid game state issue, this may also be related: I did not trade the solo game with the two Mcred production penalty.

**Comment by vincentneko** [comment]
Thanks for the report. I confirm this is not working, will try to understand why...
And you are right, solo rules are not implemented yet.

**Comment by vincentneko** [comment]
Ok, found the issue with this one, PR incomming

**Comment by vincentneko** [comment]
Fixed and merged
