### ISSUE TITLE
Playing Solo get message “Invalid Input”

### ISSUE THREAD

**Issue by lostgrail** [bafolts/terraforming-mars#295]
Since I started playing your Demo last week, solo games always have a message on top saying: “Error with Input” with an OK button. When you click the button it takes you to a blank page saying “not found”.

Original game URL: https://terraforming-mars.herokuapp.com/player?id=8e80baad6095#board
“Not found” URL: https://terraforming-mars.herokuapp.com/player?#board

![09337DF2-5685-4D4A-87A8-5300616BA56E](https://user-images.githubusercontent.com/7331135/75117392-f533df80-563e-11ea-8182-817c3691d595.png)

![9CE10BA8-DDC4-4BDD-B493-58446E013FBC](https://user-images.githubusercontent.com/7331135/75117420-3926e480-563f-11ea-90c2-4a20896e991c.png)

**Comment by vincentneko** [comment]
Thanks for the report. Can you please describe how to reproduce this issue ?

**Comment by lostgrail** [comment]
Sure.

On iOS (iPad flavour) in Safari or up to date Windows 10 in Chrome:
 I start a solo game.

In detail:
1. From the README click the demo link. 
2. Enter a single user name (“Ben”)
2b. [option] Select any combination of Prelude, Colonies, Venus Next
3. Click “Create Game”
You’ll be taken to a screen with your game link
4. Click your link 
You will be taken to the screen with your actions (select Corp, starting hand, Prelude as appropriate)
The “ERROR WITH INPUT” is visible at the top of the screen. If you click OK, it takes you to the “not found” screen.
5. Make selections and start game
The “ERROR WITH INPUT” message is still visible. Clicking OK at any pint is Thebes same behaviour.

**Comment by lostgrail** [comment]
Im going to go out in a limb and assume you are developing in Mac? 

Do you serve an option to play Solo to 63 TR instead of “Terraform All”? I do not see that option when I start a game. My guess would be that’s the invalid input? Maybe it is not displaying on other environments.

**Comment by bafolts** [comment]
My assumption is that the error dialog is being seen at all times. The nes.css library is used for dialogs and this dialog must always be visible in your browsers for some reason. Clicking the OK button is probably leading to some default URL which is not found.

**Comment by bafolts** [comment]
We use the `dialog` element which isn't supported in any browser but chrome. We will need to use the dialog-polyfill

https://github.com/GoogleChrome/dialog-polyfill

**Comment by bafolts** [comment]
We don't have the option to use the play to 63 option for solo TR. Please make a separate issue for that so we can track it separately.

**Comment by lostgrail** [comment]
Oh, more I was just wondering if it was an undefined state. So the error maybe meant that info was missing because I couldn’t properly see an option I had to pick. But since you mention it 😉

**Comment by lostgrail** [comment]
Interesting that I see it on iOS safari if it’s only supported in Chrome.

**Comment by alrusdi** [comment]
@lostgrail we are merged dialog polyfill library to main branch. Is the problem solved for you?

**Comment by lostgrail** [comment]
Can confirm; issue is resolved on iOS.

Thank you! I appreciate all the hard work
