### ISSUE TITLE
Feature request: log for production multiplier

### ISSUE THREAD

**Issue by vsrisuknimit** [bafolts/terraforming-mars#2956]
In the log, show how much a player gain for production multiplier cards such as Cartel, Galilean Waystation, Community Service.

**Comment by kberg** [comment]
For cards like that, you can accomplish the bare minimum by changing the second line of

```
public play(player: Player) {
  player.addProduction(Resources.MEGACREDITS, player.getTagCount(Tags.EARTH) + 1);
  return undefined;
}
```

to 

`player.addProduction(Resources.MEGACREDITS, player.getTagCount(Tags.EARTH) + 1, player.game);`

IMO this should happen ALL the time, but as I think you mentioned somewhere else, save that for the big logs reckoning.
