### ISSUE TITLE
"Take action for action phase, select one available action" is just too many words

### ISSUE THREAD

**Issue by kberg** [bafolts/terraforming-mars#2958]
![image](https://user-images.githubusercontent.com/413481/111074266-96930b00-84b8-11eb-921b-ea6e8e3eaaa0.png)

There are four translations, so I think this won't be that hard to fix.

**Comment by bafolts** [comment]
Using `Select action for action phase` could work.

**Comment by kberg** [comment]
Consider: Take your first action / Take your second action.

>

**Comment by bafolts** [comment]
> Consider: Take your first action / Take your second action.

This would also help players remember how many actions they have less to take :+1: . I believe this was the original string I happened to write way back when. I had the instruction manual next to me so a lot of the original messages were verbose.

https://github.com/bafolts/terraforming-mars/blob/87510620b7684003feb586c875e32c5f58f327d0/src/Player.ts#L635

Makes sense to me to upgrade to `Take your first action` and `Take your second action`.
