### ISSUE TITLE
'Buffer Gas' standard project seems to have vanished from 63TR solo mode

### ISSUE THREAD

**Issue by tjhughes1964** [bafolts/terraforming-mars#2961]
Need I say more?

**Comment by kberg** [comment]
There was a fix 3 days ago: https://github.com/bafolts/terraforming-mars/pull/2933 Where are you experiencing this?

**Comment by vsrisuknimit** [comment]
@kberg This is reproducible. #2933 caused a bug.

![image](https://user-images.githubusercontent.com/14239220/111154378-8b4be800-8569-11eb-8f26-ebe7eeb0c579.png)

**Comment by vsrisuknimit** [comment]
Tagging @bafolts.

**Comment by bafolts** [comment]
With the fix buffer gas was being shown too much. Now it seems it is not shown enough. Quite surprised as the check was simplified to look for one player in the players array on the Game class.
