### ISSUE TITLE
Feature Request: Playing Solo mode to 63 TR instead of Terraform All

### ISSUE THREAD

**Issue by lostgrail** [bafolts/terraforming-mars#297]
As described in Prelude expansion: play solo in an attempt to get 63 TR instead of terraforming all three (or four, with Venus) parameters

**Comment by bafolts** [comment]
I will wait until after #331 to implement this as a new solo only option will be needed.

**Comment by lostgrail** [comment]
Thank you for the update :)

**Comment by vincentneko** [comment]
@bafolts May I take care of this one ?

**Comment by bafolts** [comment]
Yes

**Comment by vincentneko** [comment]
Done and merged
