### ISSUE TITLE
Bug: allow targeting oneself with Comet

### ISSUE THREAD

**Issue by vsrisuknimit** [bafolts/terraforming-mars#2970]
In the following situation:
1) Multiplayer games,
2) No opponent target for plant destruction
3) You have clash site cleanup in hand

The app should offer a choice of burning your own plants (just 1 plant regardless of Deimos or Small Asteroid), in order to trigger clash site cleanup.

Edge case but real bug.

**Comment by Lynesth** [comment]
Doesn't work that way since the card says:
REQUIRES THAT A PLAYER REMOVED **ANOTHER PLAYER**'S PLANTS THIS GENERATION

**Comment by vsrisuknimit** [comment]
@Lynesth you are certainly right.
