### ISSUE TITLE
[Moon] Fix Earth Embassy visualization

### ISSUE THREAD

**Issue by kberg** [bafolts/terraforming-mars#2989]
![image](https://user-images.githubusercontent.com/413481/111909084-378e4280-8a32-11eb-9b7b-0ca8b1cac863.png)

The code for rendering this is
```
renderData: CardRenderer.builder((b) => {
  b.effect('After being played, when you perform an action, your Moon tags count as Earth tags, but not vice versa.', (eb) => {
    eb.empty().startEffect.moon().nbsp.text(' = ').nbsp.text('earth');
  });
}),
```

No matter what I do I can't get both tags to show up.

**Comment by chosta** [comment]
So instead of the text "earth" we want an Earth tag?

**Comment by kberg** [comment]
Yes.

![image](https://user-images.githubusercontent.com/413481/112185157-5a595c00-8bd6-11eb-9317-d8ccd714ce1d.png)
