### ISSUE TITLE
Discounts to trade cost not factored into trade action availability 

### ISSUE THREAD

**Issue by lostgrail** [bafolts/terraforming-mars#300]
Playing With only Colonies, I had both Rim Freighters and Cryo Sleep in play (each provides a -1 discount to trade cost). I had one energy (enough to trade with the discounts, but not enough normally) and had not traded yet this turn. No titanium and not enough MCred. The option to trade was not available in the action list.

The discounts applied correctly if I had enough to pay the full amount, and displayed correctly in the trade menu. 

![16747E82-5E49-4C4E-810D-15BC5E6F515D](https://user-images.githubusercontent.com/7331135/75129248-1d9af880-5696-11ea-9272-ec8a07c58233.png)
![9C6967F5-9B88-4DBC-9AFB-60069544E78D](https://user-images.githubusercontent.com/7331135/75129252-212e7f80-5696-11ea-8d40-e2388dd1bcb8.png)
![5F4E53F2-E526-4EB9-A009-CC3C48B64A58](https://user-images.githubusercontent.com/7331135/75129253-21c71600-5696-11ea-9ea3-c4a519a2a372.png)

Thanks for all the hard work!

**Comment by vincentneko** [comment]
Thanks for testing and feedback. Will take care of this one.

**Comment by lostgrail** [comment]
This is waaay more fun to test than what I usually get my hands on ;)

**Comment by vincentneko** [comment]
Fixed and merged
