### ISSUE TITLE
feature: option to remove all "attack"-cards

### ISSUE THREAD

**Issue by aws0m** [bafolts/terraforming-mars#3001]
Would be really nice if just like you have the option to filter out all the negative turmoil event cards. My SO really doesnt like them so when we play games together we have agreed to not play them :) but that in itself is a little problematic as then those cards just take up space in the game etc.

**Comment by nwai90** [comment]
@aws0m You can enter a custom list of cards to exclude, and download the a copy of the JSON settings. The saved custom settings can be re-uploaded for future games.

**Comment by alrusdi** [comment]
We already have an option like this. Have you noticed it?
![no-negative-events](https://user-images.githubusercontent.com/394311/111966532-d68d6a00-8b18-11eb-84c0-cf66edf46c40.png)

**Comment by aws0m** [comment]
somehow I misswrote that. What I  mean to say what that it would be nice if there was a function/button to filter out all the attack cards just like the button you have for filtering out all the negative turmoil cards :)

I ll look into the custom card list tho.

**Comment by alrusdi** [comment]
> somehow I misswrote that. 

Ah! Then custom game settings is a good variant indeed
