### ISSUE TITLE
[Agendas] Bug: Science requirement bug

### ISSUE THREAD

**Issue by vsrisuknimit** [bafolts/terraforming-mars#3009]
![image](https://user-images.githubusercontent.com/14239220/112148284-1190ab80-8bb4-11eb-86a3-e84f478cd087.png)

**Comment by nwai90** [comment]
Closed as non-reproducible: https://tfm-community.herokuapp.com/player?id=p5260e27760e8

There is a unit test already covering this code. Issue can be reopened if it recurs
