### ISSUE TITLE
Feature: Spectator Mode

### ISSUE THREAD

**Issue by aws0m** [bafolts/terraforming-mars#3015]
If there is already and issue for this I do apologize.

For both personal and for streaming purposes it would be awesome if there was a spectator mode. Like a extra player at the game table who gets access to the players score and resources boxes and the logs, and preferable the space to click on the cards in the log and all that other great stuff the webapp already has.

For streaming purposes more (but also for just spectating) one thing that would be huge is if there was a way for webpage to reload itself when actions are taken just like how you can see the First action of your opponent before they make their Second action in what I would describe to me at least as seeing the game state in real-time.

If you could get a way to constantly see the game state change when it does you could do some cool stuff with streaming I belive. 

Thx! awsöm

**Comment by bafolts** [comment]
The server side portion of this change is in place and work has started on the client side part of this change. Stay tuned.

**Comment by kberg** [comment]
Update: this is now available on terraforming-mars.herokuapp.com.
