### ISSUE TITLE
Elysium board: Wrong placement bonus and ocean tile issue

### ISSUE THREAD

**Issue by dabewi** [bafolts/terraforming-mars#302]
Hi,

a friend of mine noticed that there are two differences between the original Elysium board and the Elysium board here. I've marked them here:

https://abload.de/img/elysium2isjig.png

One placement bonus (a plant) is on the wrong field and one place for ocean tiles doesn't belong there (that makes the amount of ocean fields 13 instead of the normal 12 which could be very relevant for the Estate Dealer award).

For comparison, here is a picture of the original Elysium board (with the same markers):

https://abload.de/img/elysiumu2jr6.jpg

Cheers!

**Comment by vincentneko** [comment]
Thanks for your feedback, I will correct it asap.

**Comment by vincentneko** [comment]
Fixed and merged
