### ISSUE TITLE
Google search result

### ISSUE THREAD

**Issue by vsrisuknimit** [bafolts/terraforming-mars#3029]
![image](https://user-images.githubusercontent.com/14239220/112518531-d2a75500-8d6f-11eb-84e1-f27af81795fa.png)

Google search result currently has a weird title and snippet. It would be nice to adjust it.

https://developers.google.com/search/docs/advanced/appearance/good-titles-snippets

**Comment by bafolts** [comment]
I don't know if we have control over it but I will add a meta description tag and hope google picks that.
