### ISSUE TITLE
Feature request: Warning prompt for passing while having unused delegate in the lobby 

### ISSUE THREAD

**Issue by vsrisuknimit** [bafolts/terraforming-mars#3037]
If you click 'pass for the generation' while having a delegate in the lobby, the game prompts whether you want to pass for real or just cancel the passing for now. 

Make it the same way as tile placement confirmation but with no way to turn it off since it should be very rare that anyone want to pass without sending any delegate.

**Comment by leggupdown** [comment]
Can this be in learner's mode or default off? The fact that all options for actions appear and disappear whether or not they are available means that only distracted or new players are going to miss their delegate.

**Comment by vsrisuknimit** [comment]
@leggupdown the option will be the same. But when you select 'pass for the generation' and click 'pass', it will just prompt a warning if you happen to have a delegate unused in the lobby still. You can continue forward with passing or cancel that pass and take a different action.

![image](https://user-images.githubusercontent.com/14239220/112640312-99c2bb00-8e17-11eb-8819-ee8b47e328fc.png)

**Comment by kberg** [comment]
I'm trying to decide whether this is specialized in a good way or in a bad way. The same doesn't happen with action cards (and if you're like me, you really don't want it to keep offering first and foremost that you can spend 10MC to gain 2 heat production, and would honestly prefer those to stop being what was offered first.)

But I think this falls toward being specialized in a good way.

**Comment by vsrisuknimit** [comment]
@kberg this is a free action that someone should always use. There is rarely a case that you don't want to send free delegate from the lobby. And I see a lot of people forget them because it is not part of the perform action that they can see.

**Comment by kberg** [comment]
Yeah, I agree.

**Comment by kberg** [comment]
An easy way to implement this without a popup is to provide a sub-option to
Pass that says "Yes, I really want to pass without playing my free
delegate." Non-intrusive, and should not happen to experienced players.

**Comment by vsrisuknimit** [comment]
I think the intrusiveness is fine in this case as it should really warn the player they are about to do something regretable.
