### ISSUE TITLE
Game page no longer updates automatically while drafting

### ISSUE THREAD

**Issue by nwai90** [bafolts/terraforming-mars#3044]
Example game:
https://terraforming-mars.herokuapp.com/player?id=p7f12e59759d3
https://terraforming-mars.herokuapp.com/player?id=pabaa9443a013

The first player(s) to draft have to refresh the page to continue with the next step of the draft

**Comment by kberg** [comment]
I think this is https://github.com/bafolts/terraforming-mars/pull/3041
