### ISSUE TITLE
Bug: Too many notification

### ISSUE THREAD

**Issue by vsrisuknimit** [bafolts/terraforming-mars#3047]
![image](https://user-images.githubusercontent.com/14239220/112757590-64090800-8fb8-11eb-9f55-70e92fdeca13.png)
![image](https://user-images.githubusercontent.com/14239220/112757597-6b301600-8fb8-11eb-85be-a781b4bf7827.png)
![image](https://user-images.githubusercontent.com/14239220/112757605-72572400-8fb8-11eb-85e3-7166ad469fa6.png)

After #3045, users seem to receive way too many notifications.

@bafolts

**Comment by bafolts** [comment]
Does seem to impact draft phase as I am now coming to learn that draft phase doesn't update `gameAge` which is an oversight on my part. Anything that progresses the game should increment `gameAge`. I can put up PR to remove the `ETag`.
