### ISSUE TITLE
Wild card symbol counts multiple times for Ecologist

### ISSUE THREAD

**Issue by K-Hartmann** [bafolts/terraforming-mars#306]
In the screenshots you can see that the player is able to claim the Ecologist Milestone with only a wild-tag and one microbe-tag in play. Maybe the wild-tag counts as Microbe, Plant and Animal-Tag simultaniously. Could affect other wild-tags and the diversifier Milestone as well

![2020-02-24_20h15_28](https://user-images.githubusercontent.com/41374984/75183318-95266180-5742-11ea-9b6d-ef3d0a933aee.png)
![2020-02-24_20h16_37](https://user-images.githubusercontent.com/41374984/75183323-9788bb80-5742-11ea-8dbd-6dda6088919f.png)

**Comment by vincentneko** [comment]
Fixed and merged
