### ISSUE TITLE
Philares corporations first action in prelude phase

### ISSUE THREAD

**Issue by K-Hartmann** [bafolts/terraforming-mars#307]
When playing Philares with prelude expansion, the greenery must be placed imediately after playing the prelude cards. This also triggers a normal play phase for the player who, can now play a second card even before the other players played their prelude cards.

![2020-02-24_20h24_42](https://user-images.githubusercontent.com/41374984/75183983-e6832080-5743-11ea-9cea-620ad1ac30ab.png)
![2020-02-24_20h27_00](https://user-images.githubusercontent.com/41374984/75184026-fb5fb400-5743-11ea-9f86-c63e2beffa36.png)

**Comment by alrusdi** [comment]
This should be fixed now
