### ISSUE TITLE
[Ares] Ecological Survey doesn't grant extra plants with a plant placement bonus

### ISSUE THREAD

**Issue by ap3h3ad** [bafolts/terraforming-mars#3093]
Hi,

we've experienced the following situation: A player played Ecological Survey, which should grant extra plants/animals/microbes whenever you place a tile that gets those resources as a placement bonus. Then he places a tile on a field on the board where he gets plants as a placement bonus (printed on the board). Now he should get a bonus plant from Ecological Survey. In fact he only gets the plants that are printed on the board. 

According to the author of the card the intent is that the Ecological Survey should indeed also give the extra plant when placing a tile on the board: https://boardgamegeek.com/thread/2218211/article/36945904#36945904

Also: The cards text suggests that the player also gets an additional pet to the pets-card if he places a city tile (because placing the city tile grants a pet and Ecological Survey should double the pets).

**Comment by kberg** [comment]
What happened?

**Comment by ap3h3ad** [comment]
Sorry - it was a misunderstanding betmeen me and my opponents that reported the bug.

**Comment by kberg** [comment]
Excellent! Thanks. Have fun!
