### ISSUE TITLE
Philares adjacency ability not counting properly

### ISSUE THREAD

**Issue by K-Hartmann** [bafolts/terraforming-mars#310]
While playing Philares, i had multiple instances of recources to be gained, counted wrong, either to high or too low. In the first screenshot, Restricted Area was played next to my starting greenery, in the second screenshot, the Mining Area was not placed adjacend to any of my tiles

![2020-02-24_20h12_36](https://user-images.githubusercontent.com/41374984/75269518-53a4bd80-57f9-11ea-84f8-c5f3c3b58a34.png)

![2020-02-25_16h11_31](https://user-images.githubusercontent.com/41374984/75269678-936ba500-57f9-11ea-88c1-f94d644368cf.png)

**Comment by vincentneko** [comment]
Seems to be fixed by player actions rework
