### ISSUE TITLE
Feature request: Milestones and Awards predictor

### ISSUE THREAD

**Issue by vsrisuknimit** [bafolts/terraforming-mars#3100]
For certain awards, the current number and how the real-time VP is calculated do not represent real players' standings. 

![image](https://user-images.githubusercontent.com/14239220/113570197-d776cf00-95e1-11eb-8d74-94fc2538767c.png)

Thermalist: It should count heat + heat production + energy, until the end of the game where it only counts heat.

Industrialist: it should count steel + steel production + energy production, until the end of the game where it only counts steel + energy.

Miner: it should count steel + steel prod + titanium + titanium prod, until the end of the game where it only counts steel and titanium.

**Comment by kevinb9n** [comment]
Excellent improvement. It makes sense to fix just these clear-cut cases and not do guesswork about Cultivator.
