### ISSUE TITLE
Bug: Misleading button labels

### ISSUE THREAD

**Issue by vsrisuknimit** [bafolts/terraforming-mars#3104]
#3079 introduced this visual bug. Now all buttons have number on them when it does not make any sense.

![image](https://user-images.githubusercontent.com/14239220/113696502-1a977780-96a0-11eb-8267-1a04a0931245.png)

![image](https://user-images.githubusercontent.com/14239220/113696518-208d5880-96a0-11eb-8556-bcf69cfcc480.png)

@kberg

**Comment by kberg** [comment]
You know, the easiest thing is to remove all the numbers and try again
later. What do you think?

**Comment by vsrisuknimit** [comment]
That seems reasonable.
- Part 1 of #3096 should already prevent mis-click for Business Network and Inventor Guild. So the number should no longer be needed there. Still helpful but not essential.
- Number should only be added for KEEP, BUY, SELECT, DISCARD. Not sure what else.

**Comment by bafolts** [comment]
Removing the numbers altogether or the change in https://github.com/bafolts/terraforming-mars/pull/3109/files makes sense to me. I still am not sure the _danger_ button color is going to help anything. Given the issue with `OrOptions` not being able to share the button with it's child component makes sense to remove number for now. Until we solve problem of sharing the `Button` between `OrOptions` and it's child component we will have to duplicate what we display on any button.

**Comment by vsrisuknimit** [comment]
@bafolts One of the most common mistakes and game-breaking is when players accidentally discarding some cards when they want to play. This happens quite frequently since the selectCard works exactly the same way to play and discard/sell. One way to differentiate it so that the user stops and notice they are doing something different is by color coding.

https://github.com/bafolts/terraforming-mars/pull/3096#issuecomment-812852059
