### ISSUE TITLE
Trade discounts applied to cards?

### ISSUE THREAD

**Issue by lostgrail** [bafolts/terraforming-mars#311]
When playing, I was given a 1MCred discount on playing the project card “Market Manipulation”, but I did not have anything to provide such a discount. I did however have Rim Freighters which provides a 1 MCred discount on my Trade actions.

![4B1D4188-96D4-416B-927E-7F32A571CA6C](https://user-images.githubusercontent.com/7331135/75274165-57701a00-57d0-11ea-8cfb-ee7342a5a2c2.jpeg)
![C6CCD3DC-3D8C-432C-B394-550BB7D3ECB5](https://user-images.githubusercontent.com/7331135/75274172-5a6b0a80-57d0-11ea-976f-87d69ed7828a.jpeg)
![F7584A36-89FA-4A49-9A69-08AC2C3023DF](https://user-images.githubusercontent.com/7331135/75274176-5b9c3780-57d0-11ea-8e37-611d5c302469.jpeg)

**Comment by vincentneko** [comment]
Thanks for the report. Card cost was 0 instead of 1 MC !

**Comment by vincentneko** [comment]
Fixed and merged
