### ISSUE TITLE
Bug: New game page works but shows 'unexpected server response'

### ISSUE THREAD

**Issue by vsrisuknimit** [bafolts/terraforming-mars#3111]
You get the error message as soon as you open the page. But it will work and create the game fine.

![image](https://user-images.githubusercontent.com/14239220/114032902-c7155d00-984a-11eb-8b13-70d63e603120.png)

I previously saw this on my server as well.

**Comment by bafolts** [comment]
I have also seen this locally. @vsrisuknimit if you see it again can you see if anything was logged to the console of the server? We should be logging what the error is to console.

**Comment by kberg** [comment]
Still an issue? This is 3-weeks old.
