### ISSUE TITLE
Bug: Games down

### ISSUE THREAD

**Issue by vsrisuknimit** [bafolts/terraforming-mars#3113]
#3110 broke existing games.

https://github.com/bafolts/terraforming-mars/pull/3110/files

@kberg @bafolts

**Comment by vsrisuknimit** [comment]
I thought we are supposed to avoid changing enum.

**Comment by bafolts** [comment]
Moon is listed as beta. Until the beta is not listed it wont be as stable as the other game options.

**Comment by vsrisuknimit** [comment]
@bafolts It seems to kill non-Moon games. @nwai90's game: https://terraforming-mars.herokuapp.com/game?id=g79394e6f23a0

**Comment by bafolts** [comment]
That could be unrelated. In the logs I see this error for that game id:

```
2021-04-08T15:18:28.442880+00:00 app[web.1]: [2021-04-08 15:18:28 GMT+0000] Not found GET /api/game?id=g79394e6f23a0
```

That is surprising unless the game was purged from the database by our process which runs during a server restart. How old was the game?

**Comment by vsrisuknimit** [comment]
2 hours old

**Comment by vsrisuknimit** [comment]
Server seems to be back and working normally. Perhaps one time thing.

**Comment by bafolts** [comment]
If for some reason when the game was created it didn't get saved to the database that would make us unable to pull it from database. If this is an ongoing issue we will see it happen tomorrow when server restarts.
