### ISSUE TITLE
Hours in the timer looks a bit weird

### ISSUE THREAD

**Issue by grichman** [bafolts/terraforming-mars#3118]
It looks a bit squished, and at a glance it seems like the person who's gone over an hour actually has used less time. I think it should be pretty easy to fix:
![before](https://user-images.githubusercontent.com/2635537/114256587-393f8c00-9988-11eb-8a79-edf92b234f0a.PNG)
![after](https://user-images.githubusercontent.com/2635537/114256591-3ba1e600-9988-11eb-9c6b-df047d2cfe10.PNG)

**Comment by puuj** [comment]
I made the initial commits for hours, and at the time there was a concern about the space the timer was taking up. I don't think that's as much of an issue now so maybe there is more willingness to have everything be the same size.
