### ISSUE TITLE
RFC: E-mail turn notifications

### ISSUE THREAD

**Issue by puuj** [bafolts/terraforming-mars#3123]
This is a niche feature and I suspect most won't want it merged into the main branch, but I thought I'd mention it here. My group mostly plays long async games and is spread over time zones. Sometimes we're all at our desks and the normal notifications and sounds are effective, but when people are playing with a mobile device and aren't aware it's their turn. My solution to this has been to implement e-mail notifications. 

The strategy is:
- Add an optional e-mail to the Player/SerializedPlayer class
- Create a standalone script that can run as a cron job that iterates over games:
   - Deserialize the game
   - Use the Player.waitingFor value to determine all acting players
   - Use the timer's startedAt value to determine how long the player has been idle
   - Send an e-mail to players who have been idle more than n minutes but less than n+I minutes

The plan is to run the script as a cron job with interval I. I've implemented and tested this, but before pushing it into the live version, I thought I'd get some feedback. Right now most of the work is done in the cron job, and the only changes to the core repo is to add an e-mail. This, or some sort of account system, might be a reasonable feature to include long-term to allow game-matching or stats tracking or whatever.

There are a few questions/concerns:
- The DB loading and deserialization are non-invasive, right? No chance they can hurt the running game?
- Deserializing the game seems somewhat expensive, but it seemed the simplest way to determine acting players without duplicating lots of complicated code. Any other options? Hitting the WaitingFor API with every PlayerID could work, but that wouldn't tell me how long the timer has been running.
- Another hack is that, since the Timer fields are private, I serialize the Timer to access them. Adding accessors would be neater.

**Comment by bafolts** [comment]
The live version usually runs on heroku. Can heroku send emails on the hobby plans? My concerns would be with how the emails were sent.

**Comment by kberg** [comment]
I'm looking -- at a slow pace -- into the ability to integrate with oauth,
specifically discord oauth. And if you do that, then discord could also be
your notification source. /shrug

>

**Comment by bafolts** [comment]
Yes. Leveraging discord would be good for this. I would prefer that to sending emails with smtp. If using smtp would need some service to send the emails. Discord is built for games so would make sense to me to use that service.

**Comment by puuj** [comment]
I'm sort of agnostic on how the notification happens at this point, since that could be configurable. The real questions are more about the technical approach here -- what would be the best way to implement this?

**Comment by bafolts** [comment]
I think this would have to run and start with the game server. I don't think we write to the database often enough to do this with a separate service querying the database.

> The DB loading and deserialization are non-invasive, right? No chance they can hurt the running game?

Not sure the definition of invasive in this context but the games are loaded from the database asynchronously. The deserialization step is synchronous but is not an impact on the CPU of the server.

> Deserializing the game seems somewhat expensive, but it seemed the simplest way to determine acting players without duplicating lots of complicated code. Any other options? Hitting the WaitingFor API with every PlayerID could work, but that wouldn't tell me how long the timer has been running.

Deserializing the games would be expensive if we were to deserialize a thousand games synchronously. That would definitely end up blocking the event loop. I don't think we write the game state to the database often enough to do this with only deserializing what is already in the database. This notification service would have to run with the app unless we wrote more information to the database.

> Another hack is that, since the Timer fields are private, I serialize the Timer to access them. Adding accessors would be neater.

If a field is needed we should add an accessor for the value.

**Comment by puuj** [comment]
Thanks @bafolts for the feedback. My version of this seems to be working out on a small scale, but I now have a sense of how the production version of this might be implemented -- set an async event when the waitingFor gets updated and then possibly have the notifier set another async event if a reminder is necessary. I could try adding in some of this, but probably it makes sense to just wait until @kberg gets to that OAuth integration.
