### ISSUE TITLE
Market Manipulation let’s you “reduce” tracks that are at their bottom or not yet activated

### ISSUE THREAD

**Issue by lostgrail** [bafolts/terraforming-mars#313]
As the title states: playing Market Manipulation I was able to successfully move the Titan track down one step despite the track not yet being activated due to no floater cards in play. Similarly, I was presented with the option of lowering the Luna track when it had just been set to its end due to a trade action.

![85E8FBC4-F967-48B2-B3EF-D69B01D54FA8](https://user-images.githubusercontent.com/7331135/75274480-ed0ba980-57d0-11ea-92ff-3a55ba2b758e.jpeg)
![44CD508A-8189-4B18-A545-9143F29FDE97](https://user-images.githubusercontent.com/7331135/75274489-f268f400-57d0-11ea-9cef-7afbd75fa3db.jpeg)
![A4339599-9397-48B6-B21D-4C8DCEFE3951](https://user-images.githubusercontent.com/7331135/75274494-f3018a80-57d0-11ea-9731-7fe7940820e7.jpeg)

**Comment by vincentneko** [comment]
I will add a filter to remove not active colonies.
Luna was not offered for the option to lower track btw.

**Comment by lostgrail** [comment]
Sorry, yes. You are correct. I was only half so ;)

**Comment by vincentneko** [comment]
Fixed and merged
