### ISSUE TITLE
Feature request: game_result improvement

### ISSUE THREAD

**Issue by vsrisuknimit** [bafolts/terraforming-mars#3132]
- Looking at the data in game_result, you cannot currently tell whether a solo game is won or lost. Just a score which does not mean much for solo game.
- It would be nice to have a timestamp when the game was started or was finished. We could look back and compare it to known version of the server, known bugs, expansion released and so on.
- It would be nice to have a list of corporation that were dealt out. This way we can calculate how many times a corp is picked compared to all the time it has been dealt out.

@bafolts

**Comment by kberg** [comment]
> * Looking at the data in game_result, you cannot currently tell whether a solo game is won or lost. Just a score which does not mean much for solo game.

game options will give you the information about the solo victory conditions.
> It would be nice to have a timestamp when the game was started or was finished. We could look back and compare it to known version of the server, known bugs, expansion released and so on.

I agree, it's valuable for many things.  I've looked at making such changes, but getting database changes just right like this on a running server is a little tricky.

> * It would be nice to have a list of corporation that were dealt out. This way we can calculate how many times a corp is picked compared to all the time it has been dealt out.

This is fetchable from the original table, which stores the initial and final game position, just by selecting game potsition zero.

**Comment by vsrisuknimit** [comment]
>> Looking at the data in game_result, you cannot currently tell whether a solo game is won or lost. Just a score which does not mean much for solo game.
> game options will give you the information about the solo victory conditions.

It does not tell you whether the game is won or lost. Game options just tells you whether it is 63 TR or not.

>> It would be nice to have a list of corporation that were dealt out. This way we can calculate how many times a corp is picked compared to all the time it has been dealt out.

> This is fetchable from the original table, which stores the initial and final game position, just by selecting game potsition zero.

as @puuj pointed out in the other issue, that table does not last as long as the game_result. There are games whose game_id present in game_result but not in games. So the point is to store some useful information in game_result as well.

**Comment by kberg** [comment]
On Mon, Apr 12, 2021 at 6:18 AM Jeep ***@***.***> wrote:

> Looking at the data in game_result, you cannot currently tell whether a
> solo game is won or lost. Just a score which does not mean much for solo
> game.
>
> game options will give you the information about the solo victory
> conditions.
>
> It does not tell you whether the game is won or lost. Game options just
> tells you whether it is 63 TR or not.
>
Yes, though you have enough information to compute it.

.. except, ugh, the win condition in solo games is decided *before* the
final save. Yeah, you're right.

> It would be nice to have a list of corporation that were dealt out. This
> way we can calculate how many times a corp is picked compared to all the
> time it has been dealt out.
>
> This is fetchable from the original table, which stores the initial and
> final game position, just by selecting game potsition zero.
>
> as @puuj <https://github.com/puuj> pointed out in the other issue, that
> table does not last as long as the game_result. There are games whose
> game_id present in game_result but not in games. So the point is to store
> some useful information in game_result as well.
>
Isn't the last save in there? Perhaps it's purged. Yeah, also, fair point.

**Comment by bafolts** [comment]
> Looking at the data in game_result, you cannot currently tell whether a solo game is won or lost. Just a score which does not mean much for solo game.

We could add a field to the `game_results` table but this data will be missing for rows in the database already. Would need a default value to represent when we don't know, using `NULL` probably fine for when we don't have the data.

> It would be nice to have a timestamp when the game was started or was finished. We could look back and compare it to known version of the server, known bugs, expansion released and so on.

The `game_results` table has no timestamp fields so makes sense to add one. Having a `created_time` would probably help with even more than the examples you provided. For all the rows already in the database this would end up with whatever date the column is added.

> It would be nice to have a list of corporation that were dealt out. This way we can calculate how many times a corp is picked compared to all the time it has been dealt out.

We have this data on player. Would have to add a new field to the `game_results` table and store the card names. As we are known to do inevitably we will change a card name so the name of the card may get out dated.

We support Postgres, SQLite and local file system. For Postgres and SQLite will need to alter the table and add the columns if they don't exist.

https://www.postgresql.org/docs/12/sql-altertable.html
https://sqlite.org/lang_altertable.html

For popular heroku instances like `terraforming-mars.herokuapp.com` we would want to run this manually ahead of time to alter the table.

**Comment by kberg** [comment]
> We support Postgres, SQLite and local file system. For Postgres and SQLite will need to alter the table and add the columns if they don't exist.

The thing I'd wonded is whether it would make sense to add a single field for all extra game results data as a JSON object.

**Comment by bafolts** [comment]
Using a single field as a JSON object would make sense and avoid having to add a column every time we want to store more data. I remember the JSON objects for a `Game` being 20-30kb. Eventually storing enough of these game results we will run out of space on the 10GB postgres plan. Since the data can be archived we could post a dump of the `game_results` table somewhere every month (or year) to free up space.

**Comment by puuj** [comment]
I'll just comment here, that I agree with both adding a timestamp and adding the serialized game to the game_results table. If the results take up too much space, it would be relatively painless to archive and then delete the oldest records from the table, so that there are at most 100K (or config-var) game_results saved. If both changes are made together, less of a pain.

The only open question is if @kberg ever gets around to moving logs to another table, how that would work with game results -- would it be worth snapshotting the logs and adding it to the game, or is that too verbose? It'd be nice if the same analysis being done on corps could be done on cards.

**Comment by kberg** [comment]
oh my gosh the list of things i have said i would do.
