### ISSUE TITLE
Philares adjacency ability disrupts action counter

### ISSUE THREAD

**Issue by K-Hartmann** [bafolts/terraforming-mars#314]
Sometimes (not sure under which circumstances, but most certainly regarding the adjacency ability) it is possible to do more that 3 actions with Philares. In the screenshon I was able to play 3 cards and it was still my turn after generating 1titan from blue player. (The recource was wrongly genereated, see https://github.com/bafolts/terraforming-mars/issues/310)

![2020-02-25_16h16_17](https://user-images.githubusercontent.com/41374984/75276917-57d7d780-5807-11ea-8b6a-22b526db50fa.png)
)

**Comment by vincentneko** [comment]
This one should be working as expected now that @bafolts has modified the takeAction method.
Will wait some feedback before closing this one.

**Comment by K-Hartmann** [comment]
@vincentneko 
Perfekt, i will try to play philares again on an updated machine in the next days.

**Comment by K-Hartmann** [comment]
@vincentneko 
I could not reproduce the issues with Philares with the latest build. Seems to be fixed now!

**Comment by vincentneko** [comment]
@K-Hartmann  Great ! thanks for testing this, and thanks @bafolts for fixing this !
