### ISSUE TITLE
Titan Floating Launch Pad lets you trade an extra time

### ISSUE THREAD

**Issue by lostgrail** [bafolts/terraforming-mars#316]
After using Titan Floating Launch Pad, I am still given the option to trade, even though I only have the one trade fleet

![3364E4F7-62AD-4373-B9F9-231CF645ECE7](https://user-images.githubusercontent.com/7331135/75312525-2b808300-5828-11ea-9dd2-2261f58c8e41.png)
![F28523F4-E199-4DC6-B744-C931659C060C](https://user-images.githubusercontent.com/7331135/75312529-2c191980-5828-11ea-8286-854d0d99cc57.png)
![CF5C292C-5E41-4B7E-AF7C-1C12E2D4AA16](https://user-images.githubusercontent.com/7331135/75312531-2cb1b000-5828-11ea-9d23-1852ee7f7315.png)

**Comment by vincentneko** [comment]
Thanks for the feedback.
Fixed and merged !
