### ISSUE TITLE
Solo game does not end before turn 12 if all Terraforming is complete 

### ISSUE THREAD

**Issue by lostgrail** [bafolts/terraforming-mars#317]
Solo game in which all Terraforming was completed on turn 11 proceeded to have a 12th turn

![7D647E37-7D2B-4870-919B-E387EEEA3095](https://user-images.githubusercontent.com/7331135/75316825-5c66b500-5834-11ea-82c9-07ff9f3f69dc.png)

**Comment by lostgrail** [comment]
Not sure if it matters, but this was a Preludes game, so only 12 turns

**Comment by alrusdi** [comment]
It is correct behavior by the rules. You always play 14 (or 12 with Preludes) generations.
