### ISSUE TITLE
[Moon] Visual bug on Aristarchus Road Network card (Moon)

### ISSUE THREAD

**Issue by alrusdi** [bafolts/terraforming-mars#3192]
![aristarchus_bug](https://user-images.githubusercontent.com/394311/115751348-8d983200-a3b2-11eb-8699-e35e177549be.png)

**Comment by kberg** [comment]
Found it.

![image](https://user-images.githubusercontent.com/413481/115826669-43767700-a3d9-11eb-8df7-25505ac7667f.png)
