### ISSUE TITLE
Cannot place Lava Flows on Aria Mons on Tharsis map

### ISSUE THREAD

**Issue by lostgrail** [bafolts/terraforming-mars#320]
When going to place Lava Flows (must be placed on a volcano), Arsia Mons was not highlighted, and I could not place the tile in the correct place

![32E9BBCD-19E3-48D5-92A9-907E3DC016F8](https://user-images.githubusercontent.com/7331135/75409575-19b1e500-58e7-11ea-9a07-7102f06b837d.png)

**Comment by bafolts** [comment]
From the provided screenshot it looks like Arsia Mons is highlighted. Which space were you expecting to be highlighted. Arsia Mons is the space furthest to the left which appears highlighted in your screenshot.

**Comment by lostgrail** [comment]
Arsia Mons is the far right, between the two oceans. Highlighted here:
![A84EB24E-E777-478D-B5D7-C44034432150](https://user-images.githubusercontent.com/7331135/75413157-c9408480-58f2-11ea-9282-c2d3f8639915.jpeg)

**Comment by dabewi** [comment]
You're both right.

On the Tharsis board (which is the standard board) Arsia Mons is in the location that bafolts pointed out. On the Elysium board it is on the location that lostgrail pointed out.

Cheers!

**Comment by vincentneko** [comment]
Thanks @dabewi 
So I guess there is no issue here.

@lostgrail what browser / version are you using ? On chrome we have additional information on the map to point out specific locations:

![Screenshot 2020-02-27 09 00 21](https://user-images.githubusercontent.com/56086992/75423778-ad170480-593f-11ea-9c63-68aeddc4a45d.png)

**Comment by lostgrail** [comment]
Ah. I confused myself by playing in front of the Elysium board (sitting on my table) while playing ON the Tharsis board. No issue. 

I didn't see Tharsis Tholus highlighted.

95% of my games are on Safari on iOS (iPad flavoured)
