### ISSUE TITLE
Using Viron ability with no valid target breaks game

### ISSUE THREAD

**Issue by lostgrail** [bafolts/terraforming-mars#321]
To reproduce:
1) use a blue card (Aquifer pumping)
2) activate viron with insufficient MCred to use blue card(S)
3) sadly restart

![91DDC4C2-1A76-449C-A248-C9C3B8D0FB70](https://user-images.githubusercontent.com/7331135/75412957-2b4cba00-58f2-11ea-9545-089cbd1536e6.png)
![FE86BA35-F93E-4C9A-AB08-A9690B87A563](https://user-images.githubusercontent.com/7331135/75412997-415a7a80-58f2-11ea-80ca-6a93f154c090.png)
![F0DA0B0C-5BA3-466A-8CD4-D86E360B8AFD](https://user-images.githubusercontent.com/7331135/75413015-520af080-58f2-11ea-9f4a-e0efde7e2c94.png)

**Comment by vincentneko** [comment]
Thanks for the report.
Fixed and merged.
