### ISSUE TITLE
Eccentric Sponsor card discount triggers twice

### ISSUE THREAD

**Issue by K-Hartmann** [bafolts/terraforming-mars#322]
When playing the prelude card eccentric sponser, you can correctly play a Project card immediately, with a 25MC discount. But the first project card you play afterwards (at least if you play a project card as your very first action in the game) will be discounted additionally:

![2020-02-27_08h55_07](https://user-images.githubusercontent.com/41374984/75424533-1cd9bf00-5941-11ea-8afa-aeaee07f739d.png)

**Comment by vincentneko** [comment]
Thanks for the feedback.
My guess is that is a side effect of sorting cards...

In `player `class we have :

`const lastCardPlayed = this.playedCards[this.playedCards.length - 1];`

**Comment by vincentneko** [comment]
Fixed and merged
