### ISSUE TITLE
Accidentally delete a branch

### ISSUE THREAD

**Issue by vsrisuknimit** [bafolts/terraforming-mars#3223]
use-one-card

I think I accidentally deleted this branch.  I was deleting old local branch through GUI but I think I accidentally deleted this one. Not sure how to revert it.

**Comment by nwai90** [comment]
iirc this branch was about using one card for the various Mining cards (including Ares) and has already been merged several months ago. @bafolts will know better if that was the case

**Comment by bafolts** [comment]
Unless someone has a local copy of the branch we will not be able to revert the branch.
