### ISSUE TITLE
Title length does not consider translation

### ISSUE THREAD

**Issue by sauloachkar** [bafolts/terraforming-mars#3226]
When defining css for Card Text layout, the code is only considering the Card Title text length in original version.

Also, and "even smaller title" size should be considered to be added, maybe like this:

CardTitle.ts
```
      if (trimmedTitle.length > 29) {
        classes.push('title-even-smaller');
      } else if (trimmedTitle.length > 26) {
        classes.push('title-smaller');
      } else if (trimmedTitle.length > 23) {
        classes.push('title-small');
      }
```

cards.less
`.title-even-smaller { font-size: 13px !important; }
`

Here's and exemple of how it is now and how it would look like:
![size-14](https://user-images.githubusercontent.com/16825820/116608902-1ad70b80-a90a-11eb-97cd-4f9e0b3a5982.PNG)
![size-13](https://user-images.githubusercontent.com/16825820/116608921-21658300-a90a-11eb-894c-4ef2d58195b7.PNG)

**Comment by alrusdi** [comment]
Great idea! Actual width of the title not always depends on characters count, but most of the cases will be covered by this variant of css class assignment
