### ISSUE TITLE
Make corp name in PlayerInfo clickable.

### ISSUE THREAD

**Issue by kberg** [bafolts/terraforming-mars#3275]
![image](https://user-images.githubusercontent.com/413481/117654665-13163300-b164-11eb-8c38-af9bc14ff2d8.png)

**Comment by kevinb9n** [comment]
100% of new players I've introduced have wanted this.

**Comment by bafolts** [comment]
What happens when the corporation name is clicked?

**Comment by kberg** [comment]
Duplicate of #1664, which I reported in October.
