### ISSUE TITLE
[Bug] Mars map disappears

### ISSUE THREAD

**Issue by ap3h3ad** [bafolts/terraforming-mars#3286]
Hi,

in our current game (5 players) the map of the Mars just disappeared:

https://abload.de/img/marsbugl8kjp.png

As you can see by the scroll bar on the right - I can't scroll up where the map should be. The last actions were:

🕑apehead played Lake Marineris
🕑apehead placed ocean tile on row 3 position 5
🕑apehead placed ocean tile on row 3 position 6
🕑apehead played Trans-Neptune Probe

We play with Venus, Ares and Community expansion (and random Map).

We don't have any idea what happened, the map is just gone.

**Comment by kberg** [comment]
Which server? This was fixed at head a week ago or so

**Comment by ap3h3ad** [comment]
Hi,

the server is ~4 days old. I didn't find a regarding issue under "solved". So that may already be solved, thanks.
