### ISSUE TITLE
Robotic Workforce allows selection of non Building cards

### ISSUE THREAD

**Issue by nwai90** [bafolts/terraforming-mars#3297]
<img width="1185" alt="Screenshot 2021-05-19 at 10 11 32 AM" src="https://user-images.githubusercontent.com/2408094/118749854-e8795800-b890-11eb-981f-90d1a935aafd.png">

**Comment by kberg** [comment]
Fix is on its way in. Good catch! Gah.

**Comment by vsrisuknimit** [comment]
Closed by #3298
