### ISSUE TITLE
Jovian lanterns discrepancy with real card

### ISSUE THREAD

**Issue by chaqke** [bafolts/terraforming-mars#3306]
This card looks like it has a space tag in the physical version https://boardgamegeek.com/image/4419563/terraforming-mars-jovian-lanterns-promo-card , but does not have a space tag in the hosted version
<img width="312" alt="Screen Shot 2021-05-20 at 5 49 25 PM" src="https://user-images.githubusercontent.com/346075/119066515-cec13900-b994-11eb-8cd7-0418da2b9fe6.png">
Otherwise, this game is pretty great!  thanks for making it :-)

**Comment by vsrisuknimit** [comment]
@chaqke The card design might have changed during the course of the production. Here is a picture from the designer's website.

![image](https://user-images.githubusercontent.com/14239220/119072011-c7138b80-b9b8-11eb-8f6e-ea670da3d038.png)

https://www.fryxgames.se/hazeriders/

**Comment by kberg** [comment]
Sure does! Good catch.

**Comment by vsrisuknimit** [comment]
I just looked at the card in my box. It definitely does not have a space tag.
