### ISSUE TITLE
Problem with cost calculation of "Giant Space Mirror" with "Space Station" card in play

### ISSUE THREAD

**Issue by rogerta** [bafolts/terraforming-mars#3310]
I believe there is a problem with the cost calculation of "Giant Space Mirror" with the "Space Station" card in play.  See attached screenshot:

1. [Giant Space Mirror](https://terraforming-mars.herokuapp.com/cards?search=giant%20space%20mirror) costs 17MC.  It has a space tag.
2. [Space Station](https://terraforming-mars.herokuapp.com/cards?search=space%20station) is in play so its cost should be reduced by 2.  Space Station can't be see in the screenshot but you can see the current player (green) has -2 to space cards.
3. 2 Titanium resources are being used to pay for this card reducing the cost by a further 6MC.

So the total cost in MC for this card should be `17 - 2 - 6 = 9`MC.  However the screenshot shows `11`.

I proceeded to play anyway thinking that maybe the -2 would apply after buying the card, but I ended up with 3MC left (`14 - 11`) instead of 5MC (`14 - 9`).  Let me know if I'm misinterpreting the cost rules.

This game was running on a private server of which I am the admin (the game has ended).  Let me know if there is any info I can collect and attach to this issue to help debug.  Thanks!
```
deployed: Fri, 26 Mar 2021 22:14:30 -0400
version: 2f218f938
```
![Screenshot_20210521-223759](https://user-images.githubusercontent.com/2875588/119229363-ab59d380-bae5-11eb-8fea-54661f8d16f9.png)

**Comment by kberg** [comment]
I don't see this as a problem on the main repo.

![image](https://user-images.githubusercontent.com/413481/119231167-6a65bd00-baed-11eb-8665-fcfc097a81ad.png)

**Comment by rogerta** [comment]
It could be that my server is too old so I'll update it. I'm not exactly sure how you setup your game to test this, but your screen shot seems incorrect. It shows a cost of 7, but I think the cost should be 9. Yes/no?

**Comment by kberg** [comment]
Oh! Right, I had Phoblog. That's why it's seven.

**Comment by bafolts** [comment]
I also can't recreate.

![image](https://user-images.githubusercontent.com/2707843/120251317-69940000-c23e-11eb-83de-0633a8b92b01.png)
