### ISSUE TITLE
Plants received from Arctic Algae are not shown in the logs

### ISSUE THREAD

**Issue by rogerta** [bafolts/terraforming-mars#3311]
If an ocean is placed with [Arctic Algae](https://terraforming-mars.herokuapp.com/cards?search=arctic%20algae) in play, the logs don't show that the player has gained two plants:

![image](https://user-images.githubusercontent.com/2875588/119230064-a0ed0900-bae8-11eb-8307-5621fb6e8fee.png)

This is in contrast to [Pets](https://terraforming-mars.herokuapp.com/cards?search=Pets) that shows a player getting an animal resource when placing a city tile:

![image](https://user-images.githubusercontent.com/2875588/119230127-e14c8700-bae8-11eb-880b-5c0491ee846e.png)

It would be nice to show the the plant gain.

Version info:
```
deployed: Fri, 26 Mar 2021 22:14:30 -0400
version: 2f218f938
```

**Comment by kberg** [comment]
Thank you for the deployment date! This was fixed just the other day. Update and you should be good to go.
