### ISSUE TITLE
Suggesion: Improve Robotic Workforce Logging

### ISSUE THREAD

**Issue by dabewi** [bafolts/terraforming-mars#332]
Hi,

most of the times when Robotic Workforce is played it takes a time to comprehend which card was copied. I think it would be nice if the log would be improved, e.g.:

"XYZ played Robotic Workforce (copying Commercial District)"

This would allow to also improve the logging of other actions, e.g. whenever a card allows to add a pet or a microbe to another card the log only states which action was made but not to which card which resource was added, e.g.:

"XYZ used action Z (adding a microbe to card K)"

Cheers!

**Comment by vincentneko** [comment]
I've added a message to the log to list the copied card
