### ISSUE TITLE
Bug with Helion and "Local Heat Trapping"

### ISSUE THREAD

**Issue by PhantomFFR** [bafolts/terraforming-mars#3326]
I believe this should not work: If playing "Local Heat Trapping" as Helion when only having 5 heat remaining, and paying for the card (1 MC) with heat, it still works (and thus converts 4 instead of 5 heat to 4 plants). I would think that you'd need to be able to pay 1 MC/heat+5 heat to play Local Heat Trapping.

**Comment by bafolts** [comment]
Well this one is interesting. This will require us to know how a user is going to pay for the card. If they have 5 heat and at least one megacredit they can play this card. They must pay for it with their megacredit in this situation. We will have to enforce this when paying for the card. Any card which requires spending heat most likely has this bug.

**Comment by bafolts** [comment]
@kberg the moon made this popular with `reserveUnits` but I think we can accomplish this by putting a `reserveUnits` on the `LocalHeatTrapping` card. You must have 5 heat left to play this card. Then we can leverage the `reserveUnits` when calculating the available heat.
