### ISSUE TITLE
Some responses take 30 seconds to respond.

### ISSUE THREAD

**Issue by bafolts** [bafolts/terraforming-mars#3331]
Finally captured one of the 30 second timeouts seen a few times per day on the terraforming-mars.herokuapp.com.

```
2021-06-01T00:48:23.259421+00:00 heroku[router]: at=error code=H12 desc="Request timeout" method=POST path="/player/input?id=p9a90c59fc1f0" host=terraforming-mars.herokuapp.com request_id=6cdba4de-2e8a-4ac6-a931-647fe35a2753 fwd="204.14.36.17" dyno=web.1 connect=0ms service=30004ms status=503 bytes=0 protocol=https
```

Seems to be when a player was attempting to take some action. Will close this issue in 10 days once this data isn't available in the database. Will try to post more details. Once a player hits this issue they will see the error modal. After this they then usually try the action again. This leads to multiple 30 second responses in a row.

The CPU is not pegged and other requests make it through during this time. It is surprising that other requests make it through during this time. There are only a few places we have asynchronous operations. One of these asynchronous operations must time out. I am assuming this is some operation with the database timing out.

**Comment by kberg** [comment]
I still want to figure out a way to keep full game logs around for a couple
of days for just this reason.

>

**Comment by bafolts** [comment]
There are 135,210 rows in the `games` table. As interacting with the database is the only asynchronous operations I am assuming this is some query timing out when having to interact with the database. Looking at the node postgres client configuration it seems there are no defaults to timing out a query.

```
statement_timeout?: number, // number of milliseconds before a statement in query will time out, default is no timeout query_timeout?: number, // number of milliseconds before a query call will timeout, default is no timeout
connectionTimeoutMillis?: number, // number of milliseconds to wait for connection, default is no timeout
idle_in_transaction_session_timeout?: number // number of milliseconds before terminating any session with an open idle transaction, default is no timeout
```

Probably makes sense to add timeouts to these values. Heroku is going to time out the request at 30 seconds. Setting this to even 10 seconds would get these queries out of the way. If we are waiting more than even 10 seconds we need to optimize the queries or the tables.

**Comment by bafolts** [comment]
Seems we need to be using a `Pool`. This will handle reconnecting for us.

https://node-postgres.com/api/pool#poolquery

Will put up PR to change to use a pool.
