### ISSUE TITLE
minor rules error: EcoEx+Decomposers should get 3 microbes

### ISSUE THREAD

**Issue by kevinb9n** [bafolts/terraforming-mars#3344]
![image](https://user-images.githubusercontent.com/934551/120914301-3690a880-c652-11eb-8af2-7c465efc109c.png)

![image](https://user-images.githubusercontent.com/934551/120914320-52944a00-c652-11eb-98d7-35f03b896678.png)

Decomposers [should get ](https://boardgamegeek.com/thread/2096075/article/30501757#30501757) one microbe for its own microbe tag and one for the microbe tag on Eco Experts.

**Comment by vsrisuknimit** [comment]
@kevinb9n why 2? Should it not be 3? Decomposer + 2 more from Eco Experts.

**Comment by bafolts** [comment]
Decomposers has one microbe tag and EcologyExperts has one microbe tag so 2 adds up to me.

**Comment by kevinb9n** [comment]
D'oh, I've discussed this odd rule several times and said it wrong every time. Yes, indeed you should have a whole victory point worth of microbes already. Still a terrible play :-)
