### ISSUE TITLE
Unable to play Stratosferic Birds when Dirigibles is only card with resources and low on mega credits.

### ISSUE THREAD

**Issue by sauloachkar** [bafolts/terraforming-mars#3346]
![Screenshot_20210606-185539_Chrome](https://user-images.githubusercontent.com/16825820/121017392-9a5ec280-c773-11eb-8669-071c16dbfbb8.jpg)

I was playing rebalanced, with morning stars. Played indentured workers, so stratosferic birds were  costing $2 to play. I also had a floater on digibles. I had $2 cash. All of that, and birds did not showed to play.

**Comment by kberg** [comment]
Venus wasn't at 12%.

**Comment by sauloachkar** [comment]
Morning Star has +/-3 for Venus

**Comment by kberg** [comment]
Morning Star has +/-2. If you're using the rebalanced server, I suggest you submit an issue in that repo. If there is an upstream bug, we can address it here.

**Comment by sauloachkar** [comment]
Venus is 8%.
Birds are 12%

That's a 4%, or 2 steps gap, so it's not the case.

I reported on the rebalanced channel, and Jeep said is a main repo issue.

> Morning Star has +/-2. If you're using the rebalanced server, I suggest you submit an issue in that repo. If there is an upstream bug, we can address it here.

**Comment by nwai90** [comment]
Repro: https://terraforming-mars.herokuapp.com/player?id=p233836f610ba

MSI corp, Venus 8%, 1 floater on Dirigibles, Indentured Workers just played. Stratospheric Birds is not playable under these circumstances (though it should be)

**Comment by bafolts** [comment]
Can this be recreated on cards where the floater is not from the `Dirgibles` project card?

https://github.com/bafolts/terraforming-mars/blob/main/src/cards/venusNext/StratosphericBirds.ts#L53

There is logic requiring a player to have enough mega credits to pay with the floaters on the `Dirgibles` project card which seems incorrect.

**Comment by kberg** [comment]
By the way, thanks for reopening.

>

**Comment by nwai90** [comment]
> Can this be recreated on cards where the floater is not from the `Dirgibles` project card?
> 
> https://github.com/bafolts/terraforming-mars/blob/main/src/cards/venusNext/StratosphericBirds.ts#L53
> 
> There is logic requiring a player to have enough mega credits to pay with the floaters on the `Dirgibles` project card which seems incorrect.

@bafolts This custom logic arises because floaters on the `Dirgibles` project card can be used as 3 MC each, to pay for cards with Venus tags. `Dirigibles` is the only floater card in game that permits direct use of its floaters as payment for Venus cards.
