### ISSUE TITLE
Build now returns failure code when successful

### ISSUE THREAD

**Issue by kberg** [bafolts/terraforming-mars#3354]
```
$ npm run build

> terraforming-mars@1.0.0 webpack
> webpack --no-stats

$ echo $?
1
```

This breaks this type of command:

`npm run build && npm run test` which chains running the tests only after the build succeeds.

**Comment by kberg** [comment]
Fairly certain this is due to the new parameters for webpack:

```
$ npm run webpack

> terraforming-mars@1.0.0 webpack
> webpack --no-stats

$ echo $?
1
$ npm run lint

> terraforming-mars@1.0.0 lint
> eslint --cache src tests --ext ts

$ echo $?
0
```

**Comment by kberg** [comment]
Could be fixed with `npm install`

**Comment by kberg** [comment]
Yep! Fixed. h/t @nwai90.

**Comment by bafolts** [comment]
This is a good example of why rolling out the SFC change in smaller chunks is in our best interest. Glad we are over this transition with the build script.
