### ISSUE TITLE
Ecological Survey giving bonus for Ocean*

### ISSUE THREAD

**Issue by sauloachkar** [bafolts/terraforming-mars#3358]
Ecological Survey is still considering the space bonus for Ocean*.

Here's a print from Elysium, OceanFarm is placed on top of the ocean with 2 plants, and a bonus plant is gained from Ecological Survey.

Same should be happening for GeologicalSurvey.

![image](https://user-images.githubusercontent.com/16825820/121601014-bf755e80-ca1b-11eb-989c-0f943204f55e.png)

**Comment by kberg** [comment]
Thanks for the report. This is probably due to moving from code which more actively managed state to the task priority queue. But it's also probably not very difficult to fix.
