### ISSUE TITLE
Game is struck after playing some cards

### ISSUE THREAD

**Issue by vincentneko** [bafolts/terraforming-mars#34]
During solo play, I tried to play MOHOLE AREA or LAVA FLOWS, the game moved to "Not your turn to take any actions" state. There is no error message in the console.

**Comment by bafolts** [comment]
This bug was introduced when I did the refactor to consolidate the code for play card. It would have impacted a lot more cards than the two referenced. Should now be fixed. Any project card which had a subsequent action would have been ignored in a non prelude game.

**Comment by kberg** [comment]
That's funny.  This is because I was doing some work in the nwai90 fork. Please ignore.
