### ISSUE TITLE
Could not add floaters from 'Hydrogen to Venus' to Celestic

### ISSUE THREAD

**Issue by sfurlani** [bafolts/terraforming-mars#3414]
From my understanding the Celestic Corporation is both a `Venus` and a `Card` so Hydrogen to Venus _should_ have given me the option to add the 3 `Floaters` to it.

Most of the other cards/actions seemed to allow me to add Floaters to Celestic including:
* Trading with Titan
* Celestic Action
* Floater Technology 
* Jupiter Floating Station 
* Atmoscoop

## Code Snippits (From Chrome Inspector)

Celestic.js
```
var Celestic = (function (_super) {
    __extends(Celestic, _super);
    function Celestic() {
        var _this = _super.call(this, {
            name: CardName_1.CardName.CELESTIC,
            tags: [Tags_1.Tags.VENUS],
            startingMegaCredits: 42,
            resourceType: ResourceType_1.ResourceType.FLOATER,
            cardType: CardType_1.CardType.CORPORATION,
```

HydrogenToVenus.js
```
    HydrogenToVenus.prototype.play = function (player) {
        var jovianTags = player.getTagCount(Tags_1.Tags.JOVIAN);
        var floatersCards = player.getResourceCards(ResourceType_1.ResourceType.FLOATER).filter(function (card) {
            return HydrogenToVenus.venusCardsWithFloaters.has(card.name);
        });
        if (jovianTags > 0) {
            if (floatersCards.length === 1) {
                player.addResourceTo(floatersCards[0], { qty: jovianTags, log: true });
            }
            if (floatersCards.length > 1) {
                return new SelectCard_1.SelectCard('Select card to add ' + jovianTags + ' floater(s)', 'Add floater(s)', floatersCards, function (foundCards) {
                    player.addResourceTo(foundCards[0], { qty: jovianTags, log: true });
                    player.game.increaseVenusScaleLevel(player, 1);
                    return undefined;
                });
            }
        }
        player.game.increaseVenusScaleLevel(player, 1);
        return undefined;
    };
    HydrogenToVenus.venusCardsWithFloaters = new Set([
        CardName_1.CardName.AERIAL_MAPPERS,
        CardName_1.CardName.CELESTIC,
        CardName_1.CardName.DEUTERIUM_EXPORT,
        CardName_1.CardName.DIRIGIBLES,
        CardName_1.CardName.EXTRACTOR_BALLOONS,
        CardName_1.CardName.FLOATING_HABS,
        CardName_1.CardName.FORCED_PRECIPITATION,
        CardName_1.CardName.JET_STREAM_MICROSCRAPPERS,
        CardName_1.CardName.LOCAL_SHADING,
        CardName_1.CardName.STRATOPOLIS,
    ]);
```

Not sure if the card's name `celestic(⚖)` might be interfering with the `.has(card.name)`? in the original source:
 `CardName["CELESTIC"] = "Celestic";` vs. `CELESTIC_REBALANCED = "Celestic(⚖)"`

The `HydrogenToVenus.venusCardsWithFloaters.has(card.name)` probably needs to be replaced with a filter that searches by the Venus Tag?
```
var floatersCards = player.getResourceCards(ResourceType_1.ResourceType.FLOATER).filter(function (card) {
   return card.tags.filter((cardTag) => cardTag === Tags_1.Tags.VENUS).length
});
```

## From the Logs
```
Furlani used Celestic(⚖) action
Furlani added 1 floater(s) to Jovian Lanterns
Furlani added 1 floater(s) to Celestic(⚖)
Furlani played Hydrogen to Venus
Furlani added 3 floater(s) to Deuterium Export
```

## Screenshot Detailing Issue
![HtV_Celestic](https://user-images.githubusercontent.com/1991405/124537234-7f6d8580-dde7-11eb-83ec-a52e7e690acd.PNG)

## Logs
[game-log2021-07-05T23_11_09-0400.txt](https://github.com/bafolts/terraforming-mars/files/6767117/game-log2021-07-05T23_11_09-0400.txt)

## Related Issue
Possibly related to issue #2763 where Celestic wasn't considered an option for a Card with Floaters.

**Comment by kberg** [comment]
I must admit that reading the code I can't really make sense of the intent.

>

**Comment by vsrisuknimit** [comment]
@sfurlani this is a rebalanced-server-specific. You can report it to the rebalanced bug channel on discord. Anyway, it has been fixed. Feel free to close this issue.
