### ISSUE TITLE
[Ares] Nuclear Zone doesn't count towards Entrepeneur

### ISSUE THREAD

**Issue by ap3h3ad** [bafolts/terraforming-mars#3427]
Hi,

We're really enjoying the Ares expansion, but we stumbled over a strange regulation:

https://i.ibb.co/KXYgFHs/screenshot.png

As you can see the red player owns three tiles that have an adjacency bonus symbol on it. Two of them are counting towards the Entrepeneur award, the third (Nuclear Zone) is not. I'm assuming that this is the case because the NZ in fact doesn't give a bonus in terms of "+ somtehing" but rather a malus ("- something"). But Is this the intended behaviour? One can argue that a adjacency bonus is everything that is marked as adjacency bonus (with the little extra symbol), regardless if the card actually grants a positive or a negative bonus.

What do you think?

**Comment by kberg** [comment]
So I think this is WAI. The [rules](https://www.dropbox.com/s/3akc8e6lt3vqrdf/TM%20-%20Ares%20Expansion%20v1-0.pdf?dl=0) say:

> Adjacency bonus is indicated by a yellow hexagon on the tile and a yellow border around the resources or reward being granted .

Obviously on the web app there's no yellow border around the resources, so I hope we can ignore that part.

But the rules don't use the phrase "red-border" at all, even though Nuclear Zone and all the hazards have them, leaving you to  just understand that the red hexagonal border is **bad**. So I agree it's not 100% clear.

Still, thematically I think it is correct. What Entrepeneur deserves a reward for dropping a Nuclear Zone on Mars?

What I would like to do is clarify the rules accordingly, even writing a dedicated wiki page for Ares rules just like I transcribed The Moon rules.

Seem reasonable?

**Comment by ap3h3ad** [comment]
Yes, the  missing yellow border makes absolutely sense, thank you!

And also yes, I'd like to see this clearified in a new version of the rules. :)

**Comment by kberg** [comment]
https://github.com/bafolts/terraforming-mars/wiki/Ares-Rules
