### ISSUE TITLE
Board that has special function space work fail

### ISSUE THREAD

**Issue by Solo899815** [bafolts/terraforming-mars#3444]
-$3 to increase temp. in board "Vastitas Borealis"
-$6 to place a water in board "Hellas"

When placing tile to above space, error happen and it will require to place a copy tile again at last

Ref: 
gameid: g9e9814b0b87
gameid: gd004e6258ad6
Server: https://tfm-community.herokuapp.com

P. S. : I don't know has anyone reported before.

**Comment by nwai90** [comment]
Hi @Solo899815 Thanks for the report. This bug happens on all servers for Hellas at the moment, we will look into it

**Comment by vsrisuknimit** [comment]
Fixed by #3445.
