### ISSUE TITLE
Server disconnected and is not able to restart

### ISSUE THREAD

**Issue by dabewi** [bafolts/terraforming-mars#345]
Hi,

today, suddenly, my game server crashed. After updating the project via git pull and trying to restart it, the following error occured:

https://abload.de/img/screenshotlojfd.png

Maybe someone can tell me what the problem here is. I'm working on Ubuntu 18.

Cheers!

**Comment by bafolts** [comment]
You need to run `npm install` to install a new dependency.

**Comment by dabewi** [comment]
Hi,

thanks, but there was something else going wrong with the server.

cheers
