### ISSUE TITLE
`${10}` is shown when starting a game with beginner corporation

### ISSUE THREAD

**Issue by AndrewSav** [bafolts/terraforming-mars#3455]
When starting a game with beginner corporation, I see this:
![2021-07-17_12-06-21](https://user-images.githubusercontent.com/658865/126019107-7f39f5d6-bd01-4f17-a3a4-2e10f4ca5cfb.png)

note `${10}`, which looks like a bug to me.

**Comment by bafolts** [comment]
Which server was this played on? Do you happen to know which card was the card missing from the log?

**Comment by nwai90** [comment]
This should have been fixed by https://github.com/bafolts/terraforming-mars/commit/5ee685e6b76efade2462b8567b1b3154c03a3be4. Was the game played on a private server?

**Comment by AndrewSav** [comment]
Yes, I've been meaning to report it many weeks, but did not get around to do this before. I pulled latest master on 12th of July and still could reproduce it, so I reported it. Good timing, it has been fixed in the last 5 days! ;) Apologies for not checking for 6th, or 7th time before reporting ;) Thank you for fixing this.
