### ISSUE TITLE
Global effects do only affect the player that caused them

### ISSUE THREAD

**Issue by dabewi** [bafolts/terraforming-mars#347]
Hi,

we noticed a bug in the new version: Effects that grant benefits to all players if someone makes a specific action (e.g. Arctic Algae that grant plants every time someone places an ocean tile or Pets that grant tokens if someone places a city tile) only work if the player itself makes the action.

For example: I've played pets and I got one pet-token for my own Noctis city but none for the city tiles my opponent played after that. The same issue occured to an opponent of mine with his Arctic Algae.

Screenshot: https://abload.de/img/petstakyr.png

I'm playing blue and my city was the third one that was played. You can see that there are only 2 resources on my Pets (the one the card starts with and the one for my own city), but it should have 4 resources for the two yellow cities that were played afterwards).

Greetings.

**Comment by vincentneko** [comment]
This one is a regression related to a bugfix with Mining Guild, sorry.
An incoming PR should fix this and the bug with Mining Guild.

**Comment by vincentneko** [comment]
Fixed and merged. As always thanks for feedback.
