### ISSUE TITLE
Law Suit vs. Mons Insurance

### ISSUE THREAD

**Issue by kevinb9n** [bafolts/terraforming-mars#3482]
It's possible the app already does the right thing, but I'd be slightly surprised.

We were ~all recently surprised to learn that Mons Insurance's immediate effect doesn't decrease other players' production; it (uniquely) has *them* reduce it themselves, and therefore it doesn't power up Law Suit.
https://boardgamegeek.com/thread/2695672/law-suit-vs-mons-insurance-gen-1

(This is good from a theme perspective, it just wasn't clear how intentional the card-rules wording was.)

**Comment by SliceOfBread** [comment]
I believe the code as written is correct (perhaps by happenstance). 
Short version of what I see in the code: When a player reduces someone's production, there is an option in the code to include who is doing the reduction. If included, this allows Law Suit to be used. 
It is NOT included in Mons reduction of other's MC production ergo, Law Suit cannot be used against Mons in this instance.
Someone will surely correct me if I missed something.

**Comment by SliceOfBread** [comment]
I think this should be closed.
