### ISSUE TITLE
Removing a player does not remove a player

### ISSUE THREAD

**Issue by lostgrail** [bafolts/terraforming-mars#350]
To reproduce:
1. Create a new three player game, 
2. Putting all names in their fields
2. Click on "two players"
4. Start the game
Player 3 still exists in the game, and you cannot start the game without them.

**Comment by bafolts** [comment]
This will be fixed by https://github.com/bafolts/terraforming-mars/pull/353

**Comment by alrusdi** [comment]
Fixed and merged
