### ISSUE TITLE
No such table: games

### ISSUE THREAD

**Issue by ap3h3ad** [bafolts/terraforming-mars#3500]
Hi,

I cloned the project and started it, but I get this error:

https://abload.de/img/bug22kdq.png

Has anyone a clue what the problem could be?

**Comment by ap3h3ad** [comment]
I don't know, it  just disappeared

**Comment by kberg** [comment]
Verified this happens.

**Comment by kberg** [comment]
This is probably due to #3475

**Comment by kberg** [comment]
@bafolts @AndrewSav can you please take a look?

**Comment by bafolts** [comment]
@kberg how did you recreate this error?

**Comment by bafolts** [comment]
We call to create the database in the constructor of most `IDatabase` implementations but we don't necessarily wait until the operation has finished. This is prone to error.

**Comment by kberg** [comment]
I cloned the repo from source, ran npm install ; npm run build ; npm run
start

>

**Comment by bafolts** [comment]
I am pretty sure this was caused by https://github.com/bafolts/terraforming-mars/pull/3470. We call to `Database.getInstance().purgeUnfinishedGames()` now when we weren't before. This has exposed the issue with our `SQLite` database not necessarily being created before that function runs.

**Comment by AndrewSav** [comment]
@bafolts I wonder if we could re-open it? It still will happen in SQLite with `MAX_GAME_DAYS` set. (and before https://github.com/bafolts/terraforming-mars/pull/3502 a different (syntax error) would happen instead)

**Comment by kberg** [comment]
Sure thing.

**Comment by bafolts** [comment]
Re-opening is fine. Probably duplicates or would be addressed by #3507

**Comment by AndrewSav** [comment]
Oh yeah, I did nor realised you opened #3507.

**Comment by bafolts** [comment]
I plan to put in a fix for this.
