### ISSUE TITLE
Cannot use Celestic action on first turn

### ISSUE THREAD

**Issue by lostgrail** [bafolts/terraforming-mars#351]
Celestic does not show up as an action that can be activated on the first turn

![409AEEB0-6569-4D87-91E7-7E65E0140E99](https://user-images.githubusercontent.com/7331135/75941128-dc0c0980-5e5c-11ea-9926-7e7fefa01de0.jpeg)
![C8F9D7B1-542F-4006-B4A5-5FA8E386BC71](https://user-images.githubusercontent.com/7331135/75941133-e0382700-5e5c-11ea-8ede-2706d537dbc3.jpeg)
![445F6F44-227D-48FF-8E35-648D2FC04644](https://user-images.githubusercontent.com/7331135/75941137-e1695400-5e5c-11ea-9462-b6fec56f464f.jpeg)

**Comment by vincentneko** [comment]
Fixed and merged
