### ISSUE TITLE
Card Icons display weirdly on Pluto

### ISSUE THREAD

**Issue by lostgrail** [bafolts/terraforming-mars#352]
When sitting on surface of Pluto, card icons display weirdly.

Just joking. Half of the card icons on the Pluto colony are overlapping the colony track numbers

![532465FC-6059-4347-AD31-22D6D071F50C](https://user-images.githubusercontent.com/7331135/75941333-5fc5f600-5e5d-11ea-86a4-d444f711aac0.jpeg)

**Comment by alrusdi** [comment]
Changes to fix it are merged. Thank you for the report!
