### ISSUE TITLE
Timer isn't working properly

### ISSUE THREAD

**Issue by ap3h3ad** [bafolts/terraforming-mars#3547]
Hi,

I updated the project toady and started a new game and now the timer seems to be broken. First it shows "00:00" for everyone, now it shows the same time for everyone. It doesn't run, it seems to just set the time.

https://abload.de/img/bug0zjet.png

Cheers!

**Comment by bafolts** [comment]
This is working as of commit a589a6969e692b00c085dbb4bd1873f4e48253c0. Some commit after this introduced this bug.

**Comment by bafolts** [comment]
@kberg I believe the issue is here.

https://github.com/bafolts/terraforming-mars/blob/main/src/components/overview/PlayersOverview.vue#L123

The `player` is provided for every player.

**Comment by kberg** [comment]
> @kberg I believe the issue is here.
> 
> https://github.com/bafolts/terraforming-mars/blob/main/src/components/overview/PlayersOverview.vue#L123
> 
> The `player` is provided for every player.

You sure? It is, but that's the view of the whole game. It's used for collecting data like "this.playerView.players" etc, but not because it's the player being acted upon.

**Comment by bafolts** [comment]
I am sure. We end up passing that `playerView` through to the timer. The timer appears to work in single player games but in multi-player games only the timer from `playerView` is used.

**Comment by kberg** [comment]
Yeah I see now in your PR. Thanks.

>
