### ISSUE TITLE
Solo game broken if you win before last turn with Venus Next

### ISSUE THREAD

**Issue by lostgrail** [bafolts/terraforming-mars#355]
When all global parameters have been completed before the final generation, the game asks you to choose an action for WG Terraforming, but there are no options. As a result, the game breaks and cannot proceed. 

![0517EFC3-E24C-454E-8394-70637BB7D4D4](https://user-images.githubusercontent.com/7331135/76045116-3aeb8480-5f2a-11ea-9d05-cc1afe6d669d.png)

This game was Venus, Preludes, and colonies, so game would end on generation 12.

**Comment by vincentneko** [comment]
As always, thanks for feedback.
Fixed and merged
