### ISSUE TITLE
Unable to play card in Prelude phase after Ecology Experts is played

### ISSUE THREAD

**Issue by nwai90** [bafolts/terraforming-mars#3557]
Example link: http://terraforming-mars.herokuapp.com/player?id=p6a1ba06fdc7

Clicking on "Play card" throws a console error. Could be related to the change in https://github.com/bafolts/terraforming-mars/pull/3550

<img width="738" alt="Screenshot 2021-09-01 at 7 39 12 PM" src="https://user-images.githubusercontent.com/2408094/131665171-71e22704-8666-4b36-9418-0da21dfc6067.png">

**Comment by BeriAlpha** [comment]
I have this bug, too, attempting to play Venusian Animals after Ecology Experts. https://terraforming-mars.herokuapp.com/player?id=pc123d0862a16

**Comment by kberg** [comment]
@vsrisuknimit you merge pulls and close bugs in this repository without communicating. Please either start communicating or stop touching this repository.

**Comment by vsrisuknimit** [comment]
@kberg It fixed a critical gameplay bug. This issue can be closed.

**Comment by vsrisuknimit** [comment]
You approve and merge in one go all the times. Sometimes without checking resulting in bugs. I did check this one to make sure that it fixed the bug and merge in case no one have time to merge before bafolt updates in the morning.

**Comment by kberg** [comment]
Gotcha. I'll review this a bit later. In the meantime I DMed you on discord.

**Comment by nwai90** [comment]
Fixed by @Argeento
