### ISSUE TITLE
Display resource on cards in select card input

### ISSUE THREAD

**Issue by vincentneko** [bafolts/terraforming-mars#357]
Resources on cards are displayed on cards in cards in hand and played cards but not on cards when listed in a "select card" option.

This one might be tricky as the resources information is stored in an array inside player card, not on the card itself...

**Comment by vincentneko** [comment]
Maybe it could be easier / better to store resource amount on the cards themselves ?

**Comment by alrusdi** [comment]
I like this idea

**Comment by vincentneko** [comment]
Merged
