### ISSUE TITLE
unable to play Lunar Beam

### ISSUE THREAD

**Issue by K-Hartmann** [bafolts/terraforming-mars#358]
As seen in the screenshot, i am unable to play lunar beam in solo play, although i have the mc to do so. Can't really figure out any pontential issue here besides my unusualy low mc income?

![2020-03-06_11h35_41](https://user-images.githubusercontent.com/41374984/76076160-935c6980-5f9e-11ea-977f-f13a4427b4ec.png)

**Comment by alrusdi** [comment]
2. MegaCredits (M€) : Are used to pay for cards and other
things. Note: Your M€ income is the sum of your M€ produc-
tion and your TR. M€ production is the only production that
can be negative, **but it may never be lowered below -5**
