### ISSUE TITLE
Rebalanced difference list

### ISSUE THREAD

**Issue by ChrisTheCat** [bafolts/terraforming-mars#3581]
Not sure if this is the right place to ask, as the document is outside the project... it would be nice if this page listed the differences from the original cards, for those of us who haven't memorized them.

https://jeeps.notion.site/Rebalanced-Mars-Change-Summary-560485dd3fc24e4b84ce32b591850843

For example, I know something changed on Astrodrill, because I can see the new card and what it does. However, I have to go back and find the original Astrodrill card to figure out what changed. I then had to very carefully read both cards to be sure that the only change was the starting money. It would be great if the jeeps.notion.site page had a brief description like: +5MC

**Comment by kberg** [comment]
This isn't the right place -- there's a channel on discord for reporting Rebalanced bugs, but if there's a github repo for rebalanced issues, I don't know where it is.

**Comment by ChrisTheCat** [comment]
Where, exactly, is this channel on discord of which you speak? On the main Terraforming Mars Web App server, I only see #lfg-rebalanced and #bug-reports

**Comment by kberg** [comment]
I don't have access to it, so I can't say.

>
