### ISSUE TITLE
Plant bonus looks weird in google chrome

### ISSUE THREAD

**Issue by alrusdi** [bafolts/terraforming-mars#36]
https://alrusdi.ru/static/tm_bug_greenery_in_chrome.png
It's on Ubuntu. I'm not sure about Windows.

**Comment by vincentneko** [comment]
Same here (Fedora). I use windows as well, where the bonus is much better rendered.
I guess it's unicode &#x1f343; representation that differ from one OS to another.

**Comment by alrusdi** [comment]
May be it's better to use image icons then? I can prepare image atlas and css styles for it.

**Comment by bafolts** [comment]
Image icons would work fine. I put the CSS for the board together one night and it needs a lot of love. Since the cards now look so great the board looks bad by comparison.

**Comment by alrusdi** [comment]
I can make completely new board like this if you like it:
https://alrusdi.ru/static/board_new_look.png
It's obvious idea to do it in css+images but if you don't mind svg format it can be really great in terms of control. Nowadays this format has a good support in all kind of browsers (include mobile).

**Comment by vincentneko** [comment]
This is looking great !
I've created a new branch for this. I was thinking we could also use another font for the board text because right now I think it's difficult to locate the designated hex sometimes.

**Comment by bafolts** [comment]
Any and all improvements to the board are welcome!

**Comment by alrusdi** [comment]
I am closing this issue then. For complete board rework i will make new task with better explanation of what to do
