### ISSUE TITLE
More love to larger screens

### ISSUE THREAD

**Issue by alrusdi** [bafolts/terraforming-mars#361]
We should keep priority on mobile devices, but some love for large screen devices is also should be an option. For large screens we need use more horizontal space, use smaller font e t. c.

_Map to have as little height as possible (venus to be on the side) and Player Board to be as close as possible to the Action menus (to be under the map and to avoid a lot of vertical scrolling) ._

**Comment by vincentneko** [comment]
Idea of layout from Simon:

![boards](https://user-images.githubusercontent.com/56086992/76140034-acc0ec80-6056-11ea-9478-4c9f56406869.png)

**Comment by ssimeonoff** [comment]
A new idea: 
- the global parameters to blend in 
- reduce the colours' saturation (#03fdfcff reduced to #03fdfc88)
- values to be within the level (as in the real game)
- current value to be highlighted in white (as in the real game white cube)
- oceans count-down (when zero, show a checkmark icon)
![1](https://user-images.githubusercontent.com/6917565/77161832-e825d700-6aaa-11ea-8f2a-3ada65fdafd4.png)

**Comment by vincentneko** [comment]
Is this issue still relevant ?

**Comment by alrusdi** [comment]
Nope, let's close it
