### ISSUE TITLE
npm run dev:server starts cwd one directory up

### ISSUE THREAD

**Issue by kberg** [bafolts/terraforming-mars#3617]
This means that files are not where they are expected to be, when running with the local filesystem database or sqlite.

eg the output of a recent run said `Starting local database at C:\Users\me\git\db\files` when it should have said `Starting local database at C:\Users\me\git\terraforming-mars\db\files`

**Comment by kberg** [comment]
I believe the problem is as follows:

```
    "start": "node build/src/server.js",
    "dev:server": "npm run make:static && cross-env NODE_ENV=development tsnd src/server.ts"
```

When creating a sqlite instance, it uses this to find the path:

`
const dbFolder = path.resolve(__dirname, '../../../db');
const dbPath = path.resolve(__dirname, '../../../db/game.db');
`

When using `start` the runtime Javascript is at `build/src/server.js`, which has two directories in its path specification. When using `dev:server` the runtime source is at `src/server.ts`, which has only one.

**Comment by kberg** [comment]
To recreate this,

1. `npm run build && npm run start`
2. Create a solo game, and start playing it a bit.
3. Kill the server and restart it with `npm run dev:server`
4. Refresh the broswer tab.
5. Receive an error that the player is not found.

**Comment by Argeento** [comment]
Use `process.cwd()` instead of `__dirname`

**Comment by Argeento** [comment]
> Use process.cwd() instead of __dirname 

But.. it may be dangerous if someone starts the server from the other dir - not using npm to do that

**Comment by kberg** [comment]
> > Use process.cwd() instead of __dirname
> 
> But.. it may be dangerous if someone starts the server from the other dir - not using npm to do that

That's OK.
