### ISSUE TITLE
CLOUD SEEDING is bugged

### ISSUE THREAD

**Issue by vincentneko** [bafolts/terraforming-mars#362]
In a 2 player game, try to play it and got a circular error something, it crashed our game.

**Comment by vincentneko** [comment]
Not sure if it is the card by itself. Just tested it in another 2 players game, it was ok.

**Comment by K-Hartmann** [comment]
In our three player game we had the same behavior, playing cloud seedings crashed the server. Unfortionately no screenshots from before, we were playing on elysium with colonies and prelude

**Comment by bafolts** [comment]
This will be thrown from a call to `JSON.stringify`. There is a circular reference being created somewhere. I would be surprised if this was due to cloud seeding. I would guess a card is storing a reference to a player or something similar which could then create the circular reference. We only have a few places we call `JSON.stringify`. I can look into this.

**Comment by bafolts** [comment]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Cyclic_object_value

**Comment by bafolts** [comment]
@vincentneko and @K-Hartmann which board and game options were used when this error was observed?

**Comment by bafolts** [comment]
We append the colony data without limiting the data we need before calling `JSON.stringify`. I am guessing this was observed when colonies was being used.

**Comment by vincentneko** [comment]
> We append the colony data without limiting the data we need before calling `JSON.stringify`. I am guessing this was observed when colonies was being used.

Yes we were playing with colonies.

**Comment by bafolts** [comment]
I haven't spotted where the circular data is introduced but I would put good money it is somewhere in `game.colonies`. We should create a function to serialize only the data we need on the client from `game.colonies` when we append it to, similar to the `getPlayers` function we should create a `getColonies`.

https://github.com/bafolts/terraforming-mars/blob/master/server.ts#L335

**Comment by vincentneko** [comment]
> I haven't spotted where the circular data is introduced but I would put good money it is somewhere in `game.colonies`. We should create a function to serialize only the data we need on the client from `game.colonies` when we append it to, similar to the `getPlayers` function we should create a `getColonies`.
> 
> https://github.com/bafolts/terraforming-mars/blob/master/server.ts#L335

Not sure if it is related but the colony component has a colony prop which contains an array named colonies which hold players objects. So if a colony have 2 colonies from different players the array contains the full player object, by inspecting the data, player 1 is able to see what's in player 2 hand.
I remember when our game crashed, both my friend and I got a colony on Triton. This may be related...
The only required data in colonies array from client side is an array of colors in order to draw the cubes.

**Comment by bafolts** [comment]
I will have a pull request soon up to fix this. I am not familiar with how colonies gameplay works so if someone could do a quick sanity check that would be good.

**Comment by vincentneko** [comment]
> I will have a pull request soon up to fix this. I am not familiar with how colonies gameplay works so if someone could do a quick sanity check that would be good.

I'm in !

**Comment by bafolts** [comment]
I played a quick game with colonies and saw there was a standard project where the player would get their cube on the colony. Seemed to work fine in a two player game now.
