### ISSUE TITLE
Animate resources changes

### ISSUE THREAD

**Issue by vincentneko** [bafolts/terraforming-mars#366]
We could use [Odometer]( https://github.hubspot.com/odometer/api/themes/) to animate resource and resource production changes.

**Comment by gomfunkel** [comment]
I don't understand why the resources need animation. Can you give an example? When taking actions that modify resources I don't usually see the corresponding resources on the screen so animating changes makes little sense to me.

**Comment by vincentneko** [comment]
The idea was to mimic what @ssimeonoff has done [here ](https://ssimeonoff.github.io/cards-list)
When you filter the cards, the counters values are animated.

**Comment by vincentneko** [comment]
I'm closing this one as there is no way at the moment to keep track of the changes in the numbers.
(previous value vs current value)
