### ISSUE TITLE
Suggestion: Count all tags

### ISSUE THREAD

**Issue by dabewi** [bafolts/terraforming-mars#372]
Hi,

I think it would be neat to have a small frame that shows the amount of tags of one specific type if you hover over one of those tags:

E.g.: https://abload.de/img/tagcounts6nk57.png

I hover over one plant tag and a small frame shows up and tells me that I have three plant tags (I have one additional tag because I play Ecoline in that screenshot). This is relevant for specific card requirements (have at least x science symbols) and of course milestones like the builder.

Cheers!

**Comment by vincentneko** [comment]
Tag count is something I would like to add.
What I foresee is another horizontal bar located below resources bar with Tag icon : Tag count for all the tags.

Your suggestion seems more difficult to implement and will not work well on phones.

**Comment by vincentneko** [comment]
A little preview:

![Screenshot 2020-03-13 19 17 33](https://user-images.githubusercontent.com/56086992/76648960-039b5a00-6560-11ea-9e9b-595039b9c8bc.png)

**Comment by vincentneko** [comment]
Implemented
