### ISSUE TITLE
Bug: Cards in draft are picked alphabetically

### ISSUE THREAD

**Issue by dabewi** [bafolts/terraforming-mars#374]
Hi,

the draft seem to be alphabetically.

In every new game the draft looks like this:

https://abload.de/img/unnamed5okmn.png

If you watch the draft phases for a couple of generations you will notice the alphabetic order (so in Gen 4 we reached the "c" as in "Commercial District" and "Convoy from Europe"). Obviousley this has a massive impact on the gameplay.

Cheers.

**Comment by vincentneko** [comment]
Hi,

I've updated the game recently about this, can you please check you run the last version ?

**Comment by gomfunkel** [comment]
Could not reproduce this in the latest version.

**Comment by vincentneko** [comment]
Thanks, will close this one
