### ISSUE TITLE
Suggestion: Show resources on resource cards during choose screen

### ISSUE THREAD

**Issue by dabewi** [bafolts/terraforming-mars#375]
Hi,

if I, e.g. with the carnivores or the ants, steal a pet from another card, I'd like to see how many resources are on the cards that I can choose from. Now I have to look at the cards before I choose the action to steal tokens from another card, because I cannot see the actual resources on the cards in the "choose screen".

Cheers

**Comment by vincentneko** [comment]
This issue is already created here : 
Display resource on cards in select card input #357
