### ISSUE TITLE
Suggestion: Replace generic tiles with more specific ones

### ISSUE THREAD

**Issue by dabewi** [bafolts/terraforming-mars#376]
Hi,

if one of my opponents plays e.g. a commercial district or a capital I want to know where he played it, even after some generations. Sometimes the mars gets rather packed and with more city tiles it gets more tedious to track down which city tile represents a standard city and which one represents the capital (because I don't want to place an ocean tile near an opponents capital or a city near an opponents commercial district).

Therefore it would be nice to actually have specific symbols for the special tiles, or at least for some of them.

Cheers!

**Comment by alrusdi** [comment]
This is done

**Comment by rodrigomp84** [comment]
> This is done

Actually it seems the capital tile is still just a regular city tile. I agree with the OP that being able do tell them apart is quite important!
