### ISSUE TITLE
Decomposers do not work with multi tag cards

### ISSUE THREAD

**Issue by K-Hartmann** [bafolts/terraforming-mars#377]
As seen in the screenshot, my Decomposers have two recources, one from the Decomposer microbe tag, but only one from Ecological Zone. I observed the same behavior later in the game when I played advanced ecosystems and got only one microbe instead of three.

![2020-03-12_10h23_59](https://user-images.githubusercontent.com/41374984/76506527-97c7cd00-644b-11ea-92f3-987dfcc748d8.png)

**Comment by gomfunkel** [comment]
Experienced the same with Advanced Ecosystems when getting only 1 resource instead of 3.

**Comment by vincentneko** [comment]
Fixed and merged, thanks for the great feedback, as usual.
