### ISSUE TITLE
Moving Temp to 20° in Solar phase gives production bonus

### ISSUE THREAD

**Issue by K-Hartmann** [bafolts/terraforming-mars#383]
As seen in the screenshot, by rising the temp to 20° as world government, the player k4rlchen hast still recieved the Production Bonus.

![2020-03-13_23h33_56](https://user-images.githubusercontent.com/41374984/76664091-736f0c00-6583-11ea-9646-91da38682a67.png)

**Comment by vincentneko** [comment]
Fixed and merged
