### ISSUE TITLE
Suggestion: Make Solar phase optional

### ISSUE THREAD

**Issue by K-Hartmann** [bafolts/terraforming-mars#384]
As stated in the official rules, the Solar Phase can be skiped for a longer game. Personally i highly dislike the solar phase and allways play without it, so an option to disable it at game creation would be highly appreciated.

**Comment by FreeLikeGNU** [comment]
If this becomes an option, I'd like to be able to enable Solar on a 2 player game without the Venus/Colonies expansion to move our games along.   Perhaps have the computer randomly chose which terraforming goal is advanced each turn?
