### ISSUE TITLE
Wild tag from Prelude card counts as Venus tag in end game scoring

### ISSUE THREAD

**Issue by gomfunkel** [bafolts/terraforming-mars#386]
One player played a prelude card with a wild tag (Research Network iirc). The tag counted toward the Venuphile award in the end game scoring. The tag should not count as a Venus tag (or any other) in the end game scoring.

**Comment by vincentneko** [comment]
Thanks for the feedback, a PR has been submitted.
Fixed other awards as well (contractor, space baron, scientist)

**Comment by vincentneko** [comment]
Fixed and merged
