### ISSUE TITLE
Vitor ability triggers for all players

### ISSUE THREAD

**Issue by K-Hartmann** [bafolts/terraforming-mars#389]
Edit: After testing, I can confirm that in games with Vitor, all players have the Vitor ability with 3mc for cards with vp!

Not sure about the specific trigger, but the scenario is as follows:
Point Luna 38mc, bought 5 cards, 23mc remaining.
Prelude cards Aquired Space Agency and Mining operations.
Power plant standard Project, 12mc remaining, I specifically noticed that number was correct until that point in game.
I played Electro Catapult with 3 Steel for 11mc, but had 4mc left afterwards (See first screenshot)

Afterwards I used the catapult action and went to 11mc, then played aquired space agency with 3titanium and 1mc but my mc total actually went up to 13mc (See second screen)

![13DA560B-1152-4687-828A-0FF54C796DC7](https://user-images.githubusercontent.com/41374984/76680679-d47dfa80-65ea-11ea-84a2-0016f9bb9545.jpeg)

![C57D69F2-C427-40A8-A925-BCB9DA73AD9B](https://user-images.githubusercontent.com/41374984/76680731-64bc3f80-65eb-11ea-9037-202e0a8438d1.jpeg)

**Comment by K-Hartmann** [comment]
My Opponents play Tharsis and Vitor. Since both cards have 1vp, and I did not have the issue with an event (without vp) I played afterwards, maybe the issue is with Vitor?

**Comment by gomfunkel** [comment]
Bug in Vitor seems very likely.

Line 959 of Player.ts calls onCardPlayed of the corporation with the current player. onCardPlayed of Vitor does not check if the current player is actually playing Vitor, though.

Apparently everyone is getting 3 MC for positive VPs on cards as long as Vitor is in play.

**Comment by gomfunkel** [comment]
@vincentnek: I will fix this in a couple of hours and create a pull request.

**Comment by vincentneko** [comment]
> @vincentneko I will fix this in a couple of hours and create a pull request.

Ok great !

**Comment by gomfunkel** [comment]
@vincentneko Looks like my guess was right. PR is now available: #390
