### ISSUE TITLE
Any plan to i18n?

### ISSUE THREAD

**Issue by rzulian** [bafolts/terraforming-mars#391]
Hey,
Do you have any plan to i18n the game?

**Comment by vincentneko** [comment]
@alrusdi and I would love to add it, but right now it seems quite complicated. There is text everywhere in the application, this should need a lot of rework before thinking about it. I guess it could be something we can look into but not quite right now.

**Comment by alrusdi** [comment]
Worst part is a cards texts. A lot of cards, and naive translation can break cards markup. So we need a good idea of how to manage it.

**Comment by dabewi** [comment]
Well, for languages the game is actually officially translated (such as german) that shouldn't be a problem. The game cards have the same size so the texts on the cards should fit.

**Comment by alrusdi** [comment]
Unfortunately texts in different languages has varying length. Russian for example is more verbose and it has longer words than English

**Comment by bafolts** [comment]
For the longer descriptions on cards we should utlize `overflow-y: auto`. If a more verbose language then grows outside of the area scroll bars will be introduced. The scrollbars may not look great but a user will still be able to read the card. Usually the longer description is not that important to the game.

**Comment by alrusdi** [comment]
Or we can give each card its personal css class and add language class for game container. Then we will be able to fine tune appearance or each description box.
Still a lot of problems where to store texts and how to apply translations. Cards probably needs to be Vue templates - not just raw HTML - it can be huge work to convert them all

**Comment by bafolts** [comment]
I can probably write a script to at least get all the cards into their own template files even if they still had the HTML they had today.

**Comment by alrusdi** [comment]
This can be a good start. Then we can apply translation to small subset of the card to see how it is working. If the cards will be valid and updatable vue components it will also resolve our syncronization problems (like show resources count on each instance of the card)

**Comment by rzulian** [comment]
Probably to have cards as a Vue component is the right way. Even though it wan't solve the problem of the long translation in the different languages that can screw up the layout. I can try a couple of cards with long sentences and post the results.

**Comment by FreeLikeGNU** [comment]
What about providing the full translated text as a kind of tooltip with (possibly) truncated text on the card itself?  This could allow lots more room for translations or more detailed information, flavor text, etc...

**Comment by rzulian** [comment]
I think it would be better and smarter to have parametric descriptions on cards, and manage only the exceptions.
It would require to move card requirements to cards ` array< CardRequirementType, value >`.
So you can also have a standard canPlay code, and you will have parametrized requirement tags and description on the cards

**Comment by vincentneko** [comment]
Can we close this one ?

**Comment by alrusdi** [comment]
Yes, we have separate task for translating the cards
