### ISSUE TITLE
UI Problems after #397

### ISSUE THREAD

**Issue by gomfunkel** [bafolts/terraforming-mars#399]
A couple of UI issues I have noticed after #397 was merged: 

- Choosing black as the player color makes it very hard to read the headline/playername.
- The amount of resources you receive from a card is very hard to read (see 3 plants in the screenshot below.

<img width="293" alt="ecoline" src="https://user-images.githubusercontent.com/547035/76759321-bc91ac80-678b-11ea-9e7c-00c19407f93c.png">

- Text on the player overlay on the player home screen is very hard to read. Background probably needs to be darker.

<img width="863" alt="player_overlay" src="https://user-images.githubusercontent.com/547035/76760615-3fb40200-678e-11ea-8cc3-c5b6a565b161.png">

I will add to this as soon as I find more.

**Comment by FreeLikeGNU** [comment]
Please see https://github.com/bafolts/terraforming-mars/pull/404

**Comment by alrusdi** [comment]
this should be fixed now
