### ISSUE TITLE
Visualize used actions from blue cards

### ISSUE THREAD

**Issue by gomfunkel** [bafolts/terraforming-mars#400]
Right now it is not possible to see which blue card was already _used_ or _activated_ in the current generation without scrolling through the log. When having played an action from a blue card, this should be made visible on the card itself.

This would be helpful when looking through the cards of other players to see what options they still have in this generation for example.

**Comment by gomfunkel** [comment]
@alrusdi What do you think about re-using the new drop shadow for selected cards for this use case as well, just using a different color? Something like this:

<img width="297" alt="highlight" src="https://user-images.githubusercontent.com/547035/76788945-2b86f980-67bc-11ea-8d93-3f94e5a66af5.png">

**Comment by alrusdi** [comment]
This is good idea but it is meaning is not obvious. May be we should use some kind of bage with "activated" caption on it?

**Comment by alrusdi** [comment]
In original ssimeonoff cards list https://ssimeonoff.github.io/cards-list he uses grey-out effect for selection. It can better represent inactive state to me

**Comment by gomfunkel** [comment]
@alrusdi The grayed out variant seems interesting. I will have a look into this. Could you please assign me to this issue?

**Comment by gomfunkel** [comment]
I have a branch with a working version of this feature which just needs a little cleanup. In it, blue cards are now grayed out when their action was used. This works for both your own cards and when looking at the cards of other players.

Having two blue cards played:
<img width="868" alt="Before" src="https://user-images.githubusercontent.com/547035/76878395-073b2380-6875-11ea-9725-511f21bb050c.png">

Having used the Tardigrades action:
<img width="860" alt="After" src="https://user-images.githubusercontent.com/547035/76878690-7b75c700-6875-11ea-8acc-3daca2599bdc.png">

**Comment by alrusdi** [comment]
I like this variant. Please make PR, but actualize your version from our master branch to avoid merging conflicts

**Comment by gomfunkel** [comment]
Implemented and merged to master with #409.
