### ISSUE TITLE
Docker permission error

### ISSUE THREAD

**Issue by rzulian** [bafolts/terraforming-mars#405]
Hi,
when trying to run the image `docker run -p 8080:8080 terraforming-mars` I'm getting a `lessc: failed to create file /usr/src/app/`.
This seems to be related to the tfm user you are creating in the image, because if I'm creating an image without that user
`RUN addgroup -S tfm

RUN adduser -S -D -h /usr/src/app tfm tfm

RUN chown -R tfm:tfm /usr/src/app

USER tfm` 

It works just fine.

**Comment by vincentneko** [comment]
This one should be fixed now (the dockerfile has been updated)

**Comment by rzulian** [comment]
@vincentneko  It's working now. Thanks!

**Comment by rzulian** [comment]
@vincentneko I'm definitely not a Docker expert, but it looks that the layering can be improved, because we are pushing the data twice

<img width="734" alt="Screenshot 2020-03-26 at 10 23 03" src="https://user-images.githubusercontent.com/29941924/77631114-6f13fd00-6f4c-11ea-94a4-b7aaad09f65c.png">
