### ISSUE TITLE
Better tags, millestones and VPs tracker

### ISSUE THREAD

**Issue by alrusdi** [bafolts/terraforming-mars#407]
What about to do it in popup widget like our current Preferences?
Popup will contain a switchable tabs with different categories
Each tab will have a table with player names and parameters. Columns can be sortable by click. Default sorting can be configurable.
Millestones and Awards will have subtabs for each MIllestone and Award with description and current values
VPs tab will track oponnets and current VPs actual to the current move
![draft](https://user-images.githubusercontent.com/394311/76856822-eb844d00-6875-11ea-8aa9-ee6ab4994d14.jpg)

**Comment by FreeLikeGNU** [comment]
I'd like to see the VP next to the TR points in the top bar.   This top bar would also have a button (the bottom border) that expands to show the other players VP, TR and resources just under the viewing players stuff for quick comparisons.

**Comment by ssimeonoff** [comment]
Example of a simple row of the tags count fitting the current design:
![tags](https://user-images.githubusercontent.com/6917565/77117512-76aa4200-6a32-11ea-933e-d9336e319489.png)

**Comment by vincentneko** [comment]
Can we close this one ?

**Comment by alrusdi** [comment]
No please. Tags counter is just first (amathing) step to show more statistics in the game

**Comment by vincentneko** [comment]
@alrusdi and @nwai90 
I've created `improve_ms_awards `branch. In this branch scores for milestones and awards are exposed for client.
Do you mind taking care of the client side as I'm pretty bad with this ?

![Screenshot 2020-07-21 13 32 54](https://user-images.githubusercontent.com/56086992/88051032-41387100-cb58-11ea-8997-621980341c57.png)

**Comment by alrusdi** [comment]
I think stats data needs more generalization. Now we need an award counts. Tomorrow we will need Milestones counts. Next day we will need Turmoil Influence values...
May be it is better to have separate section in player response for stats? It can be a list with StatsModel structure (id="awards", name="Awards", scores=[...])
And then implement UI like panel with tab for each StatsModel item in that list

**Comment by vincentneko** [comment]
In my opinion it makes sense to store Milestones / Awards additional information within Milestones / Awards.
This information can then be extracted on the client side to be displayed either with Milestones / Awards or somewhere else.
