### ISSUE TITLE
Software/Content licenses 

### ISSUE THREAD

**Issue by FreeLikeGNU** [bafolts/terraforming-mars#410]
I noticed this project does not have licenses expressed for code or creative content.  Please state the terms of contribution, usage, modification and redistribution of the contents of the repository.  Thank you.

**Comment by bafolts** [comment]
I have selected the GNU license. I started this project as a hobby and am not too concerned with how it is used but I would like the source to remain open source.

**Comment by FreeLikeGNU** [comment]
Awesome! Many thanks!
