### ISSUE TITLE
Solo game can’t finish early?

### ISSUE THREAD

**Issue by lostgrail** [bafolts/terraforming-mars#413]
When finishing a solo game with all expansions on the Hellas board on generation 11, the game stalled (no action to be taken).

Presumably this is when the player would pick a global parameter in increase with WG Terraforming

![A177EF6C-433D-4B09-8C75-8C2326A381D1](https://user-images.githubusercontent.com/7331135/76922522-58640b00-68a7-11ea-8b72-c585ff335275.png)
![35590CA3-D859-495C-BD45-712B8DA3AA99](https://user-images.githubusercontent.com/7331135/76922528-5bf79200-68a7-11ea-8d6e-180f019e2eb3.png)

**Comment by alrusdi** [comment]
Fixed & merged. @lostgrail thank you for reporting!
