### ISSUE TITLE
Suggestion: Display events in opponents cards

### ISSUE THREAD

**Issue by dabewi** [bafolts/terraforming-mars#418]
Hi,

I just recently noticed that the events that opponents had played are not displayed when I take a look at the cards of an specific opponent.

I want to suggest to return to displaying them, because otherwise I don't have access to all information that I would have access to in a RL board game, e.g. the number of played events (for one of the milestones) and the VP on them.

Alternatively, if you want to continue hiding the events, please introduce a label which states the amount of played event cards.

Cheers!

**Comment by ssimeonoff** [comment]
In the real game, you don't look into other player's events - you can only ask how many they have.

And about the count,  it is already implemented as a side effect. 
The new Tag count board is visible for for other players and there you have an Event tag, which effectively tells you how many Events are played by that player.

**Comment by alrusdi** [comment]
@ssimeonoff great explanation! I think we don't need the feature to display opponents event cards.
