### ISSUE TITLE
Submit game results to @ssimeonoff for game statistics

### ISSUE THREAD

**Issue by gomfunkel** [bafolts/terraforming-mars#424]
@ssimeonoff provides a great statistic page at http://ssimeonoff.github.io.

This idea is about automatically (optionally) submitting results to the statistics database, once a game ends.

Any opinions on this would be interesting, especially from @ssimeonoff himself, obviously. 😉

**Comment by ssimeonoff** [comment]
There are few problems.

1. A games a assigned only to one player
Currently when a game is submitted, only one email(user) is stored with it with a rank value, calculated on client side (assuming player1 is the submitter).  In your case, you would want all players to be assigned to that game.  I guess it is easy to pass 2 arrays instead. Will have to fix on my end though.

2. Auth 
Do you play to use Firebase auth or your own? (you need to pass emails and names with the submit)

3. Firebase 
As a non-developer and barely now some frontend, it was the easiest thing to use to build the statistics pages. But queries are shit. No relational queries at all. To display the stats, I download the WHOLE database on the client and then crunch the numbers. The performance suffers, the traffic suffers. To fix the performance now most tableaus are not loaded until "Load" is pressed. To fix the traffice issue (partially), I store the database into LocalStorage and update it upon user's action only.
LocalStorage has its limit and as the Firebase traffic, and I am reaching both.

I want to move away from Firebase.

Recently I asked @vincentneko to set up a test postgres db for me. Unfortunately you cannot connect GitHub Pages without a third party service. 
So you better think how to build your stats and then, maybe how to migrate my data to you.

**Comment by alrusdi** [comment]
@ssimeonoff thank you for info. We will consider other options for statistics.
