### ISSUE TITLE
Suggestion: Player Board css changes

### ISSUE THREAD

**Issue by ssimeonoff** [bafolts/terraforming-mars#426]
Ideas: 
- "prod:" text is obsolte - people now this is the production values
- every cell contains 3 elements - production value, resource icon, resources value - align them
- increase the fonts for better reading
- add some background gradients to blend in better with the background
- fit the width to match the map width (or 2 Project cards columns) for better overview
![player-board](https://user-images.githubusercontent.com/6917565/77083037-249af980-69fd-11ea-83d7-efaf44906795.png)
![scrolled](https://user-images.githubusercontent.com/6917565/77083406-bc004c80-69fd-11ea-800b-b52b3007a51d.png)

**Comment by FreeLikeGNU** [comment]
I like these changes!  Is there room for VP here as well?

**Comment by alrusdi** [comment]
This seems to be implemented and merged
