### ISSUE TITLE
Feature request: Actions log to show the card preview for card-related actions(played/activated)

### ISSUE THREAD

**Issue by ssimeonoff** [bafolts/terraforming-mars#428]
![log](https://user-images.githubusercontent.com/6917565/77176117-e9173280-6ac3-11ea-83e1-b948a2ae1451.png)
In the log:
- Player name to be displayed in the player's color
- Card name to be displayed as it is in the card (matching colors and fonts)
- When the card name is clicked, the preview div is displayed (X dismisses it)

Notes:
I don't know the cards' names, even after 1000+ games, I know only a handful. 
When I played 1vs1 I kept the Cards List page open in another tab and was copy/past -ing there every card name my opponent played/activated.

**Comment by alrusdi** [comment]
It is a good idea! We will implement it, but not right now

**Comment by gomfunkel** [comment]
Started working on this (at least the coloring part, not yet the preview div) tonight and already made some progress. Would be great if someone could assign me to this.

Early Screenshot:
<img width="788" alt="colors" src="https://user-images.githubusercontent.com/547035/77365314-30b4ed00-6d56-11ea-9386-33592e148453.png">

I had to put the player names on a lighter background as well, otherwise it would be impossible to see the black player.

**Comment by ssimeonoff** [comment]
@gomfunkel 
Is that an easy option to do as well: (generations breakdown)
![Untitled](https://user-images.githubusercontent.com/6917565/77366999-84750580-6d59-11ea-81c4-2f9c0d0cf233.png)

And also, is it possible to fix a bug in this pr as well: 
"End Turn" action does not log anything. 
E.g. "Player 1 turn ended"

**Comment by gomfunkel** [comment]
Great ideas, @ssimeonoff! Should be possible as the log is just a list of strings as it is now. Will see what I can do.

**Comment by gomfunkel** [comment]
I have implemented the following ideas from this issue and submitted pull request #446. 

* Using player colors
* Using card type colors and font
* Added log message when ending turn
* Added log message on new generation

Displaying the cards on click in the logs is still to be done.

Here’s what the log now looks like:
<img width="786" alt="Screenshot 2020-03-24 at 10 18 44" src="https://user-images.githubusercontent.com/547035/77419911-75c63700-6dc9-11ea-83b5-920f41ed3e4c.png">

**Comment by pierrehilbert** [comment]
I have done some test and I have this result:
<img width="804" alt="Capture d’écran 2020-03-27 à 19 57 57" src="https://user-images.githubusercontent.com/806950/77790850-d376af80-7065-11ea-9f5d-4f93fb7f9e60.png">

Will it be okay for everyone?

**Comment by gomfunkel** [comment]
@pierrehilbert I had something a bit different in mind for the UI but if yours is working, I‘m totally fine with it. I didn‘t start implementing the functionality yet, so go ahead.

**Comment by pierrehilbert** [comment]
It's merged!

**Comment by gomfunkel** [comment]
Thank you, @pierrehilbert!

This is a good start and very helpful. I found some issues with this approach, though.

* The whole log message is linked to a card, not just the card itself
* Log messages not containing played cards open a blank card frame when clicked
* Log message containing more than one card (i.e. when using Robotic Workforce) 
* Clicking a log message multiple times always opens another card

Thinking about it a bit more we probably need a component for `<log-card/>` to allow proper interaction. I will gladly have another shot at this but am not sure when I will be able to do so.

**Comment by gomfunkel** [comment]
Thank you, @pierrehilbert! This is very helpful. I found some issues with this approach, though:

* The whole log message is linked to a card, not just the card itself
* Log messages not containing played cards open a blank card frame when clicked
* Log message containing more than one card (i.e. when using _Robotic Workforce_) only open one of the cards when clicked
* Clicking a log message multiple times always opens another card

Thinking about it a bit more we probably need a component for `<log-card/>` to allow proper interaction. I will gladly have another shot at this but am not sure when I will be able to do so.

**Comment by pierrehilbert** [comment]
I corrected the blank part and the double display of the same cards.
For the log part, I think it could be great to indicate more informations. 
Some examples: 
- When trading with a colony, display how many resources did the player get.
- When using a blue card and there is multiple choice, display which one have been chosen.

**Comment by vincentneko** [comment]
Is this issue still relevant ?

**Comment by alrusdi** [comment]
I think no
