### ISSUE TITLE
New start screen

### ISSUE THREAD

**Issue by alrusdi** [bafolts/terraforming-mars#429]
I love of how https://ssimeonoff.github.io/ start page looks.
What about make the same start page with the options:
- **New game** - current create game page
- **Solo challenge** - simplest form to setup solo game
- **How to play?** - link to game rules
- **Cards list** - link to https://ssimeonoff.github.io/cards-list
- **Board game** - link to Terraforming Mars BGG page
- **About us** - link to our Github
- **Languages** - language switcher for current session
- **Whats new?** - our changelog and plans
Of course if @ssimeonoff will allow us to use his design

![main_page](https://user-images.githubusercontent.com/394311/77224308-1d532780-6b86-11ea-9cda-8942468c823f.png)

**Comment by ssimeonoff** [comment]
Use what you want.

**Comment by alrusdi** [comment]
@bafolts can i introduce here a expressjs framework to make our life with server.ts easier? http://expressjs.com/

**Comment by ssimeonoff** [comment]
FYI: This is the original wallpaper I use to get the buttons' backgrounds: 
https://cdn.apk-cloud.com/detail/screenshot/4vz1FS5V9M4QZ52fvS2uMq-1FRBFeFBELhJblvC_DQA5PVGzcMzztcs3EWyua_ik5Q=h900.webp?vr

There are other awesome options. For example: 
![1](https://user-images.githubusercontent.com/6917565/77318463-65e91d00-6d0d-11ea-9d84-2adc2c27d8a4.png)
![2](https://user-images.githubusercontent.com/6917565/77318465-6681b380-6d0d-11ea-85b7-469ccc688a81.jpg)

**Comment by bafolts** [comment]
Using expressjs is fine. Since this project started as a hobby I never intended for it to get this far. My co-worker hates javascript dependencies so I was in the mindset early on of this project having no dependencies besides typescript. It has evolved from there.

**Comment by alrusdi** [comment]
Merged
