### ISSUE TITLE
Bug: "Hydrogen to Venus" cannot be paid with tatinium

### ISSUE THREAD

**Issue by ssimeonoff** [bafolts/terraforming-mars#433]
![90152850_207076220391432_8986540290248540160_n](https://user-images.githubusercontent.com/6917565/77258530-7355c700-6c7b-11ea-9158-6103443fbb34.png)

**Comment by vincentneko** [comment]
Are you playing on my server ?
If yes, this will be fixed soon.

**Comment by ssimeonoff** [comment]
oh y, sorry

**Comment by vincentneko** [comment]
I've found the bug and patched my server.
