### ISSUE TITLE
Commercial district graphic does not show

### ISSUE THREAD

**Issue by dr00b** [bafolts/terraforming-mars#434]
Icon did not show up on after playing commercial district. 
![image](https://user-images.githubusercontent.com/10406639/77260863-e4d44c00-6c60-11ea-9be8-5aed98cdb088.png)

Player id = https://terraforming-mars.herokuapp.com/player?id=9098db8cd43c

**Comment by dr00b** [comment]
@bafolts FYI - I checked in on this about 6-7 months ago. It's come a long way! Beautiful :)

**Comment by alrusdi** [comment]
Fixed & merged. @dr00b thank you for reporting!
