### ISSUE TITLE
Animal tags don't count

### ISSUE THREAD

**Issue by dabewi** [bafolts/terraforming-mars#447]
Hi,

in our current game I've played pets but in the overview with all my tags the animal tag from the pets card is not displayed. Instead I have two energy tags but I should only have one:

https://abload.de/img/tagbug86k13.png

This is unfortunate because of the Diversifier milestone.

Cheers!

**Comment by dabewi** [comment]
My opponent has a similar problem with the difference that his animal tag just disappears (it's not counted as engery or another tag):

https://abload.de/img/bug1ekx7.png

**Comment by alrusdi** [comment]
It is just visual bug, don't worry - Diversifier milestone should be available

**Comment by alrusdi** [comment]
Should be fixed now

**Comment by gomfunkel** [comment]
The energy tag problem mentioned by @dabewi comes from the prelude card Supply Drop which had an energy tag although it shouldn't. Fixed that with #456.
