### ISSUE TITLE
Technology Demonstration and Special Design did not award a science tag

### ISSUE THREAD

**Issue by FreeLikeGNU** [bafolts/terraforming-mars#457]
I had six science tags in a game but after playing Technology Demonstration and Special Design my science tag count did not increase for either card.

**Comment by vincentneko** [comment]
This this expected behaviour. Tags on event cards are not added to tag count, that's why event cards are put face down in the boardgame.

**Comment by FreeLikeGNU** [comment]
Ah I overlooked this rule of the game on the tabletop!  Apologies for the false alarm.
