### ISSUE TITLE
UNMI allows purchase of TR without player having increased TR in that generation.

### ISSUE THREAD

**Issue by FreeLikeGNU** [bafolts/terraforming-mars#458]
Replicate:
Have only UNMI and another corporation in custom corporation list to start a two player game.
Chose UNMI for one of the players.
First gen UNMI acts as expected and cannot use its action to increase TR unless TR has been gained from a previous action.
Pass the other player, Pass the UNMI player.
Second gen UNMI is allowed to purchase TR before raising TR that gen.
![Screenshot_2020-03-24_21-50-18](https://user-images.githubusercontent.com/674095/77503251-6f13e000-6e1a-11ea-9cf7-652aeb22e667.png)

**Comment by alrusdi** [comment]
I guess it was a game without draft option?

**Comment by FreeLikeGNU** [comment]
Yes it was without draft.  Thank you!

**Comment by alrusdi** [comment]
Fixed and merged
