### ISSUE TITLE
Immigrant City bonus for subsequent cities (+1MCprod) not triggering

### ISSUE THREAD

**Issue by Gnom3rcy** [bafolts/terraforming-mars#4580]
Tom played immigrant city, after that a few cities including capital were played by other players, which should increase Tom's megacredit production, but it does not. 

Spectator link
https://terraforming-mars.herokuapp.com/spectator?id=scdc4334315aa

**Comment by kberg** [comment]
Sorry for the long delay. @Gnom3rcy you actually saw that the MC production didn't change? Or did you assume this because there wasn't an entry in the log? We log a lot of things, just not everything. And I think we don't log that MC production bump.

**Comment by Gnom3rcy** [comment]
Yes, it didn't change. Observed multiple cities being placed with no bonus. 

Sent from Yahoo Mail on Android 
 
  On Tue, Jun 28, 2022 at 9:52 PM, Robert ***@***.***> wrote:   


Sorry for the long delay. @Gnom3rcy you actually saw that the MC production didn't change? Or did you assume this because there wasn't an entry in the log? We log a lot of things, just not everything. And I think we don't log that MC production bump.
