### ISSUE TITLE
Better global parameters widget

### ISSUE THREAD

**Issue by alrusdi** [bafolts/terraforming-mars#46]
What about new global parameters meter like this: https://alrusdi.ru/static/globs_meter.png ?
I already have markup for it.

**Comment by alrusdi** [comment]
With compact resources block it can be like this: https://alrusdi.ru/static/new_blocks.png
I will make PR if this acceptable.

**Comment by vincentneko** [comment]
It look awesome. Maybe too close from the commercial version, I don't know if it could be an issue...

**Comment by alrusdi** [comment]
Do you really care about it? Then all this work is pretty illegal because Jacob is very negative even about to publish cards info (name, full text and info).

**Comment by vincentneko** [comment]
Not really, I was just pointing this out.
For the cards, we follow same rules than ssimeonoff who represented the cards
(tag for instance are not the same)
He asked Fryxgames and they said they where ok with a no image no flavour text policy. I guess we will need to clarify this matter furthermore.

**Comment by alrusdi** [comment]
The icons i used for board is probably incorrect too in this case... Sad news. I will try to replace them soon...

**Comment by bafolts** [comment]
I haven't reached out to Fryxgames in any way. I don't plan to make money off of this project. I started it when I was playing it weekly with friends and was looking for a way to play online. Then news of the online steam version was posted and I stopped working on it. I then ended up with an hour long commute that involved a boat ride so I worked on this project during that time. I would agree that not using the images directly is probably better for everyone.

**Comment by alrusdi** [comment]
I am sorry about reopen this issue. But i have another variant to show global parameters in UI: 
https://alrusdi.ru/static/globs2.png
This one is without any images from original version. Less eye candy, but i believe still better than current one.
Can I please implement it in our UI?

**Comment by alrusdi** [comment]
Merged. Thank you everyone for participation.

**Comment by vincentneko** [comment]
This is looking great !

Sorry for not noticing before, but the reading in temperature and oxygen meters is a little difficult.
For instance, temperature is at -26 but it shows just in between -26 and -24 on the meter.
Same for oxygen, it reads 1.5 where it should be 1.

**Comment by alrusdi** [comment]
I made new PR with attempt to resolve this problems
