### ISSUE TITLE
Venus waystation card's effect is applied once for Venus Governor card

### ISSUE THREAD

**Issue by Carcassonner** [bafolts/terraforming-mars#465]
The effect should be applied when playing each Venus tag. 
Maybe it works wrong with Luna Governor card and Teractor corporation/Earth office card and Research card + Valley Trust corporation too.

**Comment by vincentneko** [comment]
Great feedback thanks. Valley Trust was bugged too.
I've also modified Cheung Shing MARS even if there are no dual building tags at the moment.

**Comment by vincentneko** [comment]
Fixed and merged
