### ISSUE TITLE
Frustrating solo game final

### ISSUE THREAD

**Issue by alrusdi** [bafolts/terraforming-mars#47]
Just finished solo game successfully and got no reward :-)
Can we do special win/lose page for solo mode?
If player wins we can show him image like this https://upload.wikimedia.org/wikipedia/commons/thumb/6/62/Terraformed_Mars.jpg/800px-Terraformed_Mars.jpg
and suggest to make another attempt to try get more Victory Points.
If player loses suggest him to try again with some hints from BGG and rules.

**Comment by bafolts** [comment]
A separate page would probably be better. What is currently there was the fastest to implement as I was rushing to get this working.

**Comment by alrusdi** [comment]
Merged
