### ISSUE TITLE
Compact award and milestones vol 2.0

### ISSUE THREAD

**Issue by ssimeonoff** [bafolts/terraforming-mars#474]
@alrusdi, 
This is directed to you...

1. Milestone are collapsed
It can be seen that 1 Milestone has been claimed by the Red player
![a1](https://user-images.githubusercontent.com/6917565/77656561-56b7d880-6f74-11ea-802a-d0dedec1f748.png)

2. Milestones text is clicked and expaned
All Milestones are displayed.
Claimed Milestones are visible again (filter:greyscale(100%); opacity:0.5;)

![a2](https://user-images.githubusercontent.com/6917565/77656831-bc0bc980-6f74-11ea-9601-7afc2d152852.png)

3. Milestones image is clicked
Milestones info is toggled (displayed or hidden)
All Milestones info divs can be toggled or only the clicked one, up to you.
![B3](https://user-images.githubusercontent.com/6917565/77656975-eb223b00-6f74-11ea-804f-2e45768e0b2a.png)

Resources: 
The player's colour cubes are already present.
The images with the Milestones and Awards you can get from my repo:
https://github.com/ssimeonoff/ssimeonoff.github.io/blob/master/images/ma-randomizer/column_m.png
https://github.com/ssimeonoff/ssimeonoff.github.io/blob/master/images/ma-randomizer/column_a.png 
FYI: Offset is 100px per image.

Pros: 
- when Milestones are collapsed, width will be saved - a colour cubes take less space than the player's name
- when Milestones are expanded, height will be saved - 100px height vs 170px
- eye-candy

**Comment by alrusdi** [comment]
This is amazing

**Comment by alrusdi** [comment]
Hooray! It's merged. @ssimeonoff thank you for amazing UI
