### ISSUE TITLE
Suggestion: Played and Hand cards reordering

### ISSUE THREAD

**Issue by ssimeonoff** [bafolts/terraforming-mars#487]
1. The latest obtained card in hand to be first.
Currently the cards are ordered by type and the new card is pushed back at the end of its type. 
"Research" is the latest obtained card.
This is the most important of the 3 suggestions. When you have a big hand, you often get cards without noticing them, because they are not in view.

2. The latest played Active card to be first (next to the corporation).
"Mars Universaty" is the latest played Active card.

3. The latest played Automated to be at top (just move the preludes at the bottom)
"Power Plant is the latest Automated"

![Untitled](https://user-images.githubusercontent.com/6917565/77836664-68f26c00-7158-11ea-9583-e78aa6a0f167.png)

**Comment by pierrehilbert** [comment]
I proposed a fix ;-)

**Comment by alrusdi** [comment]
@pierrehilbert i think @ssimeonoff means to sort card by type, and then by play/draw order. Your PR removes ordering by type.

**Comment by pierrehilbert** [comment]
Really? Because for me and other players, we found that it will be easier to order card by drawing order.

**Comment by ssimeonoff** [comment]
by drawing order, this is what I mean  - "The latest obtained card in hand to be first." without caring for the type.

**Comment by alrusdi** [comment]
Even for played cards? O_o

**Comment by alrusdi** [comment]
it is also breaks this feature https://github.com/bafolts/terraforming-mars/issues/270

**Comment by ssimeonoff** [comment]
Maybe then add it in Settings? To not seeing latest cards at the top, played or obtained, seems odd to me, but if some likes them ordered or not, maybe an option to toggle the sorting is a good thing...

**Comment by alrusdi** [comment]
I don't care much about "cards in hand" order - it's ok for me to have them in draw order.
For played cards it is important to have Active cards first and it is better to have last played active to be first in this list. Current PR does something else

**Comment by pierrehilbert** [comment]
If I'm not wrong what I did is:
- Order card by draw order in hand
- The last Active card played will be at the left
- The last Automated card played will be at the top of the stack pile

**Comment by alrusdi** [comment]
ookay, i'm sorry if i missread the code

**Comment by pierrehilbert** [comment]
If it's okay for you, please close the issue after testing ;-)

**Comment by alrusdi** [comment]
It is seems to be implemented. We did some plytests
