### ISSUE TITLE
Suggestion: Components UI improvements

### ISSUE THREAD

**Issue by ssimeonoff** [bafolts/terraforming-mars#488]
1. The map 
A brighter image showing the placement bonuses better. With the image's lightening and simple box-shadow you get a cheap 3D feeling of the globe.
![map](https://user-images.githubusercontent.com/6917565/77836929-2e3e0300-715b-11ea-88d4-55c198944cc2.png)

2. Player boards
Reusing the new Mars image, adding some flare...
![board](https://user-images.githubusercontent.com/6917565/77836958-8117ba80-715b-11ea-8dea-e936012137cf.png)

3. Global parameters - reworked and unified with the Venus track
Still now fully happy with the colours...
![globals](https://user-images.githubusercontent.com/6917565/77836981-a5739700-715b-11ea-9c52-cb45340d6260.png)

4. Milestone and awards
![ma](https://user-images.githubusercontent.com/6917565/77836987-b9b79400-715b-11ea-8875-0d190cd2960f.png)

5. Other players
Slight colour difference to easily distinguish between own and foreign board. 
The div are capped at approx. 1200x1200px (4 columns and 3 rows are visible).
And the 2 divs are inlined (if possible) - gaming on 2500x1440 gets better. 

![otherplayer](https://user-images.githubusercontent.com/6917565/77837087-c38dc700-715c-11ea-899b-760e9d2502a9.png)

**Comment by FreeLikeGNU** [comment]
love the Martian walnut trays and accents!

**Comment by alrusdi** [comment]
This is merged. @ssimeonoff thank you very much!
