### ISSUE TITLE
No issue

### ISSUE THREAD

**Issue by TokeJacobsen** [bafolts/terraforming-mars#491]
Hey Sir,

I'm a young programmer who would love to ask you a couple of questions regarding your Terraforming Mars enthusiasm.

Please reach back to me: Toke@Roshage.dk

Cheers!

https://boardgamegeek.com/thread/2395476/help-create-terraforming-mars-dataset

https://www.reddit.com/r/TerraformingMarsGame/comments/fpple6/terraforming_mars_from_a_data_scientist_point_of/

**Comment by alrusdi** [comment]
We have no any statistics, sorry

**Comment by bafolts** [comment]
This is similar to #445 . Currently @ssimeonoff stores game results on some firebase database but I don't think we store this data anywhere else. Most things with this game run free of charge. Introducing this change would require us to have some central data storage place. I don't think the hosting costs would be that expensive. I don't know where @vincentneko is running the server but this will require some data storage. Upon configuring the game server we would then provide the data storage connection information and password external of this source. I would be interested in seeing the data and I created this project as a learning tool for myself. I don't have much experience with machine learning and creating a bot for this game seems like a good challenge.
