### ISSUE TITLE
Suggestion: Select Space button

### ISSUE THREAD

**Issue by thenewjuniorexecutive** [bafolts/terraforming-mars#494]
There's rarely a decision being made by the player when this button is displayed, so it just leads to extra clicks and scrolling.

Once the next step is definitely placing a tile, could you instead jump to the map with the legal spaces highlighted and active and the text that is now displayed over the "Select space" button displayed above the map with the text being removed once a hex is selected?

**Comment by nwai90** [comment]
@bafolts @vincentneko I will submit a PR for this. It will save the user a lot of unnecessary clicks on "Select Space" by allowing them to select a valid space on the board immediately

**Comment by nwai90** [comment]
This feature has been deployed, should we close this issue?

**Comment by vincentneko** [comment]
Yes sure, thanks for taking care of it.
