### ISSUE TITLE
BUG: Players with the same player name will confuse the log window color assignment.

### ISSUE THREAD

**Issue by FreeLikeGNU** [bafolts/terraforming-mars#496]
Replicate:
Give more than one player the same name.

![Screenshot_2020-03-29_11-12-56](https://user-images.githubusercontent.com/674095/77856788-5b67d100-71ae-11ea-81bc-503507fa8448.png)

![Screenshot_2020-03-29_11-19-39](https://user-images.githubusercontent.com/674095/77856933-6e2ed580-71af-11ea-8b23-b250ca660294.png)

**Comment by FreeLikeGNU** [comment]
Seems as though the log only records and refers to player by name.  Thus the last entry added that matches is parsed and used to select the color of the log text.

**Comment by gomfunkel** [comment]
The reason for this is that all log messages simply save the _name_ of the player. Generating the log iterates over all players trying to find one with a matching name. We then use the color of the first one who matches.

See [LogPanel.ts#L31](https://github.com/bafolts/terraforming-mars/blob/94a86f47fb2108aaddc1b6b205c362f5bf7414b0/src/components/LogPanel.ts#L31)

To fix this, we need to save a more unique identifier when recording the log, for example the `playerId`. Then replacing it with the according name and color when rendering the log. We could do that but need to make sure that we are not (accidentally) exposing the `playerId` to other players.

**Comment by gomfunkel** [comment]
@FreeLikeGNU Fixed and merged with #523.

**Comment by FreeLikeGNU** [comment]
It's working well now thank you!
