### ISSUE TITLE
Feature Request: Cancel before placing a tile.

### ISSUE THREAD

**Issue by FreeLikeGNU** [bafolts/terraforming-mars#497]
Choosing an action that places a tile does not allow cancelling that action before the tile is placed.

**Comment by kberg** [comment]
The undo feature ought to handle this. Close?

**Comment by FreeLikeGNU** [comment]
> The undo feature ought to handle this. Close?
If I choose an action that places a tile can I undo if its the second action in a multiplayer game?

**Comment by kberg** [comment]
I'm OK with undo being the sole mechanism to address this, both effectively achieve the same thing. But I think it's probably hard to do, given that some tile placement produces cards and other events that can't be unseen. But if undo is good enough, then there's no need for both -- people who want to take a cautious approach to their tiles being correctly placed can enable it.

**Comment by kevinb9n** [comment]
@kberg I addressed the "unseen" bit in the new issue just linked, but setting that aside, I think undo is an unsatisfactory way to handle this. First because it's often unavailable, as mentioned. But also because it forces the player to continue making random choices to complete the action - and those choices could trigger things like an opponent's Philares effect.

A "cancel" you can do before anything committal ever happened would be a great thing.

**Comment by kberg** [comment]
Yeah I'm beginning to come around to this cancel before placing a tile idea. But there are some die-hard players who care about minimum clicks.

**Comment by nwai90** [comment]
@kberg Do you think we can close this one? As you have added a tile confirmation dialog now

**Comment by kberg** [comment]
Yep, I was just coming here to do that.

**Comment by kberg** [comment]
@FreeLikeGNU FYI, this is implemented.

**Comment by Lynesth** [comment]
No it's not. This issue is about being able to cancel the action selected if you still haven't placed the tile.

**Comment by kberg** [comment]
Good catch.

**Comment by bafolts** [comment]
I am going through old issues assigned to me. Hoping to not have any open for a year! If the `SelectSpace` has an `OrOptions` or `AndOptions` parent then this seems plausible. If the `SelectSpace` has no parent from a deferred action than it wouldn't make sense to be able to cancel as you have to select a space. Good opportunity to upgrade `SelectSpace` again. Plan to pick this up next.

**Comment by Lynesth** [comment]
> I am going through old issues assigned to me. Hoping to not have any open for a year! If the `SelectSpace` has an `OrOptions` or `AndOptions` parent then this seems plausible. If the `SelectSpace` has no parent from a deferred action than it wouldn't make sense to be able to cancel as you have to select a space. Good opportunity to upgrade `SelectSpace` again. Plan to pick this up next.

I'm not sure how this will work when I'm done converting everything as part of the Priority changes I'm making (when I have a bit more time to finish).

This also rises the question regarding cards drawn during the action.

I ultimately feel like this FR falls into the `undo` category.

**Comment by kberg** [comment]
Well, let's tread carefully here -- undo isn't *quite* enough if a player
draws cards.

Which is more important, prioritization or good undo?* Everyone will have
their opinion on the matter.

* That's an unfair question, because you could ask me whether The Moon is
more important than undo, too.

>

**Comment by bafolts** [comment]
After giving this thought I think I am in @Lynesth camp. The pain point with undo as I see it is that you have to wait until the undo action is available. If we instead always displayed the undo button, and allowed clicking it whenever, that could help in this situation. Without being able to always click undo a player has to keep taking random actions until they get back to the undo link displayed. If everything is eventually handled with deferred actions the undo should be enough to reset the state back to whenever a large heap of deferred actions showed up.

Thinking I will solve this by putting an undo button somewhere on the page always available. This would take up real estate but I think it would solve a lot of problems as a player could undo at any point.

If players want to cancel the action and they haven't enabled undo they should enable undo.

**Comment by kberg** [comment]
Perhaps I missed the idea of "an undo button being always available."
Because I also think that's a good idea. Don't mind me, I'm sure you're
right. I was just tossing out a caveat.

>

**Comment by Lynesth** [comment]
> Thinking I will solve this by putting an undo button somewhere on the page always available. This would take up real estate but I think it would solve a lot of problems as a player could undo at any point.

That's a good idea.

**Comment by kberg** [comment]
I look at games on yucata.de, and it knows how to do undo very well. It has
both an "undo" for a single step and also a "reset" for restarting a turn.
Well, here I don't think we would want to restart an entire turn, but you
could allow a player to go both a single step back, and roll back an entire
turn, again, just as long as the game actions could be undone.

>

**Comment by Lynesth** [comment]
> I look at games on yucata.de, and it knows how to do undo very well. It has both an "undo" for a single step and also a "reset" for restarting a turn.
Well, here I don't think we would want to restart an entire turn, but you could allow a player to go both a single step back, and roll back an entire turn, again, just as long as the game actions could be undone.

Since we're not sending all data to the server when the action is done, but for each part of the action &mdash; as opposed to other games that let the whole action happen on the client side fully first &mdash; that means we would need to:
 - Save each time something happens (increasing number of saves)
 - Serialize deferred actions (a big endeavour)

Getting that middle ground where you can undo 1 action fully at any time is a good choice I think.

**Comment by kberg** [comment]
For sure.

**Comment by naanlizard** [comment]
This just bit me in a game, it is very frustrating to be prompted to place a tile, and have a confirmation for where I want to place it, but not an option to back up and not place it at all

**Comment by kberg** [comment]
Understood. The ability to roll back a turn really will take a while to get done, if at all.
