### ISSUE TITLE
Can go negative titanium with WATER IMPORT FROM EUROPA

### ISSUE THREAD

**Issue by vincentneko** [bafolts/terraforming-mars#50]
A check on titanium amout in stock is missing, that can lead to negative titanium amounts.

Would it be possible to modify SelectHowToPay to have built-in checks for resource availability (MC, steel, titanium, heat...)

**Comment by bafolts** [comment]
This should be possible. I am not sure with nes.css we have the latest version the includes form validation. I will put together a client side fix for this.

**Comment by bafolts** [comment]
This is done for `SelectHowToPayForCard`. Will now need to implement for `SelectHowToPay` which will require larger changes.

**Comment by alrusdi** [comment]
Is it still actual?

**Comment by bafolts** [comment]
This is probably good enough for now to close. There are various `SelectHowToPay` which can be improved by adding an `amount` when we know it. Those will be enhancements though versus this original bug.
