### ISSUE TITLE
Bug: Wild tag triggers effect of Aridor corporation

### ISSUE THREAD

**Issue by Carcassonner** [bafolts/terraforming-mars#500]
Wild tag is not considered any tag at the time of playing the card

**Comment by ssimeonoff** [comment]
I think it is - it is considered as a Wild tag.

It also counts as a different tag for milestone "Diversifier", for Turmoil event giving you 10MC if you have 9 different tags in play (+influence) and for the project card "INTERPLANETARY TRADE".

**Comment by Carcassonner** [comment]
choosing a tag type for the wild tag does not count as playing that tag (so you can't trigger Olympus Conference for example), and it doesn't count as getting a new tag into play. It simply 'is' there for the duration of that action. (c)

https://boardgamegeek.com/thread/2030851/wild-tag-explanation-confusion
![image](https://user-images.githubusercontent.com/59147459/77906099-0b613b00-7290-11ea-8a9e-2493e1834506.png)

**Comment by vincentneko** [comment]
Yes I agree, wild tag should not trigger Aridor new tag capacity

**Comment by ssimeonoff** [comment]
Lol, never knew that.

**Comment by thenewjuniorexecutive** [comment]
And the Wild Tag can be treated as no tag for Community Services, but must be counted as one of the 11 possible face up tags (10 w/o Venus) for Interplanetary Trade.

**Comment by Carcassonner** [comment]
The effect of no card should be triggered when a wild tag card enters the game. Also, a wild tag should not be considered any tag at the end of the game.

**Comment by vincentneko** [comment]
Fixed aridor and  Community Services
