### ISSUE TITLE
Bug: Earth office card effect applies only once for Luna Governor card

### ISSUE THREAD

**Issue by Carcassonner** [bafolts/terraforming-mars#501]
Probably effect of Teractor corporation applies once too

**Comment by ssimeonoff** [comment]
It is a general bug when one card has 2 or more identical tags and an ongoing effect is applied to only one of them.

**Comment by Carcassonner** [comment]
> It is a general bug when one card has 2 or more identical tags and an ongoing effect is applied to only one of them.
> E.g. check #453.

It was fixed for venus waystation (venus tag discount) and venus governor (card with 2 venus tags). But not for this case.
I assumed the possibility of this error here #465

**Comment by vincentneko** [comment]
This one is working as intended, as the card text says:

(Effect: When you play an Earth **card**, you pay 3 MC less for it.)

**Comment by Carcassonner** [comment]
> This one is working as intended, as the card text says:
> 
> (Effect: When you play an Earth **card**, you pay 3 MC less for it.)

Ohh..sorry, it's my fault.

**Comment by Carcassonner** [comment]
Everything works great
