### ISSUE TITLE
Suggestion: "Observer" players

### ISSUE THREAD

**Issue by ssimeonoff** [bafolts/terraforming-mars#502]
Currently you cannot open the other player's areas in another tab/window/screen.

One possible workaround would be to create an "observer id" for every player.
![obs](https://user-images.githubusercontent.com/6917565/77923007-191fbc00-72a2-11ea-81af-f330b8267ce8.png)
When clicked "Observer" link open a new tab:
![obs2](https://user-images.githubusercontent.com/6917565/77923010-19b85280-72a2-11ea-972e-19b0daf60b6c.png)

Div "class="other_player_cont menu" is loaded there - nothing else.

Maybe it is a bad idea, but cannot think of another workaround.

**Comment by glass4pk** [comment]
Get the same idea too.

**Comment by kberg** [comment]
https://github.com/bafolts/terraforming-mars/issues/1192 may supplant this.

**Comment by chosta** [comment]
I am going to work on a spectator mode first thing 2021 and it's going to be a separate UI but the idea is similar to this one.

**Comment by bafolts** [comment]
Duplicate of #1192
