### ISSUE TITLE
Virus can remove your own animals

### ISSUE THREAD

**Issue by alrusdi** [bafolts/terraforming-mars#504]
How to reproduce:
1) Add an animal card with resources on it to the player's played cards list
```     
const fish = new Fish(); 
fish.resourceCount = 3; 
first.playedCards.push(fish); 
```
2) Add Virus to to the player's hand
3) Play Virus
It removes 2 animals from the Fish card without any questions

We need either provide an option to not remove the animals, or to not consider player's own cards as Virus target

**Comment by FreeLikeGNU** [comment]
I would like the option of cancelling the action of any card with an intermediate step (such as placing a tile or removing/adding tokens) since these cannot be undone if they happen on the last action of the player.

**Comment by thenewjuniorexecutive** [comment]
Playing without removing anything useful with Celebrity, or InterCin, Media Office or Media Archives (w/ discount). 

Only case I can imagine for removing your own is against a protected Predators.

**Comment by bafolts** [comment]
This card and most other cards make an assumption as to how the card would be played. This is an attempt to remove options a player would most likely never take such as removing plants or animals from themselves. For simplicity I would not consider the player's own cards and add an additional `OrOptions` where someone can play it on themselves removing zero animals or plants. There are a variety of rare reasons you may want to do this and no reason we should prevent it. Adding the final `OrOptions` will avoid having to display all of your cards when you are not going to remove anything. I would name the option `Use on self` or something similar.
