### ISSUE TITLE
Solo play last generation is not playable

### ISSUE THREAD

**Issue by vincentneko** [bafolts/terraforming-mars#51]
Solo game should end at the end of  generation 14 (or 12 with prelude), not at the beginning

**Comment by bafolts** [comment]
Before going to the production phase is where the check for `gameIsOver` is called.

https://github.com/bafolts/terraforming-mars/blob/master/src/Game.ts#L339

This seems right to me.

**Comment by vincentneko** [comment]
My bad, you are right, this is working fine.
