### ISSUE TITLE
Feature request: Pass confirmation

### ISSUE THREAD

**Issue by Carcassonner** [bafolts/terraforming-mars#510]
In the last game, I accidentally made a pass in the first move. The checkbox is Automatically set to "Pass". To avoid this, you can make the pass confirmation window dropdown if you haven't played any action on the card, or you still can play one of the cards in your hand.

**Comment by bafolts** [comment]
Either creating a confirmation dialog asking the user if they are sure they want to pass or never defaulting the options to "Pass" would make sense to me. Never defaulting the options to "Pass" would be less work than introducing a confirmation dialog and would be less clicks required to play through a game.

**Comment by FreeLikeGNU** [comment]
This has happened to me as well, mostly when using an android tablet.  I would prefer the "Pass" action not be default.

**Comment by gomfunkel** [comment]
Same. Not making _Pass_ the default would totally suffice. Confirmation dialogs or similar add too many clicks. This is related to #360 imho.

**Comment by nwai90** [comment]
@bafolts Noticed some minor bugs with certain cards; can I submit a PR to address them? And also set "Pass" to always be the last option as per https://github.com/bafolts/terraforming-mars/issues/360#issuecomment-604305330

**Comment by nwai90** [comment]
Can we close this? Identical to https://github.com/bafolts/terraforming-mars/issues/903

**Comment by alrusdi** [comment]
I think so.
