### ISSUE TITLE
Undo action doesn't work

### ISSUE THREAD

**Issue by alrusdi** [bafolts/terraforming-mars#511]
How to reproduce:
1) Start 2 player game (both with Beginner corporation)
2) Play **Power plant** stadart project as first player action
3) Do Undo Turn 

As result game crashing with error message like this:
```
/src/database/SQLite.js:28
var gameToRestore = JSON.parse(row.game);
                                               ^
TypeError: Cannot read property 'game' of undefined
```

**Comment by alrusdi** [comment]
@pierrehilbert can you check it?

**Comment by pierrehilbert** [comment]
Yes, we had the same problem yesterday night and I just found the root cause.
I'm patching it right now.

**Comment by FreeLikeGNU** [comment]
Played Research Outpost as first player of generation, placed tile and then used Undo action.  The tile was removed, card and MC/steel returned but I lost my turn, second player of generation then played.

**Comment by pierrehilbert** [comment]
Will take a look!

**Comment by FreeLikeGNU** [comment]
two player, prelude, hellas map, no draft. I think this was second or third gen.

**Comment by pierrehilbert** [comment]
Okay, I found it! The problem was that I saved the game after the research phase and it's not working the same way.
I found another solution, I will make a PR in few minutes.

**Comment by alrusdi** [comment]
Fxd. Thank you!
