### ISSUE TITLE
No special tile displayed on the board

### ISSUE THREAD

**Issue by alrusdi** [bafolts/terraforming-mars#52]
I forgot to implement this when i did the board rework. Will fix it asap. Need this issue to reference it in branch name and commit messages... Can i please about write permissions to main repository?

**Comment by bafolts** [comment]
You don't need an issue to reference for branch name and commit messages. I have been adding an issue link as a nice to have if someone else created the issue. Before I add write access I want to make sure the webhooks are running that require everyone to need a pull request approved prior to merging with `master`.
