### ISSUE TITLE
Intuitive UI

### ISSUE THREAD

**Issue by Carcassonner** [bafolts/terraforming-mars#522]
I used to play one online version of Terraforming Mars, where the games lasted no more than an hour for three players.
The key acceleration of the game process there was that there were no confirmations of actions at all. After clicking on the card, it was immediately played, and after clicking on the blue card, a selection of options was immediately provided. This version had its drawbacks, but it was really very fast

Now to perform any action other than "End turn" and "Pass", you need to make at least 3 clicks. You can reduce clicks by 1-2 for most actions if you do the following:

After clicking on one of the blue cards with actions, the window for performing the action of this card with the additional "Undo" option is automatically displayed.

After clicking on the card from the "Cards in hand" list, the "Play a project card" option is automatically selected and a window for selecting card payment appears. To do this, you probably need to divide the cards that are available for playing now and the others in the interface.

**Comment by pocc** [comment]
I'm not sure what you're asking for here, and the UI has changed dramatically since then. Can you please verify that this is still something that is missing from this web app?

**Comment by kberg** [comment]
Closing due to age and lack of response. Feel free to respond if reopening is warranted.
