### ISSUE TITLE
Colonies Interface Improvement

### ISSUE THREAD

**Issue by thenewjuniorexecutive** [bafolts/terraforming-mars#524]
1. There's no easy way to see who has extra fleets, besides searching through everyone's cards.  Possible to add a "landing pad" area that shows fleets that are yet to fly that generation?
2. To save scrolling, is it possible to display just the trade track (including at least player's colony cubes, current position, and next position) next to each available colony in the "Trade with a colony" and Titan Floating Launch Pad menus?

**Comment by ssimeonoff** [comment]
1. An easy option is to display it like that: 
We see that Red has traded and has no more trading fleet, while Green and Blue has 1 and 2.
![fleet](https://user-images.githubusercontent.com/6917565/78118274-1094c600-7407-11ea-829d-f58baa22393d.png)

- on the row "Colonies" display the remaining fleet (so no height is lost)
- use fleet icons (there are many free and nice "paper plane" icon on flaticon.com)
- optional: use different icons for the different colours for extra eye candy 

2.  Why not the whole colonies? 
When choosing to play a card, you get a list of possible cards  to play and you need to select one.
Thus same logic: 
When choosing to trade, to get displayed colonies (as the cards are displayed, not just a plain text list) and then selecting one.

**Comment by thenewjuniorexecutive** [comment]
Maybe use a compacted version of the colony tile? Most of the information lives in the bottom third of the tile.

**Comment by ssimeonoff** [comment]
- Option 1: transform scale them down
sccale(0.6) will make them approximately as wide as the card: 
![colonies2](https://user-images.githubusercontent.com/6917565/78341484-17067780-7598-11ea-8779-0dfe66a43e70.png)

- Option 2: Redesign the tiles in more horizontal manner
![colonies](https://user-images.githubusercontent.com/6917565/78341534-2d143800-7598-11ea-9fa3-a5cf695f99ee.png)

- Option 3: Redesign the tiles in even more horizontal manner combining them in a table:
![colonies3](https://user-images.githubusercontent.com/6917565/78341611-474e1600-7598-11ea-8a09-dcde8539ab4d.png)

- Option 4: Let them be  ¯\_(ツ)_/¯

**Comment by thenewjuniorexecutive** [comment]
I'm good with option 4 for the current colonies display, but like 3 if it's added to the trade with colony menu item.

**Comment by pierrehilbert** [comment]
@ssimeonoff : is this issue still relevant or could we close it?

**Comment by ssimeonoff** [comment]
1. is done , 2. is not but the ticket can be closet
