### ISSUE TITLE
Bug: Several wild tags do not work correctly

### ISSUE THREAD

**Issue by Carcassonner** [bafolts/terraforming-mars#528]
Having 6 different tags and 2 wild tags I still couldn't claim diversifier.
Also, I couldn't play an advanced ecosystems card with one of the 3 different required tags and 2 wild tags

**Comment by bafolts** [comment]
This was closed with the diversifier milestone update but I plan to also address the issue with the advanced ecosystems card prior to closing this bug.

**Comment by bafolts** [comment]
I can't recreate the issue reported with advanced ecosystem and looking at the source I would assume one of the non wildcard tags was on an event card.
