### ISSUE TITLE
Bug: Wild tags are considered tags at the end of the game.

### ISSUE THREAD

**Issue by Carcassonner** [bafolts/terraforming-mars#534]
In my last game, wild tags were considered Jupiter tags and my opponent got more points for the Ganymede Colony, Water from Europe and Io. 

Wild tags should not be considered any tags at the end of the game. (maybe they can count as building or space tags for awards too)

**Comment by FreeLikeGNU** [comment]
Apparently they should only count during the owning players taking an action, otherwise they are nothing according to this thread:

https://boardgamegeek.com/thread/2030851/article/29611733#29611733

**Comment by bafolts** [comment]
I agree this doesn't make sense to use for tags which count Jupiter tags for victory points. This wild card thing seems it is going to be an ongoing source of confusion. We should keep this bug isolated to use cases where the tag is counted for victory points for Jupiter tags.
