### ISSUE TITLE
Make overview and game home more colorful

### ISSUE THREAD

**Issue by FreeLikeGNU** [bafolts/terraforming-mars#537]
- Add names and colors of players with links to games in overview
- Provide player colors in game home

see PR: https://github.com/bafolts/terraforming-mars/pull/536

![Screenshot_2020-04-02_14-37-52](https://user-images.githubusercontent.com/674095/78302934-a0fb0580-74f0-11ea-9b04-f69f4d4f69a9.png)
![Screenshot_2020-04-02_14-38-46](https://user-images.githubusercontent.com/674095/78302936-a35d5f80-74f0-11ea-8ebb-e3023b992b88.png)

**Comment by alrusdi** [comment]
This is merged. Thank you for contribution
