### ISSUE TITLE
Activating the "play project card" action automatically when selecting a card.

### ISSUE THREAD

**Issue by FreeLikeGNU** [bafolts/terraforming-mars#538]
During a players turn, clicking on a card in hand should automatically select the "play a project card" action if the card can be played.   Eventually we could make the "cards in hand" replace the seperate playable cards to make the UI more compact.

**Comment by ssimeonoff** [comment]
This should be thought through first. 
If this is the case, then it can be claimed, that played Active Action cards should be clickable triggering.

One of my first thoughts during the first play was exactly that, but after few plays, the simplicity of :
> the actions menu options list the secondary available options.
> Cards in Hand and Played Cards are simple static lists 

felt much better.

The UX is the Steam game is the same:  You don't see you cards in hand unless you click them.

What is missing before clicking the "Play card" is to know how many cards you have and how many you can play of them.

Example: 
Even before selection an action, it can be seen:

> how many cards are in hand
> how many of them can be played

When the action "Play card" is selected, show the full cards hand, but disable the cards that cannot be played
![Untitled](https://user-images.githubusercontent.com/6917565/78360327-e97cf680-75b6-11ea-8074-066089402ef4.png)

If: 
- "Play card" action should be last in the list (so when the big list of cards appear not to cut the list of actions, as in the screenshot above)
- "Play card" action can be preselected (so the cards will be visiable even with a click)
- "Cards in hand" list is removed ("Play card" action already lists the full cards hand)

The outcome will be identical to what @FreeLikeGNU desires, but done the other way around:
"Cards in Hand" is removed and "Play Card" lists all cards in hand.

**Comment by FreeLikeGNU** [comment]
Simeon, thank you for illustrating this. 

As a personal preference, I'd like cards in hand to be visible even when not selecting a card to play, but perhaps this would make a preference selection for "Show/Hide Cards in Hand"  all the more useful to override if desired.  
I do agree that the play card action should be at the bottom and not disrupt the other action options and number of cars playable/total shown. 
Dimming cards not playable is fine with me as long as readability is not affected too much, maybe it can go full bright on hover?
