### ISSUE TITLE
Magnify cards and/or descriptions on hover to make them easier to read.  Toggle from preferences.

### ISSUE THREAD

**Issue by FreeLikeGNU** [bafolts/terraforming-mars#549]
Please see PR: https://github.com/bafolts/terraforming-mars/pull/556
Card and / or description magnification on hover combined with user select-able preferences (also available on initial card selection)

![Screenshot_2020-04-04_11-39-30](https://user-images.githubusercontent.com/674095/78458864-7a140f00-7669-11ea-987a-b20dc933abe5.png)

![Capture+_2020-04-05-13-15-03](https://user-images.githubusercontent.com/674095/78509006-ce89be00-773f-11ea-9bb4-252c4a5c5b4e.png)

**Comment by FreeLikeGNU** [comment]
Is there a reason to block this accessibility feature?

**Comment by vincentneko** [comment]
As long as this is an option you need to activate I dont see any reason to block this.

**Comment by FreeLikeGNU** [comment]
Thank you!
