### ISSUE TITLE
Copyedits

### ISSUE THREAD

**Issue by thenewjuniorexecutive** [bafolts/terraforming-mars#551]
Solo win screen: "Try to win faster then last generation comes" should be "Try to win before the last generation comes"

Log: "aquafier" standard project should be "aquifer"

In the Create New Game screen: "Use Solar Phase Option" should this be "Use World Government Option"? The rest of the Solar Phase should still happen with Colonies (or Turmoil.)

**Comment by alrusdi** [comment]
I will fix it after merging of this PR https://github.com/bafolts/terraforming-mars/pull/553 to have less conflicts.

**Comment by alrusdi** [comment]
Aquifer, solo win screen fixed.
I don't get ides about Solar Phase. It seems to be okay

**Comment by thenewjuniorexecutive** [comment]
Thanks. With all expansions, Solar Phase consists of Game End Check, World Government Terraforming, Colonies Maintenance, and Turmoil. Only WGT is optional. On the one hand "Use Solar Phase Option" sounds like you're turning the entire solar phase on and off, on the other hand, turning WGT on and off is the only optional thing in the Solar Phase, so I guess it's the Solar Phase Option.
