### ISSUE TITLE
A way to show every card in all decks on a single page as they are rendered in the game?

### ISSUE THREAD

**Issue by FreeLikeGNU** [bafolts/terraforming-mars#552]
If this already exists, forgive my ignorance.  This would be nice to help fix tricky card formatting issues.

**Comment by alrusdi** [comment]
No it doesn't exist. And it would be a great debugging feature. Can you implement it?

**Comment by FreeLikeGNU** [comment]
These are some things that could be handy should there be some interactive debug mode, this could also be a nice tool for learning the card interactions, other game mechanics, and creating tutorials, demos, game and card variations, expantions etc.

- [ ] Would exist as a special solo game available only from the server admins games overview
- [ ]Setup phase player can chose from any corporation, two of any of the preludes and have all other playable cars available. In this setup, all cards in game can be seen.
- [ ] Player starts game with chosen corp and preludes all player cards available
- [ ] Tags, resources and productions of both player and neutral are easily added or removed
- [ ] The "neutral" player would have a counter that could show the number of resources or production removed if that would occur.

**Comment by ssimeonoff** [comment]
Plan B:  Implement custom rules: 
a) number of starting corporations
b) number of starting project cards

When we play we do: a) 4
When I debug I do: b) 200

Both changes were super easy to do.

**Comment by FreeLikeGNU** [comment]
I really like the idea of adding some more custom rules such as number of: starting corporations, starting project cards and prelude cards!

**Comment by kberg** [comment]
This is implemented. See http://terraforming-mars.herokuapp.com/debug-ui
