### ISSUE TITLE
IMPORTED NUTRIENTS card -- tag problems

### ISSUE THREAD

**Issue by MuadDib90** [bafolts/terraforming-mars#5717]
Please include:
1. A clear and concise description of the bug.
2. Clear steps to reproduce, and the expected behavior.
3. Any screenshots
4. Any information from  the Bug Report Dialog

Hi,

after playing "Imported Nutrients" card, it should add an "Earth tag" to your "tag collection". But this card didn't do that for me.
So my guess is, the card itself either doesn't have the information about Earth tag, or there is something missing in the code that tells to add the tag.

<details>
<summary>Screenshots</summary>

![01](https://github.com/terraforming-mars/terraforming-mars/assets/73436978/d368a4d6-c493-4669-83a0-11ed1d489b35)

![02](https://github.com/terraforming-mars/terraforming-mars/assets/73436978/c462503c-a2c4-45a2-8178-53d833527da7)

</details>

Tomas

**Comment by kberg** [comment]
Link to the game, please?

**Comment by MuadDib90** [comment]
Well, this could be a problem, as I already closed the panel with it... assuming the screenshots would be sufficient evidence to see into the code.

**Comment by kberg** [comment]
Sorry, I need the information from the "Any information from the Bug Report
Dialog" step.

**Comment by MuadDib90** [comment]
Hmm, I forgot this one. My apologies!

But I was able to recover a link from endgame screen, if this can be of any help...

https://terraforming-mars.herokuapp.com/the-end?id=p3ea9044c0a19

**Comment by Borbarad2** [comment]
This is not a bug! Imported Nutriens is an event card, thus the tags a re not counted to the tag collection.
No bug.
