### ISSUE TITLE
Feature Request: Inspect all cards played by all players in game end screen

### ISSUE THREAD

**Issue by lostgrail** [bafolts/terraforming-mars#576]
It is sometimes interesting to see all the cards (not just the ones that gave points) that your opponent(s) played.

Basically, just the same interface you have during the game to see other players’ cards played, but available in the Game End score screen.

Thank you! This has been a great way to keep in touch with friends!

**Comment by alrusdi** [comment]
I've decided to provide a possibility to see any player's page from final screen. Now player names in final results table will be clickable

**Comment by lostgrail** [comment]
That sounds perfect

**Comment by alrusdi** [comment]
Merged
