### ISSUE TITLE
Browser notifications

### ISSUE THREAD

**Issue by vincentneko** [bafolts/terraforming-mars#58]
It would be great if the game could push a browser notification when it's our turn to play in a multiplayer game

**Comment by bafolts** [comment]
Can this be closed since https://github.com/bafolts/terraforming-mars/pull/111 was merged?

**Comment by vincentneko** [comment]
It was working for Alrusdi but not for me, and it requires a https server, which I don't have.
I think it's working fine anyway so let's close it and if some problems arise, we can open a new issue
