### ISSUE TITLE
OnHoover working only if "magnified"

### ISSUE THREAD

**Issue by rzulian** [bafolts/terraforming-mars#583]
It looks like that you cannot see a card if the "magnify card on hoover" is not selected

**Comment by alrusdi** [comment]
@rzulian Can you please give us more details about it? Screenshot may be?
I see problems **Interplanetary Trade** and **Interplanetary Trade** cards, but everything else seems to be working with any combination of options

**Comment by FreeLikeGNU** [comment]
fixed see PR
![Screenshot_2020-04-08_07-42-05](https://user-images.githubusercontent.com/674095/78797558-b5b22000-796c-11ea-89f4-49b407f52d3e.png)

**Comment by rzulian** [comment]
Thanks!
