### ISSUE TITLE
Other player details window needs a freshening

### ISSUE THREAD

**Issue by FreeLikeGNU** [bafolts/terraforming-mars#599]
See PR #598
I removed the difficult to use (on mobile) close button so the window will just close if clicked.
Made it more clear which player is being view with color cues.
![Screenshot_2020-04-09_09-37-13](https://user-images.githubusercontent.com/674095/78919754-39d8d600-7a47-11ea-9cb9-923210bd3617.png)

**Comment by alrusdi** [comment]
What a problem with the button on mobile? Just checked it and it seems to be working just fine. Is it too small? I can make it larger for small screens

**Comment by FreeLikeGNU** [comment]
It works ok on a desktop browser.  I play on a tablet and found it a difficult target.  A larger button is the whole window.  I could try a hot border if we are getting too many false positives or confusing to players.

**Comment by alrusdi** [comment]
It's okay also in mobile browser.
But  i don't against your proposal. A want you to show close button but close window by clicking anywhere. Button it is just visual hint about possibility to hide window

**Comment by FreeLikeGNU** [comment]
ah I already restored button functionality I'll try the larger button for now.

**Comment by alrusdi** [comment]
Merged

**Comment by FreeLikeGNU** [comment]
thanks!
