### ISSUE TITLE
Payment UI

### ISSUE THREAD

**Issue by FreeLikeGNU** [bafolts/terraforming-mars#607]
One thing that bugs me is paying with resources other than MC on a touch screen.  Repeated tapping often zooms the browser view.   I am working on a way to reduce the clicking involved with payment.
Numeric buttons are limited to the minimum of player resource available or cost (whichever is less).

![Screenshot_2020-04-10_18-06-07](https://user-images.githubusercontent.com/674095/79031840-bc03f000-7b56-11ea-9d9c-10728571c994.png)

**Comment by alrusdi** [comment]
Please make it as dropdown list by long tap, or make it optional.

**Comment by ssimeonoff** [comment]
You are trying to solve one problem by introducing another :)

It is recommended that mobile buttons should not go under 44x44px and with spacing between not going under 10px, to ensure normal user interaction with the interface. 
The chance for a misclick on those 0-9 buttons is higher than the success and the use will have to use the again the +/- buttons to recover.

Check: https://developer.mozilla.org/en-US/docs/Web/CSS/touch-action
I think by simply adding 
`.btn {
touch-action: manipulation; }
`
 should solve the problem.

**Comment by FreeLikeGNU** [comment]
I like this, Simeon.  Disabling click to zoom for the buttons would help a lot for the current +/- input system!  I will also look into making the input as a drop down as alrusdi suggested.  

In testing these buttons act as a kind of ribbon with detents which I liked, even though they were small.  They put absolute amounts in the field so even a mis-tap is easily corrected by sliding to either side a bit.  The +/- buttons were left in because some folks prefer that.

**Comment by vincentneko** [comment]
With recents improvements to the How to pay part, is this issue still relevant ?

**Comment by FreeLikeGNU** [comment]
Closing this due to lack of interest.
