### ISSUE TITLE
Bug: Error when trying to remove plants

### ISSUE THREAD

**Issue by A-Camp** [bafolts/terraforming-mars#615]
When playing "Small Asteroid" and trying to select plants to remove from other plays an error message for the input pops up reading `add.resourcesRemovedThisGenerationByPlayer.add is not a function`.  It is then impossible to get past this screen as the error can't be resolved but the player cannot undo playing the Small Asteroid card from the promo deck. However - every time a player tries to click save it does remove the greenery from other players. Allowing all of another players accumulated greenery to disappear while not allowing the person who played the card to advance the game.

**Comment by vincentneko** [comment]
This should be ok now
