### ISSUE TITLE
Bug: playing law suit card crushes the game

### ISSUE THREAD

**Issue by Carcassonner** [bafolts/terraforming-mars#619]
Unfortunately, I did not fix the error. The player who played this card got an endless turn. After clicking the "End turn" button, the turn was not transmitted and he continued to perform actions, and after his pass, the game broke. 

Also, probably, Law Suit gives +1 point, and not -1 point to the person to whom it should be transferred.

**Comment by vincentneko** [comment]
Thanks for the feedback. We have another PR that this time should fix this.

**Comment by alrusdi** [comment]
This should be fixed now.
