### ISSUE TITLE
Land claim marker disappears

### ISSUE THREAD

**Issue by ap3h3ad** [bafolts/terraforming-mars#623]
After some genereations due to unknown circumstances the marker that appears on a field marked with _Land Claim_ disappears and actually lifts the restriction so that everybody can build there after that (so it's not just a graphics bug).

**Comment by bafolts** [comment]
Did you observe the `Land Claim` first disappear and then on a subsequent turn a player played something there? For this to happen we would have had to set the player to `undefined` of a space. Did anyone undo an action at some point?

**Comment by ap3h3ad** [comment]
Hi.

This bug occured to us one time before but we thought it's fixed. On the other occurance I got feedback from my oppnents (as the one that played the Land Claim) that they technically could place something there were the Land Claim marker was.

**Comment by bafolts** [comment]
I would be surprised if we were somehow removing the land claim but I would not be surprised if in one of our cards or standard projects we are forgetting to include the land claim when you select a space. I will look through all of the select space and see if we forgot to include land claim somewhere. The user interface may also appear as if you can select the space but the server would most likely error if you tried to select that space.

**Comment by ap3h3ad** [comment]
Ok, we got a little insight into this:

Another user used the undo button and this not only deleted the Land Claim AND also all markers from the Arcadian Communities corporation.

**Comment by pierrehilbert** [comment]
It was a problem with the undo action.
I corrected it.
