### ISSUE TITLE
In solo game: using WGT to get bonus ocean, shows cards to buy early

### ISSUE THREAD

**Issue by thenewjuniorexecutive** [bafolts/terraforming-mars#624]
Solo game
Eight oceans out
Used WGT to raise temp from -2 to 0 at end of gen 11
Was given four cards to buy
Was then prompted to place the bonus ocean

The bonus ocean should be placed before anything happens in gen 12

**Comment by vincentneko** [comment]
@bafolts I think one of your commit fixes this, can you confirm ?

**Comment by bafolts** [comment]
Yes, this was closed by #657
