### ISSUE TITLE
Moring Star Inc. Requirement Bug

### ISSUE THREAD

**Issue by B0Bftl** [bafolts/terraforming-mars#627]
Hello,

I came across a bug while playing with Morning Star Inc.
I wanted to play "Spin-Inducing Asteroid" When Venus scale was at 12. Should be fine with the Corporate Ability, I wasn't able to play the card though. I did have enough gold and the card in hand.

![GameState](https://user-images.githubusercontent.com/9283154/79563066-5ced3080-80ac-11ea-8e10-8058eee29d0b.png)
![PlayProjectCard](https://user-images.githubusercontent.com/9283154/79563079-64acd500-80ac-11ea-82d8-0ed44555b4dd.png)

**Comment by alrusdi** [comment]
Thank you for reporting. It should be fixed now
