### ISSUE TITLE
Show cards ownership for actions

### ISSUE THREAD

**Issue by alrusdi** [bafolts/terraforming-mars#629]
When you do an action involving more than one card to add resources to it is hard to differ your cards from opponent cards. It is error prone behavior. We should show cards ownership in this case.

**Comment by vincentneko** [comment]
You should no be able to put resources on an opponent card, only remove.
If there is as case where we can do this, please let me know.

**Comment by alrusdi** [comment]
Modified task description

**Comment by nwai90** [comment]
@alrusdi Suggestion: What if we simply sorted the list of available targets to put the active player's cards last? So that opponents' target cards will always be the default selection

**Comment by alrusdi** [comment]
Sorting targets by owner is musthave, but we need some kind of marker on "your" cards too.

**Comment by samyelias** [comment]
> You should no be able to put resources on an opponent card, only remove.

Even when removing, it would be nice to see ownership. I've had Predators and been presented with my own Birds card as an option (as well as the opponent's animal card, properly ordered first).

**Comment by funkybaboon** [comment]
+1 for this. Just had a generation 9 game with Predators and I was presented with ~eight cards to remove animals from. I had to look through my opponents cards to see which card belong to whom.

**Comment by kevinb9n** [comment]
Thought I'd just mention that this is nearly the top-voted issue in #vote-for-issues and, more importantly to everyone here, at precisely the approximate time @funkybaboon commented above did my younger daughter very nearly Ants her own Tardigrade. An Incident, capital "I", I can tell you – but for the grace of God – and with her dawning of stomach-churning comprehension, as she countenanced the hideous magnitude of that betrayal she had all but wrought on these noble, hardy, yet ultimately mortal creatures, came forth a simple question.

The right question.

Would it, Dad? Would it have LET me do it?

The chin resolved. The tears, nay, not falling. Not falling. Only gathering, preparing.

And a father, taking the only path he sees left to him. No, honey, was my reply. Please. Please do not worry. Why, sweetheart, *it knows you are not a monster.*

#plusone #afathersplea #wontsomebodythinkofthechildren #didntreallyhappen #exceptitdid
