### ISSUE TITLE
Incorrect Colonies cards effect

### ISSUE THREAD

**Issue by alrusdi** [bafolts/terraforming-mars#630]
"Trading Colony" effect increases Colony Tile track  without asking, but text on cards states: "**you may** first increase that Colony Tile track 1 step"
We should also check "Trade Envoys" for the same effect

If it is acceptable behavior we should visualize it somehow.

**Comment by vincentneko** [comment]
I guess it is acceptable behaviour. I do not see any situation where having less resources than expected  with this card is beneficial.

**Comment by alrusdi** [comment]
ok, we can live with this

**Comment by vsrisuknimit** [comment]
Not sure if we can reopen the issue. Trade Envoy and Trading Colony should offer an option when trading with Europa colony. There are some situations where getting energy production is preferable to getting plant production.
