### ISSUE TITLE
Robotic Workforce works incorrecltly with Preludes

### ISSUE THREAD

**Issue by alrusdi** [bafolts/terraforming-mars#631]
In our game player played Robotic Workforce and choose "Doom farming" prelude to copy production  from. But also got production from another his prelude (Aquifer turbines)

**Comment by vincentneko** [comment]
This one is strange. Prelude are handled the same as other cards.
Can you please try to reproduce ?

**Comment by pierrehilbert** [comment]
I had an issue with Dome Farming and Robotic Workforce: only got the plant production but didn't get the megacredit part.

**Comment by pierrehilbert** [comment]
I corrected it.

**Comment by vincentneko** [comment]
Both Dome Farming and Self Sufficient Settlement are bugged, they give Energy Production instead of M€.
Dome Farming is fixed but only in prelude branch, a PR is on the way to fix this.

**Comment by vincentneko** [comment]
Fixed and merged
