### ISSUE TITLE
Bug: Ecological Zone card enters the game with the wrong amount of resources

### ISSUE THREAD

**Issue by Carcassonner** [bafolts/terraforming-mars#633]
In today's game, the card entered the game with 4 resources instead of 2.
It may be counting previously played plant/animal tags (after entering Ecological zone, I had 4 of them in total)

**Comment by alrusdi** [comment]
It is not easy reproducible. @Carcassonner can you provide more details? If game has been played on my server then game id will be good enough
Also it may not count wild tags. I don't sure if it is correct behavior.

**Comment by Carcassonner** [comment]
https://tm.alrusdi.ru/game?id=2971682b5706
This effect should not apply to wild tags, and should not be applied to previously played tags.

**Comment by alrusdi** [comment]
Steps to reproduce:
1) Play Viral Enhancers
2) Play Ecological Zone
You will get either  2 plants or 2 animals
Expected to get either 2 plants or **ONE** animal

**Comment by thenewjuniorexecutive** [comment]
Viral Enhancers can also place two animals on Eco Zone

**Comment by Carcassonner** [comment]
By Viral Enhancerss, you get a plant for a plant tag and an animal/plant for an animal tag. Only animals accumulate on the "Ecological zone" card

**Comment by thenewjuniorexecutive** [comment]
Viral Enhancer's text "Effect: When you play a plant, microbe, or an animal tag, including this, gain 1 plant or add 1 resource to THAT CARD"

So you get a resource on the played card or a plant for each trigger of Viral Enhancers. There is no restriction that the resource gained must match the tag played. It's just that this is the only plant tag on a card that holds resources (and there are no animal tags on cards that hold microbes or vice versa.) Once it's added to the "stack", the trigger of VE should not care what type tag it was triggered by, only whether the card holds resources.

This is the best source I can find for this, there's no like from Jacob on this summary, but there was no disagreement from anyone: https://boardgamegeek.com/thread/2091170/article/30459429#30459429

**Comment by Carcassonner** [comment]
Ok, I agree. In this case, the "get 1 animal and 1 plant" option is missing.

**Comment by bafolts** [comment]
What I plan to implement for this is allowing the user to select what bonus they want to apply for each tag. If they have 2 tags they will select what to apply twice. The solution we have in right now where we assume the user wants all the bonus to go to the same place was mostly for efficiency and it was before we had the interrupt system in place which makes this easier to implement.

**Comment by vincentneko** [comment]
Is this issue still relevant ?

**Comment by bafolts** [comment]
I thought this was still relevant for Ecological Zone but it isn't.
