### ISSUE TITLE
Price wars

### ISSUE THREAD

**Issue by theeagle1968** [bafolts/terraforming-mars#6395]
Currently playing a game using the Underground expansion.  Price wars was played in Gen 8. It's Gen 10, and it's still in effect.

**Comment by kberg** [comment]
Link to the game please?

**Comment by theeagle1968** [comment]
https://terraforming-mars.herokuapp.com/player?id=pf1cfb6ba84c4Sent from my Galaxy
-------- Original message --------From: Robert Konigsberg ***@***.***> Date: 2024-02-06  1:01 a.m.  (GMT-06:00) To: terraforming-mars/terraforming-mars ***@***.***> Cc: theeagle1968 ***@***.***>, Author ***@***.***> Subject: Re: [terraforming-mars/terraforming-mars] Price wars (Issue #6395) 
Link to the game please?

**Comment by theeagle1968** [comment]
Previous link was my active game. Here is the spectator link if that's better. https://terraforming-mars.herokuapp.com/spectator?id=s5cdd1c4ed5acSent from my Galaxy
-------- Original message --------From: Robert Konigsberg ***@***.***> Date: 2024-02-06  1:01 a.m.  (GMT-06:00) To: terraforming-mars/terraforming-mars ***@***.***> Cc: theeagle1968 ***@***.***>, Author ***@***.***> Subject: Re: [terraforming-mars/terraforming-mars] Price wars (Issue #6395) 
Link to the game please?

**Comment by kberg** [comment]
Thanks. I see what's wrong now.
