### ISSUE TITLE
Two Bugs. Hackers and Miranda 

### ISSUE THREAD

**Issue by Marhabal** [bafolts/terraforming-mars#648]
1) Miranda. Played animal card with prelude. Aridor then added Miranda. Contrary to rules Miranda did not activate for almost the entirety of the game despite there being an animal card in play. Its an odd situation, I know, but I guess there was no check at the end of the turn to activate the colony.

2) Two player game. Played hackers on an opponent with -1 MC. It would not allow me to lower his MC and in fact forced me to lower my own MC :(, in effect creating a net 0 MC prod gain for the card player, in addition to the -1 VP and -1 energy Prod. I guess the card checks for 0.

**Comment by Marhabal** [comment]
Just to clarify because I realize i worded this funny. 1) The animal card with the prelude had resources 2) "Miranda did not activate for almost the entirety of the game" - Miranda only activated when a second animal card with resources was played.

**Comment by Marhabal** [comment]
And thanks for this awesome project !!!

**Comment by vincentneko** [comment]
PR incoming for second issue

**Comment by vincentneko** [comment]
Second issue is fixed.

**Comment by vincentneko** [comment]
Fixed and merged
