### ISSUE TITLE
Universal endpoint for assets and styles cleanup

### ISSUE THREAD

**Issue by alrusdi** [bafolts/terraforming-mars#65]
It's getting necessary to make a webpack task to build styles.css from a bunch of smaller files in src/css directory. It should help us to have less merging conflicts and better separate modules.

What do you think? 

Also it is boring to add new item to pngs variable each time we want to use new image. Can i do universal endpoint to serve all the assets (including favicon, styles.css and everything from assets directory)?

**Comment by vincentneko** [comment]
About universal endpoint, I tried once but it was leading to a security issue that allowed to navigate server file structure beyond assets directory.
I agree it could be great to have this.

About the css I have no idea, we can wait for bafolts feedback.

**Comment by alrusdi** [comment]
We will allow only subset of supported file extensions and check if normalized target directory is still in assets https://millermedeiros.github.io/mdoc/examples/node_api/doc/path.html#path.normalize

**Comment by bafolts** [comment]
Adding a normalized end point is fine. It is growing out of control. The early version was mostly text based so all of this CSS is expanding it.

**Comment by bafolts** [comment]
Can this be closed since https://github.com/bafolts/terraforming-mars/pull/111 was merged?

**Comment by alrusdi** [comment]
I think yes
