### ISSUE TITLE
Fonts changed since update

### ISSUE THREAD

**Issue by vincentneko** [bafolts/terraforming-mars#651]
Before:

![Screenshot 2020-05-01 07 16 23](https://user-images.githubusercontent.com/56086992/80784036-f5d77d80-8b7b-11ea-99ea-ce52506542c6.png)

After:
![Screenshot 2020-05-01 07 16 36](https://user-images.githubusercontent.com/56086992/80784048-fff97c00-8b7b-11ea-8b29-b76850ae6aaa.png)

**Comment by alrusdi** [comment]
@vincentneko are you still experiencing this issue? I can't reproduce it on recent master

**Comment by vincentneko** [comment]
> @vincentneko are you still experiencing this issue? I can't reproduce it on recent master

Yes I still have it, I've tested with my chrome in private nav, still got the issue as well.

**Comment by vincentneko** [comment]
Same on my server, I've just updated it and on heroku server. I've flushed my cache, don't know what to do next.

**Comment by alrusdi** [comment]
I will try to reproduce it. Can you check in Debug Toolbar if Prototype font is loaded and assigned to .price css class?
![Снимок экрана от 2020-05-01 12-38-05](https://user-images.githubusercontent.com/394311/80790619-ca1ebc80-8ba8-11ea-8839-d5511b13562b.png)

Is it in Google Chrome btw?

**Comment by vincentneko** [comment]
Yes, it's chrome, tested on my phone as well, got the same issue.

I also have font-family: Prototype; when I inspect price

**Comment by alrusdi** [comment]
Yeah. It's my fault again
https://github.com/bafolts/terraforming-mars/commit/42b5ee0c16095f920293e79955a58b60ce899bf0#diff-581a963bf5593c7b2a2f7f243fdc2e20L51
I will fix it ASAP

**Comment by vincentneko** [comment]
Thanks for fixing !
