### ISSUE TITLE
Bug: Prelude card let MC become negative number

### ISSUE THREAD

**Issue by Solo899815** [bafolts/terraforming-mars#655]
Before playing prelude card, if a player has no MC in the board, playing prelude card that need to pay MC will cause the MC become negative number. And the only thing you can do in round 1 is pass, even you have enough steel/titanium to play a building / space tag card.

for example: [photo link](https://drive.google.com/file/d/1vgSHJk1809uhHsWAZ-SHvf4_P4BCvPZS/view)

**Comment by Solo899815** [comment]
Forget to say: Many thanks to build up this awesome project !!

**Comment by vincentneko** [comment]
Thanks for the feedback. The link requires an authorization, can you put it somewhere else ?

**Comment by vincentneko** [comment]
I was searching for an answer but did not find one. Imho, if someone has a prelude card with some M€ decrease, if the player does not have enough M€, the card must be discarded.

**Comment by Solo899815** [comment]
> Thanks for the feedback. The link requires an authorization, can you put it somewhere else ?

How about now?

**Comment by Solo899815** [comment]
> I was searching for an answer but did not find one. Imho, if someone has a prelude card with some M€ decrease, if the player does not have enough M€, the card must be discarded.

I retry the solo mode with using "PhoboLog" as corporation. I can keep 10 cards in hand and give a -7MC at first round as a result.  Is it possible to add MC validation before start the game? (I know it need a lot of work)

**Comment by vincentneko** [comment]
Thanks for the feedback. We've just fixed prelude that could lead to negative M€, what you describe is another problem we need to solve !

**Comment by vincentneko** [comment]
I'm closing this one and opening a new one.
