### ISSUE TITLE
Self-replicating robots issues

### ISSUE THREAD

**Issue by insectman** [bafolts/terraforming-mars#664]
1) Opponents can't see the card linked with Self-replicating robots, neither does its identity get logged.
2) Interface doesn't allow to link more than one card to Self-replicating robots.

**Comment by vincentneko** [comment]
I've added a log message that will show the card used with Self-replicating robots.
For point 2, this something difficult to put in place, maybe someday...

**Comment by samyelias** [comment]
Would it be possible to add the linked card title in the same place as the Resource count for the Robots card?

An indication on the linked card when it's in your hand and in the "play projects" options would also be a useful reminder.

**Comment by vincentneko** [comment]
Fixed and merged
