### ISSUE TITLE
Birds card disallows to separate production reduction

### ISSUE THREAD

**Issue by alrusdi** [bafolts/terraforming-mars#668]
Sorry for my English. Steps to reproduce:
1) Setup 2players game
2) Set 1 player 1 plant production
3) Set second player 2 plant production
4) Try to play Birds by second player
**Result**:
Plant production of 2nd player to be reduced by 2 steps
**Expected**:
Each player production to be reduced by 1 step

**Comment by vincentneko** [comment]
Not sure about this one.
Text on the card is "Decrease any plant production 2 steps" so it seems it cannot be split.

**Comment by alrusdi** [comment]
Yes, you are right
