### ISSUE TITLE
There isn't Molecular Printing in Card-list 

### ISSUE THREAD

**Issue by morisanhf** [bafolts/terraforming-mars#670]
I found there isn't Molecular Printing in this game.

I made a draft of MolecularPrinting.ts.

I have trouble with making logic 1MC  for each city in play and for each colony in play.

https://github.com/morisanhf/terraforming-mars/blob/master/src/cards/colonies/MolecularPrinting.ts

**Comment by vincentneko** [comment]
Thanks for your feedback.

For the logic, you can check AEROSPORT TOURNAMENT and QUANTUM COMMUNICATIONS.
If you can also make a test class it would be great !

Do you want to have this issue assigned to you ?

**Comment by morisanhf** [comment]
thank you for advice!
I wanna try this issue.

**Comment by vincentneko** [comment]
Thanks for taking care of this.
Merged
