### ISSUE TITLE
Unexpected server response game crash

### ISSUE THREAD

**Issue by iamblackornot** [bafolts/terraforming-mars#674]
https://terraforming-mars.herokuapp.com/player?id=da47294789ee

3 players game, Prologue addon only

Game stopped with Unexpected server response message.

Console was being "spammed" during the game with following messages:

```
[Vue warn]: You may have an infinite update loop in a component render function.

found in

---> <OrOptions>
       <WaitingFor>
         <PlayerHome>
           <Root> vue.esm.js:629:15

[Vue warn]: Avoid using non-primitive value as key, use string/number value instead.

found in

---> <SelectHowToPayForCard>
       <OrOptions>
         <WaitingFor>
           <PlayerHome>
             <Root> 3 vue.esm.js:629:15

[Vue warn]: Duplicate keys detected: '[object Object]'. This may cause an update error.

found in

---> <SelectHowToPayForCard>
       <OrOptions>
         <WaitingFor>
           <PlayerHome>
             <Root> 2 vue.esm.js:629:15

[Vue warn]: Error in render: "TypeError: turmoil is undefined"

found in

---> <Turmoil>
       <PlayerHome>
         <Root> vue.esm.js:629:15
TypeError: "turmoil is undefined"
    anonymous https://terraforming-mars.herokuapp.com/main.js line 6226 > eval line 11667 > Function:3
    VueJS 39
vue.esm.js:1896:13
    VueJS 42
```

**Comment by alrusdi** [comment]
Unexpected server response message is happened because server was reloaded for update. See duplicate: https://github.com/bafolts/terraforming-mars/issues/659

**Comment by alrusdi** [comment]
I will try to get rid of Vue warnings - they are annoying

**Comment by iamblackornot** [comment]
haven't thought that server is updated so often, thx

**Comment by bafolts** [comment]
The app provided on heroku was always meant mostly for demo purposes. Running the app locally is straight forward enough. If you have an ongoing game I would start the service locally and then provide your other players your IP address for the time being.

**Comment by iamblackornot** [comment]
thx for a advice and all the work u and others did. the app is amazing
