### ISSUE TITLE
Poseidon was allowed to claim a colony that already had three colonies on the tile

### ISSUE THREAD

**Issue by lostgrail** [bafolts/terraforming-mars#675]
During the first turn of a game, when it came to Poseidon's turn they were given the option of putting a colony on a colony tile that was already filled with three colonies from other players.

The game then kept track of the colony (without it displaying graphically), giving the Poseidon player two credits when traded with, and resetting to 10 (meaning that Luna was providing 13 credits every turn).

The expected behavior is that because the colony is full, Poseidon will not be allowed to pick them. Then the accounting on the colony tile will be correct, and the colony tile will only have three colonies on it
![Annotation 2020-05-04 203853](https://user-images.githubusercontent.com/7331135/81026218-53ebb580-8e47-11ea-99c1-2d9f68f8da2b.png)
.

**Comment by lostgrail** [comment]
And ... thank you for this. I'm glad I finally got a chance to introduce my friends to Turmoil, and the glory that is a Complete game of Terraforming Mars

**Comment by vincentneko** [comment]
Fixed and merged
