### ISSUE TITLE
Neutral Player did not become party leader when overtaking lead

### ISSUE THREAD

**Issue by lostgrail** [bafolts/terraforming-mars#676]
The Neutral player did not become leader (display correctly?) when they had more members of a party than a player.

![Annotation 2020-05-04 235245](https://user-images.githubusercontent.com/7331135/81033653-61faff80-8e62-11ea-8275-ea963a010bb5.png)

I'm sorry, I have no idea what happened. Here is the last actions log from when I noticed this:
Tom used Psychrophiles action
Tom sent 1 delegate in Greens area
Graham sent 1 delegate in Greens area
Graham played Supported Research
Ben used Orbital Cleanup action
Ben played Breathing Filters
Chris sent 1 delegate in Greens area
Chris played Herbivores
Graham's plants production modified by -1 by Chris
Adam used Aquifer standard project
Adam used Aquifer standard project
Tom passed
Graham passed
Ben played Predators
Ben used Predators action
Tom looses 1 resource(s) on Ecological Zone by Ben
Chris used Extreme-Cold Fungus action
Chris used Thermophiles action
Adam traded with Pluto
Adam played Energy Market
Ben played Insulation
Ben played Venus Governor
Chris passed
Adam used Energy Market action
Adam used Turmoil Scientists draw action
Ben sent 1 delegate in Kelvinists area
Ben traded with Ganymede
Adam converted plants into a greenery
Adam sent 1 delegate in Unity area
Ben used Sell patents standard project
Ben sent 1 delegate in Scientists area
Adam passed
Ben passed
Adam acted as World Government and increased oceans
Tom is the new chairman and got 1 TR increase
Turmoil phase has been resolved
Generation 8
Adam bought 2 card(s)
Chris bought 0 card(s)
Tom bought 0 card(s)
Graham bought 1 card(s)
Ben bought 3 card(s)
Tom traded with Luna
Tom played Sub-zero Salt Fish
Chris's plants production modified by -1 by Tom
Graham sent 1 delegate in Kelvinists area
Graham ended turn
Ben played Penguins
Ben traded with Miranda
Chris played Luxury Foods

**Comment by pierrehilbert** [comment]
Will take a look on it today.
