### ISSUE TITLE
Terralabs cannot buy all its starting cards

### ISSUE THREAD

**Issue by thenewjuniorexecutive** [bafolts/terraforming-mars#678]
Solo with all expansions + promo cards, select Terralabs as corp + more than 4 cards, saving is stopped with a "too many cards" message. Going down to 4 cards allows you to proceed and correctly deducts only 4MC for the cards.

**Comment by vincentneko** [comment]
Thanks for your feedback, I've overlooked this. I will fix this asap.

**Comment by vincentneko** [comment]
Fixed and merged
