### ISSUE TITLE
First Round Policy should be Green

### ISSUE THREAD

**Issue by morisanhf** [bafolts/terraforming-mars#680]
In this game First Round Policy should be Green but there is no policy at First Round in this demo,
![FirstRoundPolicy](https://user-images.githubusercontent.com/64735058/81140560-ba3a1a80-8fa4-11ea-9b13-70f7df817d74.PNG)

**Comment by vincentneko** [comment]
Thanks for the feedback, you're right, as per the rulebook:

Place all six Policy tiles in a pile at their designated place on the Terraforming Committee board, with GREENS on top. They start being ruling party (read more on page 4), and their policy will be active during the upcoming action phase.

**Comment by pierrehilbert** [comment]
It's now fixed.
