### ISSUE TITLE
Venus bar appears over Turmoil board in Chrome on Macbook

### ISSUE THREAD

**Issue by thenewjuniorexecutive** [bafolts/terraforming-mars#684]
With both Venus Next & Turmoil selected in Chrome  81.0.4044.138 with Sierra 10.12.6 (16G2136) on a 1920 x 1080 display, the Venus bar obscures the Turmoil board.
![Screen Shot 2020-05-06 at 11 41 52 AM](https://user-images.githubusercontent.com/62528913/81201425-417e9280-8f93-11ea-8a3c-8cd87d1e6ec4.png)

**Comment by Marhabal** [comment]
I noticed if you "restore down" the window size slightly the turmoil board will slide below. The venus board only covers it when you have window maximized.

**Comment by vincentneko** [comment]
@alrusdi I think this one is fixed with new global design ?

**Comment by alrusdi** [comment]
yes it is
