### ISSUE TITLE
Turmoil - Greens don't rule in Gen 1

### ISSUE THREAD

**Issue by ap3h3ad** [bafolts/terraforming-mars#686]
Hi!

We've just started a new game with the turmoil expansion (thank you for implementing it!). The rules state that the Green's Ruling Policy is active in the first generation (because at that point there was no election and no party had become dominant), as stated in the rules (page 2, paragraph 4: https://www.fryxgames.se/TerraformingMars/Turmoil/TURMOIL_RULES.pdf) 

In our first generation there is no Green's Ruling Policy tile active: 

https://abload.de/img/screenshot8nj2t.png

Cheers!

**Comment by vincentneko** [comment]
This one has been fixed yesterday, please update.
