### ISSUE TITLE
End game results score error

### ISSUE THREAD

**Issue by vincentneko** [bafolts/terraforming-mars#69]
I played a 2 player game, each only created a forest.

Here is the score breakdown, there is 1 in city column and 0 in Greenery column, should be the opposite

Player | Corporation | TR | Milestones | Awards | Greenery | City | VP | Total
-- | -- | -- | -- | -- | -- | -- | -- | --
yjyj | Teractor | 21 | 0 | 0 | 0 | 1 | 0 | 22
kkk | Thorgate | 21 | 0 | 0 | 0 | 1 | 0 | 22

**Comment by alrusdi** [comment]
Please read my unittest. I believe i found an error in awards calculation too (3 points for 2nd place instead of 2)

**Comment by vincentneko** [comment]
You are right, it should be 2 points for 2nd place.
