### ISSUE TITLE
Recruitment card no neutral delegate to remove

### ISSUE THREAD

**Issue by rzulian** [bafolts/terraforming-mars#699]
In a game, you get "Select which Neutral delegate to remove", but you cannot select any delegate

<img width="519" alt="Screenshot 2020-05-12 at 15 22 42" src="https://user-images.githubusercontent.com/29941924/81696779-aee36500-9464-11ea-8202-aceda8400d81.png">

<img width="992" alt="Screenshot 2020-05-12 at 15 22 52" src="https://user-images.githubusercontent.com/29941924/81696783-b0149200-9464-11ea-84e3-8fc3e5797de9.png">

**Comment by nwai90** [comment]
@rzulian In your above screenshot, the option to remove a neutral delegate from Kelvinists should be available. Does this issue still exist? I cannot replicate it after several attempts.

**Comment by vincentneko** [comment]
I'm pretty sure this issue has been indirectly resolved.
@pierrehilbert can you check / confirm this ?

**Comment by vincentneko** [comment]
I'm closing this one, please reopen if bug still occurring.
