### ISSUE TITLE
Requirement for UrbanDecomposers isn't correct

### ISSUE THREAD

**Issue by AlexBurkov** [bafolts/terraforming-mars#700]
This line isn't correct. This card doesn't require city space on the board.
https://github.com/bafolts/terraforming-mars/blob/master/src/cards/colonies/UrbanDecomposers.ts#L18

![image](https://user-images.githubusercontent.com/12098651/81746060-841dfe80-94ae-11ea-98dd-79f05b47078d.png)

**Comment by vincentneko** [comment]
Thanks for your feedback.
This line should not be here, the check is done correctly below, must be a copy and paste error.

**Comment by vincentneko** [comment]
Fixed and merged
