### ISSUE TITLE
Server crashes

### ISSUE THREAD

**Issue by rzulian** [bafolts/terraforming-mars#702]
Hi,
it happened twice in two days that the server crashed. It looks it's the turm oil  implementation.
From the log I'm getting this

<img width="896" alt="Screenshot 2020-05-14 at 23 05 21" src="https://user-images.githubusercontent.com/29941924/81986106-8790c180-9637-11ea-80fa-ca9ac753067c.png">

I don't know how to recreate this. Last time they reported it happened for an undo move

**Comment by vincentneko** [comment]
This bug was fixed a few days ago.
Can you check if the version you're running is up to date ?

**Comment by rzulian** [comment]
I was running this aa8157d.
Trying now with the latest

**Comment by rzulian** [comment]
@vincentneko  It happend again. IS there anything I can do to help you on this?

**Comment by vincentneko** [comment]
Yes, it could be useful to have the steps to reproduce it.
Was it related to a undo ?
You can also delete your database file as there might be some corrupted games inside.

**Comment by rzulian** [comment]
Yes, it was related to the undo.
I'm running every time a fresh container, so I doubt it can be a database corruption.
The problem to replicate it is that it's crashing the machine, so I've only the log available. Any suggestions?
