### ISSUE TITLE
Arctic Algae / Giant Ice Asteroid interaction

### ISSUE THREAD

**Issue by vsrisuknimit** [bafolts/terraforming-mars#703]
In theory, the plant burning effect could happen last. The opponent could gain plants from arctic algae from the ocean placement or even the ocean bonus at 0 c first before getting their plants burned.

**Comment by vincentneko** [comment]
Thanks for your feedback.
I've reordered the interrupts for the following cards so remove plant action will always be resolved after Arctic Algae.
- ASTEROID
- COMET
- BIG ASTEROID
- DEIMOS DOWN
- GIANT ICE ASTEROID
- SMALL ASTEROID

**Comment by vincentneko** [comment]
Fixed and merged
