### ISSUE TITLE
Hi-Tech Lab (0 energy) breaks the game

### ISSUE THREAD

**Issue by vsrisuknimit** [bafolts/terraforming-mars#704]
If you decide to spend 0 energy to draw 0 card, Hi-Tech Lab as implemented will still force you to pick one card. Because there is no card to pick, the game will get stuck there with no way out.

**Comment by vsrisuknimit** [comment]
Actually, for any card that does x. x must be greater than 0 according to the game designer. https://boardgamegeek.com/thread/1958633/article/28564463#28564463

**Comment by vincentneko** [comment]
Fixed and merged
