### ISSUE TITLE
Wrong translation

### ISSUE THREAD

**Issue by AlexBurkov** [bafolts/terraforming-mars#709]
This translation isn't correct. Word "вашим" must be deleted:
У вас должно быть озеленение. Выложите этот тайл по соседству с любым тайлом озеленения. 1 ПО за каждые 2 животных на этой карте.
https://github.com/bafolts/terraforming-mars/blob/master/src/locales/ru/cards.json#L407

**Comment by bafolts** [comment]
I don't speak russian so I can't offer much help here. Our resident expert is @alrusdi

**Comment by alrusdi** [comment]
Fixed & merged. @AlexBurkov thank you for reporting
