### ISSUE TITLE
About Chinese language support

### ISSUE THREAD

**Issue by glass4pk** [bafolts/terraforming-mars#715]
Hello, could I add Chinese support version into the source code? I see an json file for putting the translations.

**Comment by vincentneko** [comment]
Hello, sure, it would be a great addition to the game.

I've created a dedicated branch for it, Chinese_translation, you can push your commits on it.

Translated files are stored in locales/lang_code/ folder.
At the moment Russian translation is the most complete, I suggest you mimic what as been done for this language.

Let me know if you need some help.

**Comment by vincentneko** [comment]
The file constants.ts need also to be updated with Chinese language

**Comment by glass4pk** [comment]
Hello,I'm now add the chinese button on it at the last pull request.
I'll them keep translate the rest of the cards.
Thank you very much

**Comment by vincentneko** [comment]
Just tested it, it looks great !
Once all translation are done we will merge in master.

**Comment by glass4pk** [comment]
Hello,I'm working on the card text translation. I'm hoping to see the effect but I found that the card list page is not local, it's link to  https://ssimeonoff.github.io/cards-list  . So could I view the translations on my local env ?  To create a new game and randomly draw card is not so well.

**Comment by vincentneko** [comment]
> Hello,I'm working on the card text translation. I'm hoping to see the effect but I found that the card list page is not local, it's link to https://ssimeonoff.github.io/cards-list . So could I view the translations on my local env ? To create a new game and randomly draw card is not so well.

You can modify Game class like this and start a solo game:

Initial version: 

```
      for (let i = 0; i < 10; i++) {
        dealtCards.push(this.dealer.dealCard());
      }
```

Updated version:

```
      for (let i = 0; i < this.dealer.deck.length; i++) {
        dealtCards.push(this.dealer.dealCard());
      }
```

**Comment by glass4pk** [comment]
Hello , I've finished the  translation by compare to ru. but still find so many sport needs to be translate.
How to add more translations into it?
Can I add more .json file to this folder, copy the strings and translate?

such as:
<img width="451" alt="need translate 1" src="https://user-images.githubusercontent.com/1888886/83003555-0e369d00-a041-11ea-91f1-a42f1a65f1b6.png">
<img width="1080" alt="need translate 2" src="https://user-images.githubusercontent.com/1888886/83003572-14c51480-a041-11ea-87cd-35a222477dab.png">

**Comment by glass4pk** [comment]
I figure out how to add Venus Cards Now, I'm working on the card translation.
But I found some UI still not be translate even I've add them into the json.

**Comment by vincentneko** [comment]
Merged from @jijiqw repo.
