### ISSUE TITLE
Suggestion: Automatically set player name if not entered

### ISSUE THREAD

**Issue by nwai90** [bafolts/terraforming-mars#721]
**Context:** Player links are not clickable if names are not entered in a multiplayer game.

**Suggestion:** Set player color as default player name if there is no input.

<img width="327" alt="Screenshot 2020-05-27 at 10 25 49 AM" src="https://user-images.githubusercontent.com/2408094/82977657-15e04c80-a015-11ea-87ec-2a4aab432e42.png">
<img width="267" alt="Screenshot 2020-05-27 at 12 20 01 PM" src="https://user-images.githubusercontent.com/2408094/82977658-17117980-a015-11ea-8e1e-04d865fa43a5.png">

**Comment by alrusdi** [comment]
Merged, thank you!
