### ISSUE TITLE
Suggestion: Minor changes for player actions list

### ISSUE THREAD

**Issue by nwai90** [bafolts/terraforming-mars#726]
1. If there is only one claimable milestone, its position in the list of player actions is not fixed due to only the milestone's name being displayed without the action's title.

**Suggestion:** Always display the same title for consistency even if there is only one milestone - it will be selected by default when the "Claim Milestone" action is clicked

<img width="593" alt="Screenshot 2020-05-28 at 1 44 13 PM" src="https://user-images.githubusercontent.com/2408094/83108918-1222f780-a0f3-11ea-9d25-05be9dadf68e.png">

<img width="488" alt="Screenshot 2020-05-28 at 2 15 11 PM" src="https://user-images.githubusercontent.com/2408094/83108930-18b16f00-a0f3-11ea-890c-9a2010a6ee6d.png">

2. "Pass" is sometimes made the default selected option under certain circumstances. Related to https://github.com/bafolts/terraforming-mars/issues/510

**Suggestion:** Always fix the terminal positions of "End Turn", "Pass" and "Undo Turn" actions, in that order.

**Rationale:** "End Turn" is usually preferable to "Pass" (e.g. for tactical stalling), and "Undo Turn" should be selected only as a last resort in the event of a misclick.

<img width="489" alt="Screenshot 2020-05-28 at 2 39 42 PM" src="https://user-images.githubusercontent.com/2408094/83109362-db99ac80-a0f3-11ea-9e41-3047cb2c219d.png">

**Comment by nwai90** [comment]
@bafolts @vincentneko Thoughts? I'm happy to submit a PR for this

**Comment by vincentneko** [comment]
This is looking great !

**Comment by nwai90** [comment]
Ok, will submit a PR for it soon. The above suggested ordering is based on my own experience while playing, wondering if others have similar/other thoughts about it
