### ISSUE TITLE
Aridor counts Tags wrong

### ISSUE THREAD

**Issue by K-Hartmann** [bafolts/terraforming-mars#727]
In my game with aridor, I  am getting an increase in mc production by playing non unique tags. Currently i am 11mc/turn higher than expected. I noticed an false increase by 1mc prod while playing Methane From Titan (allready a a space tag and a jupiter tag) and also while playing Floating Habs (had already 2 venus tags)

I added a general screenshot of the game state.
![2020-05-28_10h01_42](https://user-images.githubusercontent.com/41374984/83115129-3a4a3080-a0ca-11ea-9405-259546a24f1f.png)

**Comment by vincentneko** [comment]
I tried to reproduce this issue without success. This bug was existing in the past but has been resolved. Can you check that you run last game version ?

**Comment by vincentneko** [comment]
I'm closing this one as I'm pretty sure it's fixed on master. Please reopen if I'm wrong.
