### ISSUE TITLE
Suggestion: Increase radio button size for SelectPlayer

### ISSUE THREAD

**Issue by nwai90** [bafolts/terraforming-mars#740]
<img width="405" alt="Screenshot 2020-05-28 at 8 24 37 PM" src="https://user-images.githubusercontent.com/2408094/83322329-4b8d6b80-a289-11ea-89f7-b3292f1e20f9.png">
<img width="388" alt="Screenshot 2020-05-30 at 3 18 34 PM" src="https://user-images.githubusercontent.com/2408094/83322330-4d572f00-a289-11ea-8c4c-a6e7a3065228.png">

**Comment by alrusdi** [comment]
I will try to fix it. It is annoying indeed

**Comment by nwai90** [comment]
Thanks @alrusdi ! I tried adding `form-radio` class but the radio buttons disappeared after that

**Comment by alrusdi** [comment]
Fixed & merged
