### ISSUE TITLE
General wish list, Interface ideas and perhaps some bugs

### ISSUE THREAD

**Issue by PhantomFFR** [bafolts/terraforming-mars#749]
Foreword: I have yet to play anything different than “Solo Challenge” with Prelude, promo cards and Random Board, so all my comments are in respect to it. I play using Firefox on Windows 10, without  touch input, but with a wide screen. I also have almost no understanding of programming. But after playing Solo Challenge about 50 times in the past week, here are some repeated thought of mine. I hope it’s alright to have them all in one post rather than split up into individual posts.

-----

Interface:

Related to #360: Though I’m not concerned about the sorting of the actions, but rather the default selection of Actions. As of now “standard projects” is defaulted to, even if you have playable project cards, that would rarely be the correct choice. 
Personally I feel the default selection order should be:
0 “Buy Milestone” (Though this is more guesswork due to only playing the physical board game with other people)
1 “Converting heat” (As you likely have to think less about than when “converting plants”, though perhaps this is a good safeguard (for card requirements) to have “converting plants” first after all.)
2 “Converting plants”
3 “Perform an action from a played card” or “Play a patent”
4 “Play a patent” or “Perform an action from a played card”
5 “Standard Project”
6 “Fund Award” (Perhaps this could be ahead of “Standard Project”, but again, I have yet to play this implementation other than Solo)
7 “Pass”
8 “Sell Patents”

Related to #726 and #510, or perhaps even contrarian to #510: 
Once you are out of funds/actions, “sell patents” should not be the default action, you’d barely want to do that at all, whereas passing will be what you mostly do. It being default is made a bit more annoying by the fact, that when you then select “Pass” as your action, the “Save” button moves up the screen and away from your cursor. 
Perhaps (after reading through #510), my issue is actually more about the “Save button” moving away from the cursor, so remedying this would be swell.

-----

Wish list:

It would be nice if the layout was taking landscape screen formats more into account (e.g. having the game board to the right of the “Actions” or the “cards in hand” to the right of the game board (and “Actions” below the game board).

Perhaps making the allowed spaces on the board where to may place a tile even more obvious would be a good idea, I was confused for two generations why I can’t place my greenery tile, totally forgetting about my Mohole area.

Placement bonus for metal is very similar to the background colour of the map and can be hard to actually notice.

It seems that “Select 3 cards” at the beginning of the game if playing Inventrix does not need to be a click. 

Related to #497: It would be lovely, if there was a way to cancel a card action, that requires a second input before making the second input. E.g. “Insulation”, if you notice that you actually can’t spare any heat production, you should be able to cancel playing “Insulation”. 

If playing Helion, after you run out of money to pay for an action, it should automatically use heat if you have any to pay.

Similarly if you have Psychrophiles, I can’t think of a situation I would not want to use the resources of Psychrophiles to pay for a plant-tag. So I feel this should be the default payment currency if applicable.
The 

Setup menu: A brief explanation about what the options mean (e.g. TR solo mode – “In addition to terraforming Mars, you also need to have a TR of 62 (?) to win”/expansion brings might be nice (or perhaps if available a link to the manuals of the expansions).
Idea on how to implement: This explanation should either be on a mouse over/click on a small “Info”-button next to the according option or be shown below/to the side of the current menu block when you activate the action and change to a different action if you activate that.

Getting a warning if playing a card that requires an action but you have no selection. E.g. if playing “Insulation” and you leave it at 0, the card cost you 5 M€ but you got nothing for it. There should probably a warning, either clickable or a visual indicator that you currently have nothing selected. 

-----

Bugs:

Probably the same as #359: If paying with multiple different resources you can pay more than the card costs. E.g. if you pay for a space tag the exact cost in titanium you can still add M€ up to the cost of the card, meaning you would have essentially payed twice the price for the card.

(Perhaps not a bug as such, but an inconsistence/UI thing) When using “Insulation” the buttons to add/decrease the amount of heat converted are tiny and very different to the buttons of paying for a project card. (Are cards other than Insulation also affected?)

Related to #746: I feel the “Undo” button does not work correctly, aside from the interface not automatically updating itself without refreshing the browser: Sometimes only my second action is undoable, but not both or the first? If playing Solo it would be nice, if the undo wasn’t fused with the default 2 actions (if it in fact is), but on an individual action level. (And more than just one step of undoing would be welcome as well).
It also seems like undoing standard actions like “Power plant” might not correctly show in the interface even after refreshing the page until the next turn.

Thanks for reading.

**Comment by nwai90** [comment]
Does this ordering make sense? Not shown:
- Claim a milestone (always first in the list if available)
- Convert 8 heat to temperature and Convert x plants to a greenery (always second and third options if available)

<img width="488" alt="Screenshot 2020-06-01 at 9 35 37 PM" src="https://user-images.githubusercontent.com/2408094/83414634-6b22c080-a450-11ea-98e8-110b67fe466a.png">

**Comment by FrankJones314** [comment]
Yeah, for solo mode, there is no "action 1 of 2"  Any action should be able to be undone.
