### ISSUE TITLE
Standard solo game should always go 14 generations (12 with Preludes)

### ISSUE THREAD

**Issue by thenewjuniorexecutive** [bafolts/terraforming-mars#751]
Playing standard solo with all expansions + Solar Phase,  fully terraforming Mars in Gen 11 will trigger then end game. Per rule 5 for solo, "You always play 14 generations". This replaces the multiplayer end game check. Preludes modified it to 12 generations without reinstating the original check. 

I haven't managed to complete it more than 1 generation early.

The additional gen matters if you're playing to maximize your score.

**Comment by glass4pk** [comment]
Yesterday I played a solo game , I fully terraforming all three , but still got me lose...
Is that bug?

**Comment by nwai90** [comment]
@glass4pk Was Venus expansion included? Did you select Solo TR option?

**Comment by alrusdi** [comment]
It is probably regression. We need a test for it.

**Comment by AbnRgr1978** [comment]
Non-Programmer Confirming the Prelude solo, I won but lost bug.
Finished early  Gen12, scored 96 completed all TF and lost.  Did not think to save game stats.

**Comment by vincentneko** [comment]
This should be ok now, thanks to @alrusdi and @bafolts 
Can you please confirm this ?

**Comment by alrusdi** [comment]
This should be fixed now
