### ISSUE TITLE
Corporation Arklight is wrong

### ISSUE THREAD

**Issue by AlexBurkov** [bafolts/terraforming-mars#760]
Arklight adds one resource when any player play cards with animal or plant tags. It isn't correct.
I think you must add checking for player here:
https://github.com/bafolts/terraforming-mars/blob/master/src/cards/colonies/Arklight.ts#L25

**Comment by alrusdi** [comment]
Thanks for the report. We will fix it soon

**Comment by nwai90** [comment]
@alrusdi Fixed in https://github.com/bafolts/terraforming-mars/pull/765

**Comment by alrusdi** [comment]
Should be fixed now
