### ISSUE TITLE
Choosing preludes which require MC

### ISSUE THREAD

**Issue by AlexBurkov** [bafolts/terraforming-mars#761]
We played mars and I found some bug: I chose a lot of cards and I didn't have MC. I chose two preludes: one of them gave me 6 MC and another required 5 MC. So I thought I got MC firstly and I could pay second prelude. But game showed me only one prelude which gave me MC. And I couldn't pay second. I didn't see it even.

**Comment by nwai90** [comment]
@AlexBurkov I am able to reproduce this, will fix it

**Comment by vincentneko** [comment]
Fixed by @nwai90 and merged
