### ISSUE TITLE
Open city can be chosen even if there aren't available places for city

### ISSUE THREAD

**Issue by AlexBurkov** [bafolts/terraforming-mars#762]
I couldn't bug here:( But we played and I could play this card but there aren't available places for new city.
https://github.com/bafolts/terraforming-mars/blob/master/src/cards/OpenCity.ts#L17

Sorry, I didn't choose needed card on screen. But you can see it below. It costs 23 MC
<img width="1147" alt="Screen Shot 2020-05-31 at 01 28 30" src="https://user-images.githubusercontent.com/12098651/83796206-4e34fa00-a6a9-11ea-87b2-66146f73e6ad.png">
<img width="774" alt="Screen Shot 2020-05-31 at 01 28 13" src="https://user-images.githubusercontent.com/12098651/83796221-52611780-a6a9-11ea-88a2-137fd30abe6c.png">

**Comment by alrusdi** [comment]
@AlexBurkov Did you play it on your own server? We need db/game.db file for debugging if it is possible.

**Comment by AlexBurkov** [comment]
Yes, I played it on my server. I can sent this file, but it's 135MB, I think I can't attach it here. So how I can sent it to you?

**Comment by alrusdi** [comment]
@AlexBurkov try to email it to alrusdi@gmail.com

**Comment by AlexBurkov** [comment]
> @AlexBurkov try to email it to [alrusdi@gmail.com](mailto:alrusdi@gmail.com)
> can you please to zip it before?

Done

**Comment by AlexBurkov** [comment]
That game was on 31 May

**Comment by nwai90** [comment]
@alrusdi This should have been fixed here: https://github.com/bafolts/terraforming-mars/commit/ec5ccd756bf1052b526d50b5e990547dd3d356aa#diff-e94b75f226ba27d7c775fb2e13827d0cR18

@AlexBurkov There was a patch for this around 25-26 May. Is it possible that your game might have been run on an older version of the code?

**Comment by alrusdi** [comment]
@nwai90 i think so. Can't reproduce it. @AlexBurkov please reopen it if you hit it again in updated version

**Comment by AlexBurkov** [comment]
Yes, I could play on old version. I am sorry.
