### ISSUE TITLE
Improvement: When there is only one action available from a played card, preselect it.

### ISSUE THREAD

**Issue by funkybaboon** [bafolts/terraforming-mars#775]
If I only have one action available from a played card, I still have to select it to do the action:

<img width="655" alt="Screenshot 2020-06-06 at 12 46 00" src="https://user-images.githubusercontent.com/2966599/83942476-e6d79100-a7f3-11ea-8cb9-d50468c07233.png">

Suggestion: Also preselect this action, like you do with the project cards if there is only one project card available.

<img width="616" alt="Screenshot 2020-06-06 at 13 15 41" src="https://user-images.githubusercontent.com/2966599/83942877-e0e3af00-a7f7-11ea-94f6-5384a6fbb6e9.png">

**Comment by funkybaboon** [comment]
The logic for the selection if there is only one blue card seems to be https://github.com/bafolts/terraforming-mars/blob/497a5a443907d6dc504f212bdf127885f437c569/src/components/SelectCard.ts#L28. 

I tried adding `checked="checked"` 
```
            <input v-if="playerinput.maxCardsToSelect === 1 && playerinput.minCardsToSelect === 1" type="radio" v-model="cards" :value="card" checked="checked" />
```
or simply `checked`
```
            <input v-if="playerinput.maxCardsToSelect === 1 && playerinput.minCardsToSelect === 1" type="radio" v-model="cards" :value="card" checked />
```
but it did nothing. Any hints @alrusdi what needs to be done here?

**Comment by nwai90** [comment]
> If I only have one action available from a played card, I still have to select it to do the action:
> 
> <img alt="Screenshot 2020-06-06 at 12 46 00" width="655" src="https://user-images.githubusercontent.com/2966599/83942476-e6d79100-a7f3-11ea-8cb9-d50468c07233.png">
> 
> Suggestion: Also preselect this action, like you do with the project cards if there is only one project card available.
> 
> <img alt="Screenshot 2020-06-06 at 13 15 41" width="616" src="https://user-images.githubusercontent.com/2966599/83942877-e0e3af00-a7f7-11ea-94f6-5384a6fbb6e9.png">

When we can resolve this, we should apply the change to preselect the first of the two Prelude cards as well, to save a click.

**Comment by duckmammal** [comment]
I like the option being pre-selected, but not automatically done.
