### ISSUE TITLE
Hellas map missing icon for ocean bonus

### ISSUE THREAD

**Issue by motoyugota** [bafolts/terraforming-mars#780]
With the latest UI update, the icon for the -7 credit ocean bonus at the bottom of the Hellas map is missing. The tile placement still works to give you the ocean, so it's just a missing graphic.

![2020-06-08 (9)](https://user-images.githubusercontent.com/889269/84100935-82265d00-a9d2-11ea-82fc-342323928eb3.png)

**Comment by vincentneko** [comment]
Thanks to @gomfunkel for fixing this
