### ISSUE TITLE
Feature Request: Random Milestones and Awards

### ISSUE THREAD

**Issue by nwai90** [bafolts/terraforming-mars#787]
Ref: https://ssimeonoff.github.io/ma-randomizer

We could implement this as a game option without taking synergy into account first, and add synergy considerations at a later stage.

<img width="874" alt="Screenshot 2020-06-09 at 9 43 30 PM" src="https://user-images.githubusercontent.com/2408094/84155282-c0874f00-aa9a-11ea-83f5-5f6871f6a77b.png">

<img width="804" alt="Screenshot 2020-06-09 at 9 43 57 PM" src="https://user-images.githubusercontent.com/2408094/84155288-c2e9a900-aa9a-11ea-915d-78e10d32b845.png">

**Comment by nwai90** [comment]
@vincentneko Could you help with the database side for this? I can push a draft PR first; we would have to store milestones and awards data for games that have randomized M&A, in order for them to be properly rebuilt.

**Comment by vincentneko** [comment]
> @vincentneko Could you help with the database side for this? I can push a draft PR first; we would have to store milestones and awards data for games that have randomized M&A, in order for them to be properly rebuilt.

Yes I can help with the database side.

**Comment by nwai90** [comment]
Thanks, I raised a draft PR https://github.com/bafolts/terraforming-mars/pull/790

**Comment by vincentneko** [comment]
@nwai90  I've pushed a commit on the branch that should handle game reload and clone with random  MA. Please review and test.

**Comment by nwai90** [comment]
> @nwai90 I've pushed a commit on the branch that should handle game reload and clone with random MA. Please review and test.

@vincentneko Tested, works perfect 👍I added a minor improvement here: https://github.com/bafolts/terraforming-mars/pull/806

**Comment by vincentneko** [comment]
Great, I think you can submit a PR. Now we need someone to review !

**Comment by nwai90** [comment]
Closing as changes are merged
