### ISSUE TITLE
Wrong card name

### ISSUE THREAD

**Issue by vincentmoreaudba** [bafolts/terraforming-mars#8]
10 Mining Industries should be Io Mining Industries (as the name of one of Jupiter's moon)

**Comment by bafolts** [comment]
This has been fixed in master with the following commits:

https://github.com/bafolts/terraforming-mars/commit/64129354bcce3dd1d971ac9015e2e7ff13c2207e
https://github.com/bafolts/terraforming-mars/commit/9fb6be55025636946b5e78d28dd97f167a40d164
