### ISSUE TITLE
Sixth player

### ISSUE THREAD

**Issue by AlexBurkov** [bafolts/terraforming-mars#801]
I know original game has 5 players max, but there are 6 players from us so we need possibility to play six of it. Can you add one extra player?

**Comment by nwai90** [comment]
@bafolts @vincentneko Is this something you are okay to support? I can submit a PR to allow up to 6 players per game

**Comment by vincentneko** [comment]
> @bafolts @vincentneko Is this something you are okay to support? I can submit a PR to allow up to 6 players per game

Yes I don't see why we shouldn't

**Comment by vincentneko** [comment]
Merged
