### ISSUE TITLE
Robotic workforce + mining area

### ISSUE THREAD

**Issue by rodrigomp84** [bafolts/terraforming-mars#804]
Using the "Robotic workforce" to copy the production box of the "Mining Area" card resulted in no effect at all.

According to the game designer, the expected output is that the original choice taken when playing the Mining Area card should be copied, as he explains in:
[https://boardgamegeek.com/thread/1631060/can-someone-please-explain-how-robotic-workforce-c/page/2](url)

Perhaps recording this information may be too clumsy, so the user could choose which one to get. Or this card could be simply blocked from being picked after Robotic workforce, it is still better than just wasting M$.

**Comment by nwai90** [comment]
@rodrigomp84 I am unable to replicate this issue - Robotic Workforce seems to copy Mining Area's production correctly. Do you have the game ID by any chance?

**Comment by rodrigomp84** [comment]
Really? Oh damn, I'm very sorry for the inconvenience if this was just a misunderstanding. But that was the impression on the table. It could have been the Mining area card, but I suppose it works fine if the other also does.

I have the link to the game which I passed to the player who (supposedly) had the problem, don't know if it contains the correct id
https://terraforming-mars.herokuapp.com/player?id=6ff0828695a6

In any case, thank you for the attention and sorry for the inconvenience.

**Comment by vincentneko** [comment]
It could be related to the undo feature, if it was used after Mining Area but before Robotic Workforce. Do you remember having used this feature ?

**Comment by vincentneko** [comment]
I confirm the undo will loose the resource associated with Mining Area or Mining Rights.
Will submit a PR to fix this.
Thanks for your feedback !

**Comment by vincentneko** [comment]
Fixed and merged
