### ISSUE TITLE
Using Titan Air-scrapping with no titan resource can lock out the game

### ISSUE THREAD

**Issue by rodrigomp84** [bafolts/terraforming-mars#822]
When trying to use the "Titan Air-scrapping" card action while possessing no titan resources, a player got the "Select one option" message but none was given and the game locked out, even though there were 3 floaters on the card.

He had used the action before successfully, but always with some titan resource available, so that's what's triggering the suspicions.

The log shows the card was played, and the card is in black and white on the Played Cards area, showing the 3 floaters resources on it.

**Comment by nwai90** [comment]
@rodrigomp84 I saw the issue, will submit a fix

**Comment by vincentneko** [comment]
Fixed by @nwai90
