### ISSUE TITLE
Improvement: Show the ranking of players  of  rewards 

### ISSUE THREAD

**Issue by jijiqw** [bafolts/terraforming-mars#828]
![image](https://user-images.githubusercontent.com/16096558/84862882-8a535c00-b0a6-11ea-9b12-8f6cddcbaa9f.png)

How do you think about this idea?  And any one can help make this come true ?

**Comment by alrusdi** [comment]
We have a plan for separate widget to see more detailed realtime statistics including this
https://github.com/bafolts/terraforming-mars/issues/407
