### ISSUE TITLE
Not able to buy a card only with steel

### ISSUE THREAD

**Issue by dabewi** [bafolts/terraforming-mars#83]
Hi,
during  a test game with @vincentneko I stumbled over this issue: I tried to play my _Domed Crater_ and I posess enough steel to buy it but not enough megacredits. In this case the game doesn't offer me the option to buy the card with steel instead of megacredits.

I uploaded a screenshot for clarification: https://abload.de/img/nosteelmdjgp.png

Cheers!

**Comment by alrusdi** [comment]
According to this screenshot you didn't have enough Energy production to play Domed Crater

**Comment by dabewi** [comment]
That's true, I didn't realize that. Issue closed.
