### ISSUE TITLE
Turmoil - Wrong turn order & blocked game

### ISSUE THREAD

**Issue by ap3h3ad** [bafolts/terraforming-mars#839]
Me and my usual teammates have encountered a bug with the turmoil expansion several times by now.

Whenever an event occurs that forces the player to do some specific action, e.g. discard two cards, this event takes place at the beginning of the new generation and not in the end of the actual generation. This causes a situation where I can buy some cards in the draft phase and then discard two of them to satisfy the event that took place in the previous generation - which doesn't seem to be right (I should be forced to actually discard some cards from the previous generation).

Also: As the start player of the generation after the event I can make my whole turn (the whole 2 actions) after I discarded the two cards from the previous generation's event, but then the game gets blocked - nobody else seems to be able to play unless every player has satisfied the event by discarding two cards.

So the order seems to be messed up. Currently it's like this:

1.) Generation with event ends
2.) New generation's production
3.) New generation's draft
4.) First player has to satisfy the previous event and than can play regardless of which other players have or have not discarded cards

But it should be like this:

1.) Generation with event ends
2.) Players are forced to satisfy the event
3.) New generation's production
4.) New generation's draft

Improvements:

- Place the event at the end of the generation
- Apply the same mechanism to the event solving phase as it is with the draft phase so that every player can discard their cards simultaneously.

**Comment by nwai90** [comment]
@ap3h3ad Does it still happen nowadays? Saw it is fixed by @vincentneko a few days ago in https://github.com/bafolts/terraforming-mars/issues/706

**Comment by ap3h3ad** [comment]
@nwai90 Apparently the server is not up to date. That's the reason that I closed the issue. :)

Cheers!
