### ISSUE TITLE
Not able to steal from opponent

### ISSUE THREAD

**Issue by dabewi** [bafolts/terraforming-mars#84]
Hi,

during one of the test games with @vincentneko I experienced the following behaviour:

I played _Sabotage_ and wanted to steal 7 megacredits from my opponent. Though he had 15 megacredits to that time I wasn't able to steal anything from him (or from myself, I tried that too). Regardless what amount of what ressource I chose, the game gave me the same error message:

https://abload.de/img/erroraekp3.png

Cheers.

**Comment by alrusdi** [comment]
We will try to reproduce and fix it. Thank you for reporting!

**Comment by vincentneko** [comment]
This card should not use SelectAmount, as the amount is somehow fixed by the card text (it is up to, I don't see any situation where we would want to select less than the maximum...) 

So this can be simplified to a OrOptions list.
Will propose a fix soon.

**Comment by alrusdi** [comment]
Fix merged
