### ISSUE TITLE
Feature Request: Show community high scores for solo games

### ISSUE THREAD

**Issue by nwai90** [bafolts/terraforming-mars#840]
Every game has a predefined seed and it is possible to replay previous games using "Set predefined game" option.

For a given seed, it would be interesting to know where your solo score stands, compared to others who have played the exact same game. We could store and update the highest winning score for each unique seed.

<img width="994" alt="Screenshot 2020-06-19 at 3 25 44 PM" src="https://user-images.githubusercontent.com/2408094/85111174-8b22f400-b246-11ea-8f82-c2282885b436.png">

**Comment by kevinb9n** [comment]
There are two natural leagues here where the first can't compete with the second:

One taken from games where we have ample reason to believe the player had never seen that seed before. They were the first play of that seed, or they got that seed from a "hey gimme a random cool seed from today' option, etc. Oh, and (pending #1846 resolution) they must have disabled undo.

And the other one, free-for-all, do whatever. In this case I think the Puzzle Mode I just filed is the perfect fit. (#2106) If you're going to compete, go all out.

This could be fun!
