### ISSUE TITLE
Bug: Mars University interrupt triggers before Olympus Conference

### ISSUE THREAD

**Issue by nwai90** [bafolts/terraforming-mars#848]
**Context:** If player has both cards and Olympus Conference's effect would result in drawing a card from playing a Science tag, its effect should be resolved first before Mars University's cycle effect

**Comment by vincentneko** [comment]
This is a tricky one. Right now effects will be resolved according to play order.
I'm wondering if it is the only case where we should resolve actions in a specific order.
We could introduce an optional `effectPriority ` parameter to cards in order to trigger some effects before some others.

**Comment by nwai90** [comment]
This is the only reported case so far. The two cases I can think of are Olympus Conference and Point Luna, where you would want to receive the drawn card before triggering a discard effect.

**Comment by vincentneko** [comment]
A quick and dirty fix could be to add the Olympus Conference card in the playedCards with unshift instead of push.
I've not tested it though.

**Comment by duckmammal** [comment]
it feels to me like you should be able to show players the effects that are happening as a result of their actions, and let them choose the order in which the effects are resolved, but maybe that level of abstraction is not programmed in

**Comment by nwai90** [comment]
@duckmammal You're right, it currently isn't. One consideration is that having to choose the order of effects every time might potentially introduce a lot of extra clicks for the user.

In most cases, order is likely not critical, except for the effects that draw cards (and maybe those that give resources too, though I can't think of any scenarios at the moment). Have you encountered any of them besides Point Luna and Olympus Conference so far?

**Comment by duckmammal** [comment]
There are a lot of options that are done incorrectly, but they're all corner cases that won't matter to many players, imo. Another big one is placement on the south pole of Hellas. Another would be when you have viral enhancers in play, and 3 oceans on the board, but no plants, you should be able to play moss, to choose to gain a plant when the plant tag enters, and then immediately spend the plant.

There are many such cards that create a resource that might want to be spent at the same time that the card is played.

**Comment by nwai90** [comment]
Both Moss cards should be playable for edge cases now. South Pole is tricky as the ocean placement on Hellas could theoretically give anything between 0-12 MC, maybe tackle this edge case someday

**Comment by duckmammal** [comment]
actually, with lakefront the upper-bound is 18, :P but in any case the upper bound is unlikely to matter, as long as it's above 6.
