### ISSUE TITLE
Helion not working as intended

### ISSUE THREAD

**Issue by vincentneko** [bafolts/terraforming-mars#85]
In a game with Helion, I have a stock of 13 heat, and 3 MC.
Game does not let me play a card (with no requirements) that costs 13 MC.

Also, standard projects text is strange:

Pay for a standard project
Select how to pay for power plant
Select how to pay for asteroid
Select all
Select all
Select all
Play project card

**Comment by alrusdi** [comment]
Fixed and merged. Thank you!
