### ISSUE TITLE
Bug: Showing losing screen in solo mode even though I've won

### ISSUE THREAD

**Issue by sdas-tech** [bafolts/terraforming-mars#855]
Under the rules, in solo mode the player wins if they complete all 3 global parameters by the end of Gen 14.
I've done so, however I still get the losing screen:
![image](https://user-images.githubusercontent.com/1049519/85224108-3e3c4a80-b40b-11ea-95e8-b695ccf9f0b3.png)
https://terraforming-mars.herokuapp.com/the-end?id=b241be81dc05

Game ID: ca427e36c480

**Comment by nwai90** [comment]
> Under the rules, in solo mode the player wins if they complete all 3 global parameters by the end of Gen 14.
> I've done so, however I still get the losing screen:
> ![image](https://user-images.githubusercontent.com/1049519/85224108-3e3c4a80-b40b-11ea-95e8-b695ccf9f0b3.png)
> https://terraforming-mars.herokuapp.com/the-end?id=b241be81dc05
> 
> Game ID: ca427e36c480

Was solo TR option selected? If that option is checked, you need to get 63 TR in order to win

**Comment by sdas-tech** [comment]
Ah yes you're right, I didn't realize that option changed the rules. I think it would be good to have a tooltip that explained it more clearly though.

**Comment by nwai90** [comment]
> Ah yes you're right, I didn't realize that option changed the rules. I think it would be good to have a tooltip that explained it more clearly though.

👍 Tooltips are a good idea, we will likely implement it at some point
