### ISSUE TITLE
Suggestion: Allow games to start with X amount of production

### ISSUE THREAD

**Issue by russweiher** [bafolts/terraforming-mars#856]
The base game rules allow for playing in "corporate era" or not.  Playing in corporate era includes the corporate era cards, but starts everything at 0 production.  Playing non-corporate era rules removes those cards, but starts everything at 1 production, to allow players to get moving faster.  My suggestion is to split the difference and put a slider or radio button at game setup to start everyone with 1 (or more) production.

**Comment by nwai90** [comment]
Good idea, will add it in as an option

**Comment by alrusdi** [comment]
It is implemented thanks to @nwai90
