### ISSUE TITLE
land claim not working

### ISSUE THREAD

**Issue by vincentneko** [bafolts/terraforming-mars#86]
I played land claim card. It was payed and played but no marker was put on the board, and I did not got placement bonus (should have got 6 MC as the tile was adjacent to 3 oceans)

**Comment by alrusdi** [comment]
You should not get placement bonus because Land Claim is is not a tile placement (just marker).
But no marker after this action is still a bug.

**Comment by alrusdi** [comment]
I have double checked behaviour.
1) Marker is displayed now
2) Other players cant place a tile on claimed area
3) Owner can place a tile
Seems to be fixed. @vincentneko isn't it?

**Comment by vincentneko** [comment]
Yes, thanks a lot !
