### ISSUE TITLE
Bug after player passed without any action

### ISSUE THREAD

**Issue by rodrigomp84** [bafolts/terraforming-mars#870]
On the game that is still online now:
https://terraforming-mars.herokuapp.com/player?id=2d55bc64b973
after playing a few actions on generation 1, I (red player) was the last active player and passed without any action. I got an error message - something about colonies, but unfortunately I closed it without reading it carefully - and I was then asked to pass again. After doing so, something crazy happened: production phase went off, no cards were dealt for the draft and the generation simply kept on with the same play order.
The last plays on the log before it happened were
🕑Rodrigo played Arctic Algae
🕑Rodrigo played Water to Venus
🕑Markinhos passed
🕑Rodrigo passed
🕑Rodrigo passed

and I'll put the full log down here for reference. The last four plays happened after the bug

> Generation 1
🕑Markinhos played Mining Operations
🕑5 card(s) were discarded
🕑Markinhos drew Minority Refuge and Giant Ice Asteroid
🕑Markinhos played Acquired Space Agency
🕑Lucio played Early Settlement
🕑Lucio played Biolab
🕑Thiago played Martian Industries
🕑Thiago played Metal-Rich Asteroid
🕑Rodrigo played Orbital Construction Yard
🕑Rodrigo played Loan
🕑Markinhos played Minority Refuge
🕑Markinhos built a colony on Callisto
🕑Markinhos played Research Colony
🕑Markinhos built a colony on Triton
🕑Lucio played Trading Colony
🕑Lucio built a colony on Triton
🕑Lucio played Beam From A Thorium Asteroid
🕑Thiago used Power plant standard project
🕑Thiago played Strip Mine
🕑Rodrigo added a new Colony tile: Luna
🕑Rodrigo built a colony on Triton
🕑Markinhos played Solar Power
🕑Markinhos played Power Plant
🕑Lucio used Stormcraft Incorporated action
🕑Lucio passed
🕑Thiago played Vesta Shipyard
🕑Thiago ended turn
🕑Rodrigo played Optimal Aerobraking
🕑Rodrigo played Callisto Penal Mines
🕑Markinhos played Security Fleet
🕑Markinhos ended turn
🕑Thiago passed
🕑Rodrigo played Arctic Algae
🕑Rodrigo played Water to Venus
🕑Markinhos passed
🕑Rodrigo passed
🕑Rodrigo passed
🕑Markinhos used Security Fleet action
🕑Markinhos played Cryo Sleep
🕑Lucio used Stormcraft Incorporated action
🕑Lucio passed

**Comment by nwai90** [comment]
I can't see any obvious cause from the game logs; it could have something to do with an unresolved interrupt in `Game.playerIsFinishedTakingActions()`. We probably need to check server logs for more detail about the actual error

**Comment by rodrigomp84** [comment]
Thanks for the answer, please let me know if I can be of any help.

Since the error message said something about colonies, it should be worth mentioning that I was playing Aridor and had therefore added a colony tile to the game (as it can be seen from the game log...). In any case, I have played this corporation once before without any problems.

**Comment by vincentneko** [comment]
I'm closing this one as the bug seems not to occur again.
