### ISSUE TITLE
Feature Request: Tooltips

### ISSUE THREAD

**Issue by nwai90** [bafolts/terraforming-mars#873]
Tooltips with brief one-liner explanations of what each custom game option does

**Ref:**
https://github.com/bafolts/terraforming-mars/issues/855
https://github.com/bafolts/terraforming-mars/issues/749

**Comment by alrusdi** [comment]
May be it is better to make it like small clickable questionmark icon to make it more obvious on touch devices?

**Comment by nwai90** [comment]
@alrusdi Agree, that's better for cross device. Logging it as this question has come up a few times from players

**Comment by vincentneko** [comment]
Can we close this one ?

**Comment by nwai90** [comment]
@vincentneko Sure, will close it
