### ISSUE TITLE
Initial hand drafting

### ISSUE THREAD

**Issue by vsrisuknimit** [bafolts/terraforming-mars#877]
I saw that the initial hand drafting is recently implemented.  Drafting one project card at a time is long and painful though.

A common initial hand drafting that is typically used on the TTS TfM discord server is the following:
1) Draw 3 corps, 4 preludes, 10 project cards.
2) Keep all corps, keep 2 preludes, keep 4 project cards. Pass everything else.
3) From what was passed, keep 1 out of 2 preludes, and keep 3 out of 6 project cards. Pass everything else.
4) Keep the last prelude and the remaining 3 project cards.
5) Decide what to actually keep and pay for them.

**Comment by jijiqw** [comment]
I think it is a good idea to add the corps and the preludes to initial hand drafting ,  but  do not agree for keep 4 project cards for the first selection.  
Among the ten cards, there are probably three or four cards with high value ,the other cards are poor or  bad ,   choose just one and pass else, then everyone's hand quality is about the same .

**Comment by duckmammal** [comment]
My home group also likes to draft the preludes. 

But we draft the initial cards (one at a time) thusly: 

- 5 cards to the left 
- 5 cards to the right

I've seen groups pass out all 10 cards, and then take 2 cards at a time, while passing to the right.

But honestly, this is all tweaking small details. There are a lot bigger problems to take care of than making sure everyone's got their implementation of how they start the game implemented on this site.

**Comment by kyshantry** [comment]
In my opinion the best way is 5 cards left, 5 cards right, 2 preludes left, turn 2 (first turn with drafting) pass right. 

We've starting to come around to having an auction (really this is @duckmammal 's innovation). 

Assuming a 4 player game: 

4 packs of 2 corps are revealed with a seat order assigned to them. Players each make a single bid. The bids are resolved from highest, with the highest bidder paying the second highest bid on that corp stack and then being removed from the auction. So, for example

Player 1 bids: 1, 4, 0, 10
Player 2 bids: 3, 2, 1, 0
Player 3 bids: 4, 0 , 3, 8
Player 4 bids: 5, 2, 0, 9

Then player 1 gets pack 4, pays 9 and is removed from the auction. 
Player 4 gets pack 1, pays 4 and is removed. 
Player 3 gets pack 3 and is removed. 
Player 2 gets pack 2 and pays 0. 

It takes a little getting used to, but given that we've had auctions that go up to 20 (Poseidon in seat 3) it's pretty clear that it needs to be part of the game.

**Comment by duckmammal** [comment]
@kyshantry I laid it all out in #937

**Comment by kyshantry** [comment]
Cool, they had asked me to lay out how we drafted so I included your
innovations on bidding too, unaware you had done a better job than I did
elsewhere!

**Comment by vsrisuknimit** [comment]
@kyshantry sorry. I read @duckmammal drafting format previously. When you were explaining to me, it does sound very familiar. I did not connect the dot you were in the same home team.

**Comment by liupeiqiangmoss** [comment]
I think it is a good idea to add the corps and the preludes to initial hand drafting ，It wound be better to join two company type.

**Comment by nwai90** [comment]
@vincentneko Can we close this one?

**Comment by kevinb9n** [comment]
Can I ask: what is the point of drafting preludes?  Because you have zero information about the other players at that time, it seems like it's equivalent (but more complicated) to just giving everyone more preludes to choose from.

**Comment by kyshantry** [comment]
The same reason as drafting normal cards: if one player gets 2 A+'s and
another gets all D's, game can be over t1. It helps smooth out luck at the
most important point in the game: the beginning.

**Comment by kevinb9n** [comment]
Thanks for explaining.  But that's kind of what I was thinking when I said that it seems equally well solved by just giving more preludes to choose from?

**Comment by kyshantry** [comment]
I feel like there are two key benefits. One, after having drafted the 10
project cards, you certainly have an idea of what your opponents are up to.
Secondly, I like that there is some uncertainty when you are drafting the
project cards as to what preludes you'll have.

**Comment by nwai90** [comment]
Closing as initial draft has been implemented
