### ISSUE TITLE
Mining Area seems to remove Last Actions

### ISSUE THREAD

**Issue by a5000lbKitty** [bafolts/terraforming-mars#885]
When playing a 2 player game, twice after playing Mining Area, the Last Actions section of the interface went missing.  We abandoned one game, https://terraforming-mars.herokuapp.com/player?id=112ea9840f9e.  The other game, we continued playing calling the cards as we played them.  Eventually it came back after I increased the temperature with heat and funded an award.  Tried doing the same in the game listed above, but no such luck.

**Comment by nwai90** [comment]
@vincentneko Saw that there is a typo; I submitted a PR to fix it

**Comment by a5000lbKitty** [comment]
Was playing that second game that the Last Actions came back on and soon as Mining Rights was played, we lost it again.  Same typo?

**Comment by nwai90** [comment]
Yes, same issue. Will be fixed shortly

**Comment by nwai90** [comment]
Should be rectified now, will close this issue

**Comment by a5000lbKitty** [comment]
If we refresh the game, should it take affect or only for new games?

**Comment by nwai90** [comment]
> If we refresh the game, should it take affect or only for new games?

Only for new games

**Comment by a5000lbKitty** [comment]
Cheers

**Comment by nwai90** [comment]
Thanks for the report!

**Comment by alrusdi** [comment]
It is seems to be fixed
