### ISSUE TITLE
Feature Request: Synergy for Random M&A

### ISSUE THREAD

**Issue by nwai90** [bafolts/terraforming-mars#895]
Discussion thread at https://boardgamegeek.com/thread/2023541/quantifying-milestone-and-awards-synergy-randomiza

**Comment by ssimeonoff** [comment]
you an copy the matrix from here: https://github.com/ssimeonoff/ssimeonoff.github.io/blob/master/js/ma.js

**Comment by nwai90** [comment]
Implemented by @alrusdi
