### ISSUE TITLE
Initial Greens policy should not be triggered by "Experimental Forest" prelude card

### ISSUE THREAD

**Issue by rodrigomp84** [bafolts/terraforming-mars#900]
There are some discussions about that at BGG, but the final version of the Turmoil rules are, I believe, clear enough:

>The effect or action on the Policy tile is active only during the Action phase

so it should have no effect on the prelude phase. I notice that the effect was triggered, though.

**Comment by nwai90** [comment]
@rodrigomp84 You're right, I am able to reproduce this issue. Will submit a patch

**Comment by alrusdi** [comment]
Fixed and Merged. Thanks to @nwai90
