### ISSUE TITLE
Confirmation or clearer separation of "End Turn" and "Pass"

### ISSUE THREAD

**Issue by bafolts** [bafolts/terraforming-mars#903]
I received an email indicating that sometimes there is confusion around "End Turn" and "Pass". We may want to consider modifying the UI to make it clearer which is which so that either button is only clicked when that was the intention.

From email:

> I do have one request - if possible, could you please add a confirmation button for the "pass" option?  There were several instances in which my friends and I mixed up "end turn" and "pass" options - including in the last round when I still had 57 spacebucks and so many awesome cards I wanted to play :-( :-( :-( - and we accidentally selected the wrong option, sending our turns prematurely.

**Comment by nwai90** [comment]
We could add a placeholder confirmation `alert` for now, similar to the warning alert when you overpay for a card/action. At some point later these alerts can be replaced with nicer styled confirmation boxes

**Comment by alrusdi** [comment]
If someone will do it please do it optional. It can be very annoying to have additional click for those who doesn't missclicks

**Comment by nwai90** [comment]
Yes, I think we can eventually consolidate all alerts ("Mars is Terraformed!", Overpayment warning, Pass confirmation etc.) under a single "Show in-game alerts" preference.

**Comment by vsrisuknimit** [comment]
In the case this issue still open, you can change "pass" to "pass for the generation". This way it is clearer what pass is.

**Comment by vincentneko** [comment]
Can we close this one ?
