### ISSUE TITLE
Unexpected Server Response

### ISSUE THREAD

**Issue by TMJunkie** [bafolts/terraforming-mars#909]
Received this message while playing a game with friends. I'm not a programmer but just an end user. We have all received this message on various  browsers (Firefox and Chrome) within the last 24 hours. Will this be resolved or is our game toast? At this point all we see is this message with a grey background, no game :(.

Thanks for any assistance.

Great job btw :)

**Comment by TMJunkie** [comment]
Sorry the message was "unexpected server *RESPONSE" (not error, as posted in title)

**Comment by bafolts** [comment]
There was an upgrade to the server last night to make hosting with heroku
simpler. This required us to wipe games from the database. We don't
anticipate having to do this often. Apologize for your lost game. The
upgrade should ensure we are able to serve more games simultaneously and on
our cheap hosting plan that we use.

**Comment by TMJunkie** [comment]
Thanks for the explanation. Perfectly understandable. You guys have done an admirable job so far, and it's all free, so losing a game here and there is not an issue :). Keep up the good work!
