### ISSUE TITLE
Instructions for persistent games

### ISSUE THREAD

**Issue by rogerta** [bafolts/terraforming-mars#910]
I'm trying to run a TM server on my own machine.

Environment:
```
$ uname -a
Linux rpi4a 4.19.97-v7l+ #1294 SMP Thu Jan 30 13:21:14 GMT 2020 armv7l GNU/Linux

$ cat /proc/meminfo
MemTotal:        3999756 kB
MemFree:         1177160 kB
MemAvailable:    3523756 kB
...

$ node --version
v12.18.2

$ psql --version
psql (PostgreSQL) 11.7 (Raspbian 11.7-0+deb10u1)
```
Running `npm install` and `npm start` on master branch at commit [`5237ffa520e811ab091a636f946a017c5b4f8266`](https://github.com/bafolts/terraforming-mars/commit/5237ffa520e811ab091a636f946a017c5b4f8266) works and I can create a new game.  However, when I restart the server the game is not found.

I noticed that the server supports two databases: Sqlite and Postgres.  The former is the default.  Is it an in-memory only database?

I set up a Postgres server and created a role and database called `pi`:
```
sudo su postgres
$ createuser pi
$ psql
CREATE TABLE pi;
\q
```
I then started the TM server with the following command but get a problem connecting to postgres:
```
$ whoami
pi
$ export "POSTGRES_HOST=socket:/run/postgresql"
$ node ./dist/server.js
Starting server on port 8080
version 0.X

The secret serverId for this server is 3bd868e2017a. Use it to access the following administrative routes:

* Overview of existing games: /games-overview?serverId=3bd868e2017a
* API for game IDs: /api/games?serverId=3bd868e2017a

(node:17472) UnhandledPromiseRejectionWarning: Error: The server does not support SSL connections
    at Socket.<anonymous> (/home/pi/src/terraforming-mars/node_modules/pg/lib/connection.js:76:35)
    at Object.onceWrapper (events.js:422:26)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:271:9)
    at Socket.Readable.push (_stream_readable.js:212:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:186:23)
(node:17472) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:17472) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
/home/pi/src/terraforming-mars/dist/src/database/PostgreSQL.js:16
                throw err;
                ^

Error: Connection terminated unexpectedly
    at Connection.<anonymous> (/home/pi/src/terraforming-mars/node_modules/pg/lib/client.js:272:71)
    at Object.onceWrapper (events.js:421:28)
    at Connection.emit (events.js:315:20)
    at Socket.<anonymous> (/home/pi/src/terraforming-mars/node_modules/pg/lib/connection.js:62:10)
    at Socket.emit (events.js:315:20)
    at Pipe.<anonymous> (net.js:674:12)
```

`/etc/postgresql/11/main/pg_hba.conf` contains the line:
```
local   all             all                                     peer
```
and `/etc/postgresql/11/main/postgresql.conf` has ssl enabled, but it's unclear to me why SSL matters over a unix socket.

Thanks.

**Comment by bafolts** [comment]
The postgres host should start with `postgresql://`

https://jdbc.postgresql.org/documentation/head/connect.html

You should pass everything after that prefix. If your postgresql url were:

postgresql://host/database

you would pass

POSGRES_HOST=host/database

That being said you are one of the first people to use this locally. We use bare minimum configuration so I assume the problem is you  have provided a host which wasn't found. For reference this is where the connection to postgres is configured.

https://github.com/bafolts/terraforming-mars/blob/master/src/database/PostgreSQL.ts#L12

This is the npm library used

https://node-postgres.com/features/connecting

If you do find some issue feel free to put up a pull request. The sqllite support should attempt to write to a local file to save the database and isn't in memory. What error did you see upon startup with sqllite?

**Comment by rogerta** [comment]
Thanks for the quick response Brian.  Yeah I found the code in your repo and saw that you are using [pg](https://www.npmjs.com/package/pg) as a Postgres client library.  I think I misread the docs there about how to configure the `connectionString` ctor argument, I'll take another look.  (I don't think there is anything wrong with your code.)

Got it that sqlite is not in-memory only.  The error I encountered is as described above: I start the server via `npm run start`, create a game, then stop the server with `Ctrl+C` and restart it with `npm run start`.  The game I created is no longer listed.  Could the problem be that I am shutting down the server incorrectly?  What is the proper way to shutdown the server?

**Comment by rogerta** [comment]
Hi Brian, I was able to get it working with a local postgres database by removing a small bit of code.  Before sending you a pull request I'd like to understand what that code does.

The [npm library you mention](https://node-postgres.com/features/connecting) links to [pg-connection-string](https://github.com/iceddev/pg-connection-string) to explain the format of `connectionString`.  The string does does not actually need to start with `postgresql://`.  The format that I used above (`socket:/var/run/postgresql`) is valid.

To get it working on my machine, I removed lines [13-15](https://github.com/bafolts/terraforming-mars/blob/master/src/database/PostgreSQL.ts#L13) from PostgreSQL.ts.  With these lines gone the following command correctly starts the TM server:
```
$ POSTGRES_HOST=socket:/var/run/postgresql node dist/server.js
Starting server on port 8080
version 0.X

The secret serverId for this server is b78e34c8b5e8. Use it to access the following administrative routes:

* Overview of existing games: /games-overview?serverId=b78e34c8b5e8
* API for game IDs: /api/games?serverId=b78e34c8b5e8

Connected to PostgreSQL
Connected to PostgreSQL
```
Stopping and restarting the server also find previously created games, so all seems good now with the persistence.

Can you explain the purpose of lines 13-15?  Is it not possible to specify these SSL parameters in the query portion of `postgresql://` connection strings?

**Comment by rogerta** [comment]
Thanks for the fix guys!  I'll update my server once our game is done :-)
