### ISSUE TITLE
Undo after buying cards is unfair

### ISSUE THREAD

**Issue by rodrigomp84** [bafolts/terraforming-mars#911]
I believe the undo possibility is a great thing to have, but allowing it right after a player buys a new card and sees it is unfair. Of course fairness is expected from every player willing to trade 'life hours' for 'playing hours' in such great games, but it could happen unintentionally. Of course, if this is too clumsy to implement then it's better to just rely on the players sense of fairness and attention.

**Comment by alrusdi** [comment]
Does it really hits you? Because after undo, deck of remaining cards should be unchanged and each time you do "undo" and then draw a card - that card should be always the same

**Comment by rodrigomp84** [comment]
Yeah, the thing is that the player can look at the card, so if it's a bad one (unplayable for instance) he/she may just undo and do something different instead.
In a game I was in, it happened that the player genuinely regretted doing an action and clicked undo, but realized it was unfair because he had seen the card. He ended up doing the original action to avoid complains, but in the end it was unfair to him since he actually decided to do something else not because of the card he drew. Of course only forbidding undo after buying a card would not change this situation, unless some kind of confirmation was asked for and this would definitely be too clumsy.

I agree this is not critical (specially considering undo is optional) and only worth it if the implementation is simple. On a tabletop live game, undoing after seeing a card would definitely not be allowed by the table, so I figured it could be the same on this (awesome) implementation. 

cheers!

**Comment by duckmammal** [comment]
I personally like leaving things as they are. I've had friends accidentally forget to pay with steel or titanium while using an action that would draw cards. I like the generic undo button.

**Comment by rodrigomp84** [comment]
> I personally like leaving things as they are. I've had friends accidentally forget to pay with steel or titanium while using an action that would draw cards. I like the generic undo button.

this makes sense!

**Comment by vincentneko** [comment]
As undo button is optional, I'm closing this one.
