### ISSUE TITLE
Bug involving Self-Replicating Robots and Research Coordinator?

### ISSUE THREAD

**Issue by samyelias** [bafolts/terraforming-mars#914]
Hi,

I had 

- Research Coordinator in play, 
- Replicating Robots in play with Advanced Ecosystems linked to it
- 4 cubes on Replicating Robots
- two of the required tags needed for Advanced Ecosystems, with Research Coordinator's wild card tag satisfying the third
- 8 cash in hand, which is 1 more than I should have needed to play Advanced Ecosystems (11 - 4 cubes = 7). 

However, the site would not show Advanced Ecosystems as available to play in the "play projects" option.

I wish I'd taken screenshots, but game id was 142ed6e735d2 if that helps (not sure if you keep the logs).

Might there be a buggy interaction between Self-Replicating Robots and Research Coordinator that prevented me from playing Advanced Ecosystems?

Samy

**Comment by nwai90** [comment]
That's strange. You should only be able to link cards with Building or Space tags with Self-Replicating Robots. Advanced Ecosystems has neither of those. It could be a bug

**Comment by samyelias** [comment]
It's possible I linked a different card; there's no indication that I can see which one is linked (feature request!), except in the log, but it had already scrolled above the limit of what the log display shows. Maybe I miss-clicked or just forgot my second choice.

**Comment by nwai90** [comment]
I couldn't reproduce this issue; tried with a few cards like Tectonic Stress Power and Beam from a Thorium Asteroid. Probably the logs will provide more details

**Comment by samyelias** [comment]
Sorry, I probably just forgot what card I linked to the Robots. The reason was probably because I wanted to link Advanced Ecosystems, realized I couldn't, chose whatever I could just to complete the action, and then forgot about it.

So I guess this has morphed into two feature requests that are probably already on the list:

1) indicate on Robots and preferably the linked card too that the link exists. As I said the log line disappears eventually so I couldn't resort to that

2) a little fancier, but maybe allow undo in the middle of an action instead of being forced to complete it. Or simply allow undo after the second action, which currently doesn't seem possible (and would mean adding an end of turn confirmation too I guess).
