### ISSUE TITLE
Inappropriate action between Policies and Non-turn actions

### ISSUE THREAD

**Issue by duckmammal** [bafolts/terraforming-mars#915]
During the world government phase, the start player placed an ocean when Mars First was in play. 
This (incorrectly) triggered the start player to receive 1 steel.

I'm curious if the placing of greeneries during the preludes phase might be (incorrectly) giving 4 mega credits to the start player, but nobody from our group has tried it yet.

**Comment by nwai90** [comment]
The greeneries issue should be fixed here: https://github.com/bafolts/terraforming-mars/issues/900

I will check about the Ocean placement issue

**Comment by alrusdi** [comment]
Fixed & Merged
