### ISSUE TITLE
Capital tile is a regular city tile.

### ISSUE THREAD

**Issue by rodrigomp84** [bafolts/terraforming-mars#921]
I'm sorry for creating a new issue, as it has been already discussed on an earlier broader issue. But since it is closed, it seems people are not following it any longer.

> This is done

Actually it seems the capital tile is still just a regular city tile. I agree with the OP that being able do tell them apart is quite important!

_Originally posted by @rodrigomp84 in https://github.com/bafolts/terraforming-mars/issues/376#issuecomment-653590247_

**Comment by nwai90** [comment]
We could do a white tile for Capital

**Comment by nwai90** [comment]
Closed as resolved
