### ISSUE TITLE
"Not enough cards selected", even though I do.

### ISSUE THREAD

**Issue by sdas-tech** [bafolts/terraforming-mars#924]
![image](https://user-images.githubusercontent.com/1049519/86553978-ac4a4b00-bf8f-11ea-9962-be2b1db1615b.png)

I have also experienced this outside of the initial draft.
The issue only occurs intermittently.

**Comment by nwai90** [comment]
Hi @sdas-tech You need to select a corporation as well :)

**Comment by sdas-tech** [comment]
Nevermind, I didnt have a corporation card selected :D
Will reopen if I find the bug again.

**Comment by nwai90** [comment]
👌 It may be a good idea to display a clearer message (e.g. "Please select a corporation" or "Please select two preludes")
