### ISSUE TITLE
Easier to see global parameter level

### ISSUE THREAD

**Issue by samyelias** [bafolts/terraforming-mars#926]
I think the visuals for the global parameters should more clearly show the current level. I think the best way is to change the background colour as the meter fills up, not just the number colour. However, perhaps a simpler solution is to use a more striking colour than yellow for the numbers. The change from white to yellow doesn't seem obvious enough. Even worse, if you're playing with a blue-filtered "night light" mode (as it's called in Windows), the whites turn yellow and make it even harder to tell the difference. Perhaps red or green? Some experimentation might be in order.

**Comment by nwai90** [comment]
I tried some different shades of red and green previously, but they didn't seem to fit too well. Would you be able to suggest a suitable colour that we could use?

**Comment by samyelias** [comment]
I'll see if I can play around with it. I guess maybe the background colour might have to be shifted as well as the bar fills up.

**Comment by alrusdi** [comment]
I've suggested this variant 
![globs_variant](https://user-images.githubusercontent.com/394311/86591821-bbd78d00-bfab-11ea-9f16-5259a43f194d.jpg)

But it is hard to implement (very boring task)

**Comment by duckmammal** [comment]
Better yet, would be to leave things as they are, but have a floating panel that has all the global parameters listed on it that is anchored to the right side of the screen, in much the same way your production levels / resources are anchored to the top of the screen.

**Comment by samyelias** [comment]
I thought this combination worked well, and is easy to distinguish in normal and night light mode.

![example1](https://user-images.githubusercontent.com/10133229/86652505-7b2f4200-bfb2-11ea-95cd-cecd6db68421.JPG)

**Comment by duckmammal** [comment]
I think it still doesn't settle the problems of not being able to see the global parameters while looking at the cards in your hand and the related issue of the game taking too long due to too much scrolling.

**Comment by alrusdi** [comment]
@samyelias this variant is less readable in black&white. I think it is not that better than current to change

**Comment by nwai90** [comment]
Closed as resolved in https://github.com/bafolts/terraforming-mars/pull/1123
