### ISSUE TITLE
"Unsupported waitingFor" Error when picking cards

### ISSUE THREAD

**Issue by sdas-tech** [bafolts/terraforming-mars#928]
![image](https://user-images.githubusercontent.com/1049519/86589306-c6f0e400-bfd0-11ea-871a-53ae6071b383.png)

Same error if I don't choose any cards.
https://terraforming-mars.herokuapp.com/player?id=4c458842e92e

**Comment by nwai90** [comment]
Is this issue still relevant?

**Comment by alrusdi** [comment]
irreproducible (c)
