### ISSUE TITLE
Resign-Button

### ISSUE THREAD

**Issue by dabewi** [bafolts/terraforming-mars#93]
Hi,

I'd like to see a button that allows a player to resign a game and effectively drop it.

Cheers

**Comment by alrusdi** [comment]
Please, clarify your reasons for it. Do you want to have shortcut to restart solo game? Or an option to give up multiplayer game?

**Comment by bafolts** [comment]
I am assuming this is for the situation where during a multiplayer game one
player no longer wants to play. This situation most likely isn't covered in
the rule book. I would assume a player who has given up in terraforming
would always pass and never buy research projects or standard projects but
would have to keep generating during the production phase and could still
potentially win depending on how far ahead they were in TP. I don't think
this is worth adding. A player who no longer wants to play should share
their link and have someone else play for them. This approach is simpler
and reflects what would most likely happen when playing in person.

**Comment by dabewi** [comment]
Hi,

bafolts is right in the motives. But what I had in mind is just stopping the game and just declaring the opponent the winner. At least in a 2 player game I assume it wouldn't be problematic at all.

Cheers

**Comment by alrusdi** [comment]
I dislike an idea to not finish the game. It is very common pain for like everyone boardgamer. Please either finish game, or do not start it :-)
It is okay to not continue the game because of bugs, you don't need to have a button for it. Just start new game.

**Comment by kevinb9n** [comment]
See another round of discussion about this in #1377.

I think the most salient point is this: as long as game results are inconsequential (i.e. not automatically used for rankings etc.), all you need to do is chat with your opponents and agree to abandon the game.

**Comment by AndrewSav** [comment]
How about removing games abandoned in this manner from the game list?

**Comment by aloisdg** [comment]
Need one for two players and one for solo mode.
