### ISSUE TITLE
Removing plants from no one

### ISSUE THREAD

**Issue by mloballer** [bafolts/terraforming-mars#930]
I noticed if you play an astroid card that lets you remove plants from someone and there is only one person with plants, it automatically removes it from them. I was wondering why there is not an option to not remove any plants at all? Although obscure, I can see a strategy where you may want to leave the plants to that person so they can push the oxygen out to let you play a powerful card early? I know it's in the official rules that you can choose to remove from nobody, but I am guessing you just assumed it would always be advantageous to remove the plants? Thanks for all your hard work on this project!

**Comment by nwai90** [comment]
Closed as resolved in https://github.com/bafolts/terraforming-mars/pull/941. Feel free to comment if you find any issues!
