### ISSUE TITLE
No options for whom to target in many attack situations

### ISSUE THREAD

**Issue by duckmammal** [bafolts/terraforming-mars#934]
In many situations there have been no way to indicate to the game which person's plants should be lambasted.

The most common is that there is some sort of comet or asteroid that would destroy some number of plants, let's call it 5 plants.
Player A has 6 plants, Player B has 4 plants. It will auto-target the player that can have 5 plants removed, in this case, Player A. This should **Absolutely Not** happen. Whom to attack depends on many factors, and not just the plant total at any given moment.

Another situation where the card did not work as intended was once where I used the card Sabotage against an opponent who had lots of money, steel, and titanium. The card automatically removed 3 titanium, despite the player also having Rego-Plastics, making it more interesting to me to remove 4 steel (12 MC equivalent) instead of 3 titanium (9 MC equivalent).

I think many of these 'short-cuts' have been programmed in, order to save clicks, and make the game flow more quickly, but they are taking away from the richness of the game.

**Comment by nwai90** [comment]
I took a look at the code. Sabotage always provides options and never a default selection.

Similarly for event cards that remove plants, all players that have at least 1 plant should be listed as a possible target.

Can you provide a specific example of when this happens?

**Comment by duckmammal** [comment]
I thought it happened in a game yesterday when I played Sabotage, but maybe I just double clicked something.

I wasn't given the option of hitting someone with 0 plants when I knew the other player was holding a Law Suit.

**Comment by nwai90** [comment]
This should be resolved by https://github.com/bafolts/terraforming-mars/pull/941 to account for situations  like Law Suit where a player does not want to trigger the optional "remove plants" effect. Will close the issue; feel free to comment if you don't see that option available for plant removal cards.
