### ISSUE TITLE
Too much scrolling, too hard to see important info

### ISSUE THREAD

**Issue by duckmammal** [bafolts/terraforming-mars#935]
There's a big problem right now in the game, and it stems from the fact that if you're playing interactively, you have to check many things quite often. The problem is that there is a lot of information that the game contains, and to see what's important, you have to do a loooot of scrolling. So much scrolling that there can be a significant amount of time spent on a players turn checking the global parameters (at the top) the colonies (at the bottom) the map / turmoil board (top), your discounts (near the bottom), your opponents resources (near the top), and your cards in hand (near the middle, but closer to the bottom),

There isn't a great way to check all the important info, and that's in part because the game is complex.

But there could be many enhancements.

Your resources and income and points are _sometimes_ pinned to the top of the screen. They could always be pinned to the top of the screen. This would be especially useful when looking at the map and deciding if / where to place a greenery,

Another big improvement along these lines would be to create the option of having your opponents' resources, income and points pinned to the top, along with yours. This would make understanding the players' relative state a lot easier. To further this idea to it's natural conclusion, I would also suggest that this pane, pinned to the top of the screen, show the number of cards in hand for each player. This would create a good, generic "go to" for assessing opponents without scrolling all over the place.

One thing your app gets really right is that it shows all the tags / events in one place for each player. Very good job with that. But along with that idea, there is another idea that green cards, events, and preludes are "one time" actions. Since their tags are already displayed, hiding these cards for **all players** would be a great option to have. There are only a few times in a game when I really want to confirm that a specific card green / orange card that I've passed an opponent has been played. And I basically never care what preludes they've played after the fact. 

The final enhancement I'd suggest, which I've also suggested elsewhere, is to add a pane pinned to the right side of the screen showing the 3 (or 4 if Venus is in play) current global parameters.

**Comment by duckmammal** [comment]
If you'd like me to separate out these points into different issues i could do that.

**Comment by alrusdi** [comment]
I like the idea to be able to hide not-blue cards. And it is relatively simple to implement. @duckmammal can you move it to separate issue?

**Comment by Arsenki-33** [comment]
Gathering all game informations to make strategic decision, is currently an issue, as you have to scroll a lot as the OP said.
Something I would find really helpful would be to have all players prodcution boxes, as well as tags and cards in hands displayed together like in the following pictures. The picture is just for illustration it is a simple copy and paste of a single box just to show the idea, Using differtent font color for each player would be better.

Even on an humble 15" laptp screen I think you can put two box side by side in a row. Overall this would give a lot of informations on current game status in a relatively small space.

![Terraforming Mars-Prdouction Boxes](https://user-images.githubusercontent.com/68144829/87246572-97b5f900-c44e-11ea-8df7-9e9872c51d37.png)

**Comment by bobastet** [comment]
I remember when I first started playing, the opponent's quick info was visible above my own cards. When this was changed, I really felt it was not a good idea, because, as stated, it created a lot of scrolling. I am definitely on board with making a change.

**Comment by duckmammal** [comment]
> 
> 
> I like the idea to be able to hide not-blue cards. And it is relatively simple to implement. @duckmammal can you move it to separate issue?

@alrusdi 
done here https://github.com/bafolts/terraforming-mars/issues/998

**Comment by alrusdi** [comment]
I think most of the problems here are somehow resolved in new UI. Let's close it
