### ISSUE TITLE
Corps Auction beginning of game variant

### ISSUE THREAD

**Issue by duckmammal** [bafolts/terraforming-mars#937]
The corps are wildly imbalanced, and everyone who has played the game even a handful of times knows this.

Some people are of the opinion that a good solution is to increase the number of Corps that each player is initially dealt, to increase the chances that all players get a reasonable Corp.

The downside of this option is that it pushes games towards a "same-ish" state, where the same corps are picked over and over again.

My home group has added a hidden [Vickrey Auction](https://en.wikipedia.org/wiki/Vickrey_auction) "Corps Auction" to the start of the game, after Milestones, Awards, and Colonies have been revealed.

We lay out pairs of corps, each of which is tied to a position in turn order. Each player makes a private assessment of how many End Game points they are willing to pay for each seat / corp bundle. Players simultaneously reveal their bids and receive colonies.

An example of the system might work as follows:

Seat #1: Viron, Manutech
Seat #2: Helion, Polyphemos
Seat #3: Aridor, Poseidon
Seat #4: Point Luna, Terractor

Players reveal their bids to be as follows:
Alice has bids: 1, 0, 8, 4
Bob has bids: 1, 0, 6, 6
Cheryl has bids: 2, 0, 8, 6
Dylan has bids: 5, 0, 12, 10

The bids are resolved as follows:
Dylan bid the most for a pack with 12 on Seat #3: Aridor, Poseidon. Dylan will receive Seat #3, and will pay the second place's bid for Seat #3. Alice and Cheryl both bid 8, so Dylan will pay 8 points for Seat #3. The rest of Dylan's bids are forgotten about as is Seat #3, and the process continues.

Alice has bids: 1, 0, X, 4
Bob bids: 1, 0, X, 6
Cheryl bids: 2, 0, X, 6

Bob and Cheryl both bid 6 points for Seat #4: Point Luna, Terractor. The tie breaker goes to the person who bid the most for the remaining packs. Since Cheryl bid 2 for Seat #1 and Bob only bid 1 for Seat #1, Cheryl would win Seat #4: Point Luna, Terractor and the process would continue without Cheryl or Seat #4.

Alice has bids: 1, 0, X, X
Bob bids: 1, 0, X, X

Since Alice and Bob value Seats #1 and #2 equally, they don't care too much about who gets which seat. A coin is tossed and they are assigned Seats #1 and #2 at random. In this example, we'll say Alice gets Seat #2: Helion, Polyphemos and Bob gets Seat #1: Viron, Manutech.

The final seating order (before drafting cards) will be as follows:

Bob is in Seat #1 and can choose between Viron, Manutech after the draft, and -1 start VP.
Alice in Seat #2 and can choose between Helion, Polyphemos after the draft, and -0 start VP.
Dylan in Seat #3 and can choose between Aridor, Poseidon after the draft, and -8 start VP
Cheryl in Seat #4 and can choose between Point Luna, Terractor after the draft, and -6 start VP.

I know there's a lot going on in this variant, and it's probably low on the list of things you want to get done, but if someone's interested in coding it up it'd be fun to have an auction that would make more corps playable.

**Comment by duckmammal** [comment]
I'd also say that a blind auction (non-Vickrey) would also be a good option to have.

**Comment by duckmammal** [comment]
One further comment that seating matters a lot when it comes to getting onto valuable colonies and when you get your first good income boost, which is why we tie the corps to seats in order to start the bidding.

**Comment by samyelias** [comment]
Interesting, I'd never read about an auction system where you pay the second-highest bid.

**Comment by duckmammal** [comment]
> 
> 
> Interesting, I'd never read about an auction system where you pay the second-highest bid.

It incentivizes you to bid your true value and not have to worry about overpaying. In my example someone bid 12 and only had to pay 8, and everyone thought it was fair.

**Comment by jijiqw** [comment]
sounds good , but a little difficult to  implement

**Comment by duckmammal** [comment]
I totally understand that side of things. The logic for the bidding is the easy part, but your system seems like it would have difficulty in assigning seats after the game has been set up. I just wanted to put it out there in case anyone felt like working on it.

**Comment by duckmammal** [comment]
Another couple points occurred in a game recently. 

In one example bids came out like this:

Player | Seat1 | Seat2 | Seat3
Alice:     4 4 0
Bob:      3 3 0
Charlie:  2 1 0

Normally, we say that Alice gets the highest value pack, because Alice bid the highest amount. 

But Alice bid the same amount on two different Seats. Alice is indifferent as to which seat she gets, so we should look at the next highest valuation. We see that Bob values the same two seats to be the same value as well, albeit a lower "same value". Charlie values Seat1 more, so the valuation, across all relevant players, for Seat1 is higher, and Alice should get Seat1, and pay 3 end game victory points for it.

If Charlie had bid 1 on Seat1, then the values of Seat1 and Seat2 would have been truly equal, and Alice would be assigned Seat1 or Seat2 at random, paying 3 end game VP for it.


The next situation is as follows:

Player | Seat1 | Seat2 | Seat3
Alice:    4 3 0
Bob:     3 4 0
Charlie: 2 0 1

We try to find the player with the highest bid, but there are two players. In the instance of these tied players, we make them take their seats "simultaneously". This would mean Alice would take Seat1, with a high bid of 4 points, and pay 3 points for her seat. At the same time, Bob would take Seat2, also paying 3 points for the seat. 

We eliminate Alice and Bob from the system and continue 
Charlie: X X 1

Charlie would get Seat3, paying 0 points, because there is no 2nd highest bid for Seat3.

**Comment by kevinb9n** [comment]
I'm pasting some text from Kyshantry in discord.  I myself have no comment on its relative benefits or the importance of doing anything here at all.
–––––

the way the bidding worked was that n packs of 2 corps are revealed, each attached to a seat
then each person places a sealed bid on each seat/pack (so perhaps seat 1 is tharsis vitor, seat 2 is recyclon aphrodite, seat 3 is poseidon saturn, seat 4 is phoblog interplanetary), maybe I bid (4, 1 , 15, 3)
then bids are revealed
starting with the highest bid, that person gets the pack, and pays endgame vp's equal to the second highest bid on the pack
so if my 15 was the highest out of everyone, and christine bid 12 on it, i'd pay 12 endgame vps
then i'm removed from the bidding
then the process is repeated with the highest remaining bid
and so fourth
*forth
until the fourth player gets the last pack for 0 vps
then you draft [we've tried it either draft first then bid for corps or vice versa, both seem to work fine]
