### ISSUE TITLE
Show card linked to Self-Replicating Robots

### ISSUE THREAD

**Issue by duckmammal** [bafolts/terraforming-mars#938]
There's no way to see what card is under SRR after you have put it there. There's also no way of adding a 2nd card underneath SRR once a first is added.

I know that you can only double on one card at a time, but sometimes a card's cost is fully covered by SRR and the conditions are still not high enough to play it. You should definitely be able to add a 2nd card under SRR, as is written on the card.

**Comment by jijiqw** [comment]
#664

**Comment by vincentneko** [comment]
Fixed and merged
