### ISSUE TITLE
Bug: MARKET MANIPULATION

### ISSUE THREAD

**Issue by jijiqw** [bafolts/terraforming-mars#939]
Noting to do and the  game suspend when there is only one  colony is active. it  should't be played in this case
![image](https://user-images.githubusercontent.com/16096558/86700484-ba59a380-c043-11ea-80e7-44048f8af68d.png)
![image](https://user-images.githubusercontent.com/16096558/86700514-bfb6ee00-c043-11ea-8d90-cf6f19be6aac.png)

**Comment by nwai90** [comment]
Closing as fixed in https://github.com/bafolts/terraforming-mars/pull/940
