### ISSUE TITLE
Science tags on prelude cards don't count

### ISSUE THREAD

**Issue by dabewi** [bafolts/terraforming-mars#94]
Hi,

I tried to play _Gene Repair_ that requires 3 science tags. I have two science tags on project cards and one science tag on a prelud card. Unfortunately the program doesn't allow to play _Gene Repair_ although I have enough money and there are no other requirements.

I think the method getTagCount (line 185 in Player.ts) only considers project cards and corporation cards as valid.

Screenshot: https://abload.de/img/errorh8kpl.png

Cheers

**Comment by alrusdi** [comment]
You are probably right. We will fix it soon.

**Comment by alrusdi** [comment]
Fixed and merged. Thank you!
