### ISSUE TITLE
UI improvements: selects and submit

### ISSUE THREAD

**Issue by ssimeonoff** [bafolts/terraforming-mars#943]
## Idea 1: Style them in the webpage's black-grey-brown style
Example: 
![active_buttons](https://user-images.githubusercontent.com/6917565/86768148-5b992780-c04d-11ea-957b-f0a3e4307deb.png)
![save](https://user-images.githubusercontent.com/6917565/86768210-79ff2300-c04d-11ea-8f34-fdcd13477a5b.png)
Bigger buttons (and margins) will be easier selected on mobile.

## Idea 2: Sub-options to be with smaller width and in a "flex" container (inlined) 
Example: 
![sub-options](https://user-images.githubusercontent.com/6917565/86768329-ae72df00-c04d-11ea-8329-a7b3d03ea144.png)
When the options to play or sell project cards are chosen, the sub-options (the cards themselves) are displayed inline. Follow the same logic for the other options and sub-options.

## Idea 3: Follow the original game's font's choices
"Prototype" uppercase with normal font-weight. (see first example again)
If someone is doing this, then fix `.title` class as well: from bold Arial to normal Prototype
![font](https://user-images.githubusercontent.com/6917565/86769857-188c8380-c050-11ea-9c4f-cee25f02f4c8.png)

**Comment by nwai90** [comment]
Love this UI design @ssimeonoff, especially Idea 2. I had a similar thought some time back about using buttons as well, with actions grouped into "sets".

<img width="620" alt="SuggestedActionsUI" src="https://user-images.githubusercontent.com/2408094/86771092-3c69bc80-c084-11ea-81ea-57b53a596195.png">

For example, we would simply omit row 1 if neither option was available to the player, and omit row 4 if neither Colonies nor Turmoil expansions were selected. While keeping the bottom area free for the list of cards/sub-options to choose from.

**Comment by alrusdi** [comment]
Unfortunately Prototype font is not that good for i18n - it does not contain other-than-english letters

**Comment by duckmammal** [comment]
I like style 2 a lot!

**Comment by jijiqw** [comment]
Bigger save button!
