### ISSUE TITLE
Bug: PR Office raised TR but cannot use UNMI ability

### ISSUE THREAD

**Issue by lostgrail** [bafolts/terraforming-mars#946]
id=bbb985040232

Playing a solo game to TR, I was unable to use the UNMI ability when either: 
* Played UNMI Contractor Prelude card (could be wrong about being allowed to do this)
* Played PR Office (gain one TR directly)

Thanks for all the work! Stay safe!

**Comment by lostgrail** [comment]
Update: UNMI is totally bugged out, raised Temp with Asteroid standard project, and was also unable to use UNMI ability

**Comment by nwai90** [comment]
I think I found the issue. Will submit a patch

**Comment by nwai90** [comment]
@lostgrail This should be fixed by https://github.com/bafolts/terraforming-mars/pull/947. Will close this issue for now
