### ISSUE TITLE
Pluto Colony Bonus incorrect for one player with multiple colonies

### ISSUE THREAD

**Issue by duckmammal** [bafolts/terraforming-mars#949]
Under the current game play, if a player has 2-3 colonies on Pluto, they will draw 2-3 bonus cards, and then have to discard 2-3 bonus cards.

Instead they should draw 1 bonus card, and discard 1 bonus card, 2-3 times.

Drawing 3 cards all at once gives the player more up front information about which cards they are drawing, and a more informed platform for making discard decisions.

**Comment by vincentneko** [comment]
Fixed and merged
