### ISSUE TITLE
Inventors Guild and Business Network enhancement

### ISSUE THREAD

**Issue by vincentneko** [bafolts/terraforming-mars#95]
Inventors Guild and Business Network should display full card instead of card name only.

**Comment by bafolts** [comment]
With `SelectCard` and `SelectHowToPay` we should be able to accomplish this. The `cb` for `SelectCard` would decrement mega credits by `3` automatically if the player does not have the `Helion` corporation. In the situation where the player can use heat as mega credits a `SelectHowToPay` can be returned.

**Comment by alrusdi** [comment]
Fixed and merged
