### ISSUE TITLE
Bigbox promo corp -Pharmacy Union

### ISSUE THREAD

**Issue by jijiqw** [bafolts/terraforming-mars#955]
![image](https://user-images.githubusercontent.com/16096558/86992760-c6c13600-c1d4-11ea-8332-ecbf3c811acc.png)
Do we miss the  icon of  -4 MC ？

**Comment by jijiqw** [comment]
Forget that , my fault

**Comment by nwai90** [comment]
Resolved in https://github.com/bafolts/terraforming-mars/pull/957
