### ISSUE TITLE
Game always jumps back to a certain point - cannot progress anymore

### ISSUE THREAD

**Issue by tmheducation** [bafolts/terraforming-mars#959]
In our game https://terraforming-mars.herokuapp.com/player?id=d8632bff556b I already repeated at least 5 times these steps:

- passed my turn as the last player

- bought some cards at the begin of the new generation

When I logged in again, either nothing had changed or the game had reset to the point before I had passed. We couldn't make it into the next round of gameplay (generation 8 past buying cards phase) for 24 hours yet.

A similar issue happened in another game we abandoned.

**Comment by alrusdi** [comment]
@bafolts can we get db dump somehow to reproduce it on localhost? JSON of this game can be good enough too

**Comment by tmheducation** [comment]
We were now able to progress past the point. A similar issue still seems possible though.

**Comment by alrusdi** [comment]
ok, i am closing this issue then. Please reopen it if you will hit it again.
