### ISSUE TITLE
using Iron/Titanium to reduce a card cost can spend excess Iron/Titanium

### ISSUE THREAD

**Issue by Arsenki-33** [bafolts/terraforming-mars#969]
Minor UI issue.
When you take the **play a card** action, you often have the option to spend Iron or Titanium instead, or in addition to MC.
However the UI seems to let you spend **one extra material** even though the cost is already reduced to zero.

example: You want to pay for a cost 12 card the UI will let you spend 7 iron instead of 6 which is the useful limit.

PS: I'm completely new to GH, this is my first post. Congrats for the good work on thihs great boardgame.

**Comment by nwai90** [comment]
Fixed and merged in https://github.com/bafolts/terraforming-mars/pull/1070
