### ISSUE TITLE
Display tokens on cards

### ISSUE THREAD

**Issue by dabewi** [bafolts/terraforming-mars#97]
I think it is necessary to display the amount of token on a specific card, especially that cards that provide VP per specific amount of tokens (such as _Search For Life_ or _Pets_).

Maybe the same token symbol that are used on greeneries and city tiles could be used here (and a small text field with the amount of tokens above?).

Cheers

**Comment by alrusdi** [comment]
Yes, it would be good addition.

**Comment by vincentneko** [comment]
This one is somehow tricky as the card is static HTML...

**Comment by alrusdi** [comment]
I found the situation when caption about resources will be partially hidden.
May be we shold do it like on the second image?
![res_bug](https://user-images.githubusercontent.com/394311/71167830-43abb300-2277-11ea-832f-8220ad259570.png)
![res_bug2](https://user-images.githubusercontent.com/394311/71167862-54f4bf80-2277-11ea-80bc-6b96a44691a5.png)

**Comment by vincentneko** [comment]
Yes, this should be much better. It would be great also to only display this extra div only on cards that can hold resources.

**Comment by alrusdi** [comment]
UI widget updated
