### ISSUE TITLE
Bug: Can't play Cultural Metropolis

### ISSUE THREAD

**Issue by Dudurandil** [bafolts/terraforming-mars#972]
Hi,

On game https://terraforming-mars.herokuapp.com/player?id=d375c60c42b3

I couldn't play Cultural Metropolis and I checked that all the conditions were here:
-Energy Production >=1
-2 delegates in Unity or Unity is ruling 
-Enough MC/Steel

I suspect that I couldn't play the card because I had less than 2 delegates to place (was playing Septem Tribus, so when I got this card, each generation I only had 1 delegate left)

Thanks for your help and your amazing work :)

**Comment by alrusdi** [comment]
Placing 2 delegates is mandatory. So if you don't have enough delegates - you can't play this card
https://boardgamegeek.com/thread/2201860/cultural-metropolis

**Comment by Dudurandil** [comment]
Oh I didn't know, thanks!
