### ISSUE TITLE
Bug: Nitrogen-Rich Asteroid

### ISSUE THREAD

**Issue by Dudurandil** [bafolts/terraforming-mars#973]
Hi,

On game https://terraforming-mars.herokuapp.com/player?id=325956a40080

When Nitrogen-Rich Asteroid was played, the card didn't give 4 plants production, only 1, even if the player had the 3 plant tags.

Thanks (again!) for your help and your amazing work :)

**Comment by alrusdi** [comment]
it is not reproducible. I've played EosChasmaNationalPark, Bushes, Lichen and then after playing NitrogenRichAsteroid i've got 4 plants production.
Please, next time you hit this problem - do not continue the game to give us a chance to investigate the problem.

**Comment by Dudurandil** [comment]
Thanks for your answer, we'll stop the game if it happens a next time.
