### ISSUE TITLE
Play cards from hand prototype

### ISSUE THREAD

**Issue by alrusdi** [bafolts/terraforming-mars#983]
I am trying to reduce scroll by removing Play card option. Card in the branch **play-card-in-place** can be played by pressing "Play!" button on card in hand
![Снимок экрана от 2020-07-13 16-33-54](https://user-images.githubusercontent.com/394311/87333888-3d548f80-c557-11ea-8c13-f0b768aa5218.png)

On the picture:
- Cards  Mineral Deposit and Peroxide power can be played
- User pressed on Play! button on  Nuclear zone card
- Titanium mine card is linked to Self replicating robots and can be played with discount

@bafolts @vincentneko @nwai90 is it okay to you? To me it is like first step to refactor actions (less clicks, less scroll, more dynamic data on cards)

**Comment by nwai90** [comment]
@alrusdi This looks great! I would suggest to:

(1) make the `Play!` button and text slightly larger,
(2) move the button slightly up so it doesn't cover part of the card, and
(3) use a different colour that does not represent any of the card types (e.g. green is used for automated cards, blue is used for action cards)

Perhaps also add `border-radius` to the `Play!` button and Payment popup to make their shapes consistent with the cards' rounded edges.

**Comment by vincentneko** [comment]
This looks great !
I agree with @nwai90 suggestions. Maybe using the same color (light blue) as the save button for the play button.

**Comment by ssimeonoff** [comment]
"Cards in hand" block can be also removed. 

If "Play card" card action shows all cards now (the ones that cannot be played as well), effectively it renders player_home_block--hand obsolete.

**Comment by alrusdi** [comment]
@ssimeonoff no, my idea is to completely remove Play card option

**Comment by ssimeonoff** [comment]
Yes I understand the idea, but think about it in reverse. 

If "play card" action is selected by default (see #953)  and if it shows all cards (the ones that cannot be played a well in a different styling), the "play card" action will behave exactly as you want. 

Another drawback is that "Cards in hand" is visible when the user goes for action "activate card", which is a lot of wasted space. 

Plus, the main action in the game is to play cards, so it still good to keep it as such, especially when you have all actions separated in groups.

About the UI:  When a card is selected to show an overlay over it with the payment options and submit button - YES!

**Comment by ssimeonoff** [comment]
Example: 
![1](https://user-images.githubusercontent.com/6917565/87544425-b9a9b880-c6a6-11ea-9479-f62c36131597.png)
From left to right:
1. "Play card" option is selected. The card is clicked (the submit button is called "Play". 
2. "Play card" option is selected. The card is not clicked (no extra buttons)
3. "Activate card" option is selected. The card is clicked (only one way to activate the card)
4. "Activate card" option is selected. The card is clicked (multiple options to activate the card)
5. "Activate card" option is selected. The card is not clicked (no extra buttons- it looks identical to an unselected card when "Play card" option is chosed)

clicked card: a transition upwards was given as example. It will give the feeling that the card pops, plus less of the card will be hidden behind the overlay.

**Comment by nwai90** [comment]
@alrusdi Could we also remove the dark grey background for Self-Replicating Robots card target? It seems to make the black text much harder to read compared to the original card.

<img width="208" alt="Screenshot 2020-07-15 at 11 53 50 PM" src="https://user-images.githubusercontent.com/2408094/87567605-0ae19880-c6f7-11ea-89ca-d5e593414117.png">
<img width="210" alt="Screenshot 2020-07-15 at 11 54 09 PM" src="https://user-images.githubusercontent.com/2408094/87567608-0cab5c00-c6f7-11ea-8188-8fe4b3f8bd8e.png">

**Comment by alrusdi** [comment]
@nwai90 of course we can
@ssimeonoff isn't it strange to see unplayable cards in Play card action? If it is not then we should separate them somehow. Can it be something like horizontal line with caption **Not playable cards** ?

**Comment by ssimeonoff** [comment]
Actually it is a pretty much expected, since playing cards is done by picking a card from the hand, so effectively "Play cards" and "Cards in hand" lists should be identical (which is actually my initial point: don't add "play" functionality to the "cards in hand" list, but instead improves the "play card" list and remove completely "cards in hand").

The cards that are displayed, but cannot be played - they definitely needs to have different styling, no questions about it.

For example: https://dudetakeyourturnblog.files.wordpress.com/2018/10/tfm-player-hand.jpg
The official game uses opacity to indicate if a card is unplayable (for any reason) and you can sort the cards in various ways.

Example: 
![Untitled](https://user-images.githubusercontent.com/6917565/87642176-75232900-c749-11ea-9de9-2fb8db5cbb2b.png)
- Used greyscale instead of opacity for unaplayable cards.
- The label can indicate the actual reason why the card is unplayable. 
- The labels can have different styling for the various reasons. 
- unplayable cards probably should be sorted at the end (after the playable cards)

**Comment by nwai90** [comment]
This looks great! Technically, I think the only two reasons why a card cannot be played are "Requirements not met" or "Cannot afford card". It would look quite nice with the above two colours.

**Comment by FreeLikeGNU** [comment]
>     * Used greyscale instead of opacity for unaplayable cards.
I would like to see some hint of the cards type color (blue, green, etc) only in the cards title box to inform the player of the type of card easily.

**Comment by alrusdi** [comment]
Let's close it as controversial. We can return to this discussion when new Actions UI will be introduced.
