### ISSUE TITLE
Show all discounts and extra costs while paying for a card

### ISSUE THREAD

**Issue by duckmammal** [bafolts/terraforming-mars#999]
There have been more than 20 times when I've played a card, thinking I was going to pay one price (the one written on the card), but ended up paying paying more or less, due to discounts, or the reds policy tile.

It would be visual reminder if, for each action that had a price, you could show the calculation.

It could easily be something along the lines of:
"Pay [Original Price] (- [Discounts]) (+ [Extra])"

In this example the discounts and extra would only show up if they were applicable to the cost of the current card.

It think this simple visual prompt will help players better run their game.

**Comment by jijiqw** [comment]
#776  repeat issue

**Comment by alrusdi** [comment]
Closing it as duplication. It's relatively easy to show price with discounts, but reds tile effect is little bit out of scope of price calculation (because it is an effect - not requirement).
